### ISSUE TITLE
Should patron primaryAddress be something other then 'home' for different affiliations?

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/FOLIO-Project-Stanford#101]
Currently in the userload 'home' is hardcoded as the primaryAddress. Should it be different for faculty and/or staff to be 'work' instead, or are there any other permutations?

**Comment by dlrueda** [comment]
Probably should ask Mario?  @Laszlo-J ?

**Comment by jgreben** [comment]
Leave as `home` and limit permission for view user in folio.
