### ISSUE TITLE
Map Extended Info fields to FOLIO 

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#102]
**_Proposed Mapping for Cataloging wizard fields_** 

**TECHSTAFF** - Item level note with Name=TECHSTAFF (will need to suppress from export to SW)
**PUBLIC** - Item level note with Name=Public
**HVSHELFLOC** - Do not migrate - Update **09/23/22** These should now be included. See #170 
**CIRCNOTE** - Item level note with Name=CIRCNOTE and Combine with below CIRCSTAF (will need to suppress from export to SW)
**CIRCSTAF** - 

--------------------
_**Notes**_

**TECHSTAFF** - Item level note with TECHSTAFF as type, ["Staff" check box not for discovery](https://docs.folio.org/docs/metadata/inventory/#adding-a-note-2) but this [doc](https://wiki.folio.org/display/MM/2021-08-23+-+Inventory+Search+Improvements+Meeting) contradicts that, will need to block from SW export
**PUBLIC** - Item level note with with PUBLIC as type, will need to export to SW. _Do we need to retain the Symphony-ness of this or can it just go into a regular note?_

**HVSHELFLOC** - will likely be deprecated.

**CIRCNOTE** - Used by SUL interchangeably with CIRCSTAFF
**CIRCSTAF** - Used by SUL for indicating a damaged item or things noticed at time of checkout/checkin. Not a public note. At Law, may be info about what to check for when circulating special items.

There is a Circulation note option - check-in/check-out notes. _Could we determine which would be appropriate for CIRCSTAF or just use moving forward?_

Per Laszlo: no use-cases for having the Circ notes outside of inventory. 

****Practices above will change in FOLIO workflows.
Documentation on current SUL practices -  https://consul.stanford.edu/display/DCU/Item+extended+information+TECHSTAFF+field%2C+Guidelines+for+using 

Example in Settings 

<img width="1016" alt="Screen Shot 2022-03-14 at 6 28 47 AM" src="https://user-images.githubusercontent.com/7749403/158181836-daf0ccf9-49d5-40da-ae70-02ce46b0459e.png">

**Comment by ahafele** [comment]
@Laszlo-J could you review the mapping above make sure all looks good?

**Comment by Laszlo-J** [comment]
Be aware that CIRCNOTE and CIRCSTAFF are also used by access staff to track searching. Includes: user initiated for missing item, staff initiated for same, and user-initiated for claims returned/not checked out. 

They add a note for each date and initial of the searcher. This tells us how many were done, and at 5th one triggers a selector notify to reorder. Claims 4th search triggers reinstatement of fees/fines and sel-notify.

FOLIO may have a different method to track searches, but we should retain legacy data to track user history/item searches.

**Comment by ahafele** [comment]
@Laszlo-J interesting. Do you know if there is any kind of circulation note in FOLIO that relates more specifically to this type of process? Check-in/check-out notes maybe? If so, we should map it to a more appropriate location so there isn't a divergence with the legacy data.

**Comment by ahafele** [comment]
Workflow for check-in/check-out notes is not yet known. Migrate to Inventory Items for now per mapping above.

**Comment by Laszlo-J** [comment]
@ahafele Just to follow-up I doubt we'll use check-in/check-out for searching purposes. I envision it more for noting item damage at those two stages.

**Comment by ahafele** [comment]
Continues on #106

**Comment by jgreben** [comment]
@ahafele @Laszlo-J A `circulationNote` item note data in FOLIO has a `noteType` field which can be either `Check in` or `Check out` meaning that the Circ note applies to one of those situations (see snippet below). When we migrate a note that is CIRCSTAFF or CIRCNOTE, we can assign it one of those values if we can somehow know which one to assign. Maybe all are of type `check-in`?

Also, it was noted above that CIRCNOTE and CIRCSTAFF are used interchangeably? Although I am seeing from samples of the data that CIRCNOTE is for noting damage, and CIRCSTAFF is mostly for the searching that Laszlo mentioned, but also infrequently for noting damaged. I am wondering if it would it bo OK to just combine all legacy circ notes into one `Circ Note` field, or do we need the two note types going forward?

Finally would it also be OK to have a single note of any note type with the conactenated notes of all the notes on a given item, or do we need to post multiple note entries if they exist for a given item?

```
"circulationNotes": {
      "type": "array",
      "description": "Notes to be displayed in circulation processes",
      "items": {
          ...
          "noteType": {
            "type": "string",
            "description": "Type of circulation process that the note applies to",
            "enum": [
              "Check in",
              "Check out"
            ]
          },
          "note": {
            "type": "string",
            "description": "Text to display"
          },
          ...
          ...
          "staffOnly": {
            "type": "boolean",
            "description": "Flag to restrict display of this note",
            "default": false
          }
        }
      }
    },
```

**Comment by ahafele** [comment]
Per standup convo - ok to concatenate the notes together and combine the Circ notes. 

@Laszlo-J can you answer the first question above? It was my understanding that the combined CIRCNOTE should _not_ be put into a checkin/checkout note.

**Comment by Laszlo-J** [comment]
Okay to add one `Circ Note` note, with all legacy notes concatenated.

As discussed in stand-up, no need to assign `Check in` or `Check out`, unless required by FOLIO. (If required, default to `Check in`)

Desired: also prefer a carriage return or something to allow easy staff readability, but this is less critical than for the user notes.

**Comment by ahafele** [comment]
_Capturing meeting conversation 4/22_

Concerns about adding note types that will not be used passed data migration, e.g. `Tech Staff`. 
- Can we determine the workflow now in order to migrate item extended info into a already established note type? 
- Should we follow the Orders model. Extended info goes into a general Note with the legacy note type inline with the text. E.g. `Note` = TECHSTAFF: cat by ath 2/2/12

Alissa and Laszlo to revisit the topic with relevant subgroups to see if this is amenable.
