### ISSUE TITLE
how to get vendor address categories out of Symphony

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/FOLIO-Project-Stanford#104]
Symphony vendors have 3 addresses (<addressIdx>0, 1, 2 in the XML vendcyc report). WorkFlows shows which vendor address (1, 2, or 3) is for payments, customer service, and claims. How do we get this data? It is not in the XML report. Some options for getting it:

- Find which sels we can use to get the address categories for each vendor and merge it in the vendor xml report
- Do our own selection for everything and re-write putting it into JSON format for FOLIO.
- Temp file for the report that is used by the prtvendor template. Probably used by the xsl as well. Maybe customize it so it doesn’t blitz it and see if we can use that file.

**Comment by dlrueda** [comment]
If want to try the 3rd route, saving the temp file and then customizing the report to add the vendor address category to the output...

Report source is vendorcyclist.  This script is found on Bodoni: /s/sirsi/Unicorn/Rptscript/Runs/vendorcyclist.pl

**Comment by shelleydoljack** [comment]
I'm not sure how we are going to get the correct accounting, service, and order address out with a consistently corresponding address indicator using the delivered Symphony reports. When I try doing the following selection for just selecting the ELSEVIER vendor:
![Screen Shot 2023-01-09 at 2 08 51 PM](https://user-images.githubusercontent.com/6343464/211416489-0a829394-d35d-447a-990b-9ebd4f1005b0.png)
I get a report with 0 vendors output:
```
<?xml version="1.0" encoding="UTF-8"?>
<report>
<title>Vendor Cycle List</title>
<dateCreated>2023-01-09T13:09:21</dateCreated>
<dateFormat>mm/dd/yyyy</dateFormat>
</report>
```
Looking at the Workflows entry for the vendor, the different address categories are:
![Screen Shot 2023-01-09 at 3 00 47 PM](https://user-images.githubusercontent.com/6343464/211417105-4245feba-4968-4f56-819f-0322c14c8d06.png)
The vendor has an address in address line 1 and address line 2 only. @dlrueda I think we should ask our vendor consultant about writing us a custom report to give us the data we need in the xml format.

**Comment by shelleydoljack** [comment]
For vendorID ELSEVIER in the report Suzette ran, it shows:
```
<vendorAddress>
...
<addressCategory>Payments</addressCategory>
<addressIdx>2</addressIdx>
</vendorAddress>
<vendorAddress>
...
<addressCategory>Orders, Claims</addressCategory>
<addressIdx>1</addressIdx>
</vendorAddress>
<vendorAddress>
</vendorAddress>
```
I think this is something I can work with.
