### ISSUE TITLE
How do we manage updating staff permissions ongoing?

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/FOLIO-Project-Stanford#105]
The task that handles the Pset spreadsheet is currently additive and does not deal with deletes of specific permissions. How do we want to handle updating permissions as an ongoing concern and how does the task script need to be modified accordingly.

**Comment by dlrueda** [comment]
I suggest not updating/deleting user’s permissions programmatically, at least at first.  I think we can do this manually with the subset of expert users (Systems Librarians, primary point of contact at a coordinate library, FOLIO module leads for SUL, SUL Library Systems) to:

- delete permissions from users that have left
- add permissions for new staff
- update permissions as needed for individual staff

If it becomes onerous we could certainly revisit.  Not sure, after the first couple of iterations, how much churn this would be.

**Comment by dlrueda** [comment]
Other opinions welcome!

**Comment by jgreben** [comment]
Sounds good to me. Moving to Review for other comments.

**Comment by jgreben** [comment]
Some users who can update permissions will handle this via the support channels.
