### ISSUE TITLE
Extract item xinfo from Symphony for loading to FOLIO

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#106]
When mapping is finalized in ticket #97, extract item extended info from Symphony, prep to load to FOLIO.

**Comment by ahafele** [comment]
Item extended info mapping here - https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/102

**Comment by jgreben** [comment]
Added to `/s/SUL/Bin/folio_symphony_extract/generate_marc_items.ksh`

**Comment by jgreben** [comment]
Need to fix item header: CIRCSTAFF should not have CIRCNOTE header. Keep as CIRCSTAFF.
