### ISSUE TITLE
Extract user xinfo from Symphony for loading to FOLIO

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#107]
When mapping is finalized in ticket #97, extract user extended info from Symphony, prep to load to FOLIO.

Depends on #97

**Comment by jgreben** [comment]
User notes uses this api endpoint: https://s3.amazonaws.com/foliodocs/api/mod-notes/s/notes.html

Depends on https://github.com/sul-dlss/folio_api_client/issues/112

**Comment by jgreben** [comment]
/s/SUL/Bin/folio_symphony_extract/Users/user_xinfo.ksh
