### ISSUE TITLE
Document drop down options in “user group” user custom field

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#108]
Found a note for this in backlog, not sure if it’s already done.

Need to document the list of “user group” drop down options, perhaps have it Settings spreadsheets folder?  Or Circulation folder?

Need to document how they should be created in FOLIO (if this needs to be done manually, can’t be done via script)

**Comment by jgreben** [comment]
https://docs.google.com/document/d/17bBS9wyeZ2m1d20xDggVwau61OSsU-pqYiigE8fzV1E/edit#bookmark=id.ebrz6u8703at
