### ISSUE TITLE
Identify metadata/cataloging requirements for an ILS

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#11]
Document wishlist or hard requirements

Work with relevant staff to gather

Add doc to Libsys Google drive

**Comment by shelleydoljack** [comment]
Documented on https://docs.google.com/spreadsheets/d/1CKcoRsHnhO2c6-I61T0gDG9cN2BUYZnKNdU8eCnL3tU/edit#gid=0
