### ISSUE TITLE
Explore using Symphony legacy identifier as HRID for data migration 

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#113]
Ebsco tooling supports this and would hopefully solve collusion issues. 
Would persist our SW urls and previous searches. 
Would we want to prefix with something like Lane has?

**Comment by dlrueda** [comment]
Excellent news!  

Agree that persisting SW urls and previous searches would be good, and I believe Hoover’s ArchiveSpace also relies on the catkey (not sure if it’s link to SW or to Symphony itself that they use it for)

Add to that, the Data Migration subgroup STRONGLY suggested having the HRID be the legacy system ID.

I will consult with Ryan S. at Lane about prefixing with S (but if we don’t need to that would be preferable I think)

**Comment by shelleydoljack** [comment]
Maybe just prefix with "a". The current SW export has the "a" prefix even though the SW indexing and display code removes it.

**Comment by dlrueda** [comment]
Talked to Ryan.  He much prefers that we prefix with the “a”

**Comment by dlrueda** [comment]
OK, so this means @jermnelson needs to figure out how to use the aCATKEY to generate the HRID.  Maybe ask Theodor if can’t find it in the code/settings?

**Comment by jermnelson** [comment]
> OK, so this means @jermnelson needs to figure out how to use the aCATKEY to generate the HRID. Maybe ask Theodor if can’t find it in the code/settings?

I assigned myself to this issue and will start testing today. I think the `preserve001` setting option [here](https://github.com/FOLIO-FSE/folio_migration_tools/blob/be0626087b2e5933c2a74d147954db0c6ce6cde5/src/folio_migration_tools/library_configuration.py#L9) for the `HridHandling` configuration will do what we want but will test to confirm.

**Comment by jermnelson** [comment]
Adjusting the DAG to use the `preserve001` configuration value for the `BibsTransformers`, `HoldingsTransformers`, and  `ItemsTransformer`. This results in the CATKEY being set for the Instance HRID but the holdings and item transformers are ignoring the CATKEY and are still using the existing HRID settings (which still causes holdings and items HRID collisions). Here is an example:
- Instance with the CATKEY (`a13409477`) as the HRID https://folio-test.dev.sul.stanford.edu/inventory/view/92ff76bd-9ed5-5e07-ac22-e2a8ebdf3fe2?qindex=hrid&query=a13409477&sort=title. 
- Attached holdings records HRID is `ho00000061347`
- Item's HRID is `it00000063555`. 

While we can manually assign the Holdings HRID and the Item HRID to use the CATKEY , we still would need to account for the case of multiple Holdings and Items records associated with an Instance record. @ahafele do you have an idea on how IndexData is creating Holdings and Items HRIDs for Lane?

**Comment by ahafele** [comment]
@jermnelson I *believe* they are using the legacy ID from their MARC Holdings records (they use MARC Holdings differently from us). I'm unsure of how they generate the item ID. 
Prefixes for each are 
Instance - L
Holdings - LH
Items - LI

Example - https://folio.dev.sul.stanford.edu/inventory/view/335411e1-6e67-5ad3-858d-887274c0dde3?qindex=hrid&query=L%2A&sort=title 
Instance - L327044
Holdings - LH383026 (found here https://docs.google.com/spreadsheets/d/1PKFvcFH9fJABU1E6qgPfbPxAdZc-2Ztn/edit#gid=1570596587)
Items - LI437764, LI437764

**Comment by jermnelson** [comment]
Closing this issue as PR [85](https://github.com/sul-dlss/libsys-airflow/pull/85) that implements HRIDs for Instances, Holdings, and Items has been merged.
