### ISSUE TITLE
Add ability to report out counts of data loaded (instances, holdings, orders, users, etc.)

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#115]

**Comment by dlrueda** [comment]
Queries
* Instances: instance-storage/instances?limit=0
* Holdings: holdings-storage/holdings?limit=0
* Items: item-storage/items?limit=0
* SRS BIBS: source-storage/records?recordType=MARC_BIB&limit=0
* SRS MHLDS: source-storage/records?recordType=MARC_HOLDING&limit=0
* SUL orders: orders/composite-orders?limit=0&query=(acqUnitIds==*"bd6c5f05-9ab3-41f7-8361-1c1e847196d3"*)
* loan-storage/loans?limit=0

etc.....

**Comment by jgreben** [comment]
We've migrated now.
