### ISSUE TITLE
Make folio repos public

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/FOLIO-Project-Stanford#116]
~~https://github.com/sul-dlss/LibSysTasks~~

~~https://github.com/sul-dlss/folio_api_client~~
~~- move tsv/xml/json files to shared_configs or Goggle drive~~
~~- https://github.com/sul-dlss/folio_api_client/pull/127~~
~~- [ ] run `git filter-branch`~~
~~- [ ] everyone remove and re-clone repo locally~~

https://github.com/sul-dlss/folio-k8s
- ~~move okapi allowwed IP addresses to k8s secret~~

https://github.com/sul-dlss/folio-lane-migration
- Ask Ryan/people at Lane

**Comment by dlrueda** [comment]
NOT LibSysTasks.  We determined that this repo is not used for FOLIO work.

Folio-project-stanford is the repo for FOLIO that can be made public, if it isn’t already.  (and it looks like it’s already public)

**Comment by jgreben** [comment]
It is not possible to create a secret for the `nginx.ingress.kubernetes.io/whitelist-source-range`.

**Comment by jgreben** [comment]
We can just create issues for folio-k8s in the generic FOLIO tasks repo instead.

**Comment by jgreben** [comment]
We created a new `folio-tasks` repo and deprecated the old `folio_api_client`
