### ISSUE TITLE
Use cases for mod-data-export

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/FOLIO-Project-Stanford#118]
mod-data-export needs S3-like storage for the export of MARC data. Since the on-prem version is not AWS will we need an alternative?

Fron Jon:
"how often do you need mod-data-export?  Is it a backup system generally to use in case of problems, or something regular that needs high performance?  If it’s just normal backup, we do other types of backups to s3 so it might still be the best solution to just stick with that."

**Comment by shelleydoljack** [comment]
The Metadata Department are really looking forward to using the Data Export app, which will allow them to export MARC data, to modify, and re-import into FOLIO. The bulk edit app in FOLIO will not be released until Nolana version and then it will have very limited features.
