### ISSUE TITLE
Document SW algorithm to identify full text URLs

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#119]
What algorithm does SearchWorks use when looking at 856s to know when to display a link to full text?

Vitus thinks we could replicate this algorithm and select full text 856s from Symphony that need to have a FOLIO holdings record with URL created (for SUL/INTERNET type resources)

**Comment by shelleydoljack** [comment]
The algorithm to determine a full-text URL is in the indexing code: https://github.com/sul-dlss/searchworks_traject_indexer/blob/88cac17b72c090555be18f53451aea206940f453/lib/traject/config/sirsi_config.rb#L1329-L1387 . There's some old documentation for this that I updated (there wan't much to update): https://consul.stanford.edu/display/NGDE/AccessAndUrlAlgorithms . The only thing to note is that finding aids are determined based on https://github.com/sul-dlss/SearchWorks/blob/3ede5f354d7b29f24af30e0bfc13b5aa122beefe/app/models/concerns/index_links.rb#L57-L59 and can show up either in what the indexing code determines is full text or supplementary links.
