### ISSUE TITLE
Create a "SUL" electronic Library

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#120]
Related to https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/72 

Firm decision across coordinates and SUL has not been made. Start by loading SUL records with the additional Library and Electronic Locations. 

Name options - **SUL** ~~(if we want to include other things there), SUL Electronic, Stanford Libraries Electronic Library~~

Locations under this library - **Electronic, SDR**
_Do we need a LOCKSS location?_ 
_Instructor?_
Darsi will send Alissa list of SUL locations for review.

**Comment by dlrueda** [comment]
In FOLIO Ops Drive->Migration Files->tsv->tenant
Library SUL created in libraries.tsv.

Locations SUL-ELECTRONIC and SUL-SDR created in locations.tsv
Locations both given “Online” as service point (which is one of the default reference data service points, not in our service-points.tsv

**Comment by dlrueda** [comment]
List of locations provided to Alissa.  @ahafele ok to close ticket?
