### ISSUE TITLE
Investigate why staff users are not coming through user feed

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#123]
I am trying to give Suzette access to folio-test to do some Orders spot-checking and in the process discovered that Suzette and myself do not have user records (Darsi either). 

Need to figure out what is going on with the feed from Symphony AND get Suzette added with permissions.

**Comment by dlrueda** [comment]
Unexpired users are being filtered out unless they have charges/holds/unpaid bills.

For UNEXPIRED users, ALL the users in cns.ids (for all profiles, so *.ids) should be harvested from the registry and loaded to FOLIO

(We only want to filter out EXPIRED users if no holds/charges/bills)

**Comment by dlrueda** [comment]
Will open new ticket to fix
