### ISSUE TITLE
Add Suzette as user with permissions to FOLIO-TEST

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#128]
We have asked Suzette to spot check Order records on folio-test (on-prem) before Orders are loaded (and potentially with updated code) to folio-dev )on-prem. She needs to be added as a user and given permissions.

**Comment by dlrueda** [comment]
No longer needed; Suzette has been successfully loaded to folio-test and correct Psets assigned via script
