### ISSUE TITLE
Task to Migrate Serials Receipt Data

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/FOLIO-Project-Stanford#132]

**Comment by ahafele** [comment]
Maybe we should wait until Duke/GBV work is a little further along. Initial info here - https://docs.google.com/presentation/d/1txB0kDM1QLSDZkoZlmuC9v36dnRS1qaiZtCUOO04WO4/embed#slide=id.g1780d235265_0_27

**Comment by ahafele** [comment]
We have asked Index Data to handle this for us. Acq and Law would also like it to include serials notes.

**Comment by michelleif** [comment]
to clarify, we asked IndexData about the possibility of doing this, but it requires more discussion on our side about what we want. so we haven't asked (or paid) IndexData to do anything specific yet

**Comment by ahafele** [comment]
Currently, Irina Trapido is looking into migrating receiving history and expected pieces for SUL and Law

**Comment by ahafele** [comment]
Currently, Irina Trapido is looking into migrating receiving history and expected pieces for SUL and Law

**Comment by ahafele** [comment]
Was done by Irina.
