### ISSUE TITLE
Task or DAG to migrate MARC Authorities

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/FOLIO-Project-Stanford#134]

**Comment by ahafele** [comment]
@jermnelson we are going to defer this for now. I will talk with the Metadata Subgroup about waiting until FOLIO has the functionality to utilize the records...e.g. year one vs day one.

**Comment by ahafele** [comment]
Per [Metadata Subgroup conversation](https://docs.google.com/document/d/1oF_EcPV20-Rt_w_mZoU4ULAMkz8rJNMezAgxwELfaLI/edit#bookmark=id.8h5th5fiku4w), we will defer this migration task until closer to "go live". At which time we will need a way to load, update, delete the records in batch so we can store and maintain our Authority File.

**Comment by dlrueda** [comment]
When we extract authority data from Symphony, need to dump using authdump -f flag. Dump in flat.  Then use flatskip -if -om to convert to marc before loading to FOLIO.

Reason (summarized): 
Using authdump -om, 
.550. |wg|aTurtles
is output as
.550. |ag|aTurtles

But dumping in flat format gives you the correct
.550. |wg|aTurtles
and flatskip retains the |wg

**Comment by michelleif** [comment]
I'm closing this bc we are not migrating authorities for Go Live. I added the step to dump/extract authority data to the [Migration Checklist](https://docs.google.com/spreadsheets/d/1_6QWDtS9zRcwgvc8pDdbKq10A6629y4OU39DsNBApF0/edit#gid=0).
