### ISSUE TITLE
Enable mod-graphql for testing

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/FOLIO-Project-Stanford#138]
Access would like to test out [mod-graphql](https://github.com/folio-org/mod-graphql#overview) to see if it offers any advantages over querying a bunch of individual APIs separately (i.e. SRS, holdings, items, etc). Currently we get:
> proxyClient failure: mod-graphql-1.9.0 http://mod-graphql/: finishConnect(..) failed: Connection refused: mod-graphql.folio.svc.cluster.local/[IP]:80: POST /graphql

It seems unlikely that this API will be better supported or faster than any of the lower-level web services, but it's probably worth a shot. If enabling it is a significant burden or there are other concerns, this isn't a high-priority ticket.

**Comment by jgreben** [comment]
In the folio-k8s overrides.yaml file for mod-graphql we added 
```
service:
  containerPort: 3001
```
Then re-installed the module. Now this kind of graphql query works with okapi:
```
curl -X POST -H"$TOKEN" -H"x-okapi-tenant: $TENANT_ID" -H "Content-Type: application/json" -d'{ "query": "query { instance_storage_instances(query: \"title=horse*\") { totalRecords instances { title } } }" }' $OKAPI_URL/graphql
```

There is a default set of ramls in the `tests/input/mod-inventory-storage/ramls` directory that the module uses when it starts up. We may need to customize this set if graphql seems useful and is missing any ramls that we may want to use.

**Comment by jgreben** [comment]
Helpful env vars for testing:
```
export TENANT_ID=sul
export OKAPI_URL=https://okapi-test.stanford.edu
export ADMIN_USER=...
export ADMIN_PASSWORD=...
export TOKEN=$(curl -s -X POST -H"x-okapi-tenant: $TENANT_ID" -H"Content-type: application/json" -d"{\"username\": \"${ADMIN_USER}\", \"password\": \"${ADMIN_PASSWORD}\"}" -D - $OKAPI_URL/authn/login | grep x-okapi-token)
```
