### ISSUE TITLE
Handle preceding/succeeding titles

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#142]
https://s3.amazonaws.com/foliodocs/api/mod-inventory-storage/p/instance-preceding-succeeding-titles.html 

Example of SUL record: https://folio-test.stanford.edu/inventory/view/57e5625f-3747-529b-af20-4d07cfc647 

Expected behavior: Preceding or succeeding title should appear in the Instance> Title Data accordion with a link to the relevant related Instance. 

Example of Lane record with expected behavior: https://folio-test.stanford.edu/inventory/view/0455c665-c9c1-5313-aa41-a7efa186a8

TTD:
- [x] Fork https://github.com/FOLIO-FSE/folio_migration_tools and refactor `create_preceding_succeeding_titles` method ~~to remove conditions that require ISSN/ISBN~~ to output entities to file for subsequent processing.
- [x] Use forked migration_tools repo when deploying/running libsys-airflow (this will allow the population of the inventory record without creating the links between records).
- [x] ~~Find out of stakeholders will require~~ Parity will not require linkages on day 1. Create a new issue to be worked on later to create record linkages. 
- [x] ~~Propose upstream change to FOLIO-FSE?~~ FOLIO-FSE will be coming up with some changes that may help us with this, so BOLO...

**Comment by jgreben** [comment]
The mapping rules should be handling these already, but perhaps the records need a subfield z or x:
```
"780": [
  {
    "entity": [
      {
        "rules": [
          {
            "conditions": [
              {
                "type": "trim"
              }
            ]
          }
        ],
        "target": "precedingTitles.title",
        "subfield": [
          "t"
        ],
        "description": "The primary title (or label) associated with the resource",
        "applyRulesOnConcatenatedData": true
      },
      {
        "rules": [
          {
            "conditions": [
              {
                "type": "set_identifier_type_id_by_name",
                "parameter": {
                  "name": "ISBN"
                }
              }
            ]
          }
        ],
        "target": "precedingTitles.isbnId",
        "subfield": [
          "z"
        ],
        "description": "Type for Valid ISBN",
        "applyRulesOnConcatenatedData": true
      },
      {
        "rules": [
          {
            "conditions": [
              {
                "type": "trim"
              }
            ]
          }
        ],
        "target": "precedingTitles.isbnValue",
        "subfield": [
          "z"
        ],
        "description": "Value for Valid ISBN",
        "applyRulesOnConcatenatedData": true
      },
      {
        "rules": [
          {
            "conditions": [
              {
                "type": "set_identifier_type_id_by_name",
                "parameter": {
                  "name": "ISSN"
                }
              }
            ]
          }
        ],
        "target": "precedingTitles.issnId",
        "subfield": [
          "x"
        ],
        "description": "Type for Valid ISSN",
        "applyRulesOnConcatenatedData": true
      },
      {
        "rules": [
          {
            "conditions": [
              {
                "type": "trim"
              }
            ]
          }
        ],
        "target": "precedingTitles.issnValue",
        "subfield": [
          "x"
        ],
        "description": "Value for Valid ISSN",
        "applyRulesOnConcatenatedData": true
      }
    ]
  }
]
```

**Comment by jgreben** [comment]
If I am reading this correctly, it is looking for an ISSN or an ISBN that comes from the subfield x or z in the record: https://github.com/FOLIO-FSE/folio_migration_tools/blob/7d989ab04d537a8cb9e16670f9c2da2a31924aa2/src/folio_migration_tools/marc_rules_transformation/rules_mapper_base.py#L376

**Comment by ahafele** [comment]
@jgreben in this lane example there is no x or z and it is functioning as expected - https://folio-test.stanford.edu/inventory/view/d0b84b14-32c1-5e8c-80e2-2aa45b5e5ba0. Can we update the tool to use a different subfield? I'm not seeing anything in ID notes but maybe we can ask them how they do it. 
Is the above from the default MARC mapping? The documentation I found implies that these things are a separate entity - https://s3.amazonaws.com/foliodocs/api/mod-inventory-storage/p/instance-preceding-succeeding-titles.html

**Comment by jgreben** [comment]
@ahafele I think that they actually did something different or an extra step to link these titles, and it wasn't using the same loading/mapping rules.

**Comment by jgreben** [comment]
We will probably need to fork and refactor the migration tools to create the links without regard to the $x and $z

**Comment by jgreben** [comment]
See https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/166
