### ISSUE TITLE
Add MobileId and ProximityChipId to userload transform

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/FOLIO-Project-Stanford#147]
This is what we currently do in Symphony:
```
 <!-- MOBILE ID and PROXIMITY CHIP ID  -->
        <!--****************-->
        <xsl:variable name="ACTIVEID">
            <xsl:if test="identifier[@type='mobileid'] or identifier[@type='proximity']">
                <xsl:for-each select="identifier[@type='mobileid']">
```

Except map them to custom fields `MobileId` and `ProximityChipId` respectively.

**Comment by dlrueda** [comment]
Checked user record jeromeg, which had a ProximityChipId value in the FOLIO user load (from email Thursday Sept 9).  The user record on folio-test does NOT have the ProximityChipId value.

**Comment by jgreben** [comment]
Right now proximityChipId is a custom user field, also should be mapped to userBarcode instead of card id.

**Comment by jgreben** [comment]
Is this getting into the user record without errors?

**Comment by jgreben** [comment]
Fixed by https://github.com/sul-dlss/folio-tasks/pull/81
