### ISSUE TITLE
extract fines for circ data migration

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/FOLIO-Project-Stanford#148]
extract fines for IndexData circ migration.
see #164 for which fines to migrate.

IndexData needs:

1. Description
2. Amount (or remaining amount if there’s been a partial payout)
3. Payment status (probably will all be set to “outstanding” since we’re not migrating payment history on old fines?)
4. Type of fine (from fee/fine types defined in settings)
5. Patron ID

**Comment by michelleif** [comment]
close this since IndexData is doing it for us? instead i'll change it to "extract bills" and put it in indexdata circ migration epic

**Comment by dlrueda** [comment]
Change it or close it so it can be in index data circ migration epic, sure
