### ISSUE TITLE
Add format to mapping to determine material type

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#149]
Hoover has same item type for multiple types of materials.  Need to look at FORMAT from Symphony to determine material type.

After format is added to tsv for item files, add to mapping in folio-migration repo

**Comment by shelleydoljack** [comment]
FORMAT column added to scripts that create item tsv files.

**Comment by shelleydoljack** [comment]
Closed by https://github.com/sul-dlss/libsys-airflow/pull/163
Currently only for HOOVER and HV-ARCHIVE.

**Comment by shelleydoljack** [comment]
Closed by https://github.com/sul-dlss/libsys-airflow/pull/163
Currently only for HOOVER and HV-ARCHIVE.
