### ISSUE TITLE
set up whatever needs setting up in order to send email notices (and email pw link)

### ISSUE THREAD

**Issue by michelleif** [sul-dlss/FOLIO-Project-Stanford#153]
from circ settings subgroup: "“The notice settings have been set up but we’ll only be able to test when Systems have done what they need to do to allow notices to go out.”

can we enable emails so notices can get tested? 

(I think this would also enable the reset pw link to get emailed when requested?)

**Comment by jgreben** [comment]
This is all documented on the folio-k8s README and in the migration checklist. Config files are uploaded to the migration files folder. I was able to send myself a password reset link, but we still need to test whether the mailing of notices works.

**Comment by michelleif** [comment]
Darsi confirms she is getting notices to the folio test mailing list so I'm closing this.
