### ISSUE TITLE
extract date cataloged from Symphony

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/FOLIO-Project-Stanford#154]
Need to figure out way to extract the date cataloged from Symphony. Maybe look at how the export searchworks script handles it if there is not already something in catalogdump now that can give us that data. The data should map to the instance level [catalogedDate field](https://github.com/folio-org/mod-inventory-storage/blob/abdc9dce99b83d6f9c386df08b5c33fa48c06cb2/ramls/instance.json#L367-L370).

**Comment by dlrueda** [comment]
I just checked through the catalogdump flags and do not see a way to output the date cataloged.

**Comment by shelleydoljack** [comment]
Keep date cataloged NEVER as 0 (it comes out of selcatalog as 0).

**Comment by dlrueda** [comment]
Post-process catalog dump files to add 916 with 
$a date-created $b date-cataloged

**Comment by shelleydoljack** [comment]
If we post-process the catalogdump files to add the 916 field, then we will need to change the default [marc-instance-mapping-rules.json](https://github.com/sul-dlss/folio_migration#marc-instance-mapping-rulesjson) to process the 916 field. These rules are stored at the okapi endpoint `GET /mapping-rules/marc-bib`. Maybe some other way to add this data would be to have something in the airflow dag that uses a tab-delimited file with the data (CKEY\tCREATED_DATE\tCATALOGED_DATE).

**Comment by shelleydoljack** [comment]
@dlrueda I updated do_catdumps_and_items_ckeylist_tsv.ksh and do_catdumps_and_items_tsv.ksh to do a selcatalog to get the dates created and cataloged. Please review. I didn't do a test run but it _should_ work.

**Comment by shelleydoljack** [comment]
Also added to /s/SUL/Bin/folio_symphony_extract/acquisitions/on_order_bibs/on_order_ckeys.ksh.

**Comment by shelleydoljack** [comment]
Tested with generating MARC and items for EDUCATION library records. Loaded to folio-dev, instances have date cataloged.
