### ISSUE TITLE
relationshipId in holdingsrecord.electronicAccess needs to be UUID

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/FOLIO-Project-Stanford#157]
Despite https://github.com/folio-org/mod-inventory-storage/blob/9942d7a8e36b41a4738fccd198e23da79326a38f/ramls/holdingsrecord.json#L85-L88 showing that the field takes a string, it needs to have the UUID of the electronicAccessRelationships or else FOLIO doesn't display the data (and it currently breaks indexing into SW). The UUIDs can be accessed from the endpoint `GET electronic-access-relationships` ([API docs ](https://s3.amazonaws.com/foliodocs/api/mod-inventory-storage/p/electronic-access-relationship.html)). 

Here is an example of what it looks like in FOLIO when you use the UUID for "Version of resource", holdings HRID ah14230211_2:

![Screen Shot 2022-08-24 at 9.55.46 AM.png](https://images.zenhubusercontent.com/62964511c137fa350131daff/cf39ddaa-c62b-4a1e-8cef-9e18d3d393b3)

See json data with `GET https://${OKAPI_URL}/holdings-storage/holdings/3cfb98ab-95f2-5f52-b756-7ff1d28cbd98`

Here is an example of what it looks like in FOLIO when the string "Version of resource" is used, holdings HRID ah958727_2:
![Screen Shot 2022-08-24 at 9.58.20 AM.png](https://images.zenhubusercontent.com/62964511c137fa350131daff/0ec76ad5-a2cc-4090-84bc-319f0287eb55)

See json data with `GET https://${OKAPI_URL}/holdings-storage/holdings/88581c5c-7326-5200-bacc-585a0152b436`

**Comment by jermnelson** [comment]
We are addressing this problem for electronic holdings in the [_query_for_relationships](https://github.com/sul-dlss/libsys-airflow/blob/90b96f8e524164f7db08ff635e66cc9f08cda864/plugins/folio/helpers.py#L121-L142) function that sets the relationship uuid in the holdings record.

**Comment by shelleydoljack** [comment]
In FOLIO UI, I searched folio-test holdings records by permanent location SUL-ELECTRONIC and there are 29 records. I went through the list to find which ones did not have the URL relationship field showing and did a PUT for those holdings records to update the field to a UUID. There were not many of the 29 that needed correcting. I hope this fixes the indexing problem.
