### ISSUE TITLE
Ask Kent about Business library on-order bibs

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/FOLIO-Project-Stanford#159]
How do we select them to migrate from Symphony? Will we migrate them from Symphony or maybe they will create records in FOLIO?

**Comment by dlrueda** [comment]
Kent says his on-order records are all ordered from Gobi, and a bib record is loaded for each of these and item created with current location of ON-ORDER, and a “real” home location. So these bibs will get migrated on the basis of their home location, no need to do anything special for Business on order records.
