### ISSUE TITLE
Holdings/items issues found in migrated data

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#162]
Hey Jeremy, Here are the examples we discussed. Darsi looked in her files and all have been found there as we would expect. 

- a14176510 - Symphony current location is INPROCESS so in folio it should have a status of In process. 
- a14061813, a14073045 - These Science records in Symphony have items but there are no items in folio. 
- a3133515 - This record should have two holdings with an item on each. Instead both items are being put on 1 holdings record. 
- a3122354 - This record should have 1 item and in folio has zero
- 1358079 - This should have two holdings with 1 item on each. In folio there is 1 holdings with the wrong item attached to it.
- 2883115 - govdocs example. This one might be complicated by the fact that their call number |Z usage is different.

**Comment by ahafele** [comment]
I think something went wrong with the posting of this to SRS. @jermnelson if there a place in airflow that might point me to an error like that?

**Comment by jermnelson** [comment]
> 

It depends on what record load it is and when it was loaded. Right now we are not persisting the logs between Airflow code updates.

**Comment by ahafele** [comment]
Sorry that comment was intended for a different ticket. But good to know about logs.

**Comment by jermnelson** [comment]
## a14176510
I just ran the this record again through the DAG and the item record is showing the correct status of **In process**. Here is the latest Item record from the DAG:

```python
{'_version': 1,
 'barcode': '36105230143112',
 'holdingsRecordId': 'f52b4143-69c4-5915-a1ee-62cfba97b44d',
 'hrid': 'ai14176510_1',
 'id': '35a0c482-8597-5ce7-8ade-7d204402cec3',
 'materialTypeId': '5e74635c-ed1c-40e7-8e93-ac8264e3efc0',
 'metadata': {'createdByUserId': 'a96ab0c2-19a7-4a47-8d29-fa0d1612a827',
              'createdDate': '2022-09-09T23:03:00.954',
              'updatedByUserId': 'a96ab0c2-19a7-4a47-8d29-fa0d1612a827',
              'updatedDate': '2022-09-09T23:03:00.954'},
 'notes': [{'itemNoteTypeId': '079c6747-3297-48db-a96a-524c97b42916',
            'note': 'EDI receipt',
            'staffOnly': True}],
 'permanentLoanTypeId': '2b94c631-fca9-4892-a730-03ee529ffe27',
 'permanentLocationId': 'd1d129dc-a15e-42e8-918b-01762f8c1901',
 'status': {'date': '2022-09-09T23:03:00.954512', 'name': 'In process'}}
```

This should no longer be a problem.

**Comment by ahafele** [comment]
Thanks @jermnelson should I be able to see this through one of the UI's or is was it not actually posted?

**Comment by jermnelson** [comment]
> 

Hi @ahafele, we still need to post these records again.

**Comment by ahafele** [comment]
Creating an Epic #171 with individual tickets links.
