### ISSUE TITLE
What bills do we migrate?

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#164]
What different bill types are we migrating from Symphony to FOLIO?

**Comment by dlrueda** [comment]
Some data.  There are 145,003 bills with >0 balance The count by bill reason:
     26 BADCHECK|
    197 BILLED-OD|
  27034 BILLNG-FEE|
    562 CLAIM-FEE|
    400 CLAIM-LOST|
     47 DAMAGED|
     14 GRE-CLMFEE|
   8166 LOST|
      4 LOSTCARD|
      4 LOST-ILL|
     17 LOSTKEY|
     22 MISC|
  55142 OVERDUE|
     39 PRE-NOTIS|
      1 PRE-UNICRN|
     48 PRIVILEGES|
  30975 PROCESSFEE|
    526 PROCESSING|
   7520 RECALLOVD|
      8 RECOD-MBIL|
     96 RECOD-MFEE|
    110 RECOD-MOD|
    109 REGHOLD|
    262 REPLCMENT|
  13664 RESERVEOVD|

**Comment by Laszlo-J** [comment]
Bills to migrate are in this spreadsheet: [https://docs.google.com/spreadsheets/d/1J0mjbOWC9I_ADuQerbVDfWcRf2JBx_n6oTod6Rmh6VE/edit#gid=0](url)

All should be replacement fines.

**Comment by Laszlo-J** [comment]
Updated spreadsheet for all bills. Some are not replacements, but needed for Privileges, etc.

**Comment by michelleif** [comment]
@dlrueda ok to close?
