### ISSUE TITLE
|Z in call number

### ISSUE THREAD

**Issue by michelleif** [sul-dlss/FOLIO-Project-Stanford#165]
<strong>Submitted By: </strong>jkalchik@stanford.edu
<strong>Description: </strong>When a serial issue is missing the |Z in the call number or the |Z is in the wrong place it will create multiple holdings for the library. (Note: I fixed the two incorrect items in Symphony)
<strong>Instance HRID: </strong>`a4005065`
<strong>Patron barcode: </strong>
<strong>FOLIO App: </strong>Inventory
<strong>Urgency: </strong>It's not urgent.
<strong>Browser: </strong>Chrome

**Comment by michelleif** [comment]
@ahafele do we need FOLIO to account for incorrect |Z or is this a cleanup project to correct any other incorrect examples in Symphony? (are there any?)

**Comment by ahafele** [comment]
I think this is going to be a cleanup issue. But I also think we want to look at our handling of it a little closer. I'll move this ticket to a backlog issue in the folio project.

**Comment by ahafele** [comment]
We have a variety of information in $Z and we need to look at whether or not holdings are being created appropriately as a result. Likely some cleanup work needed as well.

**Comment by ahafele** [comment]
No easy way for MD staff to get report on these issues because can't report on |Z. Maybe we could generate a report.
