### ISSUE TITLE
Item records do not have item extended info notes

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#168]
The work was done to add Symphony item extended info notes to FOLIO item notes but they are not being added to records in folio-test. 

Tickets for previous work - 
https://github.com/sul-dlss/folio_api_client/issues/107
https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/102
https://github.com/sul-dlss/libsys-airflow/pull/92

Examples that should have item extended info notes (TECHSTAFF)
13444958
13297088

**Comment by jermnelson** [comment]
@ahafele, I think I discovered the problem why these item records are not showing notes. In our current mapping file for item notes (https://github.com/sul-dlss/folio_migration/blob/f04e9ac0c4c27347c03bf74d75564a8cbfe1d828/mapping_files/item_mapping.json#L238-L242) we are assigning a default value for the item note type that doesn't exist in folio-test. Both of the example records do have the notes attached when you query them from Okapi. 

For example retrieving the item record for instance `a13444958` with barcode of **36105075027859** looks like 
```
{'id': '00b3c0d7-9667-5050-b0da-7d1a35cb7443',
 '_version': 1,
 'hrid': 'ai13444958_1',
 'holdingsRecordId': '2dfe3682-2374-59ba-8f55-268f41d93924',
 'formerIds': [],
 'barcode': '36105075027859',
 'effectiveShelvingOrder': 'G 46800 41914 K54',
 'effectiveCallNumberComponents': {'callNumber': 'G6800 1914 .K54',
  'typeId': '95467209-6d7b-468b-94df-0f5d7ad2747d'},
 'yearCaption': [],
 'administrativeNotes': [],
 'notes': [{'itemNoteTypeId': '079c6747-3297-48db-a96a-524c97b42916',
   'note': 'c:rt',
   'staffOnly': True}],
 'circulationNotes': [],
 'status': {'name': 'Available', 'date': '2022-08-12T18:54:31.289+00:00'},
 'materialTypeId': '1a54b431-2e4f-452d-9cae-9cee66c9a892',
 'permanentLoanTypeId': '2b94c631-fca9-4892-a730-03ee529ffe27',
 'permanentLocationId': 'c9cef3c6-5874-4bae-b90b-2e1d1f4674db',
 'effectiveLocationId': 'c9cef3c6-5874-4bae-b90b-2e1d1f4674db',
 'electronicAccess': [],
 'statisticalCodeIds': [],
 'metadata': {'createdDate': '2022-08-12T18:55:30.495+00:00',
  'createdByUserId': '8cc3ab86-c943-4d53-8df7-b3dc64fb44ee',
  'updatedDate': '2022-08-12T18:55:30.495+00:00',
  'updatedByUserId': '8cc3ab86-c943-4d53-8df7-b3dc64fb44ee'}}
```
I've started work on a fix for this issue.

**Comment by ahafele** [comment]
Hi @jermnelson sorry just getting to this and it looks like you found a solution. Am I understanding correctly that a "dynamic item note type" will create the needed note type in settings? Or do we need to add a migration task to create those note types?

**Comment by jermnelson** [comment]
Closed with PR https://github.com/sul-dlss/libsys-airflow/pull/155 being merged.
