### ISSUE TITLE
Add HVSHELFLOC extended item notes to Inventory/item notes mapping

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#170]
Follow mapping pattern found here - https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/102

Should go in a custom Inventory item note called HVSHELFLOC.

**Comment by dlrueda** [comment]
Need to extract Symphony item extended information field HVSHELFLOC  in /s/SUL/Bin/folio_symphony_extract/item_xinfo.ksh


HVSHELFLOC “item note type” has been created in folio-test and folio-dev

**Comment by dlrueda** [comment]
Added HVSHELFLOC call to /s/SUL/Bin/folio_symphony_extract/Bibs/item_xinfo.ksh as part of Symphony extract Oct 4 2022

**Comment by dlrueda** [comment]
Looks like all HVSHELFLOC notes got an error during item_xinfo script, presumably in the call to pipe2tsv_json.  Doing selved and call to pipe2tsv_json from command line for these two items:
36105075530373   Extra pipe characters in data string
36105075435359   Extra pipe characters in data string

even if the HVSHELFLOC value does not have a pipe (here’s the response to the selved call from command line for the items)
36105075530373  |{"HVSHELFLOC":[{"A":6,"D":"&#124;a8.34","I":"","X":0}]}|
36105075435359  |{"HVSHELFLOC":[{"A":6,"D":"&#124;aT5","I":"","X":1}]}|

**Comment by shelleydoljack** [comment]
Fixed it with Darsi. Needed to add the `--type` header, we think, since that seemed to fix it.

**Comment by dlrueda** [comment]
Actually it was that I had copy/pasted the line so the “tab” character in the header was actually multiple space characters, and that broke it.  Changed that to “TAB” and it works fine now.

**Comment by dlrueda** [comment]
Re-generating the item_xinfo notes now for full extract.  (It’s been running 3:30 hours so far, 9.5 million done out of 13million ckeys)
