### ISSUE TITLE
Modify on-order bib extract

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/FOLIO-Project-Stanford#178]
Only catalogdump things that have 0 items for the scripts this directory: `/s/SUL/Bin/folio_symphony_extract/acquisitions/on_order_bibs`

The item tsv file we create should only be for records that have no items in Symphony. Bibs for on-order records with items in Symphony will be extract with the main catdump scripts.

**Comment by shelleydoljack** [comment]
@dlrueda, I have some questions about implementation. Looking at how I generated the ckeys with zero copies spreadsheet for https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/99 , I used the data generated by the ExportSearchworks script, specifically this section: https://github.com/sul-dlss/ExportSearchWorks/blob/22bfd6be1cb39bfc54724c355d72bce0b9ee516e/uni_dump_sworks.pl#L283-L364 
I'm thinking maybe I just need to pipe the list of ckeys generated by the rollover reports selection to selcallnum and get the ones that have 0 copies (`selcallnum -c0`). I don't think I need to check if the callnum is linked to a current fiscal year orderline for migrating to FOLIO. What about `selcallnum -z`, specify number of visible copies? If the item record on the callnum segment is in shadowed currentloc or checkbox shadowed, then it is not a visible copy. I guess in combination with `-c` it won't matter to use the `-z` flag? And also, probably select non-shadowed callnums?

**Comment by shelleydoljack** [comment]
Just documenting here that first call needs to go through `selcatalog -n'<2'` in order to filter catalog records that have either 0 or 1 callnum segment, then pass to select callnums with 0 copies. Do we want bib records with 0 callnum records? Are those "on-order"?

**Comment by shelleydoljack** [comment]
Modified the on_order_ckeys.ksh script to create new on order bib marc files but need to figure out how to make the item tsv using only the filtered ckeys list.

**Comment by shelleydoljack** [comment]
Ok, this is done and new files generated. I'm almost certain of the logic to select catalog records with 0 or 1 callnums and then select callnums with 0 copies is how to do this. I don't think adding -z flag to selcallnum or selcatalog (select catalog records with 0 or 1 visible callnums) makes a difference since we just want bibs with 0 items. I tested adding `selcatalog -z'<2'` and there's no difference in our output with it.

**Comment by dlrueda** [comment]
> Just documenting here that first call needs to go through `selcatalog -n'<2'` in order to filter catalog records that have either 0 or 1 callnum segment, then pass to select callnums with 0 copies. Do we want bib records with 0 callnum records? Are those "on-order"?

I didn’t think there even were bib (catalog) records with 0 callnum records.

**Comment by dlrueda** [comment]
> I don't think I need to check if the callnum is linked to a current fiscal year orderline for migrating to FOLIO. 

I’m not sure about this.  If we’re only migrating orders in the current fiscal year, there is no reason to migrate the bibs over to FOLIO with 0 items.  Then we’d end up with an acq record in FOLIO with no order attached (and everyone wondering why this bib is in FOLIO).  I think we need to check with Suzette on this.

Actually, re-reading your comment, I think you mean the orders you are rolling will already be in the current fiscal year, so you don’t have to do yet another check on that when you are finding the ckeys from the orders yaml files and looking for those with 0 items.
