### ISSUE TITLE
a4332640 - complex Spec record with many boxes

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#179]
I would expect 1 holdings collapsed on base number M1090 with all of the boxes as items under it. Currently there are no items in folio and many holdings.

**Comment by ahafele** [comment]
10/25 no items.

**Comment by ahafele** [comment]
10/25 no items.

**Comment by ahafele** [comment]
11/18 on dev. Items look good. 
Need to have Spec do a cleanup project to add SERIES and BOX info to |Z so it migrates correctly. @dlrueda would it be easy enough to generate a list of barcodes and call numbers with the |Z portion for this ckey? That might help Spec a bit to see which don't already have the correct call number.

**Comment by dlrueda** [comment]
List of barcodes and call numbers split into base and analytic portions emailed to Alissa 11/18

**Comment by ahafele** [comment]
Report passed to Spec. Broader issue discussed with Vitus for cleanup project. Closing ticket.
