### ISSUE TITLE
New SUL Order Type Mapping

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#182]
Acq Subgroup has made some changes to the SUL Order Type Mapping. 

order_type_map.tsv has been updated. This includes change to correct first error listed - https://docs.google.com/document/d/11SUtfx70EmkMxiQ64aLqckR5w1KqEe_h2FGu1kGY8hI/edit# - from June load. 

Question - DEPNDT is still TBD. Will the blanks in mapping cause an error?

**Comment by shelleydoljack** [comment]
I'm not sure what it is about the column Symph_order_type, but the spaces that aren't recognized as spaces in a regex before the tab, need to be removed. I did that in the original tsv file that I uploaded to the FolioOps google drive. Also, TRUE and FALSE need to be downcased. And "resource" needs to be "Resource" per schema def:
```
"orderFormat": {
            "description": "The purchase order line format",
            "type": "object",
            "$schema": "http://json-schema.org/draft-04/schema#",
            "enum": [
              "Electronic Resource",
              "P/E Mix",
              "Physical Resource",
              "Other"
            ]
          },
```
Anyways, I corrected the issues. Maybe next time download the FolioOps tsv and edit in a text editor. :shrug: I removed DEPNDT from the mapping. I think those orders just won't load b/c data will be missing for orderFormat, etc.

**Comment by shelleydoljack** [comment]
order_type_map.tsv moved to `/s/SUL/Dataload/folio_symphony_extract/acquisitions/orders/tsv`. the rake tasks need to be run again, but after test loading orders to folio-dev is completed to test multi-threading.
to do :
- `STAGE=dev rake acquisitions:delete_sul_order_json`
- `STAGE=dev rake acquisitions:delete_law_order_json`
- `STAGE=dev rake acquisitions:transform_sul_orders`
- `STAGE=dev rake acquisitions:transform_law_orders`

**Comment by shelleydoljack** [comment]
json files deleted. Need to modify dev.yaml for okapi-test before running the transform task so that the order UUID's get the correct okapi_url for loading to folio-test.

**Comment by shelleydoljack** [comment]
Ran `STAGE=prod rake acquisitions:transform_*_orders` to create the json files.
