### ISSUE TITLE
SSO patron integration

### ISSUE THREAD

**Issue by michelleif** [sul-dlss/FOLIO-Project-Stanford#189]
Shibboleth (SUNetID only) for public authentication to OPAC	

part of SearchWorks Work Cycle

discovery env handles; "service" logs in to FOLIO		

Lane also allows barcode authentication for non-SUNet users (hospitals); SUL too for courtesy users.  they have user record in ILS and enter a PIN, ILS web services does lookup to authenticate; possible to allow hospital users to authenticate using their native credentials to make SearchWorks requests?

**Comment by jgreben** [comment]
The folio task here is to make sure that ticket(s) gets made or this is otherwise documented on the SW WC plan.

**Comment by jgreben** [comment]
Patrons can currently SSO login to Searchworks/MyAccount via a folio app user to do folio api calls.
