### ISSUE TITLE
Payment feed to Orafin

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#200]
send payments to Orafin (invoice data to Oracle financials so that invoices will be paid)

University of Chicago is currently working on doing exactly this.

Time estimate: if Chicago can figure it out, 4 weeks to mimic/tweak what they do

Arlef: mod-bursar-export was developed for Cornell (doesn't seem to be on ARLEF matrix)
https://github.com/folio-org/mod-bursar-export says it is archived and now some functionality part of mod-data-export-spring;

**Comment by ahafele** [comment]
Suzette is contacting University Finance to request a spec of what they currently require. Update: They would like to meet with us, so we will arrange after winter break when we hopefully have some info from Chicago first.
