### ISSUE TITLE
EDI integration

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#205]
Electronic Data Interchange; see LibSys WebForms tab, "EDIFACT invoice management" group 

Time estimate: let FOLIO do it; 6 months to customize

TAMU is live with EDIFACT (on ARLEF matrix, EDI is separate from EDIFACT and no one is listed as live with EDI)

Includes loading order records (bib records with 9xx fields), loading edifact invoices, and overlaying order records with full records (item is created and order is received)

~~Method edge-orders~~ edge-orders is for the Gobi Integration which is not day 1. 

**Loading orders** - loading orders from 9xx via Data Import delayed to Orchid. We should look into the [Lehigh Tool ](https://github.com/folio-labs/folio-order-import-tool) for loading orders. Used by arlef - Cornell, Chicago, Michigan State
**Loading edifact invoices** - We should be able to use built in Data Import functionality
**Loading bibs** - Data Import
Wrap around automation possible? e.g. file pick-up etc. 

Analysis in progress by Alissa

**Comment by ahafele** [comment]
Vendor management app being used to load bibs and invoices via data import. Lehigh Order Loading tool for orders. Day 1 vendors are being loaded. Will open additional tickets as needed on new epic.
