### ISSUE TITLE
need material type mapping for complex item types

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/FOLIO-Project-Stanford#210]
The item types LIBUSEONLY, NH-7DAY, NH-INHOUSE, NH-MEDSTKS need to map to multiple material types. If a mapping can be created that includes catalog format, library, and item type, we can use that to map these item types to the appropriate material type. Otherwise, they are currently not in our material types mappings file and will get "book" in Folio.

**Comment by Laszlo-J** [comment]
I think we need to get input from Metadata or perhaps @ahafele can chime in on this approach. If we can't identify the material and assign "book" as default it may cause a lot of post-migration database corrections... Ex: Rumsey has 16752 LIBUSEONLY which look like maps and/or atlases. Hopefully they can be ID'd as such; if not, suddenly they're all books, which will be problematic from a searching standpoint (faceting in Searchworks) and probably from collection inventory/management/development (just guessing on that one.)

**Comment by ahafele** [comment]
@Laszlo-J Material types won't be used in SW so all good there. This will mostly impact circulation rules as I understand it. 

@shelleydoljack I think best option would be to create a mapping that includes catalog format, library, and item type. I haven't been to involved in this process - what do need from us to determine if that is possible?

**Comment by dlrueda** [comment]
I’ll do some sels and we can look at the data, I’ll post here

**Comment by dlrueda** [comment]
[NH-MEDSTKS.csv](https://github.com/sul-dlss/FOLIO-Project-Stanford/files/9729102/NH-MEDSTKS.csv)
[LIBUSEONLY.csv](https://github.com/sul-dlss/FOLIO-Project-Stanford/files/9729104/LIBUSEONLY.csv)
[NH-7DAY.csv](https://github.com/sul-dlss/FOLIO-Project-Stanford/files/9729105/NH-7DAY.csv)

Have to split NH-INHOUSE up, too big to upload to ticket

**Comment by dlrueda** [comment]
These two are ckey, format, and title (files too big to show each item)
[notSAL3-NH-INHOUSE.csv](https://github.com/sul-dlss/FOLIO-Project-Stanford/files/9750087/notSAL3-NH-INHOUSE.csv)
[SAL3-NH-INHOUSE.csv](https://github.com/sul-dlss/FOLIO-Project-Stanford/files/9750088/SAL3-NH-INHOUSE.csv)

**Comment by dlrueda** [comment]
@Laszlo-J perhaps the data in above spreadsheets helps to make it clear if there is a way to base the material type on library and format?

**Comment by ahafele** [comment]
@Laszlo-J this is the ticket to look at for your question about LIBUSEONLY, NH-7DAY, NH-INHOUSE, NH-MEDSTKS. I've looked at NH-7DAY and it looks to me like Catalog Format could fairly easily be mapped to Material Type. Library might need to come into play for some. I started a mapping doc for NH-7DAY [here](https://docs.google.com/spreadsheets/d/1BhWiOkRHI4CddsH61PM7aYrwgsM527lWSOZ3j2n053s/edit#gid=1746264728) based on the data Darsi output above. Let me know if you want to look at it together, or chat post-standup

My question is whether or not a loan type would then get assigned as well since these should all be short term? @dlrueda are we assigning loan types yet?

**Comment by ahafele** [comment]
@Laszlo-J this is the ticket to look at for your question about LIBUSEONLY, NH-7DAY, NH-INHOUSE, NH-MEDSTKS. I've looked at NH-7DAY and it looks to me like Catalog Format could fairly easily be mapped to Material Type. Library might need to come into play for some. I started a mapping doc for [NH-7DAY](https://docs.google.com/spreadsheets/d/1BhWiOkRHI4CddsH61PM7aYrwgsM527lWSOZ3j2n053s/edit#gid=1746264728) here based on the data Darsi output above. Let me know if you want to look at it together, or chat post-standup

My question is whether or not a loan type would then get assigned as well since these should all be short term? @dlrueda are we assigning loan types yet?

**Comment by ahafele** [comment]
@Laszlo-J [NH-7DAY](https://docs.google.com/spreadsheets/d/1BhWiOkRHI4CddsH61PM7aYrwgsM527lWSOZ3j2n053s/edit#gid=1746264728) is done. I added the other spreadsheets to https://drive.google.com/drive/folders/1lk9bjLQRGpN15FGSCwKyS0d6zkziHHB4. At initial glance I think it will be 95% effective to just use the Catalog Format to Material Type mapping...but there may be some exceptions that will require bringing in the Library, so worth reviewing.

**Comment by Laszlo-J** [comment]
@shelleydoljack I've updated the mapping for the spreadsheets [here](https://drive.google.com/drive/folders/1lk9bjLQRGpN15FGSCwKyS0d6zkziHHB4). The only real gotcha is LIBUSEONLY and library = RUMSEYMAP.

There are dozens (hundreds?) of their items in MARC cat format that should be material type = map or archival. Don't know how/if we handle those. I assuming they should be changed manually after import into FOLIO. (One example ckey = 10452645)

**Comment by shelleydoljack** [comment]
The RUMSEYMAP items that should map to map or archival probably should have their catalog format fixed (maybe a project for Data Control?). We should keep the mapping for the majority that are MARC and should map to FOLIO book.

**Comment by dlrueda** [comment]
I can contact Laura Krueger in Rumsey and ask her about the marc vs map formats of their materials, and what material type(s) she suggests we map their items to (but mostly give her the chance to clean up her records as needed).

**Comment by shelleydoljack** [comment]
@Laszlo-J and @ahafele I created this spreadsheet to consolidate and refine the mappings for the item types that are more complicated: [complex material mapping refinement](https://docs.google.com/spreadsheets/d/1MyHwOcm8B5lZvUHTumzmKJDPtdaAwcpreKMPWHA2Kr0/edit?usp=sharing). Basically, the tab Sheet1 is what we are doing for Hoover, HV-ARCHIVE, and what was identified so far in the gsheets for LIBUSEONLY, NH-7DAY, and NH-MEDSTKS. The mapping tab concatenates the columns item type, format, and library and will be what we add to the [material type mapping file](https://github.com/sul-dlss/folio_migration/blob/main/mapping_files/material_types.tsv). Could you update Sheet1 when you finalize the mapping? I know it looks like we can refine more by incorporating HOOVER and HV-ARCHIVE into SUL's mapping, but it seems good to keep them separate since those libraries were not included in the gsheets for LIBUSEONLY, NH-7DAY, and NH-MEDSTKS.

**Comment by Laszlo-J** [comment]
@shelleydoljack redo of [NH-7DAY](https://docs.google.com/spreadsheets/d/1BhWiOkRHI4CddsH61PM7aYrwgsM527lWSOZ3j2n053s/edit?pli=1#gid=764027426) sheet is done.

**Comment by Laszlo-J** [comment]
@shelleydoljack redo of [LIBUSEONLY ](https://docs.google.com/spreadsheets/d/1jZkdtl3UYp-ZRZabGkPRC8f7EDDs5zmRLIv_oaV2B48/edit#gid=1682292220)is done.

**Comment by Laszlo-J** [comment]
@shelleydoljack redo of [NH-MEDSTKS](https://docs.google.com/spreadsheets/d/1ubF0WzSOuH-BgA0dL_p2Ul4wTT616UADscaCoKYp0fo/edit#gid=765267294) is done.

**Comment by shelleydoljack** [comment]
@Laszlo-J for LIBUSEONLY, were we going to find out from Jeanette if we can correct the EARTH-SCI records that have format MARC when they are mostly maps instead of having those map to "map"?

**Comment by dlrueda** [comment]
I thought those were RUMSEYMAP records that perhaps had the wrong format, and I did send a set of records to her for review (after Vitus took a look at them and identified those that he thought were wrongly assigned).

**Comment by shelleydoljack** [comment]
In looking at the updated mappings, I think we are trying to account for wrong data and not actually mapping a thing to the material type it should be in folio. These are the mappings that I think we should have and where Symphony data should probably be corrected (the strikethrough text):

ITEM TYPE | FORMAT | LIBRARY | Folio material type
-- | -- | -- | --
LIBUSEONLY | MANUSCRPT |   | archival
LIBUSEONLY | MAP |   | map
LIBUSEONLY | MARC |   | book
LIBUSEONLY | MARC | GREEN | microform
~~LIBUSEONLY~~ | ~~MARC~~ | ~~EARTH-SCI~~ | ~~map~~
LIBUSEONLY | MARC | SPEC-COLL | archival
LIBUSEONLY | SERIAL |   | periodical
LIBUSEONLY | VM |   | multimedia
LIBUSEONLY | VM | ENG | portable device 2
~~LIBUSEONLY~~ | ~~VM~~ | ~~EARTH-SCI~~ | ~~map~~
LIBUSEONLY | VM | RUMSEYMAP | archival
NH-7DAY | SCORE |   | score
NH-7DAY | SERIAL |   | periodical
NH-7DAY | RECORDING |   | multimedia
NH-7DAY | VM |   | multimedia
NH-7DAY | MAP |   | map
NH-7DAY | MRDF |   | multimedia
NH-7DAY | MARC |   | book
NH-MEDSTKS | SCORE |   | score
~~NH-MEDSTKS~~ | ~~SCORE~~ |   | ~~book~~
NH-MEDSTKS | SERIAL |   | periodical
NH-MEDSTKS | RECORDING |   | multimedia
NH-MEDSTKS | MAP |   | map
~~NH-MEDSTKS~~ | ~~MAP~~ |   | ~~multimedia~~
NH-MEDSTKS | MRDF |   | multimedia
NH-MEDSTKS | MARC |   | book
NH-MEDSTKS | VM |   | multimedia

**Comment by dlrueda** [comment]
I agree that we can’t turn the code into pretzels to fix bad data.  We should give the staff a report of the bad data and have them correct it.

**Comment by Laszlo-J** [comment]
@shelleydoljack I've finished the [LIBUSEONLY ](https://docs.google.com/spreadsheets/d/1jZkdtl3UYp-ZRZabGkPRC8f7EDDs5zmRLIv_oaV2B48/edit#gid=1682292220)sheet. 

I removed all bad data mapping rows, except for one MARC row = 3 MARC records still need to be mapped differently. They're microfiche, and AFAICT all microfiche are cataloged under MARC. So this isn't bad data that will be fixed. We shouldn't map these to material type = book. They should be microform.

**Comment by Laszlo-J** [comment]
@shelleydoljack [NH-MEDSTKS](https://docs.google.com/spreadsheets/d/1ubF0WzSOuH-BgA0dL_p2Ul4wTT616UADscaCoKYp0fo/edit#gid=765267294) is done. All bad data mapping removed.

**Comment by Laszlo-J** [comment]
@shelleydoljack[ SAL3-NH-INHOUSE ](https://docs.google.com/spreadsheets/d/1tB9wJEp4qvzYUmCfOqf6tRUi6G1NpRhHoaKu4ZwKWEs/edit?pli=1#gid=1473607181) and [notSAL3-NH-INHOUSE](https://docs.google.com/spreadsheets/d/1_vKs_2BI77azvM54B8rVSFIMTEclaGpdrC6zApT-9mo/edit#gid=1320878539) are done.  Those are the last sheets.

**Comment by shelleydoljack** [comment]
Thanks @Laszlo-J !
