### ISSUE TITLE
migrate proxy-to-sponsor user relationships to FOLIO

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#212]

**Comment by dlrueda** [comment]
How are proxy users set up in FOLIO?  Does a proxy user have a separate user record that is just for “the proxy,” or is it something that is set on the real user record?

Which proxy users do we want to migrate?  Some of them currently have loans, holds, bills in Symphony that are under the “group account.”  How should these be migrated to FOLIO?

**Comment by Laszlo-J** [comment]
FOLIO links sponsor/proxy user records directly. Once setup, the proxy can act on the sponsor's account (charge books, make requests.)

I'd say if the Symphony proxy account is active (not expired), link the proxy user to the faculty user via the FOLIO method.

If the account is _expired_, move all fines, check outs, requests, etc., to the faculty sponsor's account. (All their responsibility anyway.)

**Comment by michelleif** [comment]
per Charles at IndexData:
POST to the /proxyfor endpoint the payload is described here: https://github.com/folio-org/mod-users/blob/master/ramls/proxyfor.json

**Comment by dlrueda** [comment]
How do we get this data out of Symphony?

seluser
     -+ selects user records by usergroup default key.

seluser -+">0" -o+BD
...
608|2551803248|Matsumoto, Yoshiko (P=Nomura)|
608|2558016068|Matsumoto, Yoshiko|
609|2554354734|Anderson, R. Lanier|
609|2558564962|Anderson, Lanier (P=Lin)|
610|2513141980|Fishkin, Shelley Fisher|
610|2553188128|Fishkin, Shelley (P=Johnson)|
 
Note it isn’t always just one sponsor and one proxy.  First column (seluser -o+) is key of user group they both belong to.  User record does not specify which is sponsor and which is proxy, that data is in the grouplink table (use selgrouplink).  There is also a selusergroup tool but this has limited data (name-key, date-created, num-users) that probably isn’t needed for Folio.

selgrouplink
  -iG considers grouplinks with usergroup keys read from standard input
  -oG writes selected grouplinks' usergroup keys to standard output.
      U writes selected grouplinks' user keys to standard output.
      K (default) writes selected grouplinks' grouplink keys to standard output _(probably don’t need this)_
      n whether the Notice Master flag value is YES (Y) or NO (N)
      r selects grouplinks based on what the specified responsibility(ies) are

seluser -+">0" -o+ | sort -u | selgrouplink -iG -oUGKnr  | seluser -iU -oDBerY.9002.Y.9007.S

Need to be able to go from PROXY user record to find the corresponding university-affiliated user. This will be the “real user” that will be linked in FOLIO as the proxy.  Address 2 has email (use to identify by webauth id) and name (for verification in QA).

**Comment by dlrueda** [comment]
2nd seluser
-oD name
   B userID (barcode)
   e expire date
   r user cat2
   Y.2002 address2 LINE (usually contains Proxy = <proxyname>)
   Y.2007 address 2 EMAIL (should be Stanford email, which hopefully is SUNetID@stanford.edu)

Saleem, Farzana Tabitha|2558565342|0||||607|1510|N|SPONSOR|
Saleem, Faranza (P=Kelly)|2557418812|20230630|FAC-PROX|Proxy's Address|rjkelly@stanford.edu|607|1511|N|PROXY|
Matsumoto, Yoshiko|2558016068|0||||608|1512|N|SPONSOR|
Matsumoto, Yoshiko (P=Nomura)|2551803248|20230630|FAC-PROX|Proxy = Nomura, Ryo|rnomura@stanford.edu|608|1513|N|PROXY|
Anderson, R. Lanier|2554354734|0||||609|1514|N|SPONSOR|
Anderson, Lanier (P=Lin)|2558564962|20220730|FAC-PROX|Proxy = Lin, Andrew|alin42@stanford.edu|609|1515|N|PROXY|
Fishkin, Shelley Fisher|2513141980|0||||610|1522|N|SPONSOR|
Fishkin, Shelley (P=Johnson)|2553188128|20230630|FAC-PROX|Proxy = Johnson, Annika|annikaj@stanford.edu|610|1523|N|PROXY|

**Comment by Laszlo-J** [comment]
Privileges unit created a sheet that shows the real proxy user record (SUNet ID) for each proxy ID. They also added the SUNet ID to the proxy ID's address 3 email:
[https://docs.google.com/spreadsheets/d/1hwDzWfB277K2NezG3sA5z_wa5tOuhjIPajuubdVXErM/edit#gid=0](url)

**Comment by dlrueda** [comment]
Waiting to see if Law provides any.  And need to add two Green Priv proxy-sponsor to new .dat file and use it during group loan selection

**Comment by dlrueda** [comment]
Law provided pseudopatron list, but will not have any proxy-sponsor setup in FOLIO
