### ISSUE TITLE
determine setting for a loan's original service point (for circ migration)

### ISSUE THREAD

**Issue by michelleif** [sul-dlss/FOLIO-Project-Stanford#217]
loans in FOLIO include service point where item was charged. When migrating loans from Symphony, IndexData needs to know what to put for original service point. We are not attempting to get this data from Symphony logs, so we need to decide what to put instead.

also note that whatever the service point is set to, that service point's calendar needs to be adjusted to be valid for checkout dates of all migrated loans.

check with circ subgroup to see which of these options they prefer:

1. set original service point to Green for all loans. advantage: this is easiest and we only have to adjust one Service Point Calendar to account for all original loan dates. 
2. set original service point to owning library. advantage: service point listed in circulation history for migrated loan will be more meaningful. disadvantage: need to check/adjust all service point calendars

**Comment by dlrueda** [comment]
Determined updating calendars is easy, just one line.
So we’ll set service point to correspond to owning library, and circ folks will update the calendars back to 2/1/1993 (the oldest charge date in Symphony).
