### ISSUE TITLE
extract loans for IndexData migration

### ISSUE THREAD

**Issue by michelleif** [sul-dlss/FOLIO-Project-Stanford#218]
for each loan, get from Symphony:
1. corresponding FOLIO Item barcode
2. patron “barcode”
3. original loan date
4. original due date

we also need to provide original service point, see #217

IndexData will start with a subset

**Comment by michelleif** [comment]
get about 500 loans

**Comment by dlrueda** [comment]
Selected 500 loans from all different libraries, all diff locations, item types, user profiles.

Suggested by Catherine/Kelly:
green/stacks
earth-sci/maps
Equipment
Eng
music/scores
Has-newbook
green/periodicals
media-mtxt/dvds
Courtesy users
education/kits
Something noncirc
hopkins/expeditions
art/locked stacks large med small
Earth-sci/microform
art/microform

**Comment by dlrueda** [comment]
After running it through script to see if item is in folio-test #232, only about 240 charges will be in the sample.
Sample put into FOLIO Implementation -> Data Migration -> SULCirc-IndexData folder, and IndexData granted access

**Comment by dlrueda** [comment]
Still in progress:
Needs documentation
Needs script to cut relevant fields instead of manual command line
 cut -f1,10,8,9,6,7 -d"|" charges_sample > charges_sample.needed_fields

**Comment by dlrueda** [comment]
Initial extract done 10/26.

Need another one after refresh of folio-test is complete

**Comment by dlrueda** [comment]
Currently manual step to concatenate group and non-group loan cdv files together at the end.  Otherwise done

**Comment by dlrueda** [comment]
Forgot, need to add a way to use a “manual” proxy-sponsor .dat file for a couple of proxy IDs that do not have a SUNetID for the proxy.
Should be migrated with sponsorID, no proxyID
