### ISSUE TITLE
extract requests for circ migration

### ISSUE THREAD

**Issue by michelleif** [sul-dlss/FOLIO-Project-Stanford#219]
first, provide sample of some requests to Charles

**Comment by dlrueda** [comment]
script in /s/SUL/Bin/folio_symphony_extract/Holds/get_nongroup_holds.ksh

Weirdness with group vs non-group holds.  selhold returns same holds whether you say -8N -8Y or omit -8 altogether (-8 selects holds on if they are associated with a group)

**Comment by dlrueda** [comment]
basic extraction of copy and title holds done.

Need to add in proxy-sponsor lookup in case it was the proxy that made the request
