### ISSUE TITLE
Clean up duplicate data import profile associations in TEST

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/FOLIO-Project-Stanford#223]

**Comment by ahafele** [comment]
@jgreben you might have discussed this already, but just a note to indicate that lots of testing is happening on folio-test with data import profiles. Those should not be wiped out.

**Comment by jgreben** [comment]
Just to clarify, there are not duplicate profiles, but there are duplicate profile association entries that should probably be cleaned up.
