### ISSUE TITLE
Hidden Data Export permissions

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#230]
We found that there are a number of hidden permissions related to data export and maybe some non hidden ones that need to be added to the appropriate psets. All "all permissions" have been added to the Admin for now.

**Comment by michelleif** [comment]
will add this to Permissions Subgroup agenda. 
Do you have a list of the permissions that need to be added to appropriate psets?
Didn't Admin already have all possible permissions?

**Comment by ahafele** [comment]
Admin did not have all _possible_ permissions. 
Here are the Data Export - all permissions. We took a guess and added everything Data Export related (some of which seemed duplicative). I think there might also be hidden ones, but not sure if they are required or included in these sets. Shelley may know. 
Data Export - all permissions
data export configurations - all permissions
data export jobs - all permissions
Data export: all permissions

**Comment by ahafele** [comment]
Per team meeting notes: 
- Added to Cat 6 on folio-test
- Add to matrix (Done 10-28-22 MF)
​​Data Export - all permissions
data export configurations - all permissions
data export jobs - all permissions
Data export: all permissions

@dlrueda assigned to you based on team meeting, but maybe could go to someone else?

**Comment by dlrueda** [comment]
I think this work was finished with the work done above?
