### ISSUE TITLE
script to check if item from symphony loan data is in folio-test

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/FOLIO-Project-Stanford#232]

**Comment by shelleydoljack** [comment]
@dlrueda the script, `/s/SUL/Bin/folio_symphony_extract/Loans/check_items_folio.sh` looks up the barcode in folio-test and appends a column with either 1 or 0 to a new file (1 = yes in folio, 0 = not in folio). The script takes 3 arguments: pipe-delimited data file, field number which contains barcode, output file. Example: `./check_items_folio.sh active_charges_test 11 test`. Input file and output file use $DATADIR, which is currently hardcoded to the same directory as the script, so that could change if you want to put stuff in `/s/SUL/Dataload`.

**Comment by dlrueda** [comment]
Cool!
