### ISSUE TITLE
Include 956s in the "Full Text" determination

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#236]
Treat 956s in the same way we do 856s and create holdings for those that are "full text".

**Comment by jermnelson** [comment]
@ahafele doing some initial testing of ingesting the 956; we'll need to adjust the FOLIO bib instance mappings to extract the URL from subfield `u` to add to the Instance record.

**Comment by ahafele** [comment]
@jermnelson ok. I'm working on making marc to instance mapping changes this week. I'll work on dev to get that addition put in the mapping.

**Comment by ahafele** [comment]
@jermnelson this has been done on dev - see example here in00000000094

**Comment by jermnelson** [comment]
@ahafele I loaded a couple of record loads into folio-dev with a draft [PR](https://github.com/sul-dlss/libsys-airflow/pull/194) that adds 956-based electronic holdings. Here are few examples for your review:

-  a721313
- a2018118
- a2018952
- a2028136
- a2017159
