### ISSUE TITLE
expired Symphony users with loans didn't get created in FOLIO

### ISSUE THREAD

**Issue by michelleif** [sul-dlss/FOLIO-Project-Stanford#239]
Darsi exported a loan sample from Symphony for Charles ([sample file](https://drive.google.com/file/d/1oEYky8_sKyQzuzFArAuZmpsYCFOBehhX/view?usp=share_link))

Charles tried to load and found many users not present in FOLIO

the missing users are[ in this file](https://drive.google.com/file/d/1Cvtu-_QydEItWXbHHe0DIoHnYIkWFq4h/view?usp=share_link)

checked a few in StanfordWho and they don't exist so probably are no longer in registry to load

**for users still that have a loan (or bill?) in the ILS but are not in the registry, we need to create those users in FOLIO**

**Comment by dlrueda** [comment]
And we do have code that does this, but either we didn’t run it for folio-test (??) or it didn’t work correctly.  Can we run it again, will that hurt anything?  Will it update users if they are in folio-test, but create if they aren’t (like the nightly user load?)

**Comment by jgreben** [comment]
Fixed by https://github.com/sul-dlss/folio-tasks/pull/101 and `/s/SUL/Bin/folio_symphony_extract/Users/expired_users_tsv.sh`. See also `/s/SUL/Bin/folio_symphony_extract/Users/README.txt`
