### ISSUE TITLE
itemcats - figure out where to map

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#240]
We will need to somehow map at least some of the info in item cat2

**Comment by ahafele** [comment]
itemcat1 and 2 lists are being output and we will review with @dlrueda and Vitus. We can likely use stat codes.

**Comment by dlrueda** [comment]
item cat 1 counts
14 BUSCORPRPT|
 211117 BW-CHILD|
 36461 BW-PARENT|
   37 CATEVAL|
  3124 EEM|
  9577 E-THESIS|
 18830 LEVEL3-CAT|
 136294 LEVEL3OCLC|
 606084 MARCIVE|
   9 M-MARCADIA|
   1 PC-FALLSEM|
  349 PC-FQTR|
   3 PC-F-SPSEM|
   6 PC-FWSQTRS|
  134 PC-PERM|
  358 PC-SPQTR|
   41 PC-SUQTR|
  4167 PC-TOSS|
  504 PC-WQTR|
 203952 RECYCLE|
 10614 SALPROB1|
  630 SALPROB2|
   9 TEAMS|
  784 W1SAL3|
  364 W2SAL3|
 36450 WESTBRO1|
 13212 WESTBRO2|
  2453 WESTGOL1|
  258 WESTGOL2|
  3834 WESTGOL3|
  7505 WESTGOL4|
  4027 WESTGOL5|
  1045 WESTGOL6|
  1008 WESTGOL7|
  1320 WESTGOL8|
  2205 WESTGOL9|
  6573 WESTSIL1|
  3227 WESTSIL2|
  4737 WESTSIL3|
  4213 WESTSIL4|
  4669 WESTSIL5|
  9425 WESTSIL6|
  8132 WESTSIL7|
  6044 WESTSIL8|
  7757 WESTSIL9|

item cat 2 counts
8467308 |
2990077 DIGI-SCAN|
 247086 DIGI-SENT|
  334 FED-WEED|
   2 JUVENILE|
 12395 NONTAXABLE|
   1 PDIGI-SENT|
   1 PHYSTOR|
2200637 TAX=8.25|
   5 UNKNOWN|

**Comment by ahafele** [comment]
@vitustang Hi Vitus, On Wednesday we would like to talk about the above lists. We need to figure out where to put this information in FOLIO, if we need to maintain it. I'm thinking stat codes, but there may be some examples that would be more appropriate elsewhere.

**Comment by ahafele** [comment]
Vitus has created a spreadsheet and will investigate answers for each. https://docs.google.com/spreadsheets/d/1r-s7aTIHXgL97o-MV_TFURzLQoPQY1dHy60Lj5unejU/edit#gid=2065858581

**Comment by ahafele** [comment]
Per Metadata Subgroup, we will create Instance, Holding, Item stat code categories to use for the above item categories. Created for use on folio-test.

**Comment by ahafele** [comment]
I have created the code types and codes on folio-test for all that have been confirmed so far per.
We should complete the task to migrate https://github.com/sul-dlss/folio-tasks/issues/113 before we wipe folio-test.

**Comment by ahafele** [comment]
@vitustang are the descriptions found in https://docs.google.com/spreadsheets/d/1r-s7aTIHXgL97o-MV_TFURzLQoPQY1dHy60Lj5unejU/edit#gid=2065858581 usable as-is for the **stat code name** field (per the metadata subgroup conversation 12/15)?

**Comment by vitustang** [comment]
@ahafele Yes. For the LEVEL3 stat code, you can just use "Level 3 catalog record". The rest you can just use their existing descriptions

**Comment by ahafele** [comment]
Descriptions have been added to `stat code name` on folio-test

**Comment by ahafele** [comment]
@dlrueda can this ticket be closed or do we need another for the actual mapping work?

**Comment by ahafele** [comment]
Completed. Mapping ticket here at https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/271
