### ISSUE TITLE
Capture loan types for data migration between releases

### ISSUE THREAD

**Issue by Laszlo-J** [sul-dlss/FOLIO-Project-Stanford#241]
Only move loan types created by Circ subgroup. Don't migrate/add precanned FOLIO loan types.

List of current types: https://folio-test.stanford.edu/settings/inventory/loantypes
(Ignore Standard book loan and Standard periodical loan=precanned but can't delete due to association with Inventory items.)

**Comment by dlrueda** [comment]
I think I misunderstood from the meeting.  I don’t think we can NOT load the default reference data, so we might be stuck with have “Standard Loan” on the list, it’s just safer to not muck with the default reference data when we start to do upgrades.

But we DO need to get the loan types the circ group has created into our next instances of FOLIO.  

Question for developers: is it easier to create a tsv of loan types to create?  Or easier to extract from folio-test to import into next instance?

**Comment by dlrueda** [comment]
Already in a different rake task
