### ISSUE TITLE
Alternate Representations (linked 880s) are not displaying in instance records as expected

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#242]
There are a number of linked 880 fields that are not displaying in the instance record that should be. It does not seem to be consistent. 
The default MARC to instance mapping should map any linked 880 tag that exists in the mapping. 

Using data import I loaded a number of marc records on folio-dev and all fields are displaying as expected. 

folio-dev
in00000000091 - see 500, 504
in00000000087 - see 505

Marc records loaded through our migration process are not displaying fields as expected. 

folio-test
12196508 - linked 505 does not display
13798527 - linked 700 does not display
12257361 - 880$6 505 does not display
12698851 - linked 245 does but not, e.g. 264
11993351 - 100 does, 500 does not

**Comment by ahafele** [comment]
@dlrueda could we review this together when you have time?

**Comment by dlrueda** [comment]
Alissa and I chatted, and think Jeremy will have to look into why this is happening.  EBSCO tools are supposed to use the mapping

**Comment by jermnelson** [comment]
@ahafele here is what I've figured out so far. In our `marc-bib` mapping rules for the 880 retrieved from the Okapi `/mapping-rules/marc-bib`:

```
[{'target': '',
  'subfield': ['6'],
  'description': 'Field for target post-processing based on first 3 digits in subfield 6',
  'fieldReplacementRule': [{'targetField': '700', 'sourceDigits': '100'},
   {'targetField': '710', 'sourceDigits': '110'},
   {'targetField': '711', 'sourceDigits': '111'},
   {'targetField': '246', 'sourceDigits': '245'}],
  'fieldReplacementBy3Digits': True}]
```
the `fieldReplacementRule` property is being used in the `folio_migration_tools` [Bibs mapper](https://github.com/FOLIO-FSE/folio_migration_tools/blob/08d958519ef2c78480268c8910f5fb3751b2742c/src/folio_migration_tools/marc_rules_transformation/rules_mapper_bibs.py#L183-L202) to extract the MARC tag from the first 3 digits in subfield 6 in the 880 field.  A match is attempted between the `sourceDigits` property in each row of the `fieldReplacementRule` property and if found the `targetField` property value is used to extract the mapping and the value of the 880 is saved to the FOLIO Instance record based on the mapping of the `targetField`. 

If there is not a `sourceDigits` value in the `fieldReplacementRule` property (from the list above 264, 500, 505, and 700 are not in the `sourceDigits` list), the 880 values are ignored. 

Using the data import app, I just imported the four records (see https://folio-dev.stanford.edu/data-import/job-summary/b227ba5a-8e78-45ac-9b48-5a9cc0b47fe1?sort=recordNumber) and I believe the data-import app is not using the mapping rules from above but is doing the 880 linkage from within the app.

**Comment by jermnelson** [comment]
Once this upstream [ticket](https://github.com/FOLIO-FSE/folio_migration_tools/issues/426) for the `folio_migration_tools` is fixed, should resolve this issue.

**Comment by fontanka16** [comment]
@jermnelson  working on it now. Hopefully done EOD today

**Comment by ahafele** [comment]
@jermnelson adding a note here - I reviewed the ckeys above on folio-dev and all looks good!!
