### ISSUE TITLE
Data Export and Bulk Update App

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#243]
Needs some config work we think. See slack info here - https://folio-project.slack.com/archives/C9BBWRCNB/p1676416623161629 

https://github.com/folio-org/mod-data-export-worker#environment-variables

**Comment by ahafele** [comment]
Data Export permissions ticket - https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/230

**Comment by jgreben** [comment]
AWS S3 needed explicit configuration to create folders in the bucket.

```
"Resource": [
                "arn:aws:s3:::sul-folio-development/*",
                "arn:aws:s3:::sul-folio-development"
            ]
```

**Comment by jgreben** [comment]
There is an issue with folio being able to read back the contents of the S3 Bucket. The data is able to be written to S3, but not read back to be downloaded or subsequently deleted.
