### ISSUE TITLE
staff identify correct BW-PARENT for records with multiple BW-PARENT and BW-CHILD item records

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/FOLIO-Project-Stanford#244]
In this [comment](https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/234#issuecomment-1302370394) on [ticket 234](https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/234)  we decided to create a separate item tsv for the BW-CHILD records and to put the barcode of the BW-PARENT in it so that when we make the bound-with relationship in FOLIO, we have the parent record's barcode to lookup or derive the FOLIO item record UUID. Of the 204,418 total bibs with at least one BW-CHILD item (not WITHDRAWN), there are 2,846 bib records with more than one BW-CHILD record. These records have multiple 590 fields for identifying the BW-PARENT but the data is varied (not all have the parent's barcode in subfield b). How should 590 subfield a be parsed and combined with subfield c to identify the parent item's barcode? 

An additional issue is that some of these have more than one BW-CHILD item record per call number and these item records have more than one item xinfo field note. How do we migrate these? How do we identify which BW-CHILD goes with which BW-PARENT from the 590 note? 

I put the data that needs analysis in the spreadsheet [multiple BW-CHILD on single bib](https://docs.google.com/spreadsheets/d/1OxC2NpHkG_wg6AnJxAR2XsjyWHWUVyLNG1BCt_cRs6w/edit?usp=sharing) in the metadata folder of the FOLIO Implementation at Stanford drive.

**Comment by ahafele** [comment]
Vitus will take a look at the spreadsheet.

**Comment by shelleydoljack** [comment]
[Spreadsheet for too many BW-PARENT](https://docs.google.com/spreadsheets/d/1sjT7-Ju6zRunlHG5QAIQTp4kdA5UC2beCFmW54ev-6o/edit?usp=sharing)

**Comment by shelleydoljack** [comment]
[Boundwiths folder](https://drive.google.com/drive/folders/1wo5XfUSnxUx3chf9dOJU6sYmbY_8lwVP?usp=share_link) with spreadsheets for staff review

**Comment by ahafele** [comment]
Vitus working on plan with Data Control. Should be able to finish before August migration time. 
Note: There are a small number of bound-withs that have been linked using the symphony functionality. How do we find these? BCA? Vitus will investigate.

Outstanding questions: we still need to have stat codes? We still need to figure out the call number/item record situation because they aren’t 1:1, e.g. we can’t put child call number info definitively on child holding. And what to do with multiple copies that have notes. Will come to light through Data Control review.

**Comment by shelleydoljack** [comment]
New spreadsheets in [FOLIO Implementation drive > Metadata/Inventory > Boundwiths > March15](https://drive.google.com/drive/folders/1tMsRsx6zTJw0nC1dGxtvST_oaMY6Po5a?usp=sharing).

**Comment by shelleydoljack** [comment]
> Vitus working on plan with Data Control. Should be able to finish before August migration time. Note: There are a small number of bound-withs that have been linked using the symphony functionality. How do we find these? BCA? Vitus will investigate.
> 
There is a flag in selcallnum for this:
```
-b selects callnums of the specified bound-with level.  NONE, CHILD, and
     PARENT are valid options.
```
```
sirsi@bodoni /s/SUL/Users/sdoljack> trs selcallnum -bCHILD -oCN > child_selcallnum
Symphony call number selection 3.7.1 started on Wednesday, March 15, 2023, 3:09 PM
  The callnum file will be read sequentially by primary key.
  The catalog key will be written to standard output.
  The callnum primary key will be written to standard output.
  Callnums will be selected if the bound-with level is CHILD.

		*** SQL ***
SELECT catalog_key,call_sequence FROM callnum  WHERE (bound_with = -1) ORDER BY catalog_key,call_sequence
		*** SQL ***

  13818772 callnum record(s) considered.
  368 callnum record(s) selected.

sirsi@bodoni /s/SUL/Users/sdoljack> trs selcallnum -bPARENT -oCN > parent_selcallnum
Symphony call number selection 3.7.1 started on Wednesday, March 15, 2023, 3:10 PM
  The callnum file will be read sequentially by primary key.
  The catalog key will be written to standard output.
  The callnum primary key will be written to standard output.
  Callnums will be selected if the bound-with level is PARENT.

		*** SQL ***
SELECT catalog_key,call_sequence FROM callnum  WHERE (bound_with > 0) ORDER BY catalog_key,call_sequence
		*** SQL ***

  13818773 callnum record(s) considered.
  122 callnum record(s) selected.
```

**Comment by shelleydoljack** [comment]
Records using the Symphony boundwith linking feature attached.
[parent_selcallnum.txt](https://github.com/sul-dlss/FOLIO-Project-Stanford/files/11616456/parent_selcallnum.txt)
[child_selcallnum.txt](https://github.com/sul-dlss/FOLIO-Project-Stanford/files/11616458/child_selcallnum.txt)

**Comment by dlrueda** [comment]
Vitus/Datacontrol will clean up SUL.  Alissa will talk to Ryan about Law getting theirs into a state that will migrate.

**Comment by ahafele** [comment]
Ryan at Law is working on Law records. I've passed on this [documentation](https://consul.stanford.edu/display/MD/Bound+withs) and directed any related questions to Vitus.

**Comment by shelleydoljack** [comment]
Harald reports on 6/26/2023: finished working on the “Too Many Parents” bound-with report.

**Comment by ahafele** [comment]
Ryan reports that he has finished updated Law bound-withs done with the Symphony feature.
