### ISSUE TITLE
HTML in item notes

### ISSUE THREAD

**Issue by michelleif** [sul-dlss/FOLIO-Project-Stanford#245]
HTML encoding needs to be removed from item notes. 

--------------------------
<strong>Submitted By: </strong>jkalchik@stanford.edu
<strong>Description: </strong>Barcode 36105123269453 has 3 techstaff notes in Symphony that has become one techstaff note in FOLIO with html encoding between them: EDI receipt; &#124;atf:GREEN 06/18/14 batch; &#124;atf:SAL 07/28/17 batch
<strong>Instance HRID: </strong>`a6853207`
<strong>Patron barcode: </strong>``
<strong>FOLIO App: </strong>Inventory
<strong>Urgency: </strong>It's not urgent.
<strong>Browser: </strong>Chrome

**Comment by ahafele** [comment]
I was seeing this html issue before and thought it was fixed. I'll look into it.

**Comment by ahafele** [comment]
@jlkalchik I looked back at the initial ticket and we did make the decision to concatenate the notes into one. But the html is obviously incorrect. Let me know if you think the concatenation of the notes is a problem.

**Comment by shelleydoljack** [comment]
Made .bak of `/s/SUL/Bin/pipe2tsv_json` and updated the regex substitution to rid the `pipe a` chars from the selved output.
