### ISSUE TITLE
Update Orders - Ship to

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#246]
Found some missing through orders QA so Suzette has made an update to the Ship to information in the Orders mapping. 

Line 16 here - https://docs.google.com/spreadsheets/d/13bh1Dd-v_tC0A5iepeTxWVBjj2JLz3lmvFglFDjOcD4/edit#gid=215993364 

Added - Symphony Order Bib Entry: SUL Acquisitions = ACQ, AFRACQ, DIGACQ, GEACQ, GOV, MEACQ. SUL Serials = SER, MESER. SUL EAL = EALACQ. SUL Music = MUSACQ

@shelleydoljack I didn't see a tsv where this info would go, but let me know if I missed it.

**Comment by shelleydoljack** [comment]
The tenant addresses are in: https://docs.google.com/spreadsheets/d/1b8w7luLvrlnwOoShlq9MgTfsvqLVMqVub8aG8RcHl9w/edit?usp=sharing

The address "code" is the name field, all uppercase with the spaces replaced with underscores (see https://github.com/sul-dlss/folio-tasks/blob/8decc1c5599998b62c4c2bc8481dc914ed812d74/tasks/helpers/tenant.rb#L136 ).

The "mapping" for the order bib entry fields to tenant address codes is at https://github.com/sul-dlss/folio-tasks/blob/8decc1c5599998b62c4c2bc8481dc914ed812d74/tasks/helpers/orders/orders.rb#L110-L119 . It sounds like there isn't an issue with the Bill to being assigned? Just to confirm, bill to uses the order library to look up in the mapping the address code. The ship to uses the order library if it is "LAW", else it uses the bib entry in the orderline.

Based on what was entered in https://docs.google.com/spreadsheets/d/13bh1Dd-v_tC0A5iepeTxWVBjj2JLz3lmvFglFDjOcD4/edit#gid=215993364&range=B16 it looks like we just need to add "AFRACQ, DIGACQ, GEACQ, GOV, MEACQ" to map to "SUL_ACQUISITIONS" in the mapping and not add these as additional tenant addresses. Is there a default Ship to address we should use in case we still find orders with bib entry values we did not account for in the mapping? As you can tell, right now we just assign "nil" if the bib entry is not found in the mapping.

**Comment by ahafele** [comment]
The default Ship to should be ACQ

**Comment by shelleydoljack** [comment]
work on ticket https://github.com/sul-dlss/folio-tasks/issues/109
