### ISSUE TITLE
Make SDR holdings based on Coordinates

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#252]
Right now we take any sdr purl and make a holdings record for SUL SDR. The coordinates would prefer that if the instance record belongs to them (based on 596), we create a holdings for their library. We need to make the locations first. 

- HILA SDR
- Law SDR
- Business SDR

@dlrueda should I make these locations manually or should they get added to a spreadsheet?

**Comment by shelleydoljack** [comment]
Locations have been made in dev, test, stage and added to locations.tsv in FolioOps migration files.
