### ISSUE TITLE
Vendor account_number needs to be added

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#255]
SUL and Law would like Symphony Orderline field: ACCOUNT mapped to FOLIO Vendor -- account_number in the POL. (See line 103 [here](https://docs.google.com/spreadsheets/d/13bh1Dd-v_tC0A5iepeTxWVBjj2JLz3lmvFglFDjOcD4/edit#gid=215993364) )

**Comment by shelleydoljack** [comment]
Tried test loading some data to folio-dev unsuccessfully. First, the "vendorDetail" object in a po line requires an "instructions" field. When I try to post an order with this new object, I get this error:
```
{"errors"=>
  [{"message"=>"Order cannot be open as the associated vendor not found",
    "code"=>"vendorNotFound",
    "parameters"=>
     [{"key"=>"id", "value"=>"da4fa376-b6e5-4071-9452-01c0e74934dd"}]}],
 "total_records"=>1}
```
 Yet the vendor does exist in folio-dev with that UUID so 🤷 . I wonder if there is something missing from the vendor record for these fields in the order to be filled in.

**Comment by shelleydoljack** [comment]
Tried a second time, this time I added an account number to the vendor record in the Organizations app and then looked at the order line but no data was there for vendor detail. Then I did a PUT to `/orders-storage/po-lines/` (since the business logic endpoint was giving me the business) with the vendorDetail data:
```
 "vendorDetail": {
    "instructions": "test instructions",
    "vendorAccount": "3250-74"
  },
```
and looked at it in FOLIO. For PO line SUL6608198-1, it shows the data i entered in the vendor record in the Organizations app.
![Screen Shot 2023-01-06 at 4.29.28 PM.png](https://images.zenhubusercontent.com/62964511c137fa350131daff/a2fd0190-f443-4cd1-ba58-0cc6572d90c3)

Then I deleted the data under Account for the vendor in the Organizations app and now it shows the account number as the way I modified it using a PUT to the storage endpoint.

**Comment by ahafele** [comment]
Hold while @scanedastanford investigates

1. Placeholder instructions to vendor = space
2. Adjust mapping for account number
3. Put for each order using the storage endpoint (could result in issues later due to not using business endpoint)

**Comment by scanedastanford** [comment]
Change to: map Symphony Orderline field: ACCOUNT to FOLIO PO Note.
Mapping spreadsheet updated.

**Comment by shelleydoljack** [comment]
@scanedastanford we currently get the ACCOUNT field from all the orderline extended info fields. Should we change this so that it maps to FOLIO purchase order lines? Or do you want all of the ACCOUNT fields to map to one PO note?

**Comment by scanedastanford** [comment]
The order would have the same ACCOUNT repeated in all its orderlines. So it is possible to map it just once to the PO note? Or would it repeat in the PO note if the order had multiple orderlines?

**Comment by shelleydoljack** [comment]
I tested this in folio-test and was able to post the order after I first deleted it. Not sure why it worked for this order and not the other one I was trying to do in folio-dev. See https://folio-test.stanford.edu/orders/view/6d6ecd53-b545-5a61-928e-6c8c9170410e

This was the vendorDetail I added to the po line in the data I posted to `/orders/composite-orders`:
```
"vendorDetail": {
        "instructions": "",
        "vendorAccount": "22-SER-NT"
      }
```
Do we still want to map orderline xinfo field ACCOUNT to corresponding FOLIO po line?

**Comment by scanedastanford** [comment]
Great! Yes, please map orderline xinfo field ACCOUNT to the corresponding FOLIO po line.

**Comment by shelleydoljack** [comment]
I tested again with the record that was giving me issues when I first tried adding vendorDetail and it worked again. See https://folio-test.stanford.edu/orders/view/be1eaa93-4847-57d0-98fe-687032eba727 .

**Comment by ahafele** [comment]
Suzette confirms this can be closed
