### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#258]
1.  Is the re-encumber checkbox still only for ongoing orders? Because one-time encumbrances can be rolled over during FYRO. Is it possible to add to one-time orders?

2. Can PO Numbers include _ (underscores)? Some include dashes currently which get stripped in FOLIO. Acquisitions would like to do a data cleanup project to remove and also notify vendors for future orders, but would like to know what they can be replaced with, if anything.

**Comment by shelleydoljack** [comment]
For 1 - API docs still show:
```
 "reEncumber": {
      "description": "indicates this purchase order should be re-encumbered each fiscal year. Only applies to ongoing orders",
      "type": "boolean",
      "default": false
    },
```
Does folio let you check the box when creating an order through the UI?

For 2. the API docs show:
```
"poNumber": {
      "description": "A human readable ID assigned to this purchase order",
      "type": "string",
      "pattern": "^[a-zA-Z0-9]{1,22}$"
    }
```
In the folio-tasks code, I'm am stripping out the forward slashes, underscores, and dashes: ` order_id.gsub(%r{[/_-]}, '')`

**Comment by shelleydoljack** [comment]
Also, I think just alerting vendors about the change in PO number is what needs to be done. No need spending time on a cleanup project that the code will remove when we migrate.

**Comment by ahafele** [comment]
Thanks Shelley! @scanedastanford see above comments about questions from Orders QA.

**Comment by ahafele** [comment]
When creating orders the check box is checked by default for both Ongoing and One Time orders. Acquisitions is still considering if they want this checked and if so for which order types.

**Comment by ahafele** [comment]
Suzette: Leave ongoing orders as checked. One-time not. Acq still deciding on rollover options. 
Likely that we could check the box on on-time since the UI allows it.
