### ISSUE TITLE
Errors with ckey TSV files

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/FOLIO-Project-Stanford#260]
During the 2022-11-16 to 2022-11-17 migration run, the following errors occurred due to problems in the tsv files:

## ckeys_14200000_14249999.tsv
For ckey 14247465, the following rows were generated with extra tabs in the VOLUME_INFO column:

```
14247465	MAP	LC	G6000 S10 	B.N4 SERIE I	ZNO. 16		36105228520107  	EARTH-SCI	LOCKED-MAP	LOCKED-MAP	LIBUSEONLY
14247465	MAP	LC	G6000 S10 	B.N4 SERIE I	ZSUPP. 1		36105228520065  	EARTH-SCI	LOCKED-MAP	LOCKED-MAP	LIBUSEONLY
14247465	MAP	LC	G6000 S10 	B.N4 SERIE I	ZSUPP. 2		36105228520099  	EARTH-SCI	LOCKED-MAP	LOCKED-MAP	LIBUSEONLY
14247465	MAP	LC	G6000 S10 	B.N4 SERIE I	ZSUPP. 2A		36105228520057  	EARTH-SCI	LOCKED-MAP	LOCKED-MAP	LIBUSEONLY
```

## ckeys_14300000_14349999.tsv
For ckey 14305013, the BASE_CALL_NUMBER field starts with a double quotation mark that causes an EOF error:

```
14305013	MARC	ALPHANUM	"UNCTAD/DTL/STICT/2022/6		36105232099973  	GREEN	INTL-DOCS	INTL-DOCS	GOVSTKS
```

## ckeys_14350000_14399999.tsv
For ckey 14393729 the following rows were generated with extra tabs in the VOLUME_INFO column:

```
14393729	MAP	LC	G6000 S10 	B.N4 SERIE VI	ZNO. 18		36105228520081  	EARTH-SCI	LOCKED-MAP	LOCKED-MAP	LIBUSEONLY
14393729	MAP	LC	G6000 S10 	B.N4 SERIE VI	ZNO. 19		36105228520032  	EARTH-SCI	LOCKED-MAP	LOCKED-MAP	LIBUSEONLY
14393729	MAP	LC	G6000 S10 	B.N4 SERIE VI	ZNO. 20		36105228520131  	EARTH-SCI	LOCKED-MAP	LOCKED-MAP	LIBUSEONLY
14393729	MAP	LC	G6000 S10 	B.N4 SERIE VI	ZNO. 21		36105228520123  	EARTH-SCI	LOCKED-MAP	LOCKED-MAP	LIBUSEONLY
14393729	MAP	LC	G6000 S10 	B.N4 SERIE VI	ZNO. 22		36105228520115  	EARTH-SCI	LOCKED-MAP	LOCKED-MAP	LIBUSEONLY
14393729	MAP	LC	G6000 S10 	B.N4 SERIE VI	ZNO. 23		36105228520040  	EARTH-SCI	LOCKED-MAP	LOCKED-MAP	LIBUSEONLY
```

**Comment by dlrueda** [comment]
I have corrected those 3 files to get rid of the extra tabs, and the “ character.  I have also updated the data in WorkFlows to hopefully remove the extra tabs in the call numbers, and the “ character.

So you can try to load those 3 to folio-dev again. 

I am dumping the data again tonight so I hope the data will be clean on this next dump.

**Comment by jermnelson** [comment]
Fixed, closing this issue.
