### ISSUE TITLE
Export copy number in 3rd field of item key and map to FOLIO item copy number

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#261]

**Comment by jermnelson** [comment]
Related ticket https://github.com/sul-dlss/folio_migration/issues/36

**Comment by dlrueda** [comment]
Confirming that the 3rd field of the item key is definitely the copy number field (and changes if you change the copy number of the item in WorkFlows)

**Comment by shelleydoljack** [comment]
scripts updated now so that tsv files get copy number in 3rd column, named "COPY".
