### ISSUE TITLE
Add cat1 and cat2 Columns to Item TSV Export

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/FOLIO-Project-Stanford#263]

**Comment by shelleydoljack** [comment]
ITEM_CAT1 column added to the generate_marc_items_tsv.ksh and on_order_items_tsv.rb scripts.

**Comment by dlrueda** [comment]
and to find_parentbw.pl

Will need to add item_cat2, and callseq/item key (replacing catkey output) to all 3 scripts

**Comment by shelleydoljack** [comment]
Needed to re-arrange columns in tsv files. Now:
"CATKEY|CALL_SEQ|COPY|BARCODE|LIBRARY|HOMELOCATION|CURRENTLOCATION|ITEM_TYPE|ITEM_CAT1|ITEM_CAT2|ITEM_SHADOW|CALL_NUMBER_TYPE|BASE_CALL_NUMBER|VOLUME_INFO|CALL_SHADOW|FORMAT|CATALOG_SHADOW|"

**Comment by shelleydoljack** [comment]
new columns added and columns rearranged in generate_marc_items_tsv.ksh, on_order_items_tsv.rb, and find_bwparents.pl scripts and column containing barcode (4th) updated in item_xinfo.ksh script.
