### ISSUE TITLE
Change user import to add expire date?

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#266]
In FOLIO Community Implementation Group meeting, two people (Ian of Bywater and Kyle of EBSCO) said that we should be loading users who no longer have a valid affiliation as expired (expire date yesterday, or today) instead of what we currently do, which is make them inactive.

FOLIO is supposed to, based on the expire date of the user record, switch the user to Inactive status.
Need to check that FOLIO actually does this.  If it works, switch user load to set expire date to today instead of set to Inactive

**Comment by jgreben** [comment]
FOLIO does indeed make expired users inactive.

**Comment by jgreben** [comment]
Reopen if someone asks for better expire dates.
