### ISSUE TITLE
Install Nolana

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/FOLIO-Project-Stanford#270]
- https://docs.google.com/spreadsheets/d/1_6QWDtS9zRcwgvc8pDdbKq10A6629y4OU39DsNBApF0
- QA complete

- [x] folio-(dev) nolana-hotfix-1

- [x] folio-test nolana-hotfix-1

- [x] folio-stage nolana-hotfix-1

- [x] folio-prod nolana-hotfix-1

**Comment by jgreben** [comment]
https://wiki.folio.org/display/REL/Nolana+%28R3+2022%29+Release+Notes

**Comment by michelleif** [comment]
close this now that Nolana is installed on PRD?
