### ISSUE TITLE
Map itemcat to stat code

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#271]
itemcat1 is now included in the item tsv files and should be mapped according to - https://docs.google.com/spreadsheets/d/1r-s7aTIHXgL97o-MV_TFURzLQoPQY1dHy60Lj5unejU/edit#gid=965967754 (Mapping sheet). @jermnelson I assume this is for you? If this should be a tsv in the folio ops drive just let me know. 

Note: All stat codes exist on folio-test.

**Comment by shelleydoljack** [comment]
If an itemcat1 is in the data but not the mapping, what should happen to it? BW-CHILD and BW-PARENT come to mind.

**Comment by ahafele** [comment]
There are many that are being left behind. Vitus thought BW-CHILD and BW-PARENT might be useful for reporting, but for now decided not to migrate. There are some outstanding questions on the problematic bound-withs - examples that aren't 1:1, e.g. we can’t put child call number info definitively on child holding - in these cases a stat code could be useful but for now, anything that is not in the mapping should be left behind.

**Comment by jermnelson** [comment]
Hi @ahafele, the `folio_migration_tools` can easily handle the mapping for itemcat1 values to stat code for FOLIO Items. Adding the mapping for FOLIO Instances records will require post-processing as the `folio_migration_tools` for Instances only accepts MARC records and the itemcat1 value is in the tsv file.

**Comment by ahafele** [comment]
Still need to tackle itemcat2. Right now the migration tools don't allow for 2 columns to same folio field. Punted for nolana load to dev.

**Comment by ahafele** [comment]
@jermnelson maybe handle the itemcat2 in tsv file, then Darsi will output the itemcat1's in either 1 or 2 additional files. Will follow up after some thought. 

@ahafele find some examples of records with both

Related to FOLIO-Project-Stanford #305

**Comment by shelleydoljack** [comment]
Need some sample ckey ranges to check that this is working.

**Comment by dlrueda** [comment]
from file ckeys_12700000_12749999.tsv
items 36105050766059 and 36105050766448
have ITEM_CAT1 MARCIVE and ITEM_CAT2 FED-WEED

from file ckeys_12750000_12799999.tsv
item 36105027285993 has ITEM_CAT1 WESTSIL8 and ITEM_CAT2 DIGI-SENT
item 36105008214913 has ITEM_CAT1 WESTGOL8 and ITEM_CAT2 DIGI-SENT
