### ISSUE TITLE
Investigate how to suppress at item/holdings/instance level during migration

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#273]
In Symphony, we can suppress a record from discovery by:

* assigning a “shadowed” location (would correspond to FOLIO holding being suppressed)
* clicking the shadow checkbox at the item level (would correspond to FOLIO item being suppressed)
* clicking the shadow checkbox at the call number level (probably corresponds to FOLIO holding being suppressed?)
* clicking the shadow checkbox at the catalog level (would correspond to FOLIO instance being suppressed)

What do we need to do in airflow to suppress at the right level in FOLIO, depending on the .tsv file “shadow” columns, or on particular locations?

**Comment by ahafele** [comment]
Set suppress flag at item level if 
- home and current locations from ticket https://app.zenhub.com/workspaces/folio-at-stanford-628d6cab8c42a90248e5eb79/issues/gh/sul-dlss/libsys-airflow/226
- tsv column item_shadow = 1
- tsv column call_shadow = 1

Set suppress flag at Instance level if
- tsv column catalog_shadow = 1

@jermnelson to investigate options

**Comment by dlrueda** [comment]
Shadowed locations in Symphony, to be suppressed at item level in FOLIO (draft)
FED-DOCS-S
WITHDRAWN
MANNING
INSTRUCTOR
RESV-URL
SEL-NOTIFY
EDI
CDPSHADOW
TECHSHADOW
STAFSHADOW
SHADOW
MISS-INPRO
LOST
SSRC-FIC-S
SSRC-SLS
MAPCASES-S
MAPFILE-S
BENDER-S
DISCARD
3FL-REF-S
NEG-PURCH
TECH-UNIQ
SPECM-S
SPECA-S
SPECB-S
SPECAX-S
SPECBX-S
SPECMX-S
SPECMEDX-S
SPECMED-S
LOST-CLAIM
EAL-TEMP-S
LOST-PAID
E-REQST-S
E-ORDER-S
E-INPROC-S
LOCKSS
BASECALNUM
INSHIPPING
SALDCPROJ2
SALDCPROJ1
POPUPLIB
W7-STFSHD
COLDSTOR

**Comment by ahafele** [comment]
Above list needs review to figure out what to do with each. 

@dlrueda it doesn't look like you can make an entire folio location be suppressed in the way we do now, but I'm wondering what active and inactive results in?

**Comment by dlrueda** [comment]
From searching Folio wiki, looks like Inactive locations are those that are no longer valid, i.e., shouldn’t be assigned to items anymore (but it allows those that were already assigned that location to keep it).  So shouldn’t really be used to indicate shadowed/suppressed etc
