### ISSUE TITLE
Need Symphony holding code to FOLIO holdingID mapping

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/FOLIO-Project-Stanford#274]
Research was done on ticket https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/268

Basically, when loading orders there is a location object in the purchase orderline that should either contain a locationId or holdingId. In order for the Receiving app to know which holdings record to link receiving history and acquisition data, we need to be creating purchase order lines with the holdingId and not locationId. Thus, this spreadsheet of [Symph holding codes to FOLIO location mapping](https://docs.google.com/spreadsheets/d/19nXAJgwUjXekwEpf4iOIyA1eWcaaKIo6wSfQg8Guqo4/edit?usp=sharing) can't be used for the orders and a new mapping needs to be made to get from a Symphony holding code to FOLIO holdings record UUID.

**Comment by shelleydoljack** [comment]
Discussed with Jeremy how holdings record ID's are created. The holdings UUID is made up of ckey, permanentLocationId and callnumber. Currently, the order selection we are not getting out the callnumber. We could add -oN to selorderlin to get the call num key out, but then we we need use that to get callnumber from selcallnum.

For a title, like Science ckey 3195846, i get a bunch of callnum keys, not just one. I could output base callum and sort to get the unique, which gives me two: Q1 .S34 and 505 .S416. I can use the combination of instanceId, callNumber, and permanentLocationId to lookup the holdings UUID: `https://${OKAPI_URL}/holdings-storage/holdings?query=instanceId==7213c6c8-1fa5-5376-83a6-0250b825d19c and callNumber=="505 .S416" and permanentLocationId==d6349eca-00c6-4d97-ace1-21338c1cc691` . But how do I know which call number is the one to use?

**Comment by shelleydoljack** [comment]
Hmm, come to think of it, when I tested this with ckey 3195846, I was using the catkey as input to selorderlin rather than a specific orderline key. I think using the specific orderline key will get us the one callnum key where the linkage is.

**Comment by shelleydoljack** [comment]
@dlrueda  In the orders for migration script, where we mimicked the rollover reports, the selection criteria starts with selvendor, selvendcyc, selorder, selorderlin, seldist, selfunding, etc. In the selorderlin call, we input the order key and can get out the callnum key, but for this example ckey, this is the call number we get back with that:
```
echo "SUL|2023|909429F06" | trs selorder -iJ -oO 2> /dev/null | trs selorderlin -iO -oN 2> /dev/null | selcallnum -iN -oD 2> /dev/null
XX(3195846.2579)|
```
This item is not a BASECALLNUM type, so maybe that's why we don't get an actual call number. I wonder how many orderlines are linked to call segment where we don't get the call number we need to lookup the holdings in FOLIO.

**Comment by shelleydoljack** [comment]
Thinking about this more, when the orderline is linked to a call segment that just has an auto-generated call number, such as "XX(3195846.2579)" or a call number that wasn't added to the holdings record, query to the endpoint will return nothing. Should we resort to using the locationId and know those will need to be fixed after migration?

**Comment by dlrueda** [comment]
XX(3195846.2579) is the actual call number, in the auto-generated format.  (It’s ckey.callseq)

I think I saw some of these created in folio-test

**Comment by dlrueda** [comment]
grep “XX(“ *9.tsv in the Bibs_catdumps dir, there are tons.

e.g., https://folio-test.stanford.edu/inventory/view/d5bca304-aba8-5a7a-94f8-298f48abc8a3?qindex=hrid&query=a780410&sort=title

**Comment by dlrueda** [comment]
so, when you create an on-order bib, it’s because there are no other items on the title.  You don’t create a call number. But if the title has an item on it, you don’t create the marc/tsv files for on-order.  In that latter case, the call number could very well be XX(...)

I suppose for the on-order marc/tsv files you are creating we could put in the call number, whatever it is (and it’s probably often the XX(...) call number.  Would that make it easier to find the FOLIO holdings UUID?

**Comment by dlrueda** [comment]
@ahafele should probably comment.  I know we thought we’d load on-order instances/holdings with no call number.  But a lot of them have a call number anyway, for instances our on-order process doesn’t create.  And some of those are in the form XX(.....)

**Comment by shelleydoljack** [comment]
> so, when you create an on-order bib, it’s because there are no other items on the title. You don’t create a call number. But if the title has an item on it, you don’t create the marc/tsv files for on-order. In that latter case, the call number could very well be XX(...)
> 
> I suppose for the on-order marc/tsv files you are creating we could put in the call number, whatever it is (and it’s probably often the XX(...) call number. Would that make it easier to find the FOLIO holdings UUID?

I am concerned with the lack of matching call number in FOLIO holdings for the orders linked to titles with many holdings and items where there will be a "real" call number but not the auto-generated one. The on-order bibs will have only one holdings and so I don't really need the call number to figure out which holdings to link the po line to. But just thinking this through for the on-order bibs, we have in folio this record https://folio-test.stanford.edu/inventory/view/b0197b9d-5a7b-533c-a100-367996119c4f for ckey 3307390. If I query the holdings storage endpoint using the instanceId and permanentLocationId that I would have when creating folio orders, I get this:
`https://${OKAPI_URL}/holdings-storage/holdings?query=instanceId==b0197b9d-5a7b-533c-a100-367996119c4f and permanentLocationId==4573e824-9273-4f13-972f-cff7bf504217`
```
{
    "holdingsRecords": [
        {
            "id": "44d424e3-0499-5c5e-a1b0-87ccc4ecedb6",
            "_version": 1,
            "hrid": "ah3307390_1",
            "holdingsTypeId": "03c9c400-b9e3-4a07-ac0e-05ab470233ed",
            "formerIds": [
                "a3307390"
            ],
            "instanceId": "b0197b9d-5a7b-533c-a100-367996119c4f",
            "permanentLocationId": "4573e824-9273-4f13-972f-cff7bf504217",
            "effectiveLocationId": "4573e824-9273-4f13-972f-cff7bf504217",
            "electronicAccess": [
            ],
            "administrativeNotes": [
            ],
            "notes": [
            ],
            "holdingsStatements": [
            ],
            "holdingsStatementsForIndexes": [
            ],
            "holdingsStatementsForSupplements": [
            ],
            "statisticalCodeIds": [
            ],
            "holdingsItems": [
            ],
            "bareHoldingsItems": [
            ],
            "metadata": {
                "createdDate": "2022-11-29T17:37:15.314+00:00",
                "createdByUserId": "7c0a8571-e809-4fc5-9d14-69414d23c841",
                "updatedDate": "2022-11-29T17:37:15.314+00:00",
                "updatedByUserId": "7c0a8571-e809-4fc5-9d14-69414d23c841"
            },
            "sourceId": "f32d531e-df79-46b3-8932-cdd35f7a2264"
        }
    ],
    "totalRecords": 1,
    "resultInfo": {
        "totalRecords": 1,
        "facets": [
        ],
        "diagnostics": [
        ]
    }
}
```
note, there is no callNumber field. If we add the call number to our on-order bibs tsv, this is the one we would be adding:
```
echo "SUL|2023|1AQD1536" | trs selorder -iJ -oO 2> /dev/null | trs selorderlin -iO -oN 2> /dev/null | selcallnum -iN -oD 2> /dev/null
XX(3307390.3)|
```
So if we add that call number when creating the holdings, I could add to the query for looking up the holdings UUID `and callNumber=="XX(3307390.3)"`. But it seems unnecessary since the on-order bibs will always have only 1 holdings record.

**Comment by shelleydoljack** [comment]
Here's what the data looks like for ckey 3195846 and location SCI-SHELBYTITLE when I just have the instanceId and location (note: 2 holdings records have the same call number so I still wouldn't be able to uniquely identify the one that should be linked to the po line if I had the correct call number... :shrug:  ):
```
{
    "holdingsRecords": [
        {
            "id": "ced4cd62-d4ab-5612-80f0-4cb99c83d326",
            "_version": 1,
            "hrid": "ah3195846_1",
            "holdingsTypeId": "03c9c400-b9e3-4a07-ac0e-05ab470233ed",
            "formerIds": [
                "a3195846"
            ],
            "instanceId": "7213c6c8-1fa5-5376-83a6-0250b825d19c",
            "permanentLocationId": "d6349eca-00c6-4d97-ace1-21338c1cc691",
            "effectiveLocationId": "d6349eca-00c6-4d97-ace1-21338c1cc691",
            "electronicAccess": [
            ],
            "callNumberTypeId": "03dd64d0-5626-4ecd-8ece-4531e0069f35",
            "callNumber": "505 .S416",
            "administrativeNotes": [
            ],
            "notes": [
            ],
            "holdingsStatements": [
            ],
            "holdingsStatementsForIndexes": [
            ],
            "holdingsStatementsForSupplements": [
            ],
            "statisticalCodeIds": [
            ],
            "holdingsItems": [
            ],
            "bareHoldingsItems": [
            ],
            "metadata": {
                "createdDate": "2022-11-19T02:59:57.893+00:00",
                "createdByUserId": "7c0a8571-e809-4fc5-9d14-69414d23c841",
                "updatedDate": "2022-11-19T02:59:57.893+00:00",
                "updatedByUserId": "7c0a8571-e809-4fc5-9d14-69414d23c841"
            },
            "sourceId": "f32d531e-df79-46b3-8932-cdd35f7a2264"
        },
        {
            "id": "79024d3e-ebaf-5003-9a39-12c411692551",
            "_version": 1,
            "hrid": "ah3195846_2",
            "holdingsTypeId": "03c9c400-b9e3-4a07-ac0e-05ab470233ed",
            "formerIds": [
                "a3195846"
            ],
            "instanceId": "7213c6c8-1fa5-5376-83a6-0250b825d19c",
            "permanentLocationId": "d6349eca-00c6-4d97-ace1-21338c1cc691",
            "effectiveLocationId": "d6349eca-00c6-4d97-ace1-21338c1cc691",
            "electronicAccess": [
            ],
            "callNumberTypeId": "03dd64d0-5626-4ecd-8ece-4531e0069f35",
            "callNumber": "505 .S41",
            "administrativeNotes": [
            ],
            "notes": [
            ],
            "holdingsStatements": [
            ],
            "holdingsStatementsForIndexes": [
            ],
            "holdingsStatementsForSupplements": [
            ],
            "statisticalCodeIds": [
            ],
            "holdingsItems": [
            ],
            "bareHoldingsItems": [
            ],
            "metadata": {
                "createdDate": "2022-11-19T02:59:57.893+00:00",
                "createdByUserId": "7c0a8571-e809-4fc5-9d14-69414d23c841",
                "updatedDate": "2022-11-19T02:59:57.893+00:00",
                "updatedByUserId": "7c0a8571-e809-4fc5-9d14-69414d23c841"
            },
            "sourceId": "f32d531e-df79-46b3-8932-cdd35f7a2264"
        },
        {
            "id": "4252c04e-9af2-573c-8357-3f59a4c9a45e",
            "_version": 1,
            "hrid": "ah3195846_3",
            "holdingsTypeId": "e6da6c98-6dd0-41bc-8b4b-cfd4bbd9c3ae",
            "formerIds": [
                "a3195846"
            ],
            "instanceId": "7213c6c8-1fa5-5376-83a6-0250b825d19c",
            "permanentLocationId": "d6349eca-00c6-4d97-ace1-21338c1cc691",
            "effectiveLocationId": "d6349eca-00c6-4d97-ace1-21338c1cc691",
            "electronicAccess": [
            ],
            "callNumberTypeId": "95467209-6d7b-468b-94df-0f5d7ad2747d",
            "administrativeNotes": [
            ],
            "notes": [
            ],
            "holdingsStatements": [<snip>],
            "holdingsStatementsForIndexes": [
            ],
            "holdingsStatementsForSupplements": [
            ],
            "discoverySuppress": false,
            "statisticalCodeIds": [
            ],
            "holdingsItems": [
            ],
            "bareHoldingsItems": [
            ],
            "metadata": {
                "createdDate": "2022-11-19T03:00:10.691+00:00",
                "createdByUserId": "7c0a8571-e809-4fc5-9d14-69414d23c841",
                "updatedDate": "2022-11-19T03:00:10.691+00:00",
                "updatedByUserId": "7c0a8571-e809-4fc5-9d14-69414d23c841"
            },
            "sourceId": "036ee84a-6afd-4c3c-9ad3-4a12ab875f59"
        }
    ],
    "totalRecords": 3,
    "resultInfo": {
        "totalRecords": 3,
        "facets": [
        ],
        "diagnostics": [
        ]
    }
}
```

**Comment by shelleydoljack** [comment]
There are 3 buckets for this:
1. the on-order bib has one holdings and we can get the holdingsId for the po line linkage
2. the bib has many holdings and the call number linked to the symphony orderline is XX call number -> use locationId for now and see how many there are
3. the bib has many holdings and the call number linked to the symphony orderline is a "real" call number -> we can know the holdingsId from this

Going to add call number to order selection report and see how many are of type "XX".

**Comment by shelleydoljack** [comment]
Looking up the holdingsId has to be done after Inventory is done loading. Maybe add holdingsId to the po line should be done with the step to update "createInventory" to "Instance, Holdings, Items".

**Comment by shelleydoljack** [comment]
@scanedastanford and @ahafele a question I should have asked earlier is where can I put the call number for the po line in FOLIO? If I can put it in the po line in FOLIO, I think that would be easiest for the step where we grab all the orders out of orders-storage and update the createInventory and holdingsId fields. It would be harder to attempt to match the Symphony orderline with the call number to the po line number that FOLIO created. I'm not really seeing a good field in the po line to put the call number. Maybe I could put it in "edition" to just be used for looking up the holdings record and then when writing the data back to the orders-storage endpoint, I clear out that "edition" field?

**Comment by shelleydoljack** [comment]
I tested putting a callnumber in edition field with this record https://folio-test.stanford.edu/orders/view/99c01cd8-b6e0-5491-8072-25e47a7c87b9
![Screen Shot 2023-01-27 at 4 07 09 PM](https://user-images.githubusercontent.com/6343464/215222808-5294b400-aa64-4804-a919-4209eca47975.png)

I then removed the "edition" field with a PUT to orders-storage/po-lines, which will be the same endpoint, I think, we'll use to update the createInventory field for each po line.
![Screen Shot 2023-01-27 at 4 15 44 PM](https://user-images.githubusercontent.com/6343464/215223577-0dcb826f-583d-4d1a-b695-22d87c62fd75.png)

**Comment by scanedastanford** [comment]
I'm fine with that plan, using the Edition field and then clearing it out afterwards. I don't see a better field to put it in either.

**Comment by shelleydoljack** [comment]
Currently don't need mapping. Decided to lookup holdings using instanceId, locationId, and call number.
