### ISSUE TITLE
CDP items (Collection Development Program)

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#276]
https://docs.google.com/document/d/1JUUCw_LndT1B288cKqD6v_wRB_QyltLaU0jATX9vWqg/edit

All CDPSHADOW items will move to GRE-CDPSHADOW. 

Vitus is currently reviewing a list of items currently in SUL. 

Alissa to move others in Symphony

**Comment by dlrueda** [comment]
My memory is that Vitus was willing to update the GREEN items that were not CDPSHADOW to CDPSHADOW.   But it doesn’t matter to me who does the updates.

**Comment by ahafele** [comment]
All Green moved into CDPSHADOW home and current location.
