### ISSUE TITLE
Remediate non-existent permissions from Lotus to Nolana

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/FOLIO-Project-Stanford#277]
Same as this ticket: https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/129

We loaded the permissions that were on folio-test (Lotus) to folio-dev (Nolana) and got a LOT of errors in the log output. It is probably easier to compare what is now in Settings > Users > Permission Sets on folio-dev (some got loaded) to the [Permissions Matrix](https://docs.google.com/spreadsheets/d/1jfU6Bww6gXd81HREYVp8OBItYTFNJwwqMTLxJncZomQ/edit?usp=sharing) to remediate since the log output references UUID's for the permissions.

**Comment by michelleif** [comment]
some of the errors were due to nesting, if the nested set isn't already loaded, the parent set won't load. Shelley trying again to load the nested sets first.

**Comment by shelleydoljack** [comment]
@michelleif I think maybe just QA them in folio-dev and see if we are missing some. I know we had to remove some deprecated ones related to erm so maybe new permissions for those need to be added?

**Comment by michelleif** [comment]
I QA'd the folio-dev permission sets and it looks like the missing permissions are things we need to add manually due to Lotus->MorningGlory->Nolana upgrades, I don't see anything missing that **should have** come from Lotus.
I did not QA app_mylibrary or app_discovery.
And I did not compare Admin bc we assume Admin just gets all permissions available

**Comment by michelleif** [comment]
new permissions that appeared, seems ok (probably a results of some renaming / regrouping of permissions done in Morning Glory)
- Acq E-Resources 7 now has a new permission that wasn't in Lotus TEST: `UI: ui-licenses module is enabled`
- Cataloging 6 now has a new permission that wasn't in Lotus TEST: `UI: Data import module is enabled`

**Comment by michelleif** [comment]
in Acq E-Resources 7, these permissions are no longer present:
```
System generated: SYS#mod-licenses-4.1.1#/licenses/amendments/{id}#[DELETE]
System generated: SYS#mod-licenses-4.1.1#/licenses/licenses/{id}#[DELETE]
System generated: SYS#mod-licenses-4.1.1#/licenses/licenses/{id}/linkedAgreements#[GET]
```

**Comment by shelleydoljack** [comment]
We removed all the `SYS#mod-*` permissions because they are non-existent in Nolana (Note the module version is listed in the permission name). Going forward, we should avoid adding SYS#mod permissions.
