### ISSUE TITLE
Inform storage needs for data-export and licenses

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/FOLIO-Project-Stanford#278]
What sorts of documents are stored, how many, are they accessed often or mostly stored and forgotten?  What is the size like for them?  

- Record export
- Licenses
- Agreements
- E-Usage/Harvester Stats
- Invoices
- OAI-PMH?

- Current estimate: license PDFs are documents of ~3-10 pages, ~1-4MB files and there are ~400 currently in test.

For mod-data-export what is the expected the frequency of exports and/or restores? What is the average file size and number of files?

**Comment by shelleydoljack** [comment]
Also mod-agreements and the mod-erm-usage and harvester apps have storage needs.

**Comment by ahafele** [comment]
I think Invoices app needs storage too.

**Comment by shelleydoljack** [comment]
Will Acquisitions be uploading invoice pdf's into folio? Do the e-usage statistics contain sunet ids? What is the category of risk for invoices, e-usage statistics, and licenses and agreements? https://uit.stanford.edu/guide/riskclassifications#application-classification-examples

**Comment by shelleydoljack** [comment]
@scanedastanford and @trapido maybe you can help us figure [this](https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/278#issuecomment-1474173581) ☝️ out?

**Comment by trapido** [comment]
@shelleydoljack 
Risk categories:
Licenses and invoices - moderate
E-usage stats, agreements - low (usage stats are always reported at the aggregate level, there is no user info such as SUnet ids or IP addresses)

So where will these documents be stored? If we need to download several licenses/invoices at once, will we be able to?

**Comment by shelleydoljack** [comment]
@trapido what do you estimate would be the frequency of usage for each? Will there be many, systematic uploads/downloads of files? or will it be as staff interact with a license or an invoice? I imagine the eusage stats will be harvested on a frequent basis? Answers to these questions will help us determine if the documents are stored in AWS S3 bucket, or on-premise S3-like bucket, or in the folio database. We can configure local storage (folio database) or S3 storage per module, so getting an estimate of usage for each one will be helpful.

**Comment by shelleydoljack** [comment]
@ahafele do you have any idea with regard to frequency of usage for bulk edit and data export? Will staff be using Data Export to generate large files?

**Comment by michelleif** [comment]
- Frequency of usage for data export and bulk edit = **daily**. Large files? YES
- ERM usage harvester: use S3 bucket
- Licenses and Agreements: use local storage
- Invoices: use local storage
- OAI-PMH: use S3 bucket

**Comment by itrapido** [comment]
@shelleydoljack 
Staff will be uploading license and invoice files as they create license/invoice records in FOLIO. We don’t expect staff to be uploading/downloading licenses/invoices in a batch (is it even possible through the UI?)
Regarding usage stats, we are planning to harvest usage monthly.

Here are some numbers, in case this helps:
Invoices: Payments create and pay around 10K invoices a year. That adds around 2.5-3 GB of files every year.
Licenses: We have around 2 GB of existing license files, and we add around 150 licenses per year (100-200 MB of files).  
Usage: The size of the shared drive where we currently store usage stats is 4.8 GB. I would say it will grow at the rate of ~500MB per year.

**Comment by shelleydoljack** [comment]
@trapido thanks for the information. Indeed, using local storage for licenses, agreements, and invoices is the way to go for now. I'm not aware of any downloading in batch using the UI. Maybe a feature to push for. Maybe you can script something to do a bunch of curls, if necessary.

For the erm usage harvester, it seems there will be a lot of harvesting in batches so we'll configure it to use S3.

**Comment by shelleydoljack** [comment]
S3 buckets created. credentials available at:
```
vault kv get secret/kubernetes/folio/s3-prod
vault kv get secret/kubernetes/folio/s3-test
vault kv get secret/kubernetes/folio/s3-stage
```

**Comment by jgreben** [comment]
The secrets for each namespace have been updated with the S3 credentials for each namespace.
