### ISSUE TITLE
Circ settings QA nolana

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/FOLIO-Project-Stanford#280]
From Laszlo:
Circulation>Patron notices>Patron notice policies>Default notice policy & Short term loans have minor changes = reference different notices in dev than test (Suspect this had to do with the additional templates in the next setting)
Circulation>Patron notices>Patron notice templates = more templates in dev than test (I suspect these are precanned notices not in test, like Check out receipt)
Courses > Course types didn't carry over
Courses > Course depts didn't carry over = extensive list missing!
Courses > Processing statuses didn't carry over
Inventory > Items > Loan types > Course reserves didn't carry over (created 1/12 in test so maybe too late to capture setting for the upgrade?)
Users > Fee/fine > Manual charges > Lane missing in dev & test (I think this was an issue during the earlier refresh also?)
Users > Fee/fine > Payment methods > Lane > My account missing (was added to test 12/8)

**Comment by shelleydoljack** [comment]
Are the course types reference data with the module? Did we create these course types or were they just there on Lotus? We don't have code to pull these.

**Comment by shelleydoljack** [comment]
We also don't have code for processing status. We just have code for pulling course terms and course departments. Are processing status reference data from Lotus or did we create these?

**Comment by dlrueda** [comment]
@Laszlo-J I’m pretty sure that

Circulation>Patron notices>Patron notice policies and 
Circulation>Patron notices>Patron notice templates

were changed on folio-test during the circ subgroup meeting on 1/19.  Staff there needed to discuss future plans and were making edits even though they knew the data had already been extracted from folio-test for Nolana instances.  They know they will need to make these changes manually after folio-test is rebuilt at Nolana.

It was these two settings areas I’m pretty dang sure.

**Comment by shelleydoljack** [comment]
Did Lane ever create Users > Fee/fine > Manual charges?

**Comment by shelleydoljack** [comment]
Double-check the inventory loan types on folio-test (Course reserves is not there). Course reserves was created in folio-dev on 1/12 because it is new Nolana reference data. basically anything that does not have a user listed under Last Update column:
![Screen Shot 2023-01-20 at 4 02 06 PM](https://user-images.githubusercontent.com/6343464/213820423-f5d4e4d4-b78b-485a-a708-ae65e7dfa94d.png)

**Comment by shelleydoljack** [comment]
I ended up writing some code to delete some user settings in order to reload them using data I pulled from folio-test today. All but the following issues should be resolved:
- Courses > Course types didn't carry over
- Courses > Processing statuses didn't carry over
We never had a ticket to write code to moves these over. Are these user-created or are they Lotus reference data that somehow we no longer have in Nolana?

**Comment by Laszlo-J** [comment]
> Are the course types reference data with the module? Did we create these course types or were they just there on Lotus? We don't have code to pull these.

These are as-delivered, not created by us. Missing from our dev, so something didn't get installed? 

Looks like FOLIO also renamed "hybrid" to "Online/In person", at least in their dev instance (module = @folio/courses 5.3.100000130)

**Comment by Laszlo-J** [comment]
> We also don't have code for processing status. We just have code for pulling course terms and course departments. Are processing status reference data from Lotus or did we create these?

These were created by the Course reserves subgroup and should be pulled. Only one is reference data as delivered by FOLIO ("recalled".)

**Comment by Laszlo-J** [comment]
> Did Lane ever create Users > Fee/fine > Manual charges?

They did, but it was pre-refresh (<12/2). I asked Leah to remake it and she never did. So no issue. I'll tell her to add it once test is upgraded to Nolana.

**Comment by shelleydoljack** [comment]
This is completed.
