### ISSUE TITLE
Output ckey linked to MHLD in 004 of mhld.mrc

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#281]
EBSCO migration tools now have requirement to have the catkey or other system control number linking the MHLD record back to the bib record in the 004

**Comment by dlrueda** [comment]
I used editrawmarc command to update all existing *mhld.mrc files to switch 001 to 004.

Script in /s/SUL/Users/dlrueda/mhld-dir as a one-time fix.

**Comment by dlrueda** [comment]
/s/SUL/Bin/folio_symphony_extract/Bibs/generate_marc_items_tsv.ksh 
has been updated to 
trs catalogdump -om -ka004 -lALL_LIBS < $f 2> $bibrptdir/$filename.mhlddump.rpt > $marcdir/$filename.mhld.mrc

**Comment by dlrueda** [comment]
Question for @ahafele 

Now that I’ve updated the ckey to output to the 004, the 001 is also being output with the MHLD record identifier.  I can think of no reason to include the 001 with this un-needed data.  Should we use a dumpjunktag file to remove it?  The 901 also has this MHLD record identifier, and I had asked earlier if we should keep it or dumpjunktag it also.  At the time we said to keep it and let staff review.

**Comment by ahafele** [comment]
@dlrueda I think it can be junked, but we could confirm with Vitus on Wednesday if needed.
