### ISSUE TITLE
Investigate missing mod-courses reference data in nolana

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/FOLIO-Project-Stanford#282]
On folio-dev, we are missing default reference data for Settings > Courses > Course Types and Settings > Courses > Processing statuses (the one missing is "recalled", the others on folio-test were created by the circ group).

**Comment by jgreben** [comment]
Looks like for mod-courses in Nolana we will have to load Sample Data and not just Reference Data in order for these to be loaded. Another option would be to load just the the sample data we want manually using the json in the chosen directories here: https://github.com/folio-org/mod-courses/tree/v1.4.6/src/main/resources/sample-data

**Comment by shelleydoljack** [comment]
Seems easier to just add the the pull_json task than to write an exception for this module to load sample data.
