### ISSUE TITLE
Create BW-CHILD locations in folio 

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#284]
For each library in campus SUL, Law, Hoover, and Business create a location called "_Library Name_  Shelved Elsewhere" with code _LIB_-SEE-OTHER

**Comment by dlrueda** [comment]
Made the following new locations in folio-dev
HILA-SEE-OTHER
ARS-SEE-OTHER
ART-SEE-OTHER
EAL-SEE-OTHER
EAR-SEE-OTHER
EDU-SEE-OTHER
ENG-SEE-OTHER
GRE-SEE-OTHER
MAR-SEE-OTHER
MEDIA-SEE-OTHER
MUS-SEE-OTHER
RUM-SEE-OTHER
SCI-SEE-OTHER
SPEC-SEE-OTHER
SAL-SEE-OTHER
SAL3-SEE-OTHER
TAN-SEE-OTHER
