### ISSUE TITLE
Add new SEE-OTHER locations to locations spreadsheet

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#286]
Need entries in the locations.tsv file for these new locations created on folio-dev:
HILA-SEE-OTHER
ARS-SEE-OTHER
ART-SEE-OTHER
EAL-SEE-OTHER
EAR-SEE-OTHER
EDU-SEE-OTHER
ENG-SEE-OTHER
GRE-SEE-OTHER
MAR-SEE-OTHER
MEDIA-SEE-OTHER
MUS-SEE-OTHER
RUM-SEE-OTHER
SCI-SEE-OTHER
SPEC-SEE-OTHER
SAL-SEE-OTHER
SAL3-SEE-OTHER
TAN-SEE-OTHER

Including getting out their UUID.

**Comment by jgreben** [comment]
Added to locations.tsv with uuids:
https://drive.google.com/file/d/1Y752t_cmUVwp7yq7ZZ8qd9h1uvmyl4vK/view?usp=share_link
