### ISSUE TITLE
940 Acq notes migration

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#288]
- 940 Acq notes - Per Suzette these are super messy, tons of them and really only need for open orders. - Needs to be handled

Related issues
- electronic resources that don't get items? - #359
- Bound-with children that are not getting item records - #359
- Basecall num items that are not being migrated - #359
- Serials control notes - Serials Control Data Migration - #132

**Comment by ahafele** [comment]
@scanedastanford Have you all talked about this more? If not, can you put on next acq check-in agenda so we can move the ticket forward?

**Comment by scanedastanford** [comment]
We will not migrate 940 notes. We will run a report before migration for the notes we want to keep and after migration, we will add them to the POL receiving note.
