### ISSUE TITLE
Migration Junktag file

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#289]
Lane uses the 990 for administrative notes and would like to map it to folio instances. We have a relatively small amount of data here from Vendors - most cost info. See report - bodoni:/s/SUL/Users/dlrueda/990s.txt

Darsi will 
- confirm that we are not using this data in some way. If not then,
- add to export junktag file

Rita and Vitus will
- explore what other tags could be junked on export

**Comment by ahafele** [comment]
@vitustang and @scanedastanford are still working on some things in the spreadsheets - https://drive.google.com/drive/folders/1UpO2LlRdayGguESvGca1J-li8B-zEPdQ.

**Comment by dlrueda** [comment]
I have added -j -n dumpjunktag.FOLIO 
to Symphony’s catalogdump call. 

Only tag right now in /s/sirsi/Unicorn/Custom/dumpjunktag.FOLIO is 
990

We can add more tags to dumpjunktag.FOLIO as they are identified. But we’ll junk 990s with our next export.

**Comment by ahafele** [comment]
Junktag list 

909
911
922
925
926
927
928
930
933
934
935
936
937
942
943
944
946
947
948
949
950
951
952
954
955
957
959
960
961
962
963
965
966
967
971
975
980
983
984
985
987
988
990
996
695
699
592
594
596
597
598
599
790
791
792
793
890
891
897
898
899
850
851
853
854
855
863
864
866
871

**Comment by dlrueda** [comment]
Those tags are all now in /s/sirsi/Unicorn/Custom/dumpjunktag.FOLIO
