### ISSUE TITLE
Figure out FOLIO user custom fields.

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#29]
Do we need a folio-custom- fields module?  When is that module available?  Iris?

Once we can load the module, figure out how to load a custom field during user load.

Maybe/hopefully we can use this field to store registry affinity?  Then maybe don’t need all these patron groups just to know what affinity is?

**Comment by ryanmax** [comment]
Can we load users with custom field data?
Yes. Here's an example using Josh's affiliation field:
http://sul-folio-test.stanford.edu/users/preview/5e4ff550-3ff3-4c16-a71b-ed78a3092232

Can we search custom fields in the UI? 
Not yet. Open ticket: https://issues.folio.org/browse/UXPROD-3033

Can we report on them?
Not yet. Open ticket: https://issues.folio.org/browse/REP-221

Can we delete them from a user's record? 
Yes, via API, but not via the UI. Values can be changed in the UI, but I don't see a way to delete an entire custom field from a user's record.
