### ISSUE TITLE
Inactive MHLDs

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#290]
Not all MHLDs should be migrated to FOLIO. Topic was discuss with [Metadata Subgroup](https://docs.google.com/document/d/1oF_EcPV20-Rt_w_mZoU4ULAMkz8rJNMezAgxwELfaLI/edit#bookmark=id.q4eomsouw87p) and [Acquisitions Subgroup](https://stanford.zoom.us/rec/share/ViFlIktcwohyz8fhNUe2FFXZ8KOMI0_X8utpy7L5x1zGav_WhOkthy65YOMdJQb4.ivDu5HPbGEg5oEnq?startTime=1674249121000). 

When a library closes or holdings are transferred, the serials control record is re-linked to a new MHLD and the old is mhld check-in history is left behind. Contains an empty 866 and a note about “transfer” (this signals SW to not display an info). 

Per Acquisitions, history was split because of a limitation in Symphony at the time in which the serials control location could not be changed. This data is not helpful info for acquisitions and they don’t want to migrate this. Made decisions to not move this check-in history for reason. 

Darsi suggest: We remove these in Symphony (with a backup elsewhere) in/around August. Then do the MHLD migration. 

TODO - review this decision with Metadata Subgroup. Do work end of summer.

**Comment by ahafele** [comment]
Darsi going to take a first pass at filtering out  BIOLOGY MATH-CS CHEMCMENG LATHROP MEYER PHYSICS

**Comment by dlrueda** [comment]
Added -a"BIOLOGY,CHEMCHMENG,GOV-DOCS,MATH-CS,MEYER,LATHROP,PHYSICS,LANE-MED,SAL-NEWARK,SPEC-DESK,HOOV-DESK,RWC” to the catalog dump command for MHLD dump.  

Tested, it works.  Those libraries will not be included in next export.

**Comment by ahafele** [comment]
Leaving ticket open for now so we can address the additional non-closed library but still inactive mhld (e.g. possible removal from Symphony).

**Comment by ahafele** [comment]
After mhld generate we could use bibgrep.pl to remove records with certain strings in certain tags. Will take longer but alternative to deletion. 

@ahafele find examples and clear with MD first.

**Comment by ahafele** [comment]
The string is "All holdings transferred to <library name>." It is in the 852 field, subfield z (see GREEN Mhld on ckey 2179013, for example)

**Comment by jermnelson** [comment]
This should be fixed with PR [246](https://github.com/sul-dlss/libsys-airflow/pull/246) being merged.
