### ISSUE TITLE
Set Holdings Type

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#291]
Currently setting for Electronic and Bound-withs. These should remain and take precedence over the below mapping. 

**Format = folio holdings type**
MARC = Book
MANUSCRIPT = Archival Collection
VM = Visual Material
MRDF = Computer File
TECHRPTS = Book
SERIAL = Serial
RECORDING = Recording
SCORE = Score
MAP = Map
EQUIP = Equipment
*Default should be Unknown (currently Monograph)

These Holdings Types created on folio-test

**Comment by ahafele** [comment]
MHLD generated holdings will get this set via the holdings mapping. Not the case for "merged". Need a mapping for the migration generated holdings. 
`    "001": [
        {
            "rules": [],
            "target": "hrid",
            "subfield": [],
            "description": "The human readable ID"
        },
        {
            "rules": [
                {
                    "conditions": [
                        {
                            "LDR": true,
                            "type": "set_holdings_type_id"
                        }
                    ],
                    "description": "Holdings type based on 6 leader's byte"
                }
            ],
            "target": "holdingsTypeId",
            "subfield": [],
            "description": ""`

**Comment by ahafele** [comment]
Per Vitus 

I think the key thing about holdings record type is whether the holdings record represent a single-part resource or a multi-part resource. Why do we want to know? because a multi-part resource's holdings record should have a summary holdings statement that tells you what we have, whereas a holdings record for a single-part resource would not....I see that we already have Monograph, Multi-part monograph, and Serial established. That's good, but the trick is how to assign them correctly. For the "serial" holdings type, I suppose you could do it based on "mode of issuance" = serial.
For "monograph" and "multi-part monograph", Folio has mode of issuance  "single unit" and "multipart monograph", but the mapping is using value of Leader/06 of the MARC record, which does not have a code for multipart monograph, just monograph. So, how is it supposed to assign mode of issuance "multipart monograph" and holdings type "multi-part monograph" when there is no mapping for it? For the holdings type, the only way I can think of for the machine to know that this holdings record is for a multi-part monograph is by determining that:
this instance is not a serial
this holdings record has items attached that have "enumeration data"
I don't know how implementable these criteria are for the loader. Not easy, I assume.

**Comment by ahafele** [comment]
I put on Metadata Subgroup agenda for next week.

**Comment by ahafele** [comment]
Metadata Subgroup and Acq have agreed on a mapping based on symphony record format. Edit ticket description to include.

**Comment by shelleydoljack** [comment]
> These Holdings Types need to be created first. @jermnelson @shelleydoljack should I make these on test and write a ticket to extract them for loading to the other instances?

There's a holdings-type.tsv in https://drive.google.com/drive/folders/1Nn-PNgniSUH3b_Hi6f2NMNLCXYCWU7Um?usp=share_link You can make in folio-test and then copy the UUID into the spreadsheet. There's not a "pull holdings type" rake task, we create the local ones from the tsv file.

**Comment by ahafele** [comment]
Holdings types have been added to -test and UUIDs put in holdings-type.tsv on ops drive.

**Comment by ahafele** [comment]
@jermnelson looks like Archival Collection is not getting assigned for some reason. Not showing in Holdings Type facet and should be the type here - ah5164458_1.

**Comment by dlrueda** [comment]
I might guess that the mapping is looking for MANUSCRIPT, when the actual format is MANUSCRPT ??

**Comment by shelleydoljack** [comment]
@dlrueda is correct. https://github.com/sul-dlss/libsys-airflow/issues/703

**Comment by jgreben** [comment]
Migration done!
