### ISSUE TITLE
Missing preceding titles

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#293]
a2399804 Missing preceding title but has succeeding
a2501497 Missing preceding title but has succeeding
a601541 Missing preceding title

**Comment by dlrueda** [comment]
I think preceding/succeeding titles are only run at the end of the full inventory load?  So I think we can’t check that yet?

**Comment by ahafele** [comment]
I thought so too, but succeeding are showing up.

**Comment by jermnelson** [comment]
The preceding/succeeding titles are run after the the Instance records are posted into FOLIO per DAG run. I'll look at the payloads being posted for these records.

**Comment by jermnelson** [comment]
@ahafele and @dlrueda Figured out the problem; quick PR upcoming (basically `folio_migration_tools` now separates how  preceding and succeeding titles are stored)

**Comment by ahafele** [comment]
Seeing preceding now. e.g. a2247974
