### ISSUE TITLE
Infra stage and qa VMs have access to Folio-test k8s

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/FOLIO-Project-Stanford#295]
Libsys will sets up our Folio account(s) and any other needs (authentication tokens??) and provide information on how to connect to folio-test k8s.

- sul-hydra-etd-qa.stanford
- sul-hydra-etd-stage.stanford.edu.
- dor-services-app-stage-a.stanford.edu
- dor-services-app-stage-b.stanford.edu
- dor-services-worker-stage-a.stanford.edu
- dor-services-app-qa-a.stanford.edu
- dor-services-app-qa-b.stanford.edu
- dor-services-worker-qa-a.stanford.edu

Also, how shall we ensure we know what to do for prod, when the time comes?   Let's document the steps that have to be done for this.

**Comment by justinlittman** [comment]
What is the action for this ticket?

**Comment by lwrubel** [comment]
This is satisfied in part with the work in https://github.com/sul-dlss/operations-tasks/issues/3267. 

@jermnelson can you let us know what username/password we should use for okapi-test from our qa and stage environments, if different from the admin user we already have?

I don't think we can close this until we make an API call from those DSA and ETD VMs and confirm that works.

**Comment by ndushay** [comment]
Shelley put account info in the folio integration slack channel.

**Comment by lwrubel** [comment]
Tested the app user and it works for accessing most APIs. Asked about permissions for /source-storage/source-records endpoint in https://github.com/sul-dlss/dor-services-app/issues/4344.

**Comment by ndushay** [comment]
@jgreben @jermnelson @shelleydoljack - can one of you provide the info for accessing folio-test and -dev VMs from infra VMs?

**Comment by jermnelson** [comment]
@ndushay, do the Infra VMs have access to resources on our VPN? If so, they should be able to access okapi endponts for both folio-test and folio-dev.

**Comment by ndushay** [comment]
@jermnelson I'm not sure how to check.  @lwrubel do you want to take this on?

**Comment by shelleydoljack** [comment]
login to an infra vm and do a curl to an okapi endpoint?

**Comment by jgreben** [comment]
> login to an infra vm and do a curl to an okapi endpoint?

Or do that plus "nc -zv 171.67.7.49 80"

**Comment by lwrubel** [comment]
I ran a curl command to https://okapi-test.stanford.edu/_/proxy/tenants/sul/modules and the `nc` command from Josh on all of the VMs in this ticket and all succeeded.
