### ISSUE TITLE
need FOLIO locations for these Symphony holding codes that map to shadowed locations

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/FOLIO-Project-Stanford#296]
The orders that we migrate with these holding codes need to map to a FOLIO location code. Wether we decide to export the MARC record that are in these shadowed locations, or rely on FOLIO to create the instance and holding records when the order is loaded, still needs to be determined.

| hldg code  |library_location   |
|---|---|
| GRN-STF-H  | GREEN_STAFF  | 
|SUL-CAT-H|SUL_TECH-CAT|
| SUL-CON-H  |  SUL_TECH-CONS | 
| SUL-TS-H  |  SUL_TECH-SERV | 
| UNK-H | SUL_UNKNOWN |

**Comment by dlrueda** [comment]
@scanedastanford will we be migrating ALL SUL/TECH-CAT SUL/TECH-CONS and SUL/TECH-SERV items from Symphony to FOLIO?  Or only those with current fy orders attached?

Same with SUL/UNKNOWN, all or just those with orders?  (Or some other subset of them)

**Comment by dlrueda** [comment]
I was thinking we will need to have a script to select out subsets of Symphony items in locations WITHDRAWN and SHADOW, separate from the main selection by library.  So if we are only selecting some, but we can identify them, we can export the marc.

**Comment by dlrueda** [comment]
@scanedastanford we can make the location codes longer in FOLIO.  What should the location codes and names be?  We can slack or meet about this to decide if that’s easier.

**Comment by shelleydoljack** [comment]
There is also the Symphony library and location HOPKINS GRAPHICNOV with holding code HOP-GNOV-H that Darsi mentioned needed a FOLIO location. There currently aren't any orders in the order selection report with this holding code, but there could be by the time we migrate. Not sure if we want to ticket this task separately since we don't have orders with that holding code.

**Comment by dlrueda** [comment]
SUL-TS and UNK-H should both map to SUL-ACQ-PLACEHOLDER folio loc.

**Comment by dlrueda** [comment]
new locations created
SUL-COLLECTIONCARE (SUL-CON-H)
SUL-CATALOGING (SUL-CAT-H)
GRE-STAFFSHADOW (GRN-STF-H)
SUL-ACQ-PLACEHOLDER (SUL-TS-H and UNK-H)

**Comment by dlrueda** [comment]
Locations created and added to holdingcode-location mapping
