### ISSUE TITLE
Review previous identifiers

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#299]
Ebsco tools are now adding "previous" identifiers to instance (admin note), holdings, and items. Redundant data in our case. Can/should we remove? 
Also being added to the administrative notes.

![Screen Shot 2023-02-06 at 11.50.22 AM.png](https://images.zenhubusercontent.com/6259789bd12079728cab41a1/6a673dd2-8c29-4df9-a8b3-4963479b5d41)

**Comment by ahafele** [comment]
Vitus agrees that we should explore removing these. 
Where is the data coming from? e.g. the holdings ids on a677816?

**Comment by jermnelson** [comment]
These values are coming from the mapping of the CATKEY and CALL_SEQ rows in the TSV holdings/items file. When the `folio_migration_tools` merges holdings, these values get appended in the merged record. I think we can remove this property in the holdings records before we POST them to FOLIO.

**Comment by ahafele** [comment]
@jermnelson will look into removing the instance level admin note and the holdings previous id entries.
