### ISSUE TITLE
Assess cataloging requirements vs FOLIO features

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#3]
Come up with some cataloging requirements.  Make it a google doc and put it in our Google FOLIO drive

Investigate FOLIO product (folio.org) and see where we have gaps in our requirements.

**Comment by ahafele** [comment]
Covered in analysis Requirements list(s) and Gap Analysis. @dlrueda would you prefer to keep this open?

**Comment by dlrueda** [comment]
no, ok to close

**Comment by ahafele** [comment]
Analysis docs found here - https://drive.google.com/drive/u/0/folders/1e7C6IWpcgsE77cZOw4TprrR8iPIV6iSN
