### ISSUE TITLE
Explore if alternative ID field for user record exists

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#30]
This field already exists?  Or there’s a plan for it to exist?

We are hoping to use this for Stanford mobileID

**Comment by jgreben** [comment]
If not, investigate https://github.com/folio-org/folio-custom-fields

**Comment by ryanmax** [comment]
As per [UXPROD-2936](https://issues.folio.org/browse/UXPROD-2936), this functionality has been created using custom fields and will go into the juniper release.

**Comment by Laszlo-J** [comment]
There's also a field for an External System ID, which can store multiple IDs, including Google or Apple account IDs. Potential to use for SU MobileID.

Note: currently only _one_ value can be used. There's an enhancement for multiple values, but no ETA: [https://issues.folio.org/browse/MODUSERS-159](https://issues.folio.org/browse/MODUSERS-159)

Reference:
https://wiki.folio.org/display/UM/2021-02-17+Meeting+Notes

User data app:
https://github.com/folio-org/mod-users/blob/master/ramls/userdata.json

    "externalSystemId": {
      "description": "An ID that corresponds to an external authority",
      "type": "string"

**Comment by Laszlo-J** [comment]
Investigate if externalsystemId is in _addition_ to userID and can be queried separately.

**Comment by shelleydoljack** [comment]
[Alternative approach Duke implemented](https://issues.folio.org/browse/UXPROD-2936) for dealing with patrons that have multiple IDs (phone ID, card ID, watch ID, etc.).
