### ISSUE TITLE
Extract symphony tax policies 

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#304]
Rita will work on extracting symphony tax policies for Suzette to review/recreate in folio. 
cc @scanedastanford

**Comment by rlunnon** [comment]
Symphony tax policies consist of the following:

1. Global configuration settings for Acquisitions:

Do not use zero rated tax
Do not use tax rebates
Do not use vendor tax exemptions
Do not use tax included in invoice line amount
Automatically add audit trail

2. Tax policy which defines the percentage rates, by county in our case.

3. Tax Structure policy which specifies up to three tax rates, the relationship between the taxes, and whether exemptions are allowed. We only use one tax rate per structure and exemptions are always allowed, except for the tax structure NONE which can be used when the entire invoice is not taxable.

4. Tax handling map which is used to define special handling by Acquisitions material type. We have 2 material types defined: SERNOTAX for nontaxable serials, tax handling is EXEMPT, and SERTAX for taxable serials, tax handling is STANDARD. STANDARD is the default handling when there is no Acq material type specified.

When we export invoices to be paid, they are checked against the Delphi tax table which is based on the Tax policies but also includes date ranges for when a tax policy is valid. The current policies are highlighted in yellow.

[TAX policies Symphony.xlsx](https://github.com/sul-dlss/FOLIO-Project-Stanford/files/10875929/TAX.policies.Symphony.xlsx)
[Delphi tax table 20230301.xlsx](https://github.com/sul-dlss/FOLIO-Project-Stanford/files/10875930/Delphi.tax.table.20230301.xlsx)
