### ISSUE TITLE
itemcat to Instance level stat codes

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#305]
Instance level stat codes are not showing from itemcat mapping. https://docs.google.com/spreadsheets/d/1r-s7aTIHXgL97o-MV_TFURzLQoPQY1dHy60Lj5unejU/edit#gid=965967754 

https://folio-test.stanford.edu/inventory/view/ef07b06a-cb43-536a-a3d0-1b9fce61830e should have Instance Level E-THESIS

https://folio-test.stanford.edu/inventory/view/6bb9049d-1a97-5068-8294-794d7d6003f1 should have Instance Level LEVEL3

**Comment by ahafele** [comment]
Darsi will grab itemcat1 and ckey and put in separate file for this processing.

**Comment by dlrueda** [comment]
Change of strategy.  Jeremy will try to work from regular item tsv files to set the instance level stat code (he is doing this for instance suppress from discovery as well)

**Comment by jermnelson** [comment]
Closing; PR https://github.com/sul-dlss/libsys-airflow/pull/244 sets stat codes for Instances
