### ISSUE TITLE
Filter out MHLDs with certain strings 

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/FOLIO-Project-Stanford#307]
How can we remove or filter out MHLD records from the export that are "required field"? This one came up on exporting the marc holdings record for ckey 14440889: 
```
=LDR  00197cy  a22000974  4500
=001  2148412
=004  a14440889
=008  230203\\\\\\\\\\\\\\\\eng\230203
=852  \\$a**REQUIRED FIELD**
=866  \\$aSTACKS
=867  41$80$av.1-16
```
I emailed Data Control to fix the marc holding but is there something we can do to prevent this?

**Comment by dlrueda** [comment]
Also find out what the string is in the 852 that makes this MHLD “not current” and filter that out too @ahafele ??

**Comment by ahafele** [comment]
Confirming with Irina and will update. This ticket is related to #https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/290

**Comment by shelleydoljack** [comment]
Maybe use editrawmarc to remove empty fields as well (see ckey 14258935. has empty 020, 264, and 500 fields)?

**Comment by ahafele** [comment]
@dlrueda The string is "All holdings transferred to <library name>." It is in the 852 field, subfield z (see GREEN Mhld on ckey 2179013, for example)

**Comment by dlrueda** [comment]
dag processing will filter out REQUIRED FIELD from mhlds.

For 245 (marc bibs) Jeanette is doing a check for these on a regular basis, and has it on her list of things to clean up right before migration.
