### ISSUE TITLE
Set Instance Status

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#308]
We are exporting date cataloged already. 

If date cataloged = 0, then Uncataloged
If date cataloged = actual date, then Cataloged

**Comment by shelleydoljack** [comment]
We currently are populating the catalogedDate field. I do not see a way to search using mod-search for catalogedDate. This seems to work `/inventory/instances?query=catalogedDate>"2022-10-18"` but this doesn't: `/search/instances?query=(catalogedDate>"2021-03-01T00:00:00.000+00:00")` (error is "Invalid search field provided in the CQL query" for the field catalogedDate).
