### ISSUE TITLE
Can Dewey prefixes be moved to Holdings prefix?

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#309]
approx 18k Education Library call numbers with TX prefixing Dewey call numbers that Metadata would like to put into the Holdings - Call number prefix field

CALIF for cal docs is another example of this.

@jermnelson if we can figure out which records would get this treatment, e.g. all Education library holdings with call number type = dewey, what are your thoughts on the technical feasibility?

**Comment by jermnelson** [comment]
@ahafele - I think we can handle adding the Dewey (or CALIF) prefixes to the holdings record if we have list of ckeys that require this prefix to be added to the record.

**Comment by ahafele** [comment]
@jermnelson Metadata Subgroup reviewed this and decided to not move forward with prefixes. Thanks for looking into it.
