### ISSUE TITLE
Create a few records via Data Import for Infra testing

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#311]
Infra is trying to analyze the marc that comes back when looking up records in FOLIO.  It would be helpful for them to have a few non-migrated-from-Symphony examples of SRS records.

Load a few (probably from oclc) and supply HRID’s here on this ticket.

**Comment by ahafele** [comment]
OCLC # - HRID
690086252 - in00000000020
35018110 - in00000000021
1131776928 - in00000000022
48817351 - in00000000023
5568372 - in00000000024
536166385 - in00000000025
62175673 - in00000000026
43476694 - in00000000027
26590817 - in00000000028
869899469 - in00000000029

Loaded using the default single record import profile. This could change in the future.

**Comment by ndushay** [comment]
@arcadiafalcone can you see the marc for these okay, or do you need some help?

**Comment by arcadiafalcone** [comment]
@ndushay If you could export the MARC using the same process as before, that would be helpful - thanks.

**Comment by ndushay** [comment]
@jmartin-sul can you take care of this quickly and easily?

**Comment by ndushay** [comment]
@arcadiafalcone  - is this ticket now complete?  If so, please close.  If not, is what is needed understood by those who have the tasks and/or ticketed?

**Comment by arcadiafalcone** [comment]
@ndushay It can be closed, but I don't have the power to do so.
