### ISSUE TITLE
need to add number of pieces to selitem?

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/FOLIO-Project-Stanford#312]
example barcode: 
```
echo 36105016726213 | trs selitem -iB -oC6
8720788|55| 
```
Probably needs to be mapped to this field in the item data:![Screen Shot 2023-02-23 at 12.45.02 PM.png](https://images.zenhubusercontent.com/62964511c137fa350131daff/c2a17a8a-5ace-407e-896d-110413c732e9)

**Comment by dlrueda** [comment]
oh wow.  Yes, yes we do.  (Crap)

**Comment by shelleydoljack** [comment]
Added `6` to the selitem output and PIECES column header to item tsv's and bwchild tsv's in generate_marc_items_tsv.ksh. Also moved some `dolog` calls to inside the loops to get start and finish times for each ckey range.

**Comment by shelleydoljack** [comment]
Added `$pieces` to find_bwparents.pl.

**Comment by shelleydoljack** [comment]
Added pieces method (returns "1") and PIECES column to on_order_items_tsv.rb.

**Comment by shelleydoljack** [comment]
Added PIECES to item mapping: https://github.com/sul-dlss/folio_migration/pull/52
