### ISSUE TITLE
regenerate circ rules tool reference sheet

### ISSUE THREAD

**Issue by michelleif** [sul-dlss/FOLIO-Project-Stanford#313]
please grab latest set of UUIDs and names for the 4 tabs on this spreadsheet:
https://docs.google.com/spreadsheets/d/1gm4muAOqSNwJ7VO4NE3TobVvSoJF2N_HYNrI_Lw4il0/edit#gid=2026144133

Note that "material-types" was originally "item-types"; "material-types" is what is needed.

When done let Darsi and Michelle know so they can test the Circ Rules Testing Tool with some updated values.

**Comment by jermnelson** [comment]
@dlrueda and @michelleif the spreadsheet has been updated with the latest values from folio-test.

**Comment by michelleif** [comment]
There still seems to be something wrong because I ran single scenario with the following:
patron type Staff: 3684a786-6671-4268-8ed0-9db82ebca60b
item type aka material type Book: 1a54b431-2e4f-452d-9cae-9cee66c9a892
loan type Can Circulate: 2b94c631-fca9-4892-a730-03ee529ffe27
location Green Stacks: 4573e824-9273-4f13-972f-cff7bf504217

and the result is:
loan = None

I ran again, changing location to Business Stacks: 45fd8542-b00f-4d56-ae46-6a3e210896d7

and still get loan = None

There might be something wrong with the rules but even so, if the fallback policy rule is correct, then the fallback loan policy should be "No loan". There is not a loan policy called "None".

Jeremy can you tell where the "None" value is coming from?

Maybe the API being used changed from Lotus to Nolana?

**Comment by michelleif** [comment]
working now!
