### ISSUE TITLE
determine which Oracle jobs to run right before cutover

### ISSUE THREAD

**Issue by michelleif** [sul-dlss/FOLIO-Project-Stanford#317]

**Comment by shelleydoljack** [comment]
Maybe this consul page helps? [Systems custom scripts testing for Oracle 19c migration](https://consul.stanford.edu/pages/viewpage.action?pageId=162172082)

**Comment by dlrueda** [comment]
Jobs we should leave on, even after putting Symphony into read only mode
CIRC_STATS_RPT_DAILY_PROCESSIN	circ_stats_rpt.daily_processing(true)	daily	00:15
TABLE_MAINTENANCE_DO_PLEX	table_maintenance.do_plex	daily	05:00
VND_RUNLOG_CK_DO_IT_AM	vnd_runlog_ck.do_it	daily	09:00
VND_RUNLOG_CK_DO_IT_PM	vnd_runlog_ck.do_it	daily	13:00
ENCUMB_RPT_DAILY_PROCESSING	encumb_rpt.daily_processing	daily
EXPEND_RPT_SCHEDULED_PROCESSIN	expend_rpt.scheduled_processing_wrapper	daily
SPECIAL_SCHEDS_ADJUST_FOR_DST	special_scheds.adjust_sched_dst_clock_change	SUN

**Comment by dlrueda** [comment]
Jobs letting run one last time, then need to suspend
UNICORN_POLICIES_REFRESH_MAIN	unicorn_policies_refresh.main_proc	daily	01:00	Sat Aug 19 01:00
UNICIRC_SEARCH_REPT_DO_IT	unicirc_search_rept.do_it	daily	08:45	Sat Aug 19 08:45
UNI_UPDATE_DO_IT_WEEKDAY	uni_update.do_it_weekday	daily	17:30	Fri Aug 18 17:30
UNI_UPDATE_DO_IT_WEEKEND_SAT	uni_update.do_it_weekend	SAT	08:00	Sat Aug 19 08:00
UNI_UPDATES_REPORTING_DO_RPT	uni_updates_reporting.do_report	daily	21:30
VND_EXPORT_FILES_PROC_DO_EXPOR	vnd_export_files.proc_do_export	FRI	23:00	Fri Aug 18 23:00
SPECIAL_SCHEDS_QTRLY_CIRC_TBL	special_scheds.qtrly_circ_stats_table_upd	SUN	18:00	Sun Aug 20 18:00
