### ISSUE TITLE
determine which cron scripts to run right before cutover

### ISSUE THREAD

**Issue by michelleif** [sul-dlss/FOLIO-Project-Stanford#318]

**Comment by dlrueda** [comment]
/s/SUL/OneTime/Forgive-OVERDUE-PROCESSFEE/forgive_bills.ksh
/s/SUL/Bin/CompareCallnum/check_analytic_callnums.ksh

**Comment by dlrueda** [comment]
update Symphony shut down checklist with specifics, even if we cron, so can double-check it’s done https://docs.google.com/spreadsheets/d/1qTtg_Hu7cHm5M28udTdgrKm9Ee5vf2vjIcvbr0SQ4rs/edit#gid=0
