### ISSUE TITLE
Investigate getting LDP app installed on the cluster

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/FOLIO-Project-Stanford#32]
https://github.com/library-data-platform/ldp

**Comment by shelleydoljack** [comment]
From the admin guide:
> An LDP instance is composed of an LDP server configuration and an analytic database. The LDP server updates data in the database from data sources such as FOLIO modules, and users connect directly to the database to perform reporting and analytics.

Connecting to the database is done through different clients, such as DBeaver or SQL Developer. Users can copy/paste queries from https://github.com/folio-org/folio-analytics in order to run pre-written reports. There is also an LDP query builder and backend module (https://github.com/folio-org/ui-ldp and https://github.com/folio-org/mod-ldp) but it isn't clear how these related to LDP (https://github.com/library-data-platform/ldp).

**Comment by dlrueda** [comment]
maybe wait for MetaDB to be in production and learn how to install it instead.
