### ISSUE TITLE
Temp location not being set based on currentlocation column

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#321]
I don’t see that temp location is being set in FOLIO based on the CURRENTLOCATION column of the temp_locations.tsv

Some exmaples
Item 36105230631975 should have temp location GRE-HH-EXHIBIT based on IC-EXHIBIT current location.

Item 36105111794199 should have temp loc GRE-SSRC-NEWBOOK based on SSRC-NEWBK current location

**Comment by jermnelson** [comment]
I think this may be because the `temporaryLocationId` at https://github.com/sul-dlss/folio_migration/blob/ebe1aa0e922ff52d3b0e93dc4b667e8e126b4d06/mapping_files/item_mapping.json#L316-L320 is not set to CURRENTLOCATION.

**Comment by ahafele** [comment]
36105111794199 confirmed good on folio-stage
