### ISSUE TITLE
QA folio-stage

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/FOLIO-Project-Stanford#325]
https://docs.google.com/spreadsheets/d/1_6QWDtS9zRcwgvc8pDdbKq10A6629y4OU39DsNBApF0/edit?usp=sharing

**Comment by Laszlo-J** [comment]
Settings to import and/or tweak vs test:

Circulation>Circulation rules were tweaked in test; update stage to latest set.
Circulation>Loans>Loan anonymization should be set to 12 mos in stage
Circulation>Loans>Loan policies stage includes ones not in test. Example Loan Policy and One Hour (assume as-delivered.)
Requests > Title level settings not carried over.
Settings>Courses>terms>missing some from test, but has ones not in test;

Test: includes
- Spring quarter 2023
- winter 2023

Stage:
_Missing_ the ones above from Test, but have these new ones:
- Fall 2022
- Spring
- Winter 2022

Users>Patron groups>Pseudopatron missing (added to test on 3/9)
Users>Fee/fine>Comment required = NO (should be YES)
Users>Patron blocks>Conditions>All>Message to be displayed = all entries look like as delivered text; text from Test should be carried over.
Users>Patron blocks>Limits - missing pseudopatron (again, new in test)
Users>Patron blocks>Limits>staff-casual = missing 25 item charge limit
Users>Patron blocks>Limits>SUL-fee = max number of overdue items should be 0

**Comment by shelleydoljack** [comment]
> Circulation>Loans>Loan anonymization should be set to 12 mos in stage

Fixed by doing `STAGE=orig rake configurations:pull_module_configs[LOAN_HISTORY]` and `STAGE=stage rake configurations:load_module_configs[LOAN_HISTORY]`. LOAN_HISTORY was added to config settings file (https://github.com/sul-dlss/folio-tasks/issues/185).

**Comment by shelleydoljack** [comment]
> Requests > Title level settings not carried over.

Fixed by doing `STAGE=orig rake configurations:pull_module_configs[SETTINGS]` and `STAGE=stage rake configurations:load_module_configs[SETTINGS]`. SETTINGS okapi config has the title level request stuff.

**Comment by shelleydoljack** [comment]
> Settings>Courses>terms>missing some from test, but has ones not in test;

It looks like some of these were modified on folio-test since loading to stage. We don't have a task to update the course terms, just create new course terms but retaining the UUID. So trying to pull from folio-test and load to folio-stage errors with:
```
[{"message"=>
     "id value already exists in table coursereserves_terms: c0a54c4c-881e-4fa4-956e-7551412664fa",
    "type"=>"1",
    "code"=>"-1",
    "parameters"=>
     [{"key"=>"id", "value"=>"c0a54c4c-881e-4fa4-956e-7551412664fa"}]}]}
```
@Laszlo-J you can update by hand in folio-stage, or delete them by hand in folio-stage and I can reload the course terms.

**Comment by shelleydoljack** [comment]
> Users>Patron blocks>Conditions>All>Message

Fixed by doing `STAGE=orig rake users:pull_conditions` and `STAGE=stage rake users:load_conditions`.

**Comment by shelleydoljack** [comment]
> Users>Patron blocks>Limits>staff-casual = missing 25 item charge limit
> Users>Patron blocks>Limits>SUL-fee = max number of overdue items should be 0

These also can't be updated but there is a rake task to delete the limits. So I fixed this by doing `STAGE=orig rake users:pull_limits`, then `STAGE=stage rake users:delete_limits` and `STAGE=stage rake users:load_limits`.

**Comment by shelleydoljack** [comment]
> Users>Fee/fine>Comment required = NO (should be YES)

This will be addressed with https://github.com/sul-dlss/folio-tasks/issues/188

**Comment by shelleydoljack** [comment]
> Users>Patron groups>Pseudopatron missing (added to test on 3/9)
> Users>Patron blocks>Limits - missing pseudopatron (again, new in test)

Fixed by adding pseudopatron to the patron-groups.tsv in FolioOps migration files and doing `STAGE=stage rake users:load_user_groups`. 

> Circulation>Circulation rules were tweaked in test; update stage to latest set.

This needed to be done last after the other stuff was dealt with. I think the missing pseudopatron group caused the circ rules to not update in folio-stage at all. Fixed by doing `STAGE=orig rake circulation:pull_circ_rules` and `STAGE=stage rake circulation:load_circ_rules`

**Comment by Laszlo-J** [comment]
> > Settings>Courses>terms>missing some from test, but has ones not in test;
...
> 
> @Laszlo-J you can update by hand in folio-stage, or delete them by hand in folio-stage and I can reload the course terms.

I updated them by hand.

**Comment by shelleydoljack** [comment]
All issues identified here have been resolved.
