### ISSUE TITLE
folio-stage - Reference Data QA

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#326]
**z39.50** 
- targets are missing authentication info. Does this need to be manually added each time? 
- Missing authority target - Name = OCLC Authorities

**Inventory /alternativeTitleTypes** 
- missing abbreviated title

**Loan types** 
- Missing a bunch cc @Laszlo-J  

**Invoice -> adjustments** 
- needs to be added (config yaml? Not sure exactly what @shelleydoljack  said)

**Order templates** 
- will make task ticket once confirmed by Suzette

**Comment by jgreben** [comment]
> **z39.50**
> 
> * targets are missing authentication info. Does this need to be manually added each time?
> * Missing authority target - Name = OCLC Authorities

Created a task to pull and load copycat/profiles

> 
> **Inventory /alternativeTitleTypes**
> 
> * missing abbreviated title

Added new one to the tsv file and uploaded to the GDrive.

> 
> **Loan types**
> 
> * Missing a bunch cc @Laszlo-J

Added new ones to the tsv file and uploaded to the GDrive.

> 
> **Invoice -> adjustments**
> 
> * needs to be added (config yaml? Not sure exactly what @shelleydoljack  said)
> 
> **Order templates**
> 
> * will make task ticket once confirmed by Suzette

**Comment by shelleydoljack** [comment]
These are done so closing ticket.
