### ISSUE TITLE
Install Setae API in local Kubernetes cluster

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/FOLIO-Project-Stanford#331]
https://github.com/cul-it/setae-api

This is the Cornell Middleware that will sit between Folio and the Spine-O-Matic printing software (which will sit on a user's computer). 

Will need coordination with Ops and Libsys

Other options: 
- https://github.com/TAMULib/mod-spine-o-matic
- https://github.com/mtsu-walkerlib/folio-spineomatic

Kubernetes setup info for developers: https://consul.stanford.edu/display/systeam/Kubernetes+for+Developers

Tasks:
- [x] fork repo
-- https://github.com/sul-dlss/folio-setae-api/pkgs/container/folio-setae-api
-- https://github.com/sul-dlss/folio-setae-api
- [x] setup automation to create an image and push to github packages, e.g. https://github.com/orgs/sul-dlss/packages
-- at ghcr.io/sul-dlss/folio-setae-api:main
- [x] create new folio app user with read-only permissions
- [x] create a secret with folio config info and reference secret in kubernetes config so that middleware app has access to this (currently an .env file in the app)
- [x] push this image to a new pod in kubernetes cluster
- [x] make ingress/URL of middleware and configure
- [x] test HTTP vs HTTPs ports
- [x] register hostname with OPs, being done here: https://github.com/sul-dlss/operations-tasks/issues/3302

**Comment by ahafele** [comment]
I recently came across 1-2 other options for this (I think). Not sure if they are worth looking into and @jgreben might have gut responses to give. 
https://github.com/TAMULib/mod-spine-o-matic
https://github.com/mtsu-walkerlib/folio-spineomatic

**Comment by peetucket** [comment]
Thanks Alissa.  They all look pretty similar at first glance and none of them are particularly complicated.
