### ISSUE TITLE
Test printing via Spine-O-Matic software on staff computer

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/FOLIO-Project-Stanford#336]
1 .Use installation instructions to setup: https://docs.google.com/document/d/1Rn5nUc-MU58jhCzM7Hdy4fxXc1zvkNabYR0ACDxjO14 
2. Run Spine-O-Matic and try and print a label for some barcodes in the test Folio instance.
3. Test batch printing and copy and paste.

If everything works correctly - the Windows software should talk to the Setae middleware which should talk to Folio, produce metadata, return to Spine-O-Matic and we should be able to print a label.

**Comment by jmartin-sul** [comment]
Alissa has some meetings setup for next week that should start in on the testing for this, moving to in progress.

**Comment by ahafele** [comment]
Met with Collection Care who successfully generated and printed spine labels. Some details to be worked out but this ticket is done.
