### ISSUE TITLE
Connect POL to item id and see if receiving issue is resolved

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#338]
- Shelley will try to add item ids to the pol (via orders/pieces) for a few example records
1. On-order item with barcode and pol connect to holdings id - https://folio-test.stanford.edu/inventory/view/8e994abe-59d4-5fbb-a5bc-5e981d72e85d and https://folio-test.stanford.edu/inventory/view/88d94e54-562a-5d3c-ba22-4564c23ed63a
2. On-order item with barcode and pol _not_ connected to holdings id _alissa will add example_

- Alissa will try and receive and see if issue is resolved

**Comment by shelleydoljack** [comment]
I added itemId to `PUT /orders/pieces/2780f6d3-108f-4505-b85a-ca8729578b81` for https://folio-test.stanford.edu/inventory/view/8e994abe-59d4-5fbb-a5bc-5e981d72e85d. It added a new holdings to the inventory record, so now both these holdings are linked to the one po line.
![Screen Shot 2023-03-22 at 10 02 22 AM](https://user-images.githubusercontent.com/6343464/226967794-9ff6b132-e251-4e5e-99bf-1c1b54008ce6.png)

When looking at the po line in the receiving app and clicking on the expected piece, you see:
![Screen Shot 2023-03-22 at 10 11 24 AM](https://user-images.githubusercontent.com/6343464/226968130-cdb42068-3c18-461a-998e-fdd8edcbcee3.png)
Notice the [link "Connected"](https://folio-test.stanford.edu/inventory/view/8e994abe-59d4-5fbb-a5bc-5e981d72e85d/dde858a6-4efe-4be3-9633-69c6e649cabb/ea7d18c9-3852-55ca-8768-8997e28ecf0c) under "Create item". This links to the holding/item that was migrated (not the one created by doing a PUT to `orders/pieces endpoint`. I will leave this one as is. Maybe FOLIO will delete the other holdings it created when this item is received?

**Comment by shelleydoljack** [comment]
> 1. On-order item with barcode and pol connect to holdings id - https://folio-test.stanford.edu/inventory/view/8e994abe-59d4-5fbb-a5bc-5e981d72e85d and https://folio-test.stanford.edu/orders/lines/view/46bbaeb4-4f99-43d3-8f3b-c3dd9e720bd

The second link isn't returning anything in folio-test. Maybe the UUID wasn't copied completely (the last bit of UUID is 11 characters instead of 12).

**Comment by ahafele** [comment]
Sorry about that, use this link -  https://folio-test.stanford.edu/inventory/view/88d94e54-562a-5d3c-ba22-4564c23ed63a

**Comment by shelleydoljack** [comment]
Ok, for the second one, https://folio-test.stanford.edu/inventory/view/88d94e54-562a-5d3c-ba22-4564c23ed63a , I added the itemId by doing a PUT to `orders-storage/pieces`. This time it did not create another holdings record. In Receiving app for this po line, the connected link under Create Item links to https://folio-test.stanford.edu/inventory/view/88d94e54-562a-5d3c-ba22-4564c23ed63a/142f3b16-630d-57fc-864f-c24734a512cf/6d055a90-fea6-5193-8cfa-88bb856337ef . This one is now ready for testing the workflow too.

**Comment by shelleydoljack** [comment]
I got all the Order ID's from the lookup holdings report where the result was "No matches with or without callnum" (so the poline would have kept just being linked to the locationId). Then I got all the order ID's that are of orderType One-Time and found the common lines in both files. I edited the file to add library and fiscal year then input it into `cat one-time-orders_polines-linked-location | trs selorder -iJ -oK 2>/dev/null | trs selorderlin -iO -oN 2>/dev/null | trs selitem -iN -oB` to get the barcodes:
```
36105230771524  |
14393546-1001   |
36105232080593  |
36105232072434  |
36105232074257  |
36105212272079  |
36105232199468  |
13386838-1001   |
13445458-1001   |
14156249-125651 |
36105231172763  |
14423255-7001   |
36105231170163  |
36105231172888  |
36105231170098  |
36105231172839  |
36105231173225  |
13340450-1001   |
10404519-1001   |
36105134345292  |
10660752-1002   |
11651357-1001   |
3860035-2001    |
36105019585590  |
3415176-3002    |
3430598-1001    |
3436624-1001    |
3483923-1001    |
36105021471060  |
3814871-1001    |
```
Hopefully some of these are in folio-test.

UPDATE: okay, so now i excluded the barcodes in shadowed current locations:
```
36105230771524  |
36105232080593  |
36105232072434  |
36105232074257  |
36105212272079  |
36105232199468  |
14156249-125651 |
36105231172763  |
14423255-7001   |
36105231170163  |
36105231172888  |
36105231170098  |
36105231172839  |
36105231173225  |
36105134345292  |
36105019585590  |
```

**Comment by shelleydoljack** [comment]
Ugh, I ran these ☝️ barcodes through the script to check if items are in folio and only these are in folio-test:
```
36105230771524
36105212272079
36105134345292
36105019585590
```
but none of them are status ON-ORDER. 🤷

**Comment by ahafele** [comment]
Copied from Slack - Ok, definitely improved. I received both the examples you added item ids to. The first time I received the SAL 3 example it created a duplicate holdings and moved the on-order item to that holdings :scream:. But I think it is because you need to select the holdings with the call number from the drop down menu in the piece…why? I have no idea. 
I think we should try with one or two more examples before having you do the work for all of them. 
- https://folio-test.stanford.edu/inventory/view/b7a09835-2ca3-58d0-8167-4447adc25ef4
- https://folio-test.stanford.edu/inventory/view/04dd385d-a677-52b3-a081-d1a183af3c2f  (no barcode) 
Do you have a possible strategy for on-order with no barcode as well?

**Comment by shelleydoljack** [comment]
>  I will leave this one as is. Maybe FOLIO will delete the other holdings it created when this item is received?

Ahh, so FOLIO did the helpful thing with this one moved the item to the holdings it created when I did PUT to `/orders/pieces` and deleted the other holdings. 🎉 
![Screen Shot 2023-03-23 at 1 26 20 PM](https://user-images.githubusercontent.com/6343464/227327133-3d939fb1-0b38-4f27-977e-816852541721.png)

**Comment by shelleydoljack** [comment]
Ok, these are ready for you to receive:
https://folio-test.stanford.edu/inventory/view/b7a09835-2ca3-58d0-8167-4447adc25ef4
https://folio-test.stanford.edu/inventory/view/04dd385d-a677-52b3-a081-d1a183af3c2f 

I did the PUT to `/orders-storage/pieces`

**Comment by ahafele** [comment]
Thanks! I'll receive this with Suzette tomorrow to get her eyes on it and then will update the ticket.

**Comment by ahafele** [comment]
Testing receiving and it works quite well. However, there are now open decisions about loading as unsynched and the loading on items with status "on-order" more generally. e.g. if something is on-order you can't delete it through inventory. I will put a meeting on the calendar for next week to try and hash some of this out. @scanedastanford will do some reporting to see what kind of scale we are looking at for on-order items. 
Questions for @shelleydoljack if a on-time order gets loaded as unsynched and therefore no expected item is created, can they item still get linked? I think you said not since it is linked through orders/pieces, correct?

**Comment by shelleydoljack** [comment]
The itemId is in orders/pieces so if they want the item linked to receiving app, we still need to put itemId in orders/pieces. Looking at the API doc for pieces, it also has holdingId field; I'm not sure if using this instead of itemId will result in anything better than just telling folio which itemId is supposed to be connected to receiving app. I think letting folio create pieces for us, then updating those pieces with itemId is easier than trying to create our own pieces after loading orders.

**Comment by ahafele** [comment]
This work is not needed. We have decided to not migrate on-order items and instead let staff/FOLIO create these items through receiving actions.
