### ISSUE TITLE
Nolana Data Import Profiles have duplicate sub-profiles

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#339]
Duplicate field mapping and action profiles - https://folio-test.stanford.edu/settings/data-import/job-profiles/view/b02cbf4e-d3bf-4e8f-a974-eba6fbec4a4d?sort=name

**Comment by jgreben** [comment]
@ahafele can you take a look at https://folio-stage.stanford.edu/settings/data-import/job-profiles?sort=name and see how things look? If this looks good, I will reset them on test and load them up from this json data. The json data in test had the duplicates that got ported over.

**Comment by ahafele** [comment]
stage looks good.
