### ISSUE TITLE
Make consul page about our FOLIO AWS instances

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#34]
who uses folio-test, folio namespaces
what are URLs to get to those instances

document, or point to document, for code repositories to bring up those instances

**Comment by shelleydoljack** [comment]
@dlrueda  Does this look okay? https://consul.stanford.edu/display/SYSTEMS/FOLIO+on+AWS+EKS
I also cleaned up the libsys homepage a teensy bit.
