### ISSUE TITLE
Cancelled orderline migrated?

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/FOLIO-Project-Stanford#340]
https://folio-test.stanford.edu/orders/lines/view/cf64a8a8-3f5a-4e07-8c5c-6f9db18a680e

Why is this order in folio? Order ID CIS23030342, ckey 13340450

**Comment by shelleydoljack** [comment]
Another example: https://folio-test.stanford.edu/orders/lines/view/3ae1f94d-3814-476d-b875-b7659b5804ed
Order ID HV5921-98, ckey 3860035

**Comment by scanedastanford** [comment]
CIS23030342 - didn't have a cancel segment so it wasn't properly closed. I've added the cancel segment.
HV5921-98 - closed in fy12 but i don't know why it kept rolling over. i've deleted the fy23 order.

**Comment by shelleydoljack** [comment]
Thanks for checking. Is there a cleanup effort already for identifying and fixing issues like these?

**Comment by ahafele** [comment]
@scanedastanford is this cleanup ongoing or can we close this ticket?

**Comment by scanedastanford** [comment]
Cleanup is ongoing so I will close this ticket.
