### ISSUE TITLE
Fund types missing

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#348]
Fund type - didn’t load with funds (column D) https://docs.google.com/spreadsheets/d/1N0GIPHXHpHfBSZczxxMnvkwJp0yn_f68DT8c7mGK-vE/edit#gid=0. The fund types are added in Settings: https://docs.google.com/spreadsheets/d/1vtdMCJrpXvOP7VLaHuluMUU_mhH-mgl77xLZhoz6qFA/edit#gid=0

**Comment by shelleydoljack** [comment]
The fund types didn't load because the names are different. "SUL-ENDOWMENT" vs. "SUL-Endowment".

**Comment by shelleydoljack** [comment]
@scanedastanford Should I update the fund types to all caps to match what's in the fund spreadsheet?

**Comment by scanedastanford** [comment]
Yes, I've updated the fund types spreadsheet to all caps. Thank you!

**Comment by shelleydoljack** [comment]
Ok, fixed in folio-dev, -test, and -stage by manually deleting and reloading the SUL fund types. Also updated the fund-types.tsv in folio ops migration files. Getting the funds linked to the fund types will happen when we reload orders.
