### ISSUE TITLE
Budget changes

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#349]
1. For endowment, gift, and ebook funds, the allowable expenditure percentage should = 100. I've added this to the budget spreadsheet (column G) https://docs.google.com/spreadsheets/d/1KVU8MBRpedXMvQLoBDgqgR8vxHxkheV7gxpk2Esa-9k/edit#gid=0 and to the mapping (line 40) https://docs.google.com/spreadsheets/d/13bh1Dd-v_tC0A5iepeTxWVBjj2JLz3lmvFglFDjOcD4/edit#gid=0.

2. We're going to use expense classes after all. I've added them back to the budgets spreadsheets (column E) https://docs.google.com/spreadsheets/d/1KVU8MBRpedXMvQLoBDgqgR8vxHxkheV7gxpk2Esa-9k/edit#gid=0

3. Ordering is requesting to migrate the INSTRUCT note from the Orderline 1 extended info. I've added it to the mapping (line 18) https://docs.google.com/spreadsheets/d/13bh1Dd-v_tC0A5iepeTxWVBjj2JLz3lmvFglFDjOcD4/edit#gid=215993364

**Comment by shelleydoljack** [comment]
- [x] Changed column name to "allowableExpenditure" for the new field for budgets.

**Comment by shelleydoljack** [comment]
budgets.tsv updated in folio ops migration files.

**Comment by shelleydoljack** [comment]
I updated `/s/SUL/Bin/folio_symphony_extract/acquisitions/orders/run_reports.ksh` to get the INSTRUCT field from orderline 1 for SUL. Does Law want INSTRUCT from their orderlines too?
