### ISSUE TITLE
export results menu item from Circulation Log does not work

### ISSUE THREAD

**Issue by michelleif** [sul-dlss/FOLIO-Project-Stanford#350]
1. go to Circulation Log
2. use filters to limit to a smaller set of items for a faster test (like Loan / Renew)
3. in the actions menu choose Export results
4. you get green message `Your circulation log export has been requested. Please wait while the file is downloaded` but nothing ever downloads
5. go to Export manager. The attempted export shows as an "In progress" export job. There are still jobs in there "in progress" from 3/8/23 as well.

This was reported on folio-support slack https://stanfordlib.slack.com/archives/C03MB1KHR89/p1678308570170379 but we also experienced this last year, so it's not new, just haven't pursued.

**Comment by jgreben** [comment]
Same issue as #243

**Comment by michelleif** [comment]
just tested this again after Lane reported they had trouble exporting a different set of results, and fixed it by enabling a hidden permission “circulation - items in transit report”. not sure if that's why it works, or if whatever is needed in #243 is the reason. waiting for a user to retest and confirm that it works.

**Comment by michelleif** [comment]
Update, as of about April 13th, the export job now shows in Export manager as "Successful" and can be downloaded from there. 
So the part not working is downloading it from the Circulation Log directly.
I also went to try this in the FOLIO community Nolana reference environment to compare, but it turns out it's not working there and is being fixed.

**Comment by michelleif** [comment]
download directly from Circ Log is working now! It was a Chrome blocked pop-up issue. Thank you Erin from Duke!
<img width="329" alt="Screenshot 2023-04-18 at 11 17 40 AM" src="https://user-images.githubusercontent.com/23069165/232871393-700e3308-4183-430d-9337-cd0be7dc8321.png">
