### ISSUE TITLE
New Acquisitions Method - Package

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#351]
Method has been added to test and the acquisitions-methods.tsv updated. 

They updated the mapping for the package order types on line 18 and 38 for this new acq method:
https://docs.google.com/spreadsheets/d/13bh1Dd-v_tC0A5iepeTxWVBjj2JLz3lmvFglFDjOcD4/edit#gid=2048733629
 
cc @scanedastanford

**Comment by shelleydoljack** [comment]
@scanedastanford will there be any more order type mapping updates for this round of Orders QA?

**Comment by shelleydoljack** [comment]
Ran `rake acquisitions:load_acq_methods` on dev and stage with new tsv file.

**Comment by shelleydoljack** [comment]
updated order_type_map.tsv in folio ops migration files and on bodoni.

**Comment by scanedastanford** [comment]
> @scanedastanford will there be any more order type mapping updates for this round of Orders QA?

I think I've submitted all the updates for this round. Thank you!
