### ISSUE TITLE
Handle item data when we don't create items

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#359]
e.g. basecallnums, boundwidths, electronic resources, on-order items? 

- [ ] - item extended info notes #471
- [x] - itemcat1/2 to stat codes #416
- [x] - call number |Z #437

**Comment by michelleif** [comment]
can we ask someone to check on whether these are still issues?

**Comment by ahafele** [comment]
Changed ticket to reflect remaining issues

**Comment by ahafele** [comment]
Discuss at Friday Libsys meeting

**Comment by ahafele** [comment]
Alissa will get reports on how many extended info notes we are talking about. ~(add link to already create base callnum report)~.

**Comment by ahafele** [comment]
Item extended info for INTERNET per Jeanette - Since we are not sure which withdrawn/shadowed items will migrate I did not exclude them. There are 25822 item records with techstaff notes with library SUL home location INTERNET. I also checked circnote, public note, and circstaff. The 3 public and 8 circstaff notes should have been techstaff notes so I updated them and they are included in the count above. There are 18 circnotes with 15 of them just being the ckey. 
A lot are EDI receipt, the others are a mix of routing, cataloging, maintenance, format change, and a general mix of other notes.

**Comment by michelleif** [comment]
in case helpful: re WITHDRAWN items in branches, [here's a sheet](https://docs.google.com/spreadsheets/d/1LN2L89wasekg0eDwZdP47f8sRAlKN8DHVCWCeJa34fE/edit#gid=0) that tells which ones are migrating (need confirmation on Classics still but will likely be Discard)
