### ISSUE TITLE
336 resource type term v. code

### ISSUE THREAD

**Issue by michelleif** [sul-dlss/FOLIO-Project-Stanford#364]
<strong>Submitted By: </strong>jkalchik@stanford.edu
<strong>Description: </strong>The resource type term in the instance is coming from the resource type code even when the source record has the correct term. This is a data issue that should be remediated. Is there a way to identify these? (updated this one in Symphony already) I checked in airflow https://sul-libsys-airflow-prod.stanford.edu/folio/data_issues/manual__2022-11-19T04:24:57.982904+00:00/data_issues_log_bibs-transformer.tsv and it was not reported as an issue
<strong>Instance HRID: </strong>`a11746105 `
<strong>Patron barcode: </strong>``
<strong>FOLIO App: </strong>Inventory
<strong>Urgency: </strong>It's not urgent.
<strong>Browser: </strong>

**Comment by ahafele** [comment]
@jlkalchik is the issue that there is a mismatch in our data between the code and the name?

**Comment by jlkalchik** [comment]
That is correct. The information in the Instance Resource type term seems to be being mapped from the code even if the information in the 336 $a is different.

**Comment by ahafele** [comment]
migration issue.
