### ISSUE TITLE
Request - batch electronic resources statistical code

### ISSUE THREAD

**Issue by michelleif** [sul-dlss/FOLIO-Project-Stanford#367]
<strong>Submitted By: </strong>jkalchik@stanford.edu
<strong>Description: </strong>Would it be possible to add a statistical code to the holdings and/or the instance record when there is a $xeLoaderURL? At the instance record this would allow a user to search for terms in the instance record. At the holdings record it would allow the ability to filter out non-batch loaded electronic resource records.
<strong>Instance HRID: </strong>``
<strong>Patron barcode: </strong>``
<strong>FOLIO App: </strong>
<strong>Urgency: </strong>
<strong>Browser: </strong>

**Comment by ahafele** [comment]
@jlkalchik do you know what stat code you would like assigned for these and at which level is preferred?

**Comment by ahafele** [comment]
Moving to backlog - per Jeanette this depends on future plans for identifying and searching these records. Not ready to add additional data at this point.

**Comment by ahafele** [comment]
Not at this time.
