### ISSUE TITLE
Finalize patron groups

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#37]
Do we really want a patron group for each affiliation? 

Can we use custom fields for affiliation instead?  Need to be able to report, and maybe search on this.
What are other libraries doing?

**Comment by Laszlo-J** [comment]
Final user groups can be found on first sheet here: [https://docs.google.com/spreadsheets/d/10n77Zxgp3GCgwB9pPR80CZzNs6ERDzQkyCuolUQEoG0/edit#gid=221919063](url)

Custom fields include all suggested names, but more may be added as they're identified.

**Comment by jgreben** [comment]
Configs and tsv files all updated to reflect new patron groups listed in spreadsheet.
