### ISSUE TITLE
Place of publication not indexed under "All" search?

### ISSUE THREAD

**Issue by michelleif** [sul-dlss/FOLIO-Project-Stanford#373]
<strong>Submitted By: </strong>hsammons@stanford.edu
<strong>Description: </strong>When I use place of publication as a search term in  "All" search, it does not retrieve records that I know include this place of publication and the other search terms. Is place of publication not indexed? I thought "All" included everything in the Instance. 

I was also unable to retrieve records with "All" search when combining an identifier (such as ISBN) with other search terms (such as contributor)
<strong>Instance HRID: </strong>``
<strong>Patron barcode: </strong>``
<strong>FOLIO App: </strong>Inventory
<strong>Urgency: </strong>It's not urgent.
<strong>Browser: </strong>Firefox

**Comment by ahafele** [comment]
Hi Harold, What publication term are where you using? All does include place of publication and I’m finding those I’m trying but it would be good to see what string you tried. For the combined search, as far as I understand it, only Query Search supports Boolean right now - https://wiki.folio.org/pages/viewpage.action?pageId=65114231
-Alissa

From: michelleif ***@***.***>
Date: Friday, January 6, 2023 at 12:05 PM
To: sul-dlss/folio-support ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sul-dlss/folio-support] Place of publication not indexed under "All" search? (Issue sul-dlss/FOLIO-Project-Stanford#373)

Submitted By: ***@***.******@***.***>
Description: When I use place of publication as a search term in "All" search, it does not retrieve records that I know include this place of publication and the other search terms. Is place of publication not indexed? I thought "All" included everything in the Instance.

I was also unable to retrieve records with "All" search when combining an identifier (such as ISBN) with other search terms (such as contributor)
Instance HRID: <strong>Patron barcode: </strong>
FOLIO App: Inventory
Urgency: It's not urgent.
Browser: Firefox

**Comment by ahafele** [comment]
Hi Alissa,

I'm looking at HRID a1113149. "New Haven" is in the instance record under place of publication.

When I search contributor and title words together, the record is retrieved. Search string: sammons elusive poet

When I search contributor and place of publication, the record is not retrieved. Search string: sammons new haven

Thanks,
Harold

**Comment by jlkalchik** [comment]
Instance HRID a11884254 has Dar es Salaam, Tanzania as the place of publication, but an ALL search for Dar es Salaam 

![image](https://user-images.githubusercontent.com/57508732/211637205-7f0527a1-58a0-4de3-a840-08ede96ab57f.png)

An all search for yale university press heinrich elusive finds a1113149 but an all search for New Haven heinrich elusive does not.

**Comment by ahafele** [comment]
@jlkalchik when you search All for ```Dar es Salaam, Tanzania``` it returns to the results but I'm not sure why or how All search is really working. I will continue to investigate. Here are some resources I've found along the way - https://github.com/folio-org/mod-search#readme | https://confluence.cornell.edu/display/ltstr/Inventory%3A+Searching | https://wiki.folio.org/pages/viewpage.action?pageId=65114231

**Comment by ahafele** [comment]
https://issues.folio.org/browse/MSEARCH-606
