### ISSUE TITLE
strip 596 field after use?

### ISSUE THREAD

**Issue by michelleif** [sul-dlss/FOLIO-Project-Stanford#376]
<strong>Submitted By: </strong>jkalchik@stanford.edu
<strong>Description: </strong>Symphony MARC records have a 596 that is controlled by Symphony based on the item locations. I believe it should not be migrated to FOLIO since it will then be static and will not have the correct code if items change locations.
<strong>Instance HRID: </strong>
<strong>Patron barcode: </strong>
<strong>FOLIO App: </strong>
<strong>Urgency: </strong>
<strong>Browser: </strong>

**Comment by dlrueda** [comment]
haha, we JUST decided to use this field to determine location for e-resource items.  If it can be stripped out of the record after using it to determine holdings location for 856s in the record, but before loading, that’s fine.

Or else we need to figure out some other way to determine holdings from the bib when there’s an 856

**Comment by michelleif** [comment]
@dlrueda should this be moved to FOLIO-Project repo for libsys to address?

**Comment by michelleif** [comment]
@jlkalchik fyi
