### ISSUE TITLE
Identifiers

### ISSUE THREAD

**Issue by michelleif** [sul-dlss/FOLIO-Project-Stanford#377]
<strong>Submitted By: </strong>jkalchik@stanford.edu
<strong>Description: </strong>2 comments about Identifiers: 

1 - (OCoLC-M) is displaying under System control number not OCLC number.
2 - A search by just the OCLC number itself is not finding the record. You need to have the prefix in front of it to find it or use *number to find it, which potentially finds other identifier numbers that have that OCLC number as part of it.
<strong>Instance HRID: </strong>`a2659475`
<strong>Patron barcode: </strong>``
<strong>FOLIO App: </strong>Inventory
<strong>Urgency: </strong>It's not urgent.
<strong>Browser: </strong>Chrome

**Comment by ahafele** [comment]
The regular expression in the mapping is not finding these. 

current - `"(\\(OCoLC\\)|ocm|ocn|on).*"`
working - `(\\(OCoLC.*\\)|ocm|ocn|on).*`

**Comment by ahafele** [comment]
@jlkalchik do we want to change the mapping so that any 035 with OCoLC is considered an OCLC number?

**Comment by jlkalchik** [comment]
That makes the most sense to me. I also checked with Vitus and he agrees it makes sense. Neither of us see any issues it would cause.

**Comment by ahafele** [comment]
Will do in next round.

**Comment by ahafele** [comment]
@jlkalchik I made this change on folio-dev. Could you create a file with a bunch of different oclc number variants and just make sure it is working as expected? Thanks!

**Comment by ahafele** [comment]
Tested file and all looks good
