### ISSUE TITLE
Item service point information in an item never charged

### ISSUE THREAD

**Issue by michelleif** [sul-dlss/FOLIO-Project-Stanford#378]
<strong>Submitted By: </strong>jkalchik@stanford.edu
<strong>Description: </strong>Item HRID ai4449986_1 has under circulation Circ Desk 2 even though it has never been charged. I am not sure if this is a problem or what this actually means.
<strong>Instance HRID: </strong>
<strong>Patron barcode: </strong>
<strong>FOLIO App: </strong>
<strong>Urgency: </strong>
<strong>Browser: </strong>

**Comment by michelleif** [comment]
@jlkalchik i found the item record but i don't see where Circ Desk is, can you provide a screenshot thanks!

**Comment by jlkalchik** [comment]
![image](https://user-images.githubusercontent.com/57508732/186552151-58dda777-d170-4f89-b6c8-f2eed3a06fd8.png)

**Comment by michelleif** [comment]
Thanks! I was looking in the wrong place. Weird, I saw that on a different item too. I wonder if it does that to a FastAdd? @Laszlo-J can you check this out?

**Comment by jgreben** [comment]
I'm willing to bet that it assigns the default service point for the user that loaded the record, in this case, Superuser.
![Screen Shot 2022-08-25 at 09 14 10](https://user-images.githubusercontent.com/3093850/186716810-c247343d-6a57-4379-ba48-29132ac80953.png)

**Comment by dlrueda** [comment]
In that case we should switch the super user’s service point to Green Loan probably.  Or Online?

**Comment by jlkalchik** [comment]
https://issues.folio.org/browse/UIIN-2109

**Comment by jlkalchik** [comment]
Talked about at Data Import meeting today and the default if you forget to specify API call is order entered. Ann-Marie said she thinks it is fixed for Morning Glory.

**Comment by michelleif** [comment]
@jlkalchik is this still an issue in Nolana?
