### ISSUE TITLE
795 to Collection name Note

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#379]
795 has been mapped to an Instance Note named `Collection name`

@vitustang could you please tell me what subfields needs to be included?

**Comment by vitustang** [comment]
@ahafele the 795 has two three subfields defined:
- |a -- collection name
- |p -- sub-collection name
- |6 -- linkage subfield for linking to an 880 field if there is a non-Latin script version of the collection name

If a 795 does have a |6 and has a non-Latin version of the name in an 880 field, would it be possible to have two collection name notes in the Instance record?

**Comment by ahafele** [comment]
Thanks Vitus. I believe that if we add the 795 mapping, then any linked 880 will follow. I'll test that. 
Update: Confirmed linked 880 gets mapped also.

**Comment by ahafele** [comment]
Added to mapping.
