### ISSUE TITLE
700 $5 (used to identify SUL-specific added entries)

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#389]

**Comment by ahafele** [comment]
Spec - used all the time. e.g. former owners of specific item. Don't need to search the subfield part. 

Jeanette: want to be able to see in instance that the 700 was created by Stanford. Broader SUL probably not using. 

Law - will use for alum or faculty contributors that may not get picked up otherwise "institution specific" 

Hoover uses, and mapping might be helpful when doing copy cataloging – if we import a record from OCLC that has a 7xx$5 from other institution in the worldcat record, which sometimes exists, it might be helpful to see in the instance record that this note is institution-specific and to know which institution added it (and to erase that field from our ILS, as I would do in WorkFlows, if it's not HILA-created/specific, to erase that field)

**Comment by ahafele** [comment]
@jlkalchik could you provide me with a couple ckey examples for this?

**Comment by jlkalchik** [comment]
Straightforward Spec example: 1004276
Spec with 3x 700 local fields with also other SUL items: 583994
Spec with 2 700 fields for same person, 1 local: 12914793
Spec with local 700 $t: 14087254
Spec with 655 & 740 fields also local: 1995915
Spec with 710 also local: 12358517
Hoover record with 700 linked to an 880 field with $5: 11939776
Hoover record with $5DLC: 7716800

Sometimes used in broader SUL but not systematically like Spec
Green & Art & ARS & SAL3 only records: 9940072 & 12438496 & 14324400 & 14248656

Only 14 instances of $5CSt-Law found in 700 fields.

$5 from other institutions can come in through the eloader: 9292029
Also come in through copy cataloging and are not properly removed: 13835001 
(per https://consul.stanford.edu/display/MD/Copy+Cataloging '$5 in any field requires the deletion of the entire field. Most commonly found in 5XX fields.')

**Comment by ahafele** [comment]
Not a great place to include this in mapping. 
Would reference folks utilize this? Ask Spec as well - Ann. 
Discussed in SIG?

**Comment by ahafele** [comment]
Tested mapping but will not work. Will discuss with spec in January

**Comment by ahafele** [comment]
Confirmed with Spec that having available in the MARC is sufficient.
