### ISSUE TITLE
Research satae API questions

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/FOLIO-Project-Stanford#390]
- What is https://github.com/cul-it/setae-api/blob/main/app/aboveLabel.txt - looks specific to Cornell. 

I see no references to this in the middleware code at all.  I will remove from our fork of the code to avoid confusion.

- What is https://github.com/cul-it/setae-api/blob/main/app/prefix-suffix.csv 

There appears to be data returned by the Folio API for the call number that can include a "prefix" or a "suffix" field, e.g. for `36105029776601`, the call number of the Folio API data looks like this:

```
 "effectiveCallNumberComponents"=>{"callNumber"=>"PT2621 .O46 Z56 2001", "prefix"=>nil, "suffix"=>nil, "typeId"=>"95467209-6d7b-468b-94df-0f5d7ad2747d"},
```

In this particular record, the `prefix` and `suffix` are both empty, but it must be possible for them to have a value in Folio.  This `prefix-suffix.csv` file will do a replacement of either the prefix or suffix in the data before passing it on the Spine-O-Matic.  So in the current .CSV file (specific to Cornell), if it finds `History of Science` in the prefix field, it will replace it with `Hist.Science`.  If it finds `A.D. White` in the prefix field, it will get rid of it (replace with a blank string) and so on.  I will make this an empty file in our install until/if we have a use for it.

- Why is it hitting orders endpoints? https://github.com/cul-it/setae-api/blob/main/app/main.py 

Very good question.  It appears to be adding a `fund` field to the data before sending to Spine-O-Matic in cases where there is a `holdingsRecordId` and then it looks in the first `holdingSummaries` for a fund code.  But only adds it to the item record metadata if the code is either "p2053" or "p2052".  Those codes are clearly specific to Cornell, but perhaps this whole block of code (including the two API calls) are unnecessary for us if we don't ever need to add a fund code from the holding summary to the label.  

- Are call number prefix/suffix accessible through middleware or only added in spinomatic?  Included here: https://github.com/cul-it/setae-api/blob/main/app/alma-rest-item.xsl 

The prefix and suffix are in the response that comes from Folio (as shown in the data snippet in a bullet point above, which is what the data looks like coming from Folio).  This .xsl file then transforms that data to the XML format that is seen by Spine-O-Matic so it is available there too (after passing through the optional search/replace as described in the bullet point above).

**Comment by ahafele** [comment]
Thanks for these answers, Peter.
