### ISSUE TITLE
Can we make the unmerged MHLDs more visually distinct?

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#393]
TS heads has asked the above question. We could consider having the MHLDs load with a call number "MARC" or something to visually queue staff that it is the mhld holdings. Copy number field also displays in Inventory view.

**Comment by ahafele** [comment]
Won't do for next round. Will let users test more on unmerged before changing

**Comment by michelleif** [comment]
did users do their test?

**Comment by michelleif** [comment]
to be discussed at Metadata Subgroup meeting first week of June

**Comment by ahafele** [comment]
MD Subgroup has confirmed that it is still confusing and they would like the string `MARC Holdings` put into the Holdings Call Number field.

@jermnelson not sure what this process will look like - if you are inserting into MARC or FOLIO Holdings directly
MARC - 852 hi
FOLIO - callNumber
