### ISSUE TITLE
delete default service points "circ desk 1" & "circ desk 2" or turn off as pickup location

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/FOLIO-Project-Stanford#394]
https://github.com/sul-dlss/LibSysTasks/issues/832

**Comment by jgreben** [comment]
Looks like cd1 and cd2 have Discovery Display Names `Circulation Desk -- Hallway` and `Circulation Desk -- Back Entrance` which seem to indicate they mean something to us? They are already turned off as pickup locations. But we can delete them if we do not ever need them.

**Comment by Laszlo-J** [comment]
No, these are FOLIO reference data - they're called that in the FOLIO snapshot too. I manually turned off the pickup locations. Go ahead and delete.

**Comment by jgreben** [comment]
Deleted in dev, test. stage, and prod.
