### ISSUE TITLE
remove as-delivered values used for material type settings

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/FOLIO-Project-Stanford#395]
https://github.com/sul-dlss/LibSysTasks/issues/831

**Comment by jgreben** [comment]
We need to see whether these impact the use of DI profiles and maybe search also. We will definitely have to reindex search after doing this.

**Comment by shelleydoljack** [comment]
Removing the default material types makes me nervous. Are any of them referenced in a data import profile, like the default ones? Or in order templates? Or how does this impact indexing, since there is a material type facet for item?

**Comment by ahafele** [comment]
Testing on -dev. Some default Material Types we do want to keep. Need a very clear list of which should be deleted.

**Comment by ahafele** [comment]
the two "unused" material types are in use for certain workflows. Closing this ticket.
