### ISSUE TITLE
Folio app_readonly user needs additional permissions

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/FOLIO-Project-Stanford#399]
Testing the app with this barcode: `36105111422254` produces an internal server error on https://folio-setae-api-test.stanford.edu/items/36105111422254

Debugging on the rails console using `folio_client` shows we are making an extra API call for this particular barcode to `/orders/order-lines`, which the `app_readonly` user does not have access to:

```
The operation requires privileges which the client does not have: Access for user 'app_readonly' (cb2614ab-da1d-5f0f-84e1-b4fabae8a6e0) requires permission: orders.po-lines.item.get (FolioClient::ForbiddenError)
```

**Comment by peetucket** [comment]
@jgreben can you help with this permission issue?

**Comment by jgreben** [comment]
Done.

**Comment by peetucket** [comment]
Thanks, 36105111422254 works now
