### ISSUE TITLE
Document how to create local instance

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#4]
Investigate folio.org (etc) and generate a document with requirements, concerns, steps, etc. on creating a local FOLIO instance.

**Comment by jgreben** [comment]
See: https://docs.google.com/document/d/1BWDJPjgRazIAxD1IYoDTYQRFxvqIe4A1qd08UKlahxg/edit

**Comment by jgreben** [comment]
The document is pretty much done but will still be a work in progress. I think at this point with sys-ops help we can spin up a sul-folio-dev server and install a folio instance for people to try out.
