### ISSUE TITLE
What fields are needed to load material types

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#40]
I know that we are adding some material types in addition to those provided as default reference data.

In fact, we might want to remove the default ones and reload (once we know how to do the UUID5 types) so that we know the UUID and don’t need to make a map when we load instance/item data.

Either way, we will need to load a few.  What fields should be provided on a spreadsheet?  Then I can get Suzette to fill out a spreadsheet in the “Settings Spreadsheets” folder

**Comment by ahafele** [comment]
Material types are used by Inventory (items), Orders, and Circulation rules. The list is defined in Settings>Inventory>Items. 
We will likely need to add to the default list. 

Notes on Material Types - https://docs.google.com/document/d/104PhH4dzpF50NJc2eEpPeEp5X5UqV6yKVSQPZnwlG-8/edit# 

- Metadata Subgroup has discussed and would like to be kept informed but not best suited to make decision. 
- Acquisitions and CIrc subgroups need to weigh in. 

Questions
- How do we want to edit the default list? 
- Does Acq need their own (separate) list? 
- How to migrate/map the information into instance>items? ** Darsi has a list of item types from Symphony as a starting point to review by Circ group.

**Comment by dlrueda** [comment]
Catherine is doing work on this in the Circ subgroup

**Comment by Laszlo-J** [comment]
Circ subgroup plans to finalize this list within two meetings.

**Comment by ahafele** [comment]
Laszlo confirms this is complete with the new .tsv list in https://drive.google.com/drive/folders/1JE96Yh3ZLK9XeKcyZSMV36SQpd_VzLW2
