### ISSUE TITLE
Install Nolana hot fix

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#401]
do DEV first

**Comment by michelleif** [comment]
supposed to be ready april 19 now

**Comment by michelleif** [comment]
https://wiki.folio.org/display/REL/Nolana+%28R3+2022%29+Release+Notes#Nolana(R32022)ReleaseNotes-Hotfixrelease%231-GreenreleasedatAPril20

**Comment by michelleif** [comment]
see https://issues.folio.org/browse/STCOM-1148 for another step per TAMU
