### ISSUE TITLE
Setup SRU/SRW access

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#406]
https://github.com/folio-org/Net-Z3950-FOLIO#access-via-sru

Preservation would like to use this afterall. @jgreben I don't remember what you said was required here. This ticket is not urgent, but will fill an additional uni2bind use case.

**Comment by jgreben** [comment]
E.g. http://folio-sru-test.stanford.edu/sul?version=1.1&operation=searchRetrieve&query=title=turtle&maximumRecords=1&recordSchema=opac

**Comment by ahafele** [comment]
Documentation sent to Preservation 

https://github.com/folio-org/Net-Z3950-FOLIO/blob/master/doc/capabilities.md#sru-searching
https://github.com/folio-org/mod-search/tree/release/v1.8#cql-query-operators
Example with barcode - http://folio-sru-test.stanford.edu/sul?version=1.1&operation=searchRetrieve&query=item.barcode=36105123455300&maximumRecords=1&recordSchema=opac
