### ISSUE TITLE
Deploy Lehigh FOLIO Order import tool for Evaluation by Staff

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/FOLIO-Project-Stanford#407]
After discussion with LibSys, we want to deploy a local version of the Lehigh University's [FOLIO Import Tool](https://github.com/folio-labs/folio-order-import-tool) as a possible interim solution for loading Order records into FOLIO. While this tool doesn't have an API for use by the dataloading management app, we have decided that instead of implementing custom Order generation from MARC BIB vendor records in our dataloading app, we will instead wait until we deploy FOLIO's Orchid release later in the year that has support for Order loading in the mod-data-import app. In the meantime, acquisition staff have agreed to manually load orders and want to evaluate the [FOLIO Import Tool](https://github.com/folio-labs/folio-order-import-tool) to see if it is suitable for the job this fall. 

Action items:
- [x] Investigate the needed specs and generate Puppet PRs for provisioning a VM by Ops 
- [x] Deploy the Lehigh App either running as Java App directly on the VM or using [Docker](https://github.com/folio-labs/folio-order-import-tool#docker-image)

**Comment by jermnelson** [comment]
Corresponding Ops ticket https://github.com/sul-dlss/operations-tasks/issues/3356. The server is now running at https://sul-folio-orders-dev.stanford.edu/ connecting to folio-test. @ahafele can you confirm and close this ticket?

**Comment by ahafele** [comment]
Confirmed that I can load a file and get an Order record in folio. https://folio-test.stanford.edu/orders/view/03321ca8-852b-4f79-bb8f-620d3c5016a1 
More testing needed by Acq and will create additional tickets if needed.
