### ISSUE TITLE
Update Order holding codes in Symphony

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#408]
Need to update a large number of Order holding codes. Can be done with Data Control. Attached list if for SUL but Law has a similar issue - need to ask them if they can generate a similar spreadsheet. 

List from Irina that I believe is based on serial control holding code, so I don't think we would need to also update the serials control code.  https://docs.google.com/spreadsheets/d/1dnQmvwMikGWl0qNghwt1UWx5jDuvnJaw/edit#gid=1040530438 

From Kat 

They can be modified with Data Control or with the editdist tool.
In Data Control, you can read in a file of distribution keys and output the holding code.
 
![image.png](https://images.zenhubusercontent.com/6259789bd12079728cab41a1/ebaba9c6-ec73-4f62-996c-6201b9b40f8c)Image
 
![image.png](https://images.zenhubusercontent.com/6259789bd12079728cab41a1/189db3a7-6bcb-4794-b015-83786c5c0b3c)Image
 
Above is a shot from my system, but you could sort this by current Holding Code and then Batch Edit only the groups of those that need to change one at a time.
 
The same steps could be done with SerDist (serial distributions table).
 
Using editdist, if you have the keys at the command line, you would change each group with:
cat small_group_of_dists | editdist –qNEWCODE >distout 2>disterr
 
For editserdist, if you have the keys at the command line, you would change each one with:
cat small_group_of_serdists | editserdist –bNEWCODE >serdistout 2>serdisterr

**Comment by ahafele** [comment]
@dlrueda Irina updated the report to include _SYM Distribution ID_. I think that is correct, yes?  https://docs.google.com/spreadsheets/d/1dnQmvwMikGWl0qNghwt1UWx5jDuvnJaw/edit#gid=1040530438

**Comment by dlrueda** [comment]
3 orders updated on Bodoni and are being reviewed
965549F15|ARS-H|5787698|
951673F15|ARS-H|5780998|
866710F14|ARS-H|5776892|

**Comment by dlrueda** [comment]
Irina and Suzette reported the 3 look fine, so will update the rest on bodoni

**Comment by dlrueda** [comment]
Work complete on Bodoni 5/2/2023.

Done with editdist api.

See /s/SUL/OneTime/Order-UpdateHoldingCode directory for howto, work files, and report files.
If users want a final output of holding code now on the distribution keys they supplied, can do from ords-to-* files.

**Comment by ahafele** [comment]
Law is preparing a similar spreadsheet and hopes to have it to us by early next week. Want me to add here or new ticket @dlrueda ?

**Comment by dlrueda** [comment]
Adding to this one is fine, please tag me again when it’s ready

**Comment by ahafele** [comment]
@dlrueda here is a report from Law for the changes the want made, but it doesn't include the distribution keys. Can you work with this? Might be tricky to have them try and generate with dist key. 
https://docs.google.com/spreadsheets/d/1Izia5RTWpD884SRie61aeOTAxpojKEPm/edit#gid=1818066575

**Comment by dlrueda** [comment]
Any chance @trapido can work with them and output the distribution key?  If they aren’t doing this in BCA then maybe not and I can create the string of selcommands to get down to the distribution key in that order.  But if there are multiples and not all of them are set to the “old holding code” then this will get more complicated.

Irina, just let me know if you can’t, and I’ll do the sels and go from there.

**Comment by trapido** [comment]
@dlrueda I ran a BCA report and it looks like almost all Law orders have multiple distribution keys (see attached), and the holding codes are not always the same: 1324L04, 3921L01, 1989L98, 5365L02, 3255L03 have one distribution with GREEN-H holding code and the rest with LAW-H; 547L98 and 4387L99 have a “POLICY NOT FOUND” distribution in addition to LAW-H, 2692L00 – some distributions have “LAW-H” and some have “LAW-BAS-H”, 3044L08 – has “LAW-INT-H” and “LAW-H” distributions, etc.
Should I tell Law that they should have the same holding code?
[Law Holding Codes.xlsx](https://github.com/sul-dlss/FOLIO-Project-Stanford/files/11502978/Law.Holding.Codes.xlsx)

**Comment by trapido** [comment]
@dlrueda Law provided a new report with distribution keys: https://docs.google.com/spreadsheets/d/1w1QVPlbAH4-a131pFK-3zalcnSNGqkUa/edit?usp=sharing&ouid=106621209740850014250&rtpof=true&sd=true

**Comment by dlrueda** [comment]
Law holding codes updated 6/13

**Comment by ahafele** [comment]
@trapido this work has been done! Do you want to share with Law and have them review?
