### ISSUE TITLE
Migrate vendor extended info

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#409]
For SUL and Law. 

Shelley says - may have to create a script to extract that data in tab-delimited format. We have some code for loading user notes from Symphony into folio that I could refactor for loading vendor extended info notes (they both use the mod-notes folio module

Per email from Suzette and Jake: 
Note type: Create a new label called "Organization"
·  Note title: Since there has been no consistent use of Note vs Comment in Symphony, we propose making all the note titles say "Note" in Folio for consistency. If we have a Comment title, there might be questions later about what the difference is between the two.
·  Details: The value for the field. We think this should be repeatable and a new note for each field. So for the example below, there would be 8 different notes; but all will be titled "Note."
![image.png](https://images.zenhubusercontent.com/6259789bd12079728cab41a1/89c336b8-a15e-4e90-b4ab-a57afcbc80a4)

**Comment by shelleydoljack** [comment]
@scanedastanford to select the vendors, I want to make sure I'm using the same selection you are using for the reports you run to get vendor data out. If I look at the vendor selection from the order selection scripts (yes, it starts with vendors), the vendors are selected based on fiscal year and if total orders > 0. Is this the same for the vendor reports you run?

**Comment by shelleydoljack** [comment]
Oh, probably don't want to limit by total orders since that will exclude BUSINESS.

**Comment by shelleydoljack** [comment]
So I thought we could use selved to get the vendor xinfo out, but its format is not supported by that tool (if it were, then we could output tsv and refactor some code we have to load user notes). We could use `selvendor -O7` but we get a multi-line formatted file that will not be fun to work with. e.g.
```
.VENDOR_LIBRARY. LAW
.VENDOR_ID. YBP
.VENDOR_XINFO_BEGIN.
.SAN. 1694510
.NOTE. X12 CAPABLE
.NOTE. Login for GOBI -- UN:achen7132; PW: rcrown
.NOTE. 6/1/09: Karla Meyette (KMeyette@ybp.com) for US orders, Ruth Spink (RSpink@ybp.com) for UK orders; lp: amc
.NOTE. 11/14/22: Per Lynn Lamy, effective immediately, my colleague Suzanne Good (SuzanneGood@ybp.com) will be serving as your designated GOBI Customer Service representative."; lp: jlk
.VENDOR_XINFO_END.
```
veddump is even worse. However, I see that the vendor extended info is already in the XML reports that @scanedastanford generates from Symphony, so I'm thinking maybe we use that data instead. e.g.
```
<vendorExtendedInfo>
<entry name="Standard Address #">1694510</entry>
<entry name="Note">X12 CAPABLE</entry>
<entry name="Note">Login for GOBI -- UN:achen7132; PW: rcrown</entry>
<entry name="Note">6/1/09: Karla Meyette (KMeyette@ybp.com) for US orders, Ruth Spink (RSpink@ybp.com) for UK orders; lp: amc</entry>
<entry name="Note">11/14/22: Per Lynn Lamy, effective immediately, my colleague Suzanne Good (SuzanneGood@ybp.com) will be serving as your designated GOBI Customer Service representative.&quot;; lp: jlk</entry>
</vendorExtendedInfo>
```

**Comment by shelleydoljack** [comment]
Closing this ticket since this will be handled in folio-tasks.
