### ISSUE TITLE
export data import info from sul-folio-test

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#41]
Kent asks:

in data import settings, could job profiles, action profiles and field mapping profiles be moved to folio-test.dev.sul.stanford.edu

Certainly we will want to load these things in future.  Question is, can we get them out of sul-folio-test now before retiring it?

**Comment by shelleydoljack** [comment]
The API documentation to get the job profiles is at https://s3.amazonaws.com/foliodocs/api/mod-data-import-converter-storage/p/data-import-converter-storage.html . It shows we would need to GET the endpoints /data-import-profiles/jobProfiles, /data-import-profiles/actionProfiles, /data-import-profiles/mappingProfiles, and /data-import-profiles/profileAssociations. The documentation for profileAssociations is really sparse and it's not clear how to GET the data. I also experimented with POSTing to /data-import-profiles/jobProfiles the json data for a job profile I got out of sul-folio-test and I keep getting a http 422 error about a bad/unrecognized field. It seems like it'll be easier for users to re-create these profiles in folio-test and for a down-the-road solution to do a database copy for maintaining users' data they've entered in test systems.

**Comment by dlrueda** [comment]
You don’t mean a pure database copy of everything, right?  I don’t think it’s going to work to do a database copy for everything in the database and port to a new instance.  We aren’t going to want all the bib data, or checkouts, or order records.  (At least I don’t think so.)

We’re going to want to automatically load our “policies” that we’ve figured out and want to keep: location hierarchy, loan policies, data import settings (as in this ticket).

Maybe that’s all repeating what you already meant by “database copy"

**Comment by dlrueda** [comment]
I wondered how TAMU dealt with loading up the data import profiles stuff

On https://github.com/TAMULib/mod-data-migration/blob/main/scripts/reference_data_cleanup.sh
they have lines 
select '/data-import-profiles/jobProfiles/' || id from diku_mod_data_import_converter_storage.job_profiles where id not in ('d0ebb7b0-2f0f-11eb-adc1-0242ac120002', '91f9b8d6-d80e-4727-9783-73fb53e3c786');
select '/data-import-profiles/actionProfiles/' || id from diku_mod_data_import_converter_storage.action_profiles where id not in ('d0ebba8a-2f0f-11eb-adc1-0242ac120002', 'cddff0e1-233c-47ba-8be5-553c632709d9', '6aa8e98b-0d9f-41dd-b26f-15658d07eb52', 'fa45f3ec-9b83-11eb-a8b3-0242ac130003', 'f8e58651-f651-485d-aead-d2fa8700e2d1');
select '/data-import-profiles/matchProfiles/' || id from diku_mod_data_import_converter_storage.match_profiles where id not in ('d27d71ce-8a1e-44c6-acea-96961b5592c6', '31dbb554-0826-48ec-a0a4-3c55293d4dee');
select '/data-import-profiles/mappingProfiles/' || id from diku_mod_data_import_converter_storage.mapping_profiles where id not in ('d0ebbc2e-2f0f-11eb-adc1-0242ac120002', '862000b9-84ea-4cae-a223-5fc0552f2b42', 'f90864ef-8030-480f-a43f-8cdd21233252', 'bf7b3b86-9b84-11eb-a8b3-0242ac130003', '991c0300-44a6-47e3-8ea2-b01bb56a38cc’);

and this has json format for the data
https://github.com/TAMULib/mod-data-migration/tree/main/src/main/resources/referenceData/bibs

**Comment by shelleydoljack** [comment]
https://github.com/sul-dlss/folio_api_client/pull/30
