### ISSUE TITLE
Collection Care locations needed

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#410]
Use TS-* instead of SUL-*

TS - Collection-Care (change SUL-COLLECTIONCARE to this)
TS - CC - Bindery-Prep
TS - CC - Book-Jacket
TS - CC - Repair
TS - CC - Kasemake
TS - CC - Special-Projects 

All under SUL Collection Care service point.

@dlrueda if these names look good I can create and then put in spreadsheet. Do you want dashes in the name or just the code?

**Comment by dlrueda** [comment]
Checking with Access Team at standup today about not having the “library stem” at the beginning of these, making sure not a problem for SW.

**Comment by dlrueda** [comment]
Consensus was that having the library stem would be better.  Then when Law and HILA want their flavors of these, the pattern will be easily set.
So I think that means:
SUL TS CC Bindery Prep as the names and SUL-TS-CC-BINDERYPREP as the code
etc

**Comment by ahafele** [comment]
@ahafele related - Need to update the matrix to assign collection care service point to CC members.

**Comment by ahafele** [comment]
@dlrueda the new locations have been added to test and updated in the tsv file (at bottom with new in column k). Ready for your review and then to be put on folio-stage
