### ISSUE TITLE
TS New Book tracking

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#411]
Change service point _PILOT - SUL - Processing_ to **SUL - TS - PROCESSING** and code?
Change location _PILOT - Processing_ to **TS - Processing** and code?

Add to spreadsheet and stage

@dlrueda are these names ok?

**Comment by dlrueda** [comment]
we decided we should follow pattern for locations to include SUL, so 
SUL-TS-PROCESSING for location code, SUL TS Processing for name

**Comment by ahafele** [comment]
Need to update the service point names for MD, Collection Care, and Acq also

**Comment by ahafele** [comment]
Updated on test and added to folio-ops tsv

**Comment by ahafele** [comment]
@dlrueda ready for additions or for Shelley to add to folio-stage

**Comment by jgreben** [comment]
this is done
