### ISSUE TITLE
Database records and SW facet

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#415]
Creating ticket to discuss this further. 
Per Greta - The Databases facet in SearchWorks is driven by data from the MARC record.  All the facets are but there are a couple of twists with Databases.  In addition to (or often instead of) the 008 value for databases that it looks for, you can also add items to the facet by changing the Symphony item type to  DATABASE.    Also, there are database topics which are letter codes that i add in an 099 field so that you can specify that you want say Biology databases or fil studies databases and what not.

Database A-Z list should be fine since those topics are generated from 099 in MARC and that will continue to be populated. https://searchworks.stanford.edu/databases

Database facet currently uses combo of 008 and item type. In FOLIO 008 will continue to exists, Instance level Stat code of `database` will be used instead of an item type. This work is not yet done - https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/416#issuecomment-1588200537

**Comment by ahafele** [comment]
@saseestone can you take a look at the above? Do we need to keep this ticket open?

**Comment by saseestone** [comment]
New ticket created: https://github.com/sul-dlss/searchworks_traject_indexer/issues/948

**Comment by saseestone** [comment]
New ticket created: https://github.com/sul-dlss/searchworks_traject_indexer/issues/948. I'm inclined to close this one, and track in our SearchWorks/FOLIO project board. Feel free to reopen if desired.
