### ISSUE TITLE
Create script to create test users

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#42]
base it on script Josh made to load the testing users on  sul-folio-test.  it’s ok to have them all be admin type users with all permissions.

**Comment by jgreben** [comment]
See: https://github.com/sul-dlss/sul_folio_scripts/tree/main/single-server-install#scripts-to-create-admin-users

**Comment by jgreben** [comment]
Fixed by https://github.com/sul-dlss/sul_folio_scripts/pull/9
