### ISSUE TITLE
Aeon lookup to bodoni cgi-bin script during cutover?

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#420]
Hi Darsi,

I'm following up on the possibility of keeping the Aeon look-up on during the cutover week of August 19th, which came up during the Cutover Planning meeting today. As I mentioned in the chat, it would be super ideal for Hoover for the look-up to remain on, so that we can fulfill researcher requests during that week. As I mentioned, not being to have Aeon pull barcodes during that week would be very difficult for us.

I know it will take some testing to keep that connection in to the server during that time, so thank you so much for your help with this!

Please let us know if you have questions for us. 

Best,
Rhea

**Comment by dlrueda** [comment]
The big question in my mind about this is if we can have some cgi-bin scripts still available on bodoni but have MyAccount off.  MyAccount needs to be off during cutover (I think anyway, it would be too much work to try and have a view-only MyAccount for that 1-2 weeks).  So do we need to have the Symphony netserver halted entirely? Would that make cgi-bin scripts unusable?

**Comment by shelleydoljack** [comment]
Halting the Symphony netserver would make all the cgi-bin scripts unusable. We determined in libsys staff on 8/4/2023 that we could leave the scripts untouched during cutover since they all do lookups and the one that doesn't won't work or be called during cutover.
