### ISSUE TITLE
Update Organizations migration to map customer codes correctly

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#421]
Suzette will add info to https://docs.google.com/spreadsheets/d/13bh1Dd-v_tC0A5iepeTxWVBjj2JLz3lmvFglFDjOcD4/edit#gid=1806017489 so that conversion that can happen to move e.g. 9000 to feeder.

**Comment by scanedastanford** [comment]
I've added it to the mapping, line 5. But now I wonder if I should just update them in the xml vendors report I will be sending. Will that be better?

**Comment by shelleydoljack** [comment]
I think I'll just add it to the code for organizations migration. Less things to do manually after rollover when we migrate.

**Comment by ahafele** [comment]
@shelleydoljack can we close this ticket then?
