### ISSUE TITLE
Update Organizations migration to use "tax paid to vendor" to check "Liable for Vat"

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#422]
Suzette will include in next Org report. @scanedastanford is above correct? "tax paid to vendor" = "Liable for Vat"?

**Comment by scanedastanford** [comment]
Yes, I can include this in the xml vendors report that I will send for addresses. In the report, it will have:
<taxPaidToVendor>true</taxPaidToVendor>
These are the ones we want the "Liable for Vat" checked.

**Comment by ahafele** [comment]
@scanedastanford once your review of this is done, could you close this ticket? Thanks!
