### ISSUE TITLE
Create app_caiasoft user and Pset for it

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#424]
After meeting with Laura of Caiasoft, we confirmed that we will NOT be using the edge_caiasoft module/functionality.  She will update/lookup everything via APIs.

We need an app_caiasoft user for this purpose.

We no longer need the app_edge_caiasoft user (I’m pretty sure) if we’re not using the edge_caiasoft module.  So if it’s safe to re-use/re-purpose/re-name app_edge_caiasoft to app_caiasoft, that’s fine by me.  Or create a new user, whichever.

Permissions needed:
Probably Psets: Cat5, Access 5
(needs to do lookups, edit holdings, edit items, edit SRS (to update Lane’s marc holdings), Checkin, maybe other circ functions, not sure)
(Her caiasoft user is assigned the folio_admin Set at Cornell !!)

**Comment by dlrueda** [comment]
Needed on folio-test.  Will need on folio-prod.  Not really needed on folio-dev or folio-stage (but doesn’t hurt if easier)

**Comment by jgreben** [comment]
https://folio-test.stanford.edu/users/preview/a50d2717-cdaf-581e-b0ab-af79790bd403?query=app_caiasoft&sort=name

**Comment by jgreben** [comment]
What permissions does this user or permission set actually need.

**Comment by shelleydoljack** [comment]
> What permissions does this user or permission set actually need.

Let's not nest the staff user psets with app user psets (i undid all the nesting we had for app_mylibrary, etc.). I think take a look at those staff user psets Darsi mentions above (Cat5, Access 5) and add those permissions to the remote_storage pset.

**Comment by shelleydoljack** [comment]
@dlrueda Don't we still need a remote_storage pset?

**Comment by dlrueda** [comment]
I forgot!

**Comment by shelleydoljack** [comment]
remote_storage pset created in folio-test and added to permission_sets.json, which was uploaded to FolioOps migration files. rake task to load pset and assign pset to app users ran on folio-test, -stage, and -prod. app_users.tsv also updated to remove "_edge_" from the name field.
