### ISSUE TITLE
Slow/failing circ transactions after Nolana hot fix 1

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#425]
Filed a ticket in FOLIO Jira [CIRC-1783](https://issues.folio.org/browse/CIRC-1783) for very slow checkout behavior after updating to Nolana hot fix 1.

Tara of IndexData asked Wayne, who wonders:
I think they should monitor the logs of mod-inventory-storage, mod-users, and mod-circulation-storage to see if there are inefficient SQL queries getting logged. It may be that they have some rule that forces a check against some property of the item or something that is not indexed and causes a problem when you have 10 million records.
They may also want to check the Kubernetes Deployment for mod-circulation. We generally run 3 replicas, and we use the default memory allocation from the module descriptor (1073741824 bytes). I would say with more complex rules one may want to bump that up, but they should look at the actual memory usage first to see if they are pushing the limit (although we haven't, and you say CU has a crazy rule set, as well, so maybe that's not an issue).

Note that Tara has a system with 700+ rules (not at hot fix 1 I don’t think) and it doesn’t show slowness.

**Comment by jgreben** [comment]
I think this was resolved pretty much with the resource enhancements to the modules.
