### ISSUE TITLE
Load new locations and service points to folio-stage, folio-dev

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#429]
There are a few new locations and service points created on folio-test that we should load to folio-dev and folio-stage for consistency.

Files are in FOLIO Ops Drive in 
[Migration Files - tsv - tenant directory](https://drive.google.com/drive/u/1/folders/1EyaO2EInNKHFq8Kx0q-KbYPGGqAnGSOs)

Load service points first.

Named
servicepoints-new-May5.tsv
locations-new-May4.tsv

Only new locations to load are in those files.  locations.tsv and service-points.tsv ALREADY HAVE these locations and service points, no need to update.

You can remove servicepoints-new-May5.tsv and locations-new-May4.tsv when finished.  These files were created for the sole purpose of loading just these new locations/service points to folio-stage and folio-dev.

**Comment by shelleydoljack** [comment]
Loaded to folio-dev and folio-stage. Doublecheck it's okay? I didn't see any errors in the stdout when loading.

**Comment by shelleydoljack** [comment]
Deleted the files from Folio Ops drive.
