### ISSUE TITLE
Reload FUNDS data with new column 

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#43]
Lane and Law are adding more data to the FUNDS spreadsheet and externalAccountNo is being populated. Will need to be reloaded to test once this is complete. 

Is this the right repo for this or should it go into sul_folio_scripts?

**Comment by ahafele** [comment]
This spreadsheet is now ready to be reloaded to test. 
https://docs.google.com/spreadsheets/d/1N0GIPHXHpHfBSZczxxMnvkwJp0yn_f68DT8c7mGK-vE/edit#gid=0

**Comment by shelleydoljack** [comment]
The ledgers need to be updated before this funds spreadsheet can be loaded. I think maybe we need to fix the fiscal year in the ledgers spreadsheet to 2022?

**Comment by ahafele** [comment]
Per Suzette - ok to update to 2022.

**Comment by ahafele** [comment]
Done by Shelley on 12/10/21
