### ISSUE TITLE
put Symphony authkey in subfield 0 instead of subfield =

### ISSUE THREAD

**Issue by michelleif** [sul-dlss/FOLIO-Project-Stanford#430]
we tested migrating Symphony authkey for headings into $=, FOLIO quickMARC doesn't like this, so instead:
put authkey into $0

do test on DEV first

**Comment by dlrueda** [comment]
@rlunnon is there a list of tags this should be performed on?

Or is “all fields in the marc record” safe to do this on?  Is $= a valid field in any other marc tag?

**Comment by rlunnon** [comment]
Here is a list of the bib tags that may have a subfield =.  The 400,410 and 411 tags are authorized but there are only a handful, and none has a subfield = , so I did not include them. The 240 tag is authorized only in the RECORDING and SCORE formats. 

[Symphony tags with subfield =.xlsx](https://github.com/sul-dlss/FOLIO-Project-Stanford/files/11657185/Symphony.tags.with.subfield.xlsx)

**Comment by jermnelson** [comment]
Thanks @rlunnon, for the 240 field, is the format for RECORDING and SCORE in the subfield $h or do should I look in a different field/subfield in the record to make this determination?

**Comment by rlunnon** [comment]
@jermnelson it wouldn't do any harm to check the 240 in all records, if that is easier than sorting out the RECORDING and SCORE records. There shouldn't be any 240 with subfield = in the other formats.

The record format is determined by position 06 of the leader. 
RECORDING format values:
i
j

SCORE format values:
c
d

**Comment by michelleif** [comment]
update: waiting to see if Khalilah gets back to Vitus on whether or not adding the $0 will mess up authority matching later

**Comment by ahafele** [comment]
Per Vitus, Khalilah has given the go ahead. See thread [here](https://folio-project.slack.com/archives/CTCB5HVLZ/p1686073896643469).

@jermnelson please change $= to $0 and add (SIRSI) e.g. |0(SIRSI)1863552

Run test on -dev first.

**Comment by ahafele** [comment]
@dlrueda Vitus also asked to `Delete all the |?UNAUTHORIZED because we won't need them. They will just clutter up the field.` does that get done here or in your export?

**Comment by ahafele** [comment]
related to #472

**Comment by dlrueda** [comment]
deleting the string `|?UNAUTHORIZED` should be done on the airflow side.  So it can be a part of this ticket.

**Comment by jermnelson** [comment]
@ahafele question about the authkey value. In the MARC records I've seen with the subfield `$=`, the authkey has a caret character before the value i.e.` $=^A262428`, that with the SIRSI prefix ends up in the subfield `0` as `$0(SIRSI)^A262428`. Should the caret character be removed?

**Comment by ahafele** [comment]
Hmm I defer to @dlrueda on this one. Darsi, see question about about ^
Jeremy, please also add to this work the deleting of the string` |?UNAUTHORIZED `

**Comment by dlrueda** [comment]
Absolutely remove the caret!  In fact, remove “^A” so both the caret and the A.

Sorry it should’ve been in the original spec, doh.

**Comment by jermnelson** [comment]
Thanks @ahafele and @dlrueda! Will remove `^A` for the subfield. Also, are there any MARC records examples I can test to remove `|?UNAUTHORIZED`? Thanks!

**Comment by ahafele** [comment]
a14465595
a14257390
a4365992

**Comment by dlrueda** [comment]
and some from range ckeys_13350000_13399999

.001. |aa13399970
.001. |aa13399971
.001. |aa13399973
.001. |aa13399974
.001. |aa13399976
.001. |aa13399977
.001. |aa13399978
.001. |aa13399980
.001. |aa13399981
.001. |aa13399983
.001. |aa13399984
.001. |aa13399985
.001. |aa13399986
