### ISSUE TITLE
Series and POL number linking issue

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#432]
**Problem** Ongoing orders that have multiple lines but POL 1 did not load as/get linked to the series title, for example: https://folio-test.stanford.edu/orders/view/b628cdf4-d47a-59ae-97d0-6ea5ee4072e9?qindex=poNumber&query=181779F07
 where POL 2 is the series title. 
 
**Solution**
Don't run the recurring order line 2 script and only run the recurring orders line 1 script

**Details from email**
 
From: Shelley Doljack
Date: Thursday, May 18, 2023 at 1:53 PM
To: Suzette Caneda
Cc: Alissa T Hafele , Jake Kubrin
Subject: Re: POL 1 not linked to series title

Hi Suzette,
 
We have two scripts for recurring orders. Recurring orders line 1: selects orders with number of line items greater than 0 and selects the orderlines copies paid = 0 and copies funded > 0 and then I select specifically orderline 1. The other script,  recurring order line 2, we select orders with number of line items greater than 1 and selects the orderlines copies paid = 0 and copies funded > 0. I think this means we would not run the second script.

**Comment by shelleydoljack** [comment]
`*_recurord_lin2.ksh` scripts renamed and made not executable.
