### ISSUE TITLE
Verify |Z of boundwith children is being add to the child holdings record

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#437]
What about cases where there are multiple child |Z to deal with? Manually add a note for these edge cases?

**Comment by ahafele** [comment]
@shelleydoljack do you want to verify that the code handles this or do you want me to have a user verify the data?

**Comment by shelleydoljack** [comment]
It's not. See https://github.com/sul-dlss/searchworks_traject_indexer/issues/904

**Comment by ahafele** [comment]
https://github.com/sul-dlss/searchworks_traject_indexer/issues/904#issuecomment-1611388125

**Comment by shelleydoljack** [comment]
Fixed in latest production migration
![Screen Shot 2023-07-10 at 12 44 29 PM](https://github.com/sul-dlss/FOLIO-Project-Stanford/assets/6343464/cba788fd-5c9a-4c8e-ab43-b9ab522b9a43)
