### ISSUE TITLE
Save UUIDs not working from -test or -stage

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#438]
Inventory - `Save Instances UUIDs` and `Save Holdings UUIDs` not working. Message says the request was received but the download doesn't ever happen. Tried -test and -stage on chrome and firefox.

![Screen Shot 2023-05-30 at 7.42.35 AM.png](https://images.zenhubusercontent.com/6259789bd12079728cab41a1/bfe1da4d-5f6b-423d-900f-6374289f4e30)

**Comment by michelleif** [comment]
I tried this on TEST just now with Chrome and it works. (I had problems with saving different data previously and the issue was that I hadn't allowed pop-ups on Chrome)
