### ISSUE TITLE
GOBI brief bibs and Orders create connection failure

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#445]
A test for [GOBI brief bibs and Orders](https://sul-libsys-airflow-stage.stanford.edu/vendor_management/interfaces/1) resulted in a failed[ create_connection_task](https://sul-libsys-airflow-stage.stanford.edu/dagrun/list/?_flt_3_dag_id=data_fetcher&_flt_3_state=failed). Connection info in interface is correct.

I'm not sure if this is a bug or related to the the in progress work referenced [here](https://stanfordlib.slack.com/archives/C04EZLBMLQN/p1685726461504169?thread_ts=1685722773.673209&cid=C04EZLBMLQN). Ticketing so I don't loose.

**Comment by justinlittman** [comment]
![image.png](https://images.zenhubusercontent.com/5d8270f64def500001d12f23/f89e3654-8235-4faa-a66f-d2774fb017e5)

**Comment by ahafele** [comment]
This works. URI was missing. Test connection feature will help, thanks!
