### ISSUE TITLE
Manual upload error for Marcit 

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#447]
I've configured but not made active the Marcit [New interface](https://sul-libsys-airflow-stage.stanford.edu/vendor_management/interfaces/22) and tried to manually upload a file. It is failing on the [data_import_task](https://sul-libsys-airflow-stage.stanford.edu/log?execution_date=2023-06-07T13%3A35%3A46%2B00%3A00&task_id=data_import_task&dag_id=default_data_processor&map_index=-1). 

But files are making it to Data Import and loading.

**Comment by justinlittman** [comment]
@ahafele Is this working or still broken?

**Comment by ahafele** [comment]
@justinlittman yes but not in the same way as before. This [error](https://sul-libsys-airflow-dev.stanford.edu/task?dag_id=default_data_processor&task_id=data_import_task&execution_date=2023-06-14T16%3A30%3A20%2B00%3A00&map_index=-1) was sent to email but I don't see the fail [here](https://sul-libsys-airflow-stage.stanford.edu/dagrun/list/?_flt_3_dag_id=default_data_processor&_flt_3_state=failed). Last time the file actually made it to data import despite the failure, this time not.

**Comment by justinlittman** [comment]
I think I have the fixed if you want to test again.

**Comment by ahafele** [comment]
~~@justinlittman trying again but has been stuck in default_data_processor for some time despite status of loaded with a timestamp. https://sul-libsys-airflow-dev.stanford.edu/vendor_management/files/4038~~
Forget that, will test on -stage and then comment with accurate info

**Comment by ahafele** [comment]
Working.
