### ISSUE TITLE
point Help link in FOLIO UI to our own help page

### ISSUE THREAD

**Issue by michelleif** [sul-dlss/FOLIO-Project-Stanford#452]
instead of having the FOLIO Help button go to default of docs.folio.org, point it to Stanford's own FOLIO help site:

https://sites.google.com/stanford.edu/folio-training-central/help

This ticket has info on how to do it
https://issues.folio.org/browse/STCOR-621

**Comment by michelleif** [comment]
need to adjust [no forking policy](https://docs.google.com/document/d/1aw1arjC2WiX6um49HsRZ31Lg9XYcuXSmQ0TH7FvSGGg/edit)  if we do this?

**Comment by jgreben** [comment]
This should not really apply to the forking policy because we already need to (and do) fork this. The policy should be updated.

**Comment by michelleif** [comment]
policy is being updated (suggested text [here](https://docs.google.com/document/d/1aw1arjC2WiX6um49HsRZ31Lg9XYcuXSmQ0TH7FvSGGg/edit?disco=AAAA5ZPKBmc)

can we make the change in FOLIO to point the Help button to our help site?

**Comment by jgreben** [comment]
See:
- https://github.com/sul-dlss/folio-platform-complete/commit/dcbd8c99a39791ab42c1e8ac91ce826f136fecdd
- https://github.com/sul-dlss/folio-platform-complete/commit/022a31bab90574669dcff613cbdc95460a463ea6
- https://github.com/sul-dlss/folio-platform-complete/commit/c41e00e98e86ed76049e0fd0fbec2070ffbdf643
- https://github.com/sul-dlss/folio-platform-complete/commit/16d514facffcb11d7d19401cbc524b64d57b3082
