### ISSUE TITLE
Lehigh Tool - set material type to book

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#453]
In the startup properties file could we please set the materialType to book? https://github.com/folio-labs/folio-order-import-tool#pre-configured-values-defined-as-parameters-in-the-startup-properties-file

**Comment by jermnelson** [comment]
materialType now set to "book" in `import.properties`. Restarted service on the VM and new configuration is present in UI:

![Screenshot 2023-06-12 at 3 23 48 PM](https://github.com/sul-dlss/FOLIO-Project-Stanford/assets/71847/8391af0d-06aa-4d17-95d6-780ac64e3d38)

**Comment by ahafele** [comment]
@scanedastanford could you give this a test and if all good you can close this ticket.

**Comment by scanedastanford** [comment]
I get an error: Error: Record is missing material type (looked in 980$d)

**Comment by ahafele** [comment]
@jermnelson not urgent, but reassigning to you. We aren't sure why the new setting is not working.
