### ISSUE TITLE
Error on Refresh Data from FOLIO

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#454]
https://app.honeybadger.io/projects/111133/faults/96773912

**Comment by justinlittman** [comment]
I suspect this is due to the current problem with some of the Folio libraries:

![image.png](https://images.zenhubusercontent.com/5d8270f64def500001d12f23/f18471a3-bc38-4c74-902a-14282189c82d)

**Comment by justinlittman** [comment]
@ahafele Can you retest?

**Comment by ahafele** [comment]
Tried again and no error this time, but data is not refreshing. I see the request queued [here](https://sul-libsys-airflow-stage.stanford.edu/dagrun/list/?_flt_3_dag_id=folio_vendor_sync&_flt_3_state=queued) but the DAG is paused. 

I added a test Interface to this vendor https://sul-libsys-airflow-stage.stanford.edu/vendor_management/vendors/2061
see https://folio-stage.stanford.edu/organizations/6043aedf-4234-4446-8873-ee279292f5b0

**Comment by ahafele** [comment]
Tried again and no error this time, but data is not refreshing. I see the request queued [here](https://sul-libsys-airflow-stage.stanford.edu/dagrun/list/?_flt_3_dag_id=folio_vendor_sync&_flt_3_state=queued) but the DAG is paused. 

I added a test Interface to this vendor https://sul-libsys-airflow-stage.stanford.edu/vendor_management/vendors/2061
see https://folio-stage.stanford.edu/organizations/6043aedf-4234-4446-8873-ee279292f5b0

**Comment by justinlittman** [comment]
DAG is now unpaused.

**Comment by ahafele** [comment]
Working as expected.
