### ISSUE TITLE
Download of files when processed are .mrk and should be .mrc

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#455]
Downloading files when there is both original and processed, are .mrk but should be .mrc

When only the original file is available, it downloads as .mrc and this is how it should be. 

Opens as .mrk and should be .mrc 
![Screen Shot 2023-06-12 at 7.52.00 AM.png](https://images.zenhubusercontent.com/6259789bd12079728cab41a1/aa60ac65-c1c2-4689-83f0-93e0d8b67502)

Opens as .mrc and is correct 

![Screen Shot 2023-06-12 at 7.52.04 AM.png](https://images.zenhubusercontent.com/6259789bd12079728cab41a1/c5775dfc-3bbf-43cb-bd6b-c72c08ea0866)

**Comment by justinlittman** [comment]
Determined that this was due to a user upload.
