### ISSUE TITLE
Reporting - Load email counts not accurate

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#456]
The Load Report email is _sometimes_ not reflecting the same counts as the FOLIO load report page. 

User testing indicates that as-is, this report is not useful and would prefer just a link back to the FOLIO report. **bib record(s) read from MARC file.** should remain and is useful. 

Example:

[Load](https://sul-libsys-airflow-stage.stanford.edu/vendor_management/files/8481) for [Casalini](https://sul-libsys-airflow-stage.stanford.edu/vendor_management/interfaces/13) emailed this report:

Filename digital-theatre-plus-all-usa-from-2023-01-2023-05.mrc - https://folio-stage.stanford.edu/data-import/job-summary/d8f2f928-5127-4dba-8007-4860aedb686a

247 bib record(s) read from MARC file.

12 SRS records created

0 SRS records updated

0 SRS records discarded

0 SRS errors

12 Instance records created

0 Instance records updated

100 Instance records discarded

47 Instance errors

FOLIO[ Data Import Report ](https://folio-stage.stanford.edu/data-import/job-summary/d8f2f928-5127-4dba-8007-4860aedb686a) shows:

![Screen Shot 2023-06-12 at 9.12.38 AM.png](https://images.zenhubusercontent.com/6259789bd12079728cab41a1/59d5617c-9a2a-44f7-8d29-c6eb89e76736)

**Comment by justinlittman** [comment]
I suspect that we are declaring victory (and grabbing the stats) on data import before it is completed.

**Comment by mjgiarlo** [comment]
Like @justinlittman says, I suspect our current practice of determining a data import is done---by detecting non-zero numbers in the job summary---is flawed. We should do another round of checking the Folio API documentation, or ask around on Slack to come up with a better strategy.
