### ISSUE TITLE
Timestamps on interface show page

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#457]
Could someone help me understand these different timestamps? 

**Created:** Date entry in log was created? 
**Updated:** ?? 
**File Timestamp:** date file was created. None if manually uploaded.

**Comment by justinlittman** [comment]
Created: When the VendorFile db record is first created. This is performed when a fetch is successfully or unsuccessfully attempted.
Updated: In theory this is supposed to be whenever the db record is updated, e.g., the status is changed. In reality, it isn't always updated (but if there are times that we miss updating it, we can always correct the code).
