### ISSUE TITLE
Reporting email subject line

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#458]
Right now the report email subject line includes the Vendor Name and Vendor Code. 

Could it include the Interface Name and Vendor Code instead? 

e.g. 
current - CASALINI LIBRI (CASALI-SUL)

desired - Casalini - Full bibs (CASALI-SUL)

**Comment by ahafele** [comment]
@mjgiarlo Subject line now includes interface ID. Could it be name instead?

**Comment by mjgiarlo** [comment]
@ahafele I created a new issue for this and put it at the top of Ready: https://github.com/sul-dlss/libsys-airflow/issues/655
