### ISSUE TITLE
Customize default MARC mapping

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#47]
Final decisions not made. 
Vitus interested in the mapping work. 

Work done so far - 
https://docs.google.com/spreadsheets/d/13IC2PCz3OQLBg5ubuMgj-ZM8jk6RmvMb/edit#gid=250086991 and https://docs.google.com/spreadsheets/d/1-YdX758wEXUm2Z6sIR0oGQ917ZdS6Zc7/edit?usp=sharing&ouid=112203764977781723220&rtpof=true&sd=true

**Comment by ahafele** [comment]
This will be discussed further after the Bib QA is complete (first part WC 2 is plan).

**Comment by ahafele** [comment]
I am working on making customizations using https://github.com/folio-org/mod-source-record-manager/blob/master/RuleProcessorApi.md. We will need to then move the customized map from one instance to another. @jermnelson or @jgreben do we just need a ticket to write a task to do this or is it more complicated than that?

**Comment by jgreben** [comment]
@ahafele It depends. Is there going to be a json file provided to upload, or will we need to convert a spreadsheet? I think from the previous discussion it was the former? In that case we could just add a task to the migration checklist because it will just be a POST of the json to the specific endpoint.

**Comment by ahafele** [comment]
Alissa will store the custom mapping json in FOLIO Ops/json. Line has been added to the [check list](https://docs.google.com/spreadsheets/d/1_6QWDtS9zRcwgvc8pDdbKq10A6629y4OU39DsNBApF0/edit#gid=0) to POST this from the drive.
Ongoing work happening here - https://app.zenhub.com/workspaces/folio-support-629a1e61f3dff1001f022159/issues/sul-dlss/folio-support/28
