### ISSUE TITLE
Compare base callnum + analytic with callnum item number

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/FOLIO-Project-Stanford#470]
Need to fix the extra space after `|Z` in callnum that causes the last position of base callnum to be lopped off. Write a script that can be run from cron that outputs `selcallnum -oBZD`, remove pipe between B and Z and check if the string matches what is output in D. If it doesn't match, then output item ID (barcode) so we can fix before migrating to folio.

Background ticket: https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/468

**Comment by shelleydoljack** [comment]
I wrote a script to compare these `/s/SUL/Bin/CompareCallnum/compare_callnum.ksh` and there are 29,477 item records that have issues. The data file is in `/s/SUL/Dataload/CompareCallnum/compare_4`. Seems like way too many to fix manually before migration.

I noticed there is a script `/s/SUL/Bin/CallnumSpaces/vol_spaces.pl` that looks like it is written to remove the space in  `vol. 1` to `vol.1`.  Maybe can be adapted (at least the api transaction part?) to remove the space at the start of `|Z`?

**Comment by dlrueda** [comment]
Adding another script with at the moment just some selcallnums for analysis.
I’m looking for space as the first character of the analytic.

Noticed that if the class scheme is SHELBYTITL then the D output is JUST the analytic, even though -oB also has a value (either the Dewey or LC call number).  So straight comparing D to B+Z will always be wrong for that class scheme.

Wondering if looking for “| “ in the output is a good first step.

Also, can begin the selcallnum with -a”>0” to eliminate any call numbers with no analytic portion

**Comment by dlrueda** [comment]
Script /s/SUL/Bin/CompareCallnum/check_analytic_callnums.ksh 

looks for analytics that begin with 1+ spaces, trims leading spaces from analytic, and generates api commands to update the call number to 
base|Ztrimmed-analytic

Right now splits into different class schemes, which isn’t necessary, but makes it easy to run one file’s worth of apicommands to check results.

Right now selcallnum/selitem is commented out cuz it takes a long time to run (longer than it should).
We could run this occasionally in case more analytics w/ leading space are introduced

@shelleydoljack please review

**Comment by shelleydoljack** [comment]
Looks good.

**Comment by shelleydoljack** [comment]
Although, I have to wonder if the extra spaces in the item barcode field would be bad. I know that's how it comes out from selitem, but maybe not a good idea to have the extra spaces with the API transaction? 🤷

**Comment by dlrueda** [comment]
I realized that this isn’t going to work.  My output was BZ, but the B has cut off the final character of the base callnum because the analytic position is messed up from the space as the first character of the analytic.

So I can’t construct the new call number as B+Z (after removing the space in front of the Z), because the B was missing the last character that should have been there.

I did this first on the 5 SUDOC items, and will try to add back the last character of the base of the call number from pre-update data.

I think maybe an editcallnum (if possible) to update the Z field with Z data without the leading space might work.  Need to test.

**Comment by dlrueda** [comment]
Ugh.

I wrote editcallnum commands with -N/*/new analytic/  (including escaping the /s in call numbers)
but I get 

> Symphony edit callnum 3.7.1 started on Monday, July 17, 2023, 5:07 PM
>   The callnum key will be read from standard input.
>   "*" (old callnum analytic string) will be changed to "V.2",
> and the shelving key will be remade.
>   0 callnum record(s) edited.
> Symphony edit callnum finished on Monday, July 17, 2023, 5:07 PM

for each command.  I think the space is messing up the ability for editcallnum to do it.  If I manually update the calcium in WFs to get rid of the space, and then execute the exact same editcallnum command, it works fine.

**Comment by dlrueda** [comment]
I think this means updating the call number with an API command, and doing something like the following to create the new call number.

output selcallnum -oaDBZ
trim Z of leading spaces (there are sometimes more than 1)
make a new call number consisting of concatenating first (a-1) characters of D, then “|Z", then new-Z

**Comment by dlrueda** [comment]
Made a script in /s/SUL/OneTime/Batch-update-callnums/Space-1stchar-subZ
that generates the api transactions to edit the call number, removing the leading space(s) in the analytic.  Follows the logic in the above comment.

I’ve spot checked a bunch of them and them see ok.

@shelleydoljack please review. 

When this is fine, I’ll manually send the file of api transactions to apiserver

**Comment by shelleydoljack** [comment]
So, I'm not sure how well this works. On line 60, you are using the analytic position to know how far the callnumber goes: `$callnumtoprint = substr($callnumber, 0, $analpos);` but [the analytic position is stored incorrectly in the database](https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/468#issuecomment-1608407811). Wouldn't this just introduce an extra space before the `|Z`? Looking at the apicommands file, it seems to mostly work, I guess, but there are some with a space before the `|Z`, e.g. `^S63IVFFADMIN^FESUL^FcNONE^FWADMIN^NQ36105004778010  ^NAG4232.P3 1982 .U5 |ZSO OR SHEET 3^IoADMIN^^O` Not sure if that will introduce a new problem.

**Comment by dlrueda** [comment]
Alissa, Shelley, and Darsi discussed
We agree the whole problem with these is that the analytic position is in the wrong place, usually one too little.  Recreating the call number and creating the “base call number” portion by taking one extra field beyond what the analytic currently is _looks right_ and we think that’s as good as we can do.  No way to look all of them over.

Data in pre-update state is in /s/SUL/OneTime/Batch-update-callnums/Space-1stchar-subZ

Final steps taken:
“ |” removed manually from apicommands file

apicommands run through apiserver 7/21
records will go through adutext and to SW based on them being done via api transaction

**Comment by dlrueda** [comment]
Next day I thought to check and see that the commands worked, so I ran /s/SUL/Bin/CompareCallnum/check_analytic_callnums.ksh

and it found 36 barcodes with “| “ !!
I checked a few, and they were not in the original file of callnums, so these are new call numbers that have a space as first character of |Z / incorrect analytic position.

I added a date to output filenames so we can run this before Symphony extract for migration
