### ISSUE TITLE
item extended info notes when we don't create items

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#471]
Electronic Resources
Bound-with Children
Basecall nums

We need to migrate these notes to the Holdings record that is created. I propose we create a Holdings Note Type of `Former item note` (staff only) and concatenate all the item extended info notes there. Can we included their type? e.g. `Tech Staff: note here; Circ: note here`

@shelleydoljack @dlrueda @jermnelson thoughts on the above plan?

**Comment by shelleydoljack** [comment]
So there would be 1 `former item note` for a BW-CHILD item that had a tech staff and circ note?

**Comment by ahafele** [comment]
Yes, that was my thinking. The other option is to recreate all the item note types in holdings and use those, but not sure that is worth it for this subset of notes.

**Comment by ahafele** [comment]
Yes, that was my thinking. The other option is to recreate all the item note types in holdings and use those, but not sure that is worth it for this subset of notes.

**Comment by dlrueda** [comment]
Can the `former item note` be repeated? So an item with a tech staff note and a circ note would get two `former item note` notes?  One would be `Tech Staff: note here` and the other would be `Circ: note here`

Maybe we can get ALL xinfo notes out easily in a format that is easily squishable into the holdings note.  But would have to experiment.

**Comment by ahafele** [comment]
Another complication I just thought of - if we have PUBLIC notes and squish them together with everything else, SW would no be able to use them. 

Because of this and Darsi's comment above maybe we just copy what we do with items. E.g. create Holdings Note Types of `Tech Staff` `Circ` `Public` and move them accordingly.

**Comment by ahafele** [comment]
@shelleydoljack going to just create the same note types for holdings and we can migrate these notes into the Holdings record in the same way we do items.

**Comment by ahafele** [comment]
Added to -test and put into a tsv [here](https://drive.google.com/drive/folders/1Nn-PNgniSUH3b_Hi6f2NMNLCXYCWU7Um). Does it need to be added to the migration [checklist](https://docs.google.com/spreadsheets/d/1_6QWDtS9zRcwgvc8pDdbKq10A6629y4OU39DsNBApF0/edit#gid=0) for loading to other instances or will it just get picked up in `load_all_inventory_settings`?

**Comment by shelleydoljack** [comment]
We need a new rake task to load them.

**Comment by ahafele** [comment]
https://github.com/sul-dlss/folio-tasks/issues/228

**Comment by shelleydoljack** [comment]
What are "basecallnums"? Is that item records with "BASECALLNUM" in the call number field? Or something more than that?

**Comment by ahafele** [comment]
I think it is a location that we are not migrating.

**Comment by dlrueda** [comment]
BASECALNUM (note the one L) is right, a location we won’t migrate. (They hooked orders to them in Symphony, they don’t represent a real item)

**Comment by dlrueda** [comment]
Can you add to new_generate_marc_items_tsv.ksh 

I’m putting in the different way to select items in that script, and it’s working.

**Comment by shelleydoljack** [comment]
The format of the tsv file for items that don't get items in folio but the itemxinfo notes go in a folio holdings record, we need to output:
`CATKEY|CALL SEQ|COPY|XINFO NOTE TYPE|XINFO NOTE|`
e.g.
`7860|3|1|CIRCNOTE|this is a circnote|`
with filename: ckeys_$ckeyrange.holdingsnote.tsv, e.g. `ckeys_03700000_03749999.holdingsnote.tsv`

**Comment by shelleydoljack** [comment]
If BASECALNUM is a location we aren't migrating, then is it okay to remove it from this list in the generate marc and items script?
```
# Define home and current locations TO EXCLUDE for each library
migratewd="-l~BASECALNUM,EDI,INSTRUCTOR,LOCKSS"
discardwd="-l~BASECALNUM,EDI,INSTRUCTOR,LOCKSS,WITHDRAWN"
discardwdandshadow="-l~BASECALNUM,EDI,INSTRUCTOR,LOCKSS,SHADOW,WITHDRAWN"
```
And then remove the rows from the tsv where BASECALNUM is in fields 6 or 7 (home loc and current loc) when we `dolog "Start remove internet and bwchild items"` ? Is it okay for the ckeys from the BASECALNUM tsv rows to be included in the files that go to catalogdump? Or would it be safer to remove the BASECALNUM rows before cutting out the ckey field to send to catdumps?

**Comment by dlrueda** [comment]
ah, I suppose it would be safest to remove the BASECALNUM rows before generating the ckey list to generate the marc.

But we could maybe do a sel to see if there were any records with JUST the BASECALNUM item?

**Comment by shelleydoljack** [comment]
ehhh, i'm just gonna remove them before the ckey list is created.

**Comment by shelleydoljack** [comment]
I updated generate_marc_items_tsv.ksh to include BASECALNUM in the locations for selitem and added some code to remove those rows before creating ckey list for catalogdump. I guess the downside of this is that if there is a record with only a BASECALNUM item, it won't have a corresponding marc record to create a folio instance. If we do want a folio instance, then we'd probably need to add some code to make it suppress from discovery. 🤷 Anyways, the basecalnum file gets concatenated with the internet and bwchild files to create one large file of item data to pipe to selved to get the xinfo fields. items_to_50K_ranges.pl was updated to split the resulting holdings_xinfo_2 file into ranges. There is a holdings_xinfo.ksh script in the scriptdir that was only used for testing the xinfo output. The changes made should just work™️ if I got the cut right:
```
# for each resulting holdings note file
for i in `ls $bibkeydir/holdingsnote*`
do
  #filenames startwith: holdingsnote_
  ckeyrange=`basename $i | cut -c14-`
```

**Comment by shelleydoljack** [comment]
Ugh, but now I see, of course, there are pipes in the data people entered into these fields, which is messing up the column count:
```
1138856|3|1|TECHSTAFF|ENTRY>|aac, coded as bound with, i:nr 03/21/2023; deleted a space after |c and |b in 590, i:bz, 6/29/23<ENTRY|
1166949|2|1|TECHSTAFF|ENTRY>|acorrected call no. from:063 .H465P|Z198:NO.2, i:nr 04/21/2023<ENTRY|
1327938|2|1|CIRCNOTE|ENTRY>|aCopy 1 bound with no. 13.|c1327936 (parent record's ckey).<ENTRY|
```
Might need to instead use the pipe2tsv_json script and then cat the files foreach note type into one file.

**Comment by shelleydoljack** [comment]
Ok, I added code to get rid of the extra columns. So now it should just work. I generated some files in the bibs catdumps dir based off of just the file of internet and bwchild we have in the bibworkdir.

**Comment by shelleydoljack** [comment]
Need to output LIBRARY, HOMELOCATION, CURRENTLOCATION, ITEM_TYPE, ITEM_CAT1.

**Comment by shelleydoljack** [comment]
Added the BASECALNUM records to the holdingsnote tsv and additional columns. @ahafele here is a sample BASECALNUM record that has a library (SUL) that is different from the library of the "real" items on that record, ckey 121556. But here is one where the library is the same, ckey 141943. I also generated new files. Here is the file of all the item xinfo notes for items with BASECALNUM in home or current location: [BASECALNUM item xinfo notes](https://docs.google.com/spreadsheets/d/1EuleXfeZJJLhIrFKnTi0FfXsHMGdAw-AQNgF9320R9A/edit?usp=sharing)

**Comment by shelleydoljack** [comment]
Also, the file with all the notes that will be holdings note is in `/s/SUL/Dataload/folio_symphony_extract/Bibs/Bibs_workdir/holdings_xinfo_3`.

**Comment by ahafele** [comment]
Went back and reviewed the decision making around basecalnum notes and can confirm we need to migrate the ext. info notes. There are some that aren't needed, but unless we want to parse those out we need to take all. @jermnelson something we didn't explicitly say yesterday so calling out here - all of the item extended info notes that are moving to a holdings record need to be on the same holdings record. So if we have 3 item ext. info notes for one ckey but we aren't creating the item then all three need to be added to the same holdings record.

**Comment by shelleydoljack** [comment]
This is done. Notes for ckey 1327938 in folio-prod:
![Screen Shot 2023-08-02 at 12.39.36 PM.png](https://images.zenhubusercontent.com/62964511c137fa350131daff/5bc3366c-f09d-4040-b600-a09212bdcd68)
