### ISSUE TITLE
Dump Symphony Authority records - August 19

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#472]
@dlrueda creating placeholder ticket for the auth dump info. Please adjust as needed. 

Per Vitus: 

- Output authority records with authdump -of instead of -om, because -om has a bug that turns |w to |a
- Create a new field, 924, as container of the authority key. We have already defined 921 for LC URI, 922 for VIAF URI, and 923 for ORCID URI.
- Output authority records with -ka924

**Comment by dlrueda** [comment]
No need to “create a new field 924” because we will just be doing this during the authdump, not adding a 924 to the authority record in Symphony.

**Comment by dlrueda** [comment]
Done.
Authority file (both marc and flat formats) in /s/SUL/Dataload/folio_symphony_extract/Authorities
