### ISSUE TITLE
Figure out why circ log isn’t populating on folio prod

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#473]
Look at mod-audit configuration (is this that writes to circulation log)?

**Comment by shelleydoljack** [comment]
Take a look at [Low-level design for circulation log](https://wiki.folio.org/pages/viewpage.action?pageId=36583179) and [High-level solution structure](https://wiki.folio.org/display/DD/High-level+solution+structure), they might offer some clues.
