### ISSUE TITLE
Determine what "hidden" records should be migrated

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#48]
We have many flavors of hidden records - should we migrate and how? 

Questions:
Does this depend on old order migration and who decides the cutoff for "old"? 
There is a bigger discussion about migrating "old" data in general. 
Vitus: withdrawn/etc should be available in some form. 
We can keep symphony databases. We could potentially preserve "old" data and access through LDP (rec from index data).

**Comment by ahafele** [comment]
Here is a list of hidden record varieties - https://docs.google.com/document/d/1CGyiJ2LFnSXluuVRmR4mHuKnkGiIgreQ4sCcBXsRXrY/edit# 
Suzette will add with Acq info and Vitus will review with Catcoord for decisions about migration.

**Comment by ahafele** [comment]
Checking back with Vitus on topic.

**Comment by ahafele** [comment]
Catcoord/Vitus have updated the spreadsheet. https://docs.google.com/spreadsheets/d/1woNjwILUgDelYbFueNHYLZttcToGl7-vcDqjyQcg9Io/edit?usp=sharing

**Comment by ahafele** [comment]
@dlrueda the spreadsheet was reviewed and input about whether to migrate or not was added. See above.

**Comment by ahafele** [comment]
Waiting on information in column D so we know how to export records. https://docs.google.com/spreadsheets/d/1woNjwILUgDelYbFueNHYLZttcToGl7-vcDqjyQcg9Io/edit?usp=sharing

**Comment by ahafele** [comment]
Also still need answers on circ related ones (lines 27-31) @Laszlo-J

**Comment by michelleif** [comment]
Status as of June 1, 2023:
WITHDRAWN items:
Each unit will decide whether it wants to discard, migrate, or retain outside of FOLIO, by June 9, [here](https://docs.google.com/spreadsheets/d/1LN2L89wasekg0eDwZdP47f8sRAlKN8DHVCWCeJa34fE/edit#gid=0).
Week of June 5th is a discussion with IndexData about using metadb to retain non-migrated data such as withdrawn items that aren't being migrated or discarded.

SHADOWED items:
After June 9, revisit whether we attempt to determine which should migrate and which shouldn't, or migrate all.
