### ISSUE TITLE
Load new locations to -stage, -dev, prod

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#482]
Please load new locations to folio-stage, folio-dev, and folio (prod).

Items have been created in folio-test. New tsv file named locations-new-Jul1.tsv in
[FOLIO Ops -> Migration files -> tsv -> tenant ](https://drive.google.com/drive/u/1/folders/1EyaO2EInNKHFq8Kx0q-KbYPGGqAnGSOs)

These locations are also in the main locations.tsv file, so the the locations-new-Jul1.tsv file can be removed after loads are complete.

**Comment by shelleydoljack** [comment]
Had to update the tsv to downcase FALSE/TRUE -> false/true. Loaded to the folio envs.
