### ISSUE TITLE
Load new material type file to -stage, -dev, prod

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#483]
Load new material type file material-types-new-Jul1.tsv from
[FOLIO Ops -> Migration files -> tsv -> Inventory](https://drive.google.com/drive/u/1/folders/1Nn-PNgniSUH3b_Hi6f2NMNLCXYCWU7Um) 

Then delete material-types-new-Jul1.tsv file

**Comment by shelleydoljack** [comment]
Done.
