### ISSUE TITLE
Update order holding codes in Symphony one more time

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#484]
Some time in August before cutover. @trapido  will provide a new report and process is outlined here #408.

**Comment by ahafele** [comment]
@trapido Hi Irina, could you provide the updated report so Darsi can run this one more time? Thanks!

**Comment by trapido** [comment]
Thanks so much for the reminder, @ahafele (and for fixing the codes, @dlrueda)!
I am attaching the new list.
[HoldingCodesCleaup.xlsx](https://github.com/sul-dlss/FOLIO-Project-Stanford/files/12297018/HoldingCodesCleaup.xlsx)

**Comment by dlrueda** [comment]
Done on bodoni 8/10
