### ISSUE TITLE
Handle location modifications for ABLE printing

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#487]
Preservation needs to print a shortened version of the home location at the end of an item’s call number. Uni2bind had a mapping table with all our home locations and the shortened version for printing. 

Example
![Picture1.jpg](https://images.zenhubusercontent.com/6259789bd12079728cab41a1/346e984a-0013-4ccd-ade5-83a1acc84221)

Per Tod Olson from Chicago: 
`And yes, we do some modifications of locations for label printing. I believe it is just handled in the configuration of the Z39.50 server for our able database/endpoint. You can ask Index Data for our Z39.50 configuration. And if you'd like to see our requirements for ABLE, I can share a Google Doc with you, or send you a PDF.`

Their requirements doc can be seen [here](https://drive.google.com/file/d/1NcAbOAljaw5LVUQe5bpQugG35ijGB5iZ/view?usp=drive_link).

**Comment by jgreben** [comment]
@ahafele We are currently using pretty much the same zserver config that UChicago uses (at least what they have published in the repo). Is this issue about doing something more/different than UChicago to get some additional location info out of folio as part of the z3950 response?

**Comment by jgreben** [comment]
Currently the Chicago config (and ours) provides the output for `callNumber` in:
```
"postProcessing": {
    "opac": {
      "holding": {
        "callNumber": {
         ...
```
And the zserver responds with these holdings fields (one of which is callNumber):
```
Data holdings 0
...
nucCode: Stanford University
localLocation: SAL3 (off-campus storage)
shelvingLocation: SAL3 Shelved Elsewhere
callNumber: A19690201
```

So do we want to try `localLocation` or `shelvingLocation`?

**Comment by ahafele** [comment]
We need to be able to use only part of the string returned for location, e.g. SAL3 (off-campus storage) and translate it to SAL3. I assumed this meant some kind of mapping file, but I could be wrong about how Chicago has implemented it. HF Group rep (ABLE) has confirmed that this is not done on the ABLE side.
Tod said we could ask Index Data for their configuration - not sure why it would be different than what is in the repo, but should we ask? 

From Chicago's ABLE requirement doc:
We use only the last part of OLE’s three-part location:
e.g. UC/JRL/Gen —> Gen
In FOLIO:
JRL-Gen —> Gen
Note: Some locations require modification:
EckX —> Eck
SSAdX —> SSAd
JRLASR —> Gen
XClosedCJK —> CJK
XClosedGen —> Gen

**Comment by jgreben** [comment]
I don't see anything in their config about those specific locations and the substitutions they say they are doing. It would help if we could get the most current configs around this from IndexData.

**Comment by jgreben** [comment]
I got the UChicago "Real" config from Wayne and I think I got a version now for us that will work.

![Screenshot 2023-08-01 at 13 09 55](https://github.com/sul-dlss/FOLIO-Project-Stanford/assets/3093850/09309974-b23c-4e5c-8500-355605461762)

**Comment by ahafele** [comment]
Awesome, thanks so much @jgreben ! (this will probably resolve a diacritic issue they were seeing also) 
I'll have Preservation test this.

**Comment by jgreben** [comment]
Do you know if the backslashes in the ABLE output represent line breaks on the spine like in your photo? If so, I think there needs to be one after the "PN" in my screenshot.

**Comment by ahafele** [comment]
Hannah from preservation reports that imprints are looking good! (and the other diacritic related issue is resolved) woot! (Not sure about \ but I think they can play around with that within ABLE)
