### ISSUE TITLE
Clean up |Z in call numbers for Spec and University Archives

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#490]
A pre-migration task to try and cleanup some of Spec and UA's item records so that they include a correctly formatted |Z and therefore holdings are properly created in FOLIO. See process done for Hoover for reference. 

Problems
1. Space after |Z and Box (e.g. [Fuller](https://folio-stage.stanford.edu/inventory/view/4c77cd83-bf6b-518e-803c-cb0ec7d2f455?query=a4332640&sort=title)) - is this fixed in #470? 
2. No |Z 
Per Franz:
```
MOST records from at least 2007-2022 will not have |Zs at all. The most common pattern would be similar, i.e. "Mxxx BOX x" with Mxxx as the call number, but we have also have smaller numbers of MSS PHOTO, MSS PRINTS, JL and other types of call numbers, some of which do have spaces in them. Another problem might be the range of container names used besides "Box," as well as prefixes for Accession and/or Series numbers which have been used to disambiguate. 
However if you are able to just replace the first space after the call number with a |Z none of this should be an issue!
I might also add that University Archives (our sister division) may not have used |Z either, and all of the above applies to them as well, although most of their call numbers begin with "SC" followed by four numbers.
```

**Comment by dlrueda** [comment]
Analysis happening in /s/SUL/OneTime/Batch-update-callnums/Spec-no-analytic (although not super officially organized and readable, sorry).

Spec call numbers often are in form
M####
and |Z has been added for those, right after the M####.  20,601 callnumbers updated.

**Comment by dlrueda** [comment]
For MSS type callnums, those that have a |Z, the |Z come after MSS PRINTS #### etc:

MSS PRINTS 0434|Z13TH IN BOX
MSS PHOTO 217|ZBOX 5
MSS MEDIA 0004|ZVIDEO BOX 11
MSS CODEX 1400 F|ZVOL 2

CODEX: There are about 20 to do (most CODEX callnums without |z don’t have any |z info in them). 
DIGITAL: Only 1 record to do
I suggest do manually by Spec staff.  Email sent to Alissa.

I’ll think about a regex that can put the |Z in the right place for MSS PRINTS/PHOTO/MEDIA

**Comment by dlrueda** [comment]
JL### follows same as M####.  Substitute first space of callnumber with |Z
Done 7/23, 888 callnums updated

**Comment by dlrueda** [comment]
MSS callnums updated 7/24.
MSS-PRINTS: 581 updates
MSS-PHOTO: 355
MSS-MEDIA: 49

See /s/SUL/OneTime/Batch-update-callnums/Spec-no-analytic/steps.20230716.SPEC-UA
for all steps.

Not sure if we’ll want to redo full selection and update before migration, or assume there won’t be enough added in the last month to make it worth the effort.

**Comment by dlrueda** [comment]
7/24/23: Updated 511 Univ Archives SC#### callnums
