### ISSUE TITLE
withdrawn items

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#491]
withdrawn items need to: 

- map the Symphony home location to the FOLIO permanent location
- setting the item status to withdrawn
- checking the item’s Suppress from discovery
- ~add an item Admin note of `Withdrawn in Symphony~
- @jermnelson MD has changed this request to be an item note of type = Withdrawn for either home or current location of WITHDRAWN

@dlrueda Anything to add to this ticket? I presume we are aiming to do this before prod load?

**Comment by dlrueda** [comment]
Ticket created sul-dlss/folio_migration#99
Includes
- home location mapping to FOLIO permanent location
- setting item status to withdrawn
- suppressing item with home or current location withdrawn

**Comment by dlrueda** [comment]
Assigned Jeremy to folio_migration#99
Assigned Jeremy to THIS ticket to add the item Admin note of `Withdrawn in Symphony` for either home or current location of WITHDRAWN

**Comment by ahafele** [comment]
MD has changed this request to be an item note of type = Withdrawn
I've made this note type on test, stage, dev and added to folio ops tsv

**Comment by ahafele** [comment]
@jermnelson it looks like we still need to do the note portion of this ticket. Add item note of type Withdrawn and text - "Withdrawn in Symphony"
Item note type needs to be added to prod from folio ops tsv (or manually if uuid doesn't matter)
