### ISSUE TITLE
New patron groups - add new and/or rename existing groups

### ISSUE THREAD

**Issue by Laszlo-J** [sul-dlss/FOLIO-Project-Stanford#492]
SUL Access Services needs new user groups.  Some of these replace old groups. Some are new ones. I've updated the spreadsheet for the group changes, associated patron type mapping and custom fields:
[https://docs.google.com/spreadsheets/d/10n77Zxgp3GCgwB9pPR80CZzNs6ERDzQkyCuolUQEoG0/edit#gid=221919063](url)

Summary of changes:

1. **sul-fee**: _rename_ to sul-purchased
2. **courtesy**: _also_ map ASSO-BDRCT; add new custom fields for BorrowDirect
3. **sul-guest**: split into two _new_ groups -
- program-short-term (see custom fields in spreadsheet)
- sul-contractprograms (map MXAS-25LIMIT; see custom fields in spreadsheet)
4. **sul-exception**: _rename_ to sul-guest
5. **faculty**: 
- add mapping: FAC-RSP, FAC-RLCPT, FAC-RLCPB
- add custom fields for RSP & RLCP
6. **graduate**:
- add more mapping = DOC-RSP, DOC-RLCPT, DOC-RLCPB
- add custom fields for RSP & RLCP

**Comment by dlrueda** [comment]
@Laszlo-J this ticket is named “New user groups” but from the description do you mean “New patron groups”???

**Comment by Laszlo-J** [comment]
Yes, sorry... I fixed it.
