### ISSUE TITLE
Aeon integration script (and app user?) 

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#502]
In Integrations->Aeon folder of FOLIO Implementation drive 
https://drive.google.com/drive/u/0/folders/1BXc5ahTcnKZGwRtzNcBlQ2M1tJF6Pupx

Katie of Atlas will talk to their devs on Wednesday July 19.
There are a few options:
- we host this script somewhere, and they can call it within the existing Addon (probably no Atlas dev work)
- Atlas hosts the script and calls it, requires Atlas dev work
- Atlas uses the APIs in this script and updates their Addon to call the APIs and parse the results. Requires Atlas dev work, but matches what they do when looking up stuff in ArchiveSpace

Katie will get us the IPs that need to access our okapi 

Do we need an app user created for this?
Right now is using app_readonly and has pw in the script!

**Comment by dlrueda** [comment]
Aeon is requesting an app user and token for this.  So probably next step is to make the app user, and then explain to them how to do the token part?

**Comment by shelleydoljack** [comment]
app_aeon user created with the read_inventory pset on prod, stage, and test. The app_users.tsv and app_users_psets.tsv have been updated in folio ops migration files. i also added a google doc with the login info https://docs.google.com/document/d/17bWtWmCp3gPPHlMLrt1dxkl6D6p-v9062fg4uRnFzHg/edit?usp=sharing

**Comment by shelleydoljack** [comment]
Testing and deploying the add-on is now in their court. The work for this ticket is done.
