### ISSUE TITLE
Dup callnums and libs in Symphony, how do they migrate

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#503]
I want to look at what our migration code does to this items.

All of them had their call numbers updated as part of overlaying their bib record with copy found by Backstage (these are the SAL UNCAT items).  The result was sometimes 2+ items on the same ckey, different call number structures, same exact call number for same library.  (This isn’t supposed to be possible in Symphony but since these were updated with an API command, the update happened without the unique call number check happening.)

Will these migrate ok to FOLIO?  Check out the records after the next test load.

I will be very interested to see if our migration to FOLIO results in one holdings record with both items underneath. Right now they are separate call number structures, but they have the same call number and volume.  (I thought Symphony would reject that as a dup but I suppose catalogdump being an api command and not coming from WFs, that check wasn’t done.) Both are volume 1 though.  This might get screwed up!
36105110777500  |SAL|UNCAT|UNCAT|PA3405 .S96 NO.46|LC|
36105110777518  |SAL|UNCAT|UNCAT|PA3405 .S96 NO.46|LC|

Same with these 3 that are on same bib record and now are identical
36105110757882  |SAL|UNCAT|UNCAT|E78 .C15 P35 NO.13, ETC|LC|
36105110757890  |SAL|UNCAT|UNCAT|E78 .C15 P35 NO.13, ETC|LC|
36105110757908  |SAL|UNCAT|UNCAT|E78 .C15 P35 NO.13, ETC|LC|

And these
36105111469974  |SAL|UNCAT|UNCAT|B751 .I6 1960|LC|
36105111469966  |SAL|UNCAT|UNCAT|B751 .I6 1960|LC|
36105111469958  |SAL|UNCAT|UNCAT|B751 .I6 1960|LC|

36105110755316  |SAL|UNCAT|UNCAT|KKW8541 .B58 1838X|LC|
36105110755324  |SAL|UNCAT|UNCAT|KKW8541 .B58 1838X|LC|

36105111477928  |SAL|UNCAT|UNCAT|KHA484 .A311888 Z36 1888|LC|
36105111477936  |SAL|UNCAT|UNCAT|KHA484 .A311888 Z36 1888|LC|

36105110778730  |SAL|UNCAT|UNCAT|PT2461 .S315 S8 1868|LC|
36105110778748  |SAL|UNCAT|UNCAT|PT2461 .S315 S8 1868|LC|

36105111479825  |SAL|UNCAT|UNCAT|HC276.2 .A12 .F7 1974|LC|
36105111488370  |SAL|UNCAT|UNCAT|HC276.2 .A12 .F7 1974|LC|

36105111475633  |SAL|UNCAT|UNCAT|HT169 .A82 C36 1977|LC|
36105111475641  |SAL|UNCAT|UNCAT|HT169 .A82 C36 1977|LC|
36105111475658  |SAL|UNCAT|UNCAT|HT169 .A82 C36 1977|LC|

36105110758997  |SAL|UNCAT|UNCAT|HD5737 .A6 P76|LC|
36105110759003  |SAL|UNCAT|UNCAT|HD5737 .A6 P76|LC|

36105111470113  |SAL|UNCAT|UNCAT|TX349 .D3|LC|
36105111470121  |SAL|UNCAT|UNCAT|TX349 .D3|LC|

36105111507435  |SAL|UNCAT|UNCAT|DH801 .H2.S6 NO. 16|LC|
36105111507443  |SAL|UNCAT|UNCAT|DH801 .H2.S6 NO. 16|LC|

36105111466624  |SAL|UNCAT|UNCAT|P106 .G57 1973A|LC|
36105111466632  |SAL|UNCAT|UNCAT|P106 .G57 1973A|LC|

These 3 are on a record that has 3 other items, SAL3, v.1,v.2,v.3. I imagine these are also v.1-3, just didn’t have that in the call number before.
36105110758419  |SAL|UNCAT|UNCAT|LF3195 .W45 M38 1950|LC|
36105110758427  |SAL|UNCAT|UNCAT|LF3195 .W45 M38 1950|LC|
36105110758435  |SAL|UNCAT|UNCAT|LF3195 .W45 M38 1950|LC|

36105111505892  |SAL|UNCAT|UNCAT|KBD200 .R38 1926|LC|
36105111505900  |SAL|UNCAT|UNCAT|KBD200 .R38 1926|LC|

36105111472994  |SAL|UNCAT|UNCAT|D387 .L46 1848|LC|
36105111473000  |SAL|UNCAT|UNCAT|D387 .L46 1848|LC|
36105111473018  |SAL|UNCAT|UNCAT|D387 .L46 1848|LC|

36105021401489  |SAL|UNCAT|UNCAT|DS517.1 .S4 1912|LC|
36105233480685  |SAL|UNCAT|UNCAT|DS517.1 .S4 1912|LC|
36105233480693  |SAL|UNCAT|UNCAT|DS517.1 .S4 1912|LC|

Only 1 of these items existed when we sent this record to BS; 2 of them were created on 7/10.  The bib says they are v.1-3, but there was no volume as part of the call number for the one item that existed beforehand.
36105021401489  |SAL|UNCAT|UNCAT|DS517.1 .S4 1912|LC|
36105233480685  |SAL|UNCAT|UNCAT|DS517.1 .S4 1912|LC|
36105233480693  |SAL|UNCAT|UNCAT|DS517.1 .S4 1912|LC|

Not only are these duplicate call numbers now, but they are on two different titles. As far as my eye can tell, I think these are a dup titles/records.
Ckeys 182029 ocm04797374, 176525 ocm04797374
36105111465709  |SAL|UNCAT|UNCAT|LB1568 .G3 D85|LC|
36105111464892  |SAL|UNCAT|UNCAT|LB1568 .G3 D85|LC|

36105111492166  |SAL|UNCAT|UNCAT|DD901 .B77 M61|LC|
36105111492174  |SAL|UNCAT|UNCAT|DD901 .B77 M61|LC|

36105111496480  |SAL|UNCAT|UNCAT|JN3971 .A67 L27|LC|
36105111496498  |SAL|UNCAT|UNCAT|JN3971 .A67 L27|LC|

36105111493818  |SAL|UNCAT|UNCAT|HJ1138 .P96|LC|
36105111493826  |SAL|UNCAT|UNCAT|HJ1138 .P96|LC|

36105111496324  |SAL|UNCAT|UNCAT|DD259.2 .S68|LC|
36105111496332  |SAL|UNCAT|UNCAT|DD259.2 .S68|LC|

36105111464603  |SAL|UNCAT|UNCAT|DR48 .H48|LC|
36105111464611  |SAL|UNCAT|UNCAT|DR48 .H48|LC|

These below had an UNCAT and an item with a LC callnum before sent to BS.  Now they are dup call numbers. Oh, it doesn’t matter because the libraries are different.  There are more than these 3 pairs, but I stopped collecting after 3 when I realized it shouldn’t matter.
177757|SAL|36105111496001  |UNCAT|UNCAT|STKS-MONO|70 34387|ALPHANUM|
177757|SAL3|36105210202813  |STACKS|STACKS|STKS-MONO|Z6605 .G7 B64 1961|LC|

169588|SAL|001AAU1243      |UNCAT|UNCAT|STKS-MONO|70 37228|ALPHANUM|
169588|SAL3|36105029308405  |STACKS|STACKS|STKS-MONO|PQ2631 .I638 .R4 1971|LC|

183271|SAL|001AAW1173      |UNCAT|UNCAT|STKS-MONO|70 25986|ALPHANUM|
183271|SAL3|36105028670581  |STACKS|STACKS|STKS-MONO|DB80.8 .S73 H57 1861|LC|

**Comment by shelleydoljack** [comment]
```
36105110777500 |SAL|UNCAT|UNCAT|PA3405 .S96 NO.46|LC|
36105110777518 |SAL|UNCAT|UNCAT|PA3405 .S96 NO.46|LC|
```
these got on the same holdings record in folio![Screen Shot 2023-08-07 at 3.40.56 PM.png](https://images.zenhubusercontent.com/62964511c137fa350131daff/d52a3fec-7cea-48d3-9026-0e43173eecaa)

**Comment by dlrueda** [comment]
OK, good, thank you for checking this. I think it’s ok for this to have happened.  These materials will be heading to SAL3 and copy just doesn’t matter. (I think it’s interesting that two items can both be copy 1, but w/e)
