### ISSUE TITLE
Edit Lane patron groups: new one for residents

### ISSUE THREAD

**Issue by Laszlo-J** [sul-dlss/FOLIO-Project-Stanford#506]

**Comment by Laszlo-J** [comment]
Added new patron group (lane-resident), and break out from existing group (lane-hospital staff.)
[https://docs.google.com/spreadsheets/d/10n77Zxgp3GCgwB9pPR80CZzNs6ERDzQkyCuolUQEoG0/edit#gid=221919063&range=10:10](url)

**Comment by dlrueda** [comment]
Rename affiliate-sponsored-eresources to lane-resident in all folio instances.  Update patron-group.tsv FOLIO Ops file

**Comment by Laszlo-J** [comment]
I already added the new group in all instances; should I just delete affiliate-sponsored-eresources? Or must we rename _that_ group because of an UUID issue? (Don't know...)

**Comment by Laszlo-J** [comment]
Okay, I deleted the new lane-resident group I made in all instances yesterday, renamed the affiliate group instead, and updated/uploaded the new tsv file. (I also renamed the lane-hospital staff description to remove residents.)
