### ISSUE TITLE
Load new locations to folio prod

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#512]
1.
New locations-new-Jul28.tsv file to load to folio prod, folio-stage, and folio-dev.

“TRUE” is already set to be text only, and changed to “true" (so hopefully the file will be fine as is).

2. 
locations-new-Jul5.tsv needs to be loaded to folio-stage and folio-dev.  (folio prod already done)

I uploaded a fresh copy of this file with true as text only

Please delete both of these locations-new tsv files from Folio Ops drive once they’ve been loaded to the various FOLIOs.

**Comment by shelleydoljack** [comment]
I get the error, "SULTS" not found, when trying to load to folio-dev. Is there an updated library tsv and service points tsv to load too?

**Comment by shelleydoljack** [comment]
Updated libraryCode SULTS to SUL in locations-new-Jul28.tsv and loaded to dev, stage, prod.

**Comment by shelleydoljack** [comment]
locations-new-Jul5.tsv loaded to dev and stage. Files deleted from google drive.

**Comment by dlrueda** [comment]
So I think the service points we needed hadn’t been loaded to -dev or something.  or maybe to prod too. I’ll sort it out
