### ISSUE TITLE
Ideas for comparing counts on migration

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#516]
Brainstorm below. Needs refinement. 

Counts of **marc records** that we export from symphony to compare with instances and SRS
- Option: catdump reports and grep for how many printed. 
- Should also compare how many were printed vs. how many ckeys. WC of each ckey files and then compare with what was printed. 
- Need to do this check before Lane does there’s? 

**Items**: WC item files and compare with items created in FOLIO
- How to account for stuff that doesn’t make it into files above? 
- Getting all items per library with some home loc/cur loc exclusions. All locations except edi instructor and lockss
- Exclude some withdrawn and some shadow home locations
Libraries. Exclude: Meyer, Physics, Lathrop, Bio, Chem, Gov docs, Math CS, Hoov Desk, Lane-med, RWC, Spec Desk
- A report of this would just be recreating what is in the code. But could do some kind of table extract to double-check.

**Comment by dlrueda** [comment]
count of Bibs_ckeys_to_process/ckeys*
10,063,623

count of BIbs_ckeys_to_process/items*
11,044,131

**Comment by dlrueda** [comment]
289 Bibs_catdumps/ckeys\*9.tsv files (item tsv files). Each has a header line.
wc of Bibs_catdumps/ckeys\*9.tsv (item tsv files)
11,044,420

11,044,420 - 289 = 11,044,131

Hooray it matches the number of items in Bibs_ckeys_to_process/items* files.
We supplied the right number of items in the items.tsv files on extract

**Comment by dlrueda** [comment]
Number of MARC records printed as stated in Bibs_rptdir catdump.rpt files
10,063,623

Hooray same as count of ckeys in Bibs_ckeys_to_process/ckeys* files

In order to see if the Bibs_catdumps .mrc files had the right number of bibs per file, I’d need to flatskip the .mrc files to .flat and do a wc of “DOCUMENT BOUNDARY” lines.  But I think we can trust the catdump.rpt files.

**Comment by dlrueda** [comment]
Compare these marc and item counts with number of instances and items that we create in FOLIO.

**Comment by dlrueda** [comment]
Count of Bibs_ckeys_to_process/bwchild_items*
216,394

282 Bibs_catdumps bwchild.tsv files, each with a header line
wc of Bibs_catdump bwchild.tsv files
216,676

216,676 - 282 = 216,394

Hooray, it matches the number of items in Bibs_ckeys_to_process/bwchild_items* files.
We supplied the right number of bwchild items in the bwchild.tsv files on extract

**Comment by shelleydoljack** [comment]
> Inventory load completed! At 2023-08-21 22:46:39.112385 (UTC)
Inventory (292 DAGs completed)
Instances: 10,069,342
Holdings: 12,052,254
Items: 11,042,711
SRS (266 DAGs completed):
BIBS: 9,274,796
Holdings: 692,625

https://stanfordlib.slack.com/archives/C02CWRMBMT8/p1692658965616979

maybe there are more instances b/c the on-order marc records are not included in the Bibs_rptdir catdump.rpt files

**Comment by dlrueda** [comment]
Yes, total number of instances expected is
count of /Bibs_ckeys_to_process ckey* files: 10,063,623
\+ number SUL on-order bib records: 4,976
\+ number LAW on-order bib record: 911
= 10,069,510

**Comment by dlrueda** [comment]
Missing 168 instance records from expected amount.  Let’s see if we add any through the remediation step.

**Comment by shelleydoljack** [comment]
There are 216,394 lines in the bwchild tsv files, but to compare the count of boundWithParts relationships made in folio, we should get the bwchild tsv lines where barcode field is not empty string (which indicates we don't know the parent barcode so not bw-parts relationship to be made in folio).

I did:
`awk -F"|" '{if ($4!="") print $0}' bwchild_items_all_updated > ~/FolioCutoverLoad/bw-parts-relationships`
and
`awk -F"|" '{if ($4=="") print $0}' bwchild_items_all_updated > ~/FolioCutoverLoad/no-bw-parts-relationships`

total boundwith parts relationships that should be made in folio: 199,034
total boundwith child records that should just be instance and holding and no bw-part relationship: 17,360

total boundwith relationships in folio `/inventory-storage/bound-with-parts?limit=0`: 198,985

we're missing 49

**Comment by shelleydoljack** [comment]
thinking about this more, the bwchild_items_all and bwchild_items_all_updated files should be the same number of lines and that should be the number of bwchild holdings records in folio (whether or not they have a relationship in bound-with-parts).
bwchild_items_all: 221,381 lines
bwchild_items_all_updated: 216,394
so 4,987 holdings records are missing for bwchild records.

**Comment by shelleydoljack** [comment]
Missing bwchild holdings loaded (see https://github.com/sul-dlss/libsys-airflow/issues/751). 1 possibly still missing (tsv had 4,986 data rows).
