### ISSUE TITLE
need new location for EAL-CURRENTPER

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/FOLIO-Project-Stanford#519]
Once created in folio-test, need to add it to https://docs.google.com/spreadsheets/d/19nXAJgwUjXekwEpf4iOIyA1eWcaaKIo6wSfQg8Guqo4/edit?usp=sharing for EAL-CURR-H (and anything else there should get it? EAL-SER-H?) and to https://github.com/sul-dlss/folio_migration (so the marc holding record get the correct location too).

**Comment by dlrueda** [comment]
EAL-CURRENTPER created in folio-test
and added it to the holding code mapping https://docs.google.com/spreadsheets/d/19nXAJgwUjXekwEpf4iOIyA1eWcaaKIo6wSfQg8Guqo4/edit#gid=69121295

Ticket being created for locations.tsv and locations-mhld.tsv mappings

Not sure about the other holding codes for EAL that aren’t mapped to anything legit.  I’m asking Irina and Suzette (again)

**Comment by dlrueda** [comment]
Mapping done
