### ISSUE TITLE
Give api calls to identify boundwith children to Caiasoft

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#521]
On accession, Caiasoft will check if the item is a boundwith parent, and update the location on the bw child holdings to SAL3-SEE-OTHER (or SPEC-SAL3-SEE-OTHER, HILA-SAL3-SEE-OTHER, etc)

Supply Laura of Caiasoft will correct call to identify the bw child holdings for the item being accessioned.

laura@caiasoft.com
or slack channel #caiasoft-stanford-implementation

**Comment by shelleydoljack** [comment]
For finding boundwith children records, the data from `GET /{okapi_url}/inventory/items/{item id}` will include a key-value of `"isBoundWith": true` and an array of `"boundWithTitles"` that includes the instance UUID and holdings record UUID of the boundwith children. This is probably the best way to get a list of holdings records where the locations will need updating. Also, I believe this data appears in the item records only after indexing. If the holdings are not backed by MARC SRS (which _should_ be exclusively the case for SUL and Law), then it should be really easy to do a `PUT /inventory/holdings/{holding id}`.

Another way to see what the boundwith children holdings records are, is to do a `GET /inventory-storage/bound-with-parts?query=itemId==7d368682-7ec1-5a96-bef0-f2468871b046&limit=100` (may need to increase limit, depending???) and iterate through the data for all the `holdingsRecordId` fields.
