### ISSUE TITLE
Suppress these records at instance level

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#533]
We missed a title-level suppress flag in the item tsv field for types of records that didn’t get an item tsv entry:
BASECALNUM, INTERNET, BW-CHILD

Need to suppress these at the instance level (422 total).  Some might already be suppressed correctly based on other items on the record that DID make it into the item tsv files.

10000541
10000692
10001628
10002895
10004348
10004414
10006361
10006381
10008584
10011785
10012007
10012152
10014732
10015551
10038936
10041162
10041678
10042641
10093930
10094970
10094998
10108073
10144295
10152220
10160861
10178112
10179666
10179681
10180438
10182643
10184295
10221834
10247855
10266854
10268478
10268488
10280977
10318058
10354281
10385529
10401098
10408913
1044596
10468448
10576860
10580557
10590791
10594681
10629905
10635831
10635834
10636288
10642372
10642376
10642379
10642448
10642693
10642871
10643323
10643325
10643853
10643856
10643858
10643860
10645330
10645332
10646890
10646930
10648228
10659525
10659618
10659620
10659623
10659625
10660041
10681833
10704007
10704037
10720411
10723211
10727847
10727859
10736701
10737685
10737693
10738648
10741685
10741705
10770682
11064144
11064174
11064180
11296326
11353626
11405922
11454014
11455278
11469812
11528284
11546587
11589022
11601133
11607317
11637164
11642520
11655495
11682085
11699068
11850292
11874532
12082323
12140188
12141934
12141936
12141938
12141940
12141941
12141944
12141946
12141947
12141949
12141951
12141955
12155860
12194957
12204079
12213703
12257618
12358525
12362769
12388199
1256548
12737670
12757669
12757804
1276915
12808160
12836755
13113478
13113485
13119030
13136768
13154361
13154364
13154365
13154366
13282337
13296764
13298971
13346972
13354934
13380615
13391635
13408836
13416457
13417290
13418291
13427457
13473505
135310
13567046
13570950
13582492
13583416
13615014
13615015
13631129
13631130
13681662
13681824
13688547
13704987
13709756
13716050
13726598
13743963
13743973
13803003
13834524
13870284
13886341
13887057
13902768
13971709
14019559
14024049
14050652
14071959
14174217
14181465
14189887
14243600
14305074
14359848
14450849
14461949
14467505
14474204
1457428
14638413
14642992
14724225
14731410
14774518
14783476
14801478
14802619
14804016
14807270
14807772
14807776
14815161
14816473
14869791
14880846
14880847
14880853
14880858
14880863
14880870
14880872
14880878
15125141
1937588
1937590
1937592
1937594
2888846
3035589
3266150
3266242
3266255
3266357
3266373
3266447
3266509
3266695
3271517
3272175
3274128
3275728
3276162
3279175
3305359
3361553
3760912
3763812
379998
3816033
3822730
3822754
399006
4338132
4376541
4392222
4404132
4404161
4404172
4404175
4404180
4404187
4441379
4465440
4512651
4532516
4539570
4557411
456190
4648882
4709640
4713684
491839
5170877
5175490
5325377
5326052
5356332
5402948
5446339
5463175
5480286
5628214
5678735
5682193
5685491
5686484
5690868
5691312
5703711
5706056
5726382
5740944
5741040
5741373
5753313
5753326
5754282
575455
5757400
5757786
5758371
5806697
5828958
5985744
5994903
6003697
6009126
6097162
6209032
6287444
6287625
6302254
6302463
6303115
6309117
6309379
6312872
6312910
6346369
6349719
6424176
6429978
6491923
6505346
6509060
6521130
6632224
6632327
6682855
6700674
6725896
6747344
6777474
6806017
6806856
6809011
6809943
6812510
6834957
6844881
6845541
6848344
6861857
6913899
6991457
6992180
7103412
7105879
7133130
7134026
7140843
7161736
7191220
7515630
7593456
7613883
7616182
7654028
7654471
7679318
7697284
7761651
7769917
7778476
78587
7902303
7955569
8015196
8015395
8100612
8122870
8220750
8481204
8502383
8529568
8531181
8532960
8534324
8534411
8537807
8574354
8574478
8576762
8578892
8610059
8627177
8627955
8689641
8689643
8689646
8726695
8772816
8784977
8789827
8800838
8838993
9052193
9054281
9099888
9147276
9200713
9220831
9320739
9344993
9345038
9504519
9504588
9523830
9533393
9539031
9547782
9589729
9619812
9620424
9646371
9652252
9714499
9750891
9761820
9804797
9915838
9984102

**Comment by jermnelson** [comment]
These 48 ckeys already had `discoverySuppress` set to True:

10001628
10014732
10152220
10160861
10178112
10179681
10180438
10221834
10247855
10268478
10354281
10385529
10401098
1044596
10576860
10590791
10659525
10727859
12388199
13282337
135310
13834524
13902768
14450849
14461949
1457428
3035589
3305359
3361553
379998
4532516
4539570
575455
5828958
6346369
6632224
7593456
7613883
7778476
8100612
8627177
8689641
8689643
8689646
9054281
9200713
9523830
9804797

These 8 ckeys are not in FOLIO so investigating why:
10038936
10041162
10041678
10042641
10094970
10094998
14731410
7515630

The remaining 366 Instances `discoverySuppress` has been set to True.

**Comment by dlrueda** [comment]
I think we removed BASECALNUM items from our complete list of items one step too soon.


```
# cat all item files together
cat $bibworkdir/*items > $bibworkdir/items_all_w_internet_basecalnum

# remove rows with BASECALNUM in homeloc and/or currloc
dolog "Start select BASECALNUM item rows"
awk -F"|" '{if ($6 == "BASECALNUM" || $7 == "BASECALNUM") print $0}' $bibworkdir/items_all_w_internet_basecalnum | sort -n > $bibworkdir/items_basecalnum
dolog "Finished selecting BASECALNUM item rows"

dolog "Start remove BASECALNUM so not sent to catdumps"
grep -v "|BASECALNUM|" $bibworkdir/items_all_w_internet_basecalnum > $bibworkdir/items_all_w_internet
dolog "Finished removing BASECALNUM rows"

# get single list of ckeys to do catdumps for
cut -f1 -d"|" $bibworkdir/items_all_w_internet | sort -n -u > $bibworkdir/ckeys_all.sorted
```


We should have gotten the single list of ckeys to do catdumps for first.  I’m not sure why I didn’t catch that when reviewing the changes put in for getting instance level stat codes etc for records we weren’t migrating items for

**Comment by dlrueda** [comment]
ok so we have who knows how many records that only had a BASECALNUM item.  Probably not too many.  Looking at the code now to try and figure that out.
