### ISSUE TITLE
Suppress MUS-TECHSHADOW records

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#535]
For this list, please suppress at item, holdings, AND instance level
1011382|36105042430442  |MUSIC|TECH-SERV|
11891927|36105225441497  |MUSIC|TECH-SERV|
12269927|36105229054213  |MUSIC|TECH-SERV|
1322084|36105042516810  |MUSIC|TECH-SERV|
14263931|36105229077115  |MUSIC|TECH-SERV|
14263931|36105229077115  |MUSIC|TECH-SERV|
1725805|36105042628680  |MUSIC|TECH-SERV|
2268742|36105004258492  |MUSIC|TECH-SERV|
3771905|36105020120288  |MUSIC|TECH-SERV|
4514861|36105110994717  |MUSIC|TECH-SERV|
4779977|36105025939450  |MUSIC|TECH-SERV|
4813018|36105025953147  |MUSIC|TECH-SERV|
5558756|36105113620657  |MUSIC|TECH-SERV|
5683822|36105119437767  |MUSIC|TECH-SERV|
6553640|36105127395312  |MUSIC|TECH-SERV|
6915438|36105122366284  |MUSIC|TECH-SERV|
721809|36105000390463  |MUSIC|TECH-SERV|
7594169|36105131952710  |MUSIC|TECH-SERV|
8882927|36105134166664  |MUSIC|TECH-SERV|

**Comment by dlrueda** [comment]
Please suppress the item and MUS-TECHSHADOW holdings for this list items
1245376|36105042476692  |MUSIC|TECH-SERV|
1270127|36105042509765  |MUSIC|TECH-SERV|
1424844|36105042535356  |MUSIC|TECH-SERV|
1460530|36105042551668  |MUSIC|TECH-SERV|
1573391|36105042589445  |MUSIC|TECH-SERV|
1660113|36105042611215  |MUSIC|TECH-SERV|
1669202|36105042612908  |MUSIC|TECH-SERV|
1671794|36105042613666  |MUSIC|TECH-SERV|
1691212|36105004299397  |MUSIC|TECH-SERV|
1691212|36105004312133  |MUSIC|TECH-SERV|
1691212|36105042618426  |MUSIC|TECH-SERV|
1707595|36105004312125  |MUSIC|TECH-SERV|
1707595|36105042622881  |MUSIC|TECH-SERV|
1707707|36105011407124  |MUSIC|TECH-SERV|
1707707|36105042622907  |MUSIC|TECH-SERV|
1717544|36105004258500  |MUSIC|TECH-SERV|
1724927|36105042628441  |MUSIC|TECH-SERV|
2816|36105002637127  |MUSIC|TECH-SERV|
2891262|36105008679537  |MUSIC|TECH-SERV|
3360200|36105019164602  |MUSIC|TECH-SERV|
3360200|36105019164610  |MUSIC|TECH-SERV|
3360200|36105019164628  |MUSIC|TECH-SERV|
3360200|36105019164636  |MUSIC|TECH-SERV|
3381328|36105011413239  |MUSIC|TECH-SERV|
3458159|36105021474478  |MUSIC|TECH-SERV|
4244669|36105028964158  |MUSIC|TECH-SERV|
4244669|36105028964166  |MUSIC|TECH-SERV|
660335|36105042309315  |MUSIC|TECH-SERV|
746300|36105042334552  |MUSIC|TECH-SERV|
959631|36105122627164  |MUSIC|TECH-SERV|
9714631|36105224190244  |MUSIC|TECH-SERV|

**Comment by jermnelson** [comment]
@dlrueda first set of ckeys have `discoverySuppress` set to True for Instances/Holdings/Items. 

The second set of ckeys have `discoverySuppress` set to True for Holdings/Items for Holdings with a `permanentLocationId` of *Music Tech Services Shadow* location.

**Comment by ahafele** [comment]
I think some holdings may have gotten inadvertently suppressed through this process or maybe instance level suppression didn't work? The example I have is from the first list of ckeys - the Electronic Holdings on the record got suppressed but not the Instance level. There are also SAL3 holdings on the record https://folio.stanford.edu/inventory/view/d567c076-8bb5-5a64-b0c3-020b9255525f?filters=effectiveLocation.e99ac505-53ee-4db8-bf82-d9efcae6f5c9%2CholdingsPermanentLocation.b0a1a8c3-cc9a-487c-a2ed-308fc3a49a91&segment=holdings&sort=title

**Comment by jermnelson** [comment]
Hmm, looking at the jupyter notebook had the discoverySuppress set to True on 8/30 for this Instance/Holdings/Item:

```
Instance d567c076-8bb5-5a64-b0c3-020b9255525f discoverySuppress True
   Holding c602e437-b13d-5657-8d2d-106981f1faea discoverySuppress True
     Item fa8077d2-4bee-5b50-aab4-8cb4b5a85756 discoverySuppress True
   Holding 65ce8bf0-df6c-5d8f-85a0-061a4b1c3921 discoverySuppress True
```
   
Now seeing that discoverySuppress is now set to False along with a new holdings record (1c5cfd18-724c-48f5-bdea-cf5b6b858b32) and item record (d0b08e5e-0642-4306-a4d6-46a0ce1e9c6d) added to this instance with the version now at 3:

```
Instance d567c076-8bb5-5a64-b0c3-020b9255525f discoverySuppress False
 Holding c602e437-b13d-5657-8d2d-106981f1faea discoverySuppress True
  Item fa8077d2-4bee-5b50-aab4-8cb4b5a85756 discoverySuppress True
 Holding 65ce8bf0-df6c-5d8f-85a0-061a4b1c3921 discoverySuppress True
 Holding 1c5cfd18-724c-48f5-bdea-cf5b6b858b32 discoverySuppress None
  Item d0b08e5e-0642-4306-a4d6-46a0ce1e9c6d discoverySuppress None
```

I think this Instance was manually edited and the discoverySuppress was set back to False.

**Comment by ahafele** [comment]
Ah ok, I think that is all good. I guess my remaining question is - should the electronic holdings have been suppressed?

**Comment by jgreben** [comment]
Migration done.
