### ISSUE TITLE
Circ log app in folio-test missing Actions button

### ISSUE THREAD

**Issue by Laszlo-J** [sul-dlss/FOLIO-Project-Stanford#537]
It was there yesterday. Today the button's missing...

Cleared cache, logged in/out, etc. Tried in Chrome and FF.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazJTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--728da36c31f6eed36a0fb59628e468b0c25bf953/image.png)

**Comment by jgreben** [comment]
Okapi was not clustering correctly due to work on securing the supertenant. This should be fixed now.
