### ISSUE TITLE
Unsuppress these items

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#542]
Some of them are not suppressed, hopefully a call to  “unsuppress” will not be harmful if the item is already unsurpassed?
All items on instance HRID a14423313

36105214732229
36105234430689
36105233679237
36105233679229
36105233679211
36105233679203
36105233679195
36105233679187
36105233679179
36105233679161
36105233679393
36105214731478
36105214732690
36105214732542
36105214731502
36105214731510
36105214731577
36105214731528
36105214731536
36105214731544
36105214731551
36105214732740
36105214732682
36105214731676
36105214731668
36105214732674
36105214731643
36105214732666
36105214732658
36105214732633
36105214731593
36105214731619
36105214731601
36105214731692
36105214731833
36105214731700
36105214731718
36105214731726
36105214731734
36105214731742
36105214731759
36105214731825
36105214731817
36105222621307
36105214731809
36105214731791
36105214731775
36105214731783
36105214731916
36105214731841
36105214731908
36105214731924
36105214731858
36105214731866
36105214731874
36105214731890
36105214731882
36105214731999
36105214731981
36105214731932
36105214731973
36105214731965
36105214731957
36105214731940
36105214732070
36105214732062
36105214732054
36105214732047
36105214732039
36105214732021
36105214732013
36105214732005
36105214732161
36105214732153
36105214732146
36105214732138
36105214732120
36105214732088
36105214732112
36105214732104
36105214732096
36105214732294
36105214732179
36105214732286
36105214732278
36105214732260
36105214732187
36105214732252
36105214732245
36105214732195
36105214732203
36105214732237
36105214732211
36105214732377
36105214732369
36105214732351
36105214732302
36105214732344
36105214732310
36105214732336
36105214732328
36105214732385
36105214732526
36105214732518
36105214732500
36105214732492
36105214732393
36105214732484
36105214732476
36105214732468
36105214732450
36105214732443
36105214732401
36105214732435
36105214732427
14423313-118001
36105214732419
36105214732559
36105214732534
36105214732625
36105214732591
36105214732609
36105214732617
36105214732567
36105214732583
36105214732807
36105214732799
36105214732575
36105214732641
36105214732781
36105214732773
36105214732765
36105214732757
36105214732732

**Comment by jermnelson** [comment]
@dlrueda all of these items now have their `discoverySuppress` property set to **False**.  I just did a PUT to the `/inventory/items` Okapi endpont for each item after first retrieving the item and updating the `discoverySuppress`  to False.
