### ISSUE TITLE
circstaff notes were not migrated

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#552]
Catherine brought to my attention that Symphony CIRCSTAFF notes were not migrated to Folio.

These are the notes in files like
ckeys_00150000_00199999.tsv.circstaff.tsv

“circ note” notes WERE migrated correctly.

Step 1 is to confirm that these were not created in all cases (it would be bad to duplicate them!)

But, after confirmation, can we run a process to add the CIRCSTAFF notes for all *circstaff.tsv files in
/s/SUL/Dataload/folio_symphony_extract/Bibs/Bibs_catdumps?

**Comment by ahafele** [comment]
Maybe related to https://github.com/sul-dlss/libsys-airflow/issues/151 ?

**Comment by dlrueda** [comment]
huh. Yep, that’s exactly it.  Wish I’d seen that ticket during migration! On the other hand, it was closed so maybe we thought we’d fixed it?

**Comment by jermnelson** [comment]
Looking at the code and at some examples, I think I have an idea what happened. Basically, there was an error when merging the CIRCSTAFF tsv file into then general notes TSV file. Working on remediation now.

**Comment by jermnelson** [comment]
@dlrueda remediation complete; here are some random examples of CIRCSTAFF notes that are now added to items:

- https://folio.stanford.edu/inventory/view/e8492213-74aa-5aea-a542-2ea0a6584838/999507d9-eca8-544d-a31d-470b53230b58/67e1f1dd-b662-5ff2-a367-b25dd3bf6f2a
- https://folio.stanford.edu/inventory/view/c3b9974d-4608-52aa-9352-a27fdf8ffe43/aedcbaa2-e308-5719-b2ec-67f5fd024078/ffb98714-8089-50f4-a9aa-c80b62724693
- https://folio.stanford.edu/inventory/view/05459575-bb85-5d2d-a7c8-663b05ca15c3/4ab2ef12-f224-5f8a-b0b1-136a8fef88df/364cd088-0d58-5c87-b35f-8d8619c950e1
- https://folio.stanford.edu/inventory/view/0dace4e2-3bda-5c63-838a-e3af6c55c625/db001070-ff1e-5c23-ba7f-951d2a76a7b3/7de9cffd-a913-580e-b85b-27c6eeaf11b9
- https://folio.stanford.edu/inventory/view/9a7d025e-d402-5695-80fb-0ed8685245bf/8992945a-c361-5453-9b58-e1566d5ebe79/1342058a-11fa-5217-8f39-a6b23abcfd70
