### ISSUE TITLE
Update Order Loading Tool configuration

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#554]
Please update SUL configurations to 

daysToShowResults: 20
daysToKeepResults: 365

For daysToKeepResults, I assume that length of time is ok and also that we could access these if needed? If I understand the documentation this would mean the UI would show 20 days worth and the server would contain 365 then begin deleting older than 365 https://github.com/folio-labs/folio-order-import-tool#how-to-configure-the-service

**Comment by jermnelson** [comment]
@ahafele both dev and prod servers have been updated with these configuration values.

**Comment by ahafele** [comment]
Thank you!
