### ISSUE TITLE
ABLE - certain barcodes searches are no longer returning records

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#562]
When testing the change made to fix https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/551 the original list of barcodes is no longer returning records for about half. Additional records are not retrievable - by barcode or title searches. We haven't noticed a pattern in the data. 
Troubleshooting and talking with Index Data to try and resolve.

**Comment by ahafele** [comment]
Josh talking with Wayne from Index Data - “the default GraphQL query limits you to I think 100 holdings records per instance and 100 items per holdings record. This can cause a problem if the barcode you scan isn’t among the first 100. So we also have a custom GraphQL query that we load into the container, overwriting the default”

**Comment by jgreben** [comment]
This is only an issue using the ABLE client for MacOS.

**Comment by ahafele** [comment]
All barcodes are returned using windows version
