### ISSUE TITLE
create app_rialto user

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#565]
Need new app user for the Rialto app: app_rialto

Needs ability to lookup user and have custom field information returned.

For starters, just grant user-import.all single permission for this user.

If that doesn’t work, can always give it the import_export_data PSet, which is what app_sdr uses.

**Comment by shelleydoljack** [comment]
Will the app user need to edit user data? If it is just for looking up info, then I think we should give it different permissions.

**Comment by shelleydoljack** [comment]
I propose the user get the `ui-users.view` permission, which has these sub-permissions:
```
"module.users.enabled",
"users-bl.collection.get",
"users-bl.item.get",
"addresstypes.collection.get",
"users.collection.get",
"users.item.get",
"usergroups.collection.get",
"configuration.entries.collection.get",
"user-settings.custom-fields.collection.get",
"user-settings.custom-fields.item.get",
"user-settings.custom-fields.item.stats.get",
"departments.collection.get",
"departments.item.get"
```

**Comment by shelleydoljack** [comment]
I created the app_rialto user in all folio's with the ui-users.view permission.

@peetucket the password for app_rialto user can be found in vault. Note that the folio environment (dev, test, stage, prod) is in the vault path for app user passwords (this is mainly so a password could change in one environment and not break the others):
`vault kv get -field=content puppet/application/folio/test/app_rialto_password`

**Comment by dlrueda** [comment]
As you assumed, no edits needed for this app user

**Comment by peetucket** [comment]
Confirmed working against okapi-stage and pulling user data.  When you want to consult about the org code stuff, let me know.  I have my ends working I think.
