### ISSUE TITLE
Add missing SRS record

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#566]
Slack discussion here - https://stanfordlib.slack.com/archives/C03MB1KHR89/p1695675108930219

Needs to be added for https://folio.stanford.edu/inventory/view/0b94cb6b-9940-436c-aecb-080d2e187eee?query=in00000016352&segment=instances&sort=title

Last time Jeremy - 

copied the existing 001 field to an 035, updated the 001 to the Instance HRID, and added a 999 with the SRS and Instance UUID in the subfield s and i subfields.

**Comment by jermnelson** [comment]
@ahafele completed, MARC record now available https://folio.stanford.edu/inventory/viewsource/0b94cb6b-9940-436c-aecb-080d2e187eee?query=in00000016352&segment=instances&sort=title

**Comment by ahafele** [comment]
Thanks!!
