### ISSUE TITLE
Allow access for SUL Aeon

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#572]
The Aeon IP’s we’ve allowed so far are for the Hoover Aeon instance/server.

We need to add now for the SUL Aeon instance/server

Allow for okapi
20.29.204.55
52.250.48.144

Here’s what we did for Hoover access
Have a PR for it: [sul-dlss/folio-k8s#133](https://github.com/sul-dlss/folio-k8s/pull/133)
Needs to be merged and applied to platform-complete and okapi.

Allow access to folio-test and folio prod (FOLIO prod is priority, they will point both to prod right now for testing, it’s just lookups)

**Comment by shelleydoljack** [comment]
Deployed to test, stage, and prod.
