### ISSUE TITLE
Determine strategy for getting item/holdings data

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#579]
For POD and ShareVDE we need to include holdings and items data. 

**Options**

Data Export: allows you to build profiles that can include holdings and items data in mapped MARC fields. However, you can not use data export profiles to exclude suppressed records. We could maybe export the bibliographic, holdings, items data separately with different metadb reports and link together with record IDs. This could work for ShareVDE, need to check on POD  

OAI/PMH: Allows for harvesting of bib, holdings, and items data but https://wiki.folio.org/display/FOLIOtips/OAI-PMH+Settings indicates that time is the finest selection criteria available. This would not work for our selection criteria. 

SearchWorks method: Direct database queries. Selection criteria would also be the same. Jeremy was going to investigate this option. Separate ticket #582

_Okapi calls?_

**Comment by shelleydoljack** [comment]
I think OAI-PMH to get all and then incrementals going forward, and then having separate scripts or processes to parse those files for the various data export criteria is one strategy to explore. I'm not sure the direct db query we are doing with SW is going to last.

**Comment by ahafele** [comment]
Update from Share-VDE - can use marcxml files. About the possibility to export data via OAI-PMH: we are using this protocol, for example to manage data coming frm POD (where also Stanford puts its data, if I’m not wrong).

**Comment by ahafele** [comment]
Current thinking is that data will be retrieved directly from metadb. Close this ticket if others have been created.

**Comment by jgreben** [comment]
Using SQL and API as needed in airflow app.
