### ISSUE TITLE
Determine OCLC api calls needed

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#580]
https://developer.api.oclc.org/wc-metadata-v2#

Client ID: 7RyFsXCcwROKnXR0lJMKO4nZGKEUrptPLPxTsdj2JifTZkkcZBHwE94k1Ig6WZpWoXo5QFHzn56dVxR5
Secret: _Ask Alissa_

**Comment by ahafele** [comment]
Example of records with no OCLC numbers but would probably find match in worldcat:
[in00000030384](https://folio.stanford.edu/inventory/view/6d4ee9f4-4a81-41d8-97e1-94429a45c5c0?query=in00000030384&sort=title)
[in00000030383](https://folio.stanford.edu/inventory/view/60672d8f-f66b-4d97-bb21-685ca55f27d0?query=in00000030383&sort=title)

**Comment by jermnelson** [comment]
Using the [brief-bibs-search](https://developer.api.oclc.org/wc-metadata-v2#/Search%20Bibliographic%20Resources/search-brief-bibs) endpoint, we can retrieve matches for these two resources using title or ISBN. For the title search, the first record [in00000030384](https://folio.stanford.edu/inventory/view/6d4ee9f4-4a81-41d8-97e1-94429a45c5c0?query=in00000030384&sort=title) returns 37 hits, using one of the record's ISBN, returns 4 hits. 

We'll need to do some experimenting to see what criteria we want to use and how to determine what OCLC record to use.

**Comment by ahafele** [comment]
@jermnelson I chatted with Nancy a bit about this and she think that right now the process is to just send the record to OCLC and if there is no oclc number they determine the match with their algorithm. If this isn't possible through any of the endpoints, we might want to rethink sending bibs with no oclc number through the API.

**Comment by ahafele** [comment]
Outstanding question here - for records with no OCLC number we want to rely on OCLC's own algorithms to determine if there is an appropriate match or if they should create a new record. Previously we did this by sending them a file of MARC records. Is it possible to send the records to /manage/bibs endpoint with the same result?

**Comment by ahafele** [comment]
Cornell sends records with no OCLC number through the API. Waiting additional information to see what endpoint they use.
