### ISSUE TITLE
Investigate using SearchWorks strategy for data exports to POD/ShareVDE

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#582]
SearchWorks method used direct database queries. Selection criteria would be the same or very close.

**Comment by jermnelson** [comment]
Searchwork queries using the [FolioPostgresReader](https://github.com/sul-dlss/searchworks_traject_indexer/blob/main/lib/traject/readers/folio_postgres_reader.rb) class in [SearchWorks Traject Indexer](https://github.com/sul-dlss/searchworks_traject_indexer) project.

**Comment by ahafele** [comment]
Will not work
