### ISSUE TITLE
Create Pod to perform upgrade within the cluster

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/FOLIO-Project-Stanford#598]

**Comment by shelleydoljack** [comment]
pod will need to have helm and ruby. Maybe even env vars that pull from the namespace's secret? Also will need to somehow get the correct branch of platform-complete for the okapi and stripes install files.

**Comment by shelleydoljack** [comment]
Oh, and maybe perl or docker to run the bootstrap-superuser.pl script with flag `-eFLAGS='--onlyperms'` to get the new permissions assigned to superuser.
