### ISSUE TITLE
What are FOLIO special interest groups, which should we join?

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#6]

**Comment by shelleydoljack** [comment]
The SIGs are listed on the wiki main page: https://wiki.folio.org
Of interest for us might be:
- Metadata Management: https://wiki.folio.org/display/MM
- User Management: https://wiki.folio.org/display/UM
- Systems Operation and Management: https://wiki.folio.org/display/SYSOPS

**Comment by shelleydoljack** [comment]
Document for people to fill out which SIGs they are attending: https://docs.google.com/document/d/1lV7LuH484aEF-E9zEIR6FSNroVE7GEGcfCxaOg3h50Y/edit#
