### ISSUE TITLE
Ask Circ folks which users/data we need to load to FOLIO

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#60]
What users need to be loaded to FOLIO? Need to consult with Circ/Priv folks.

First guesses on what to ask, I’m sure there are more questions to ask as well...

- [ ] non-expired users in Symphony
- [ ] expired users if they have a charge
- [ ] expired users if they have an outstanding replacement fee?
- [ ] expired users if they have an outstanding overdue fine or billing processing fee?
- [ ] expired users if they have an unexpired hold?

**Comment by dlrueda** [comment]
This is just for real users for now, not considering pseudopatrons as part of this ticket.

**Comment by dlrueda** [comment]
Coordinate-created users?

**Comment by dlrueda** [comment]
SUL-created users (fee borrowers)

**Comment by Laszlo-J** [comment]
Will check with larger Circ subgroup in our next meeting.

Access Services/Catherine desires to keep expired users w/lost or billed items on their account. Also desired to keep locally-created records (fee-borrowers, etc.)

**Comment by Laszlo-J** [comment]
Per Mario & Rebecca, please load the following users from Symphony:

• Expired users 
    o	with outstanding loans or billed items
    o	with anything charged out
    o	with an unexpired hold
• SUL-created users (fee-borrowers, etc.)
• Coordinate-created users
• Expired student users
• Courtesy card users (including spouses)
• On Leave users
• Retiree users

I think the last 4 should already be in the University load? Not sure.
