### ISSUE TITLE
Reference Data and Poppy upgrade

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#602]
Per Wayne at Index Data, reference data that will get overwritten when doing refdata=true is:

* Patron groups (`/groups`)
* Address types (`/addresstypes`)
* Expense classes (`/finance-storage/expense-classes`)
* Fund types (`/finance-storage/fund-types`)
* Circ rules (`/circulation-rules-storage`)
* Staff slips (`/staff-slips-storage/staff-slips`)
* Loan policies (`/loan-policy-storage/loan-policies?limit=100`)
* Request policies (`/request-policy-storage/request-policies`)
* Overdue fines policies (`/overdue-fines-policies`)
* Request cancellation reasons (`/cancellation-reason-storage/cancellation-reasons`)
* Patron notice policies (`/patron-notice-policy-storage/patron-notice-policies`)
* Lost item fees policies (`/lost-item-fees-policies`)

Reference data where we have removed or edited default:

**Inventory**
- stat codes/types
- material types?
- orders? 

**ERM** 
- licenses

**Acq**
- fund types
- expense classes

**Circ**
- service points

**Comment by dlrueda** [comment]
When I go to Settings -> Users on folio-dev, there are no patron groups anymore. 

folio-dev
![image](https://github.com/sul-dlss/FOLIO-Project-Stanford/assets/14914677/3282d9e5-54fe-4f3d-bcb0-e9c0a83c36e3)

folio-stage
![image](https://github.com/sul-dlss/FOLIO-Project-Stanford/assets/14914677/ffa07891-e096-4673-afc5-345b41f9396c)

**Comment by dlrueda** [comment]
On folio-test, Circ staff say they lost the data in these policies, and would like it reloaded from prod data:
* Staff slips (/staff-slips-storage/staff-slips)
   The policies are there (Hold, Pick slip, Request deliver, Transit), but on prod Hold, Pick slip, and Transit all have more data in them than in folio-test.


I think we'll need to dump the json on prod before doing the upgrade, and restore it from our dump after the upgrade.

**Comment by ahafele** [comment]
On folio-test Inventory, Data Import, and Acq settings have been reviewed and look good. Jeanette confirms they would like data import profiles refreshed from prod and they will relink manually.

**Comment by jgreben** [comment]
Creating ticket for staff slips issue
