### ISSUE TITLE
Barcodes not returning call number

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#604]
Collection Care reports that certain barcodes on this record are not returning any call number in ABLE. This is a serial that they will likely do more binding for.
I've included examples below. From my investigation there is no 952 returned at all when looking via SRU. There doesn't seem to be any pattern to locations, call number length, or number of items returned (e.g. some are found that are further down the list of items in FOLIO)

**Not found**
36105123419959 - page 2 of item records in FOLIO. enumeration: V.19:NO.668-695 2007:OCT.
36105232952635 - page 4 of item records in FOLIO (reported from hannah) V.35:NO.353-421 2023:APR-MAY

**Found**
36105132689303 - page 2 of item records in FOLIO. enumeration: V.20:NO.530-557 2008:JULY
36105073486065 - enumeration: V.13 2001:FEB.
36105212603836 - enumeration: V.25:NO.595-634 2013:SEP.-OCT

example SRU search 
http://folio-sru-prod.stanford.edu/sul?version=1.1&operation=searchRetrieve&query=item.barcode=36105132689303&maximumRecords=1&recordSchema=opac

**Comment by jgreben** [comment]
@ahafele Can you give this a try on folio-test? I updated the mod-search.graphql-query config to the one that Wayne recommended with holdings record limit of 20K. It takes longer to load the page, but I think it includes the missing barcodes with that config.

**Comment by ahafele** [comment]
This looks good @jgreben! Barcodes now return call number info.

**Comment by jgreben** [comment]
Great! I applied the configuration in prod as well.

**Comment by ahafele** [comment]
Tested in prod and looks good. Barcodes now returning call numbers. Thanks!
