### ISSUE TITLE
Email checkout receipt not sending on folio-test

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#606]
An email receipt is sent to the user when they check an item out.  It is sent to foliotesting@lists.stanford.edu (that's the email in the user record on all the non-prod servers)

That email is not being sent from folio-test.

**Comment by dlrueda** [comment]
Not sure if it's related, but the entry in the Circ log for my checkout didn't get made either.
My barcode: 2557433875
Item I charged out: 20500751125

I did confirm that the item was checked out to me; it shows in my Open Loans.

**Comment by jgreben** [comment]
Fixed by https://github.com/sul-dlss/folio-k8s/blob/19f42347283282df8d0e50d3c2270f3956bd630f/helm-postfix.yaml#L4
