### ISSUE TITLE
No postings to circulation log on folio-test

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#607]
I am not seeing anything posted to the circulation log on folio-test.  I've checked out, then back in, item 20500751125.  Nothing is showing for that in the Circ log.

My user barcode is 2557433875.  The last activity for my barcode is from 1/23

**Comment by jgreben** [comment]
The SYSTEM_USER_PASSWORD was invalid and folio deactivated the pub-sub user. Everything is updated in dev and test, and the secrets in vault are updated with a valid password.
