### ISSUE TITLE
Poppy Upgrade - Dashboard App

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#609]
Not urgent - I have Dashboard app permissions but don't see any available widgets when trying to add one. There should be a couple ERM widgets available according to https://poppy.docs.folio.org/docs/dashboard/#adding-widgets 

<img width="1613" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzVPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b79ed346209e91a19dd0a8178dd7f2c380af4a46/Screenshot%202024-02-12%20at%2011.38.50%E2%80%AFAM.png" alt="Screenshot 2024-02-12 at 11.38.50 AM.png" />

**Comment by jgreben** [comment]
We never set this right when going to Nolana. A couple of things:

- To ensure that the widget definitions made available by mod-agreements and mod-licenses are available, mod-service-interaction should be initialised with the tenantParameter `loadSample%3Dtrue` specified.

- To ensure that dashboard has all the available dashboard widget definitions:
Assign a user the permission `servint.admin.action`
With that user, issue a GET to Okapi endpoint /servint/admin/triggerTypeImport - this will import all available widget definitions from modules that supply them

(https://folio-org.atlassian.net/wiki/spaces/REL/pages/5210458/R2+2021+Juniper+Release+Notes).

**Comment by jgreben** [comment]
@ahafele I got the ERM items to appear, but I think we need to reinstall mod-service-interaction with sample data if there are more widget definitions that are supposed to appear.

**Comment by jgreben** [comment]
I just looked at https://folio-snapshot.dev.folio.org/ and I only see the ERM widget definitions, so maybe that's all there is supposed to be?

**Comment by ahafele** [comment]
Yes just a couple of ERM widgets are available as of Poppy.

**Comment by ahafele** [comment]
foli
