### ISSUE TITLE
Upgrade Poppy to R2-2023-csp-1

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/FOLIO-Project-Stanford#610]

**Comment by jgreben** [comment]
- Create folio-platform-complete branch
- Follow upgrade steps

**Comment by shelleydoljack** [comment]
Starting to work on creating branches for Poppy csp 1.

**Comment by shelleydoljack** [comment]
[folio-dev branch](https://github.com/sul-dlss/folio-platform-complete/tree/R2-2023-csp-1-folio-dev)

[folio-test branch](https://github.com/sul-dlss/folio-platform-complete/tree/R2-2023-csp-1-folio-test)

[folio-stage branch](https://github.com/sul-dlss/folio-platform-complete/tree/R2-2023-csp-1-folio-stage)

[folio-prod branch](https://github.com/sul-dlss/folio-platform-complete/tree/R2-2023-csp-1-folio-prod)

**Comment by shelleydoljack** [comment]
Going to close this since there will be csp 2 that we'll need to create platform complete branches for.
