### ISSUE TITLE
Import Staff slips from prod after upgrading to poppy

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/FOLIO-Project-Stanford#612]
On folio-test, Circ staff say they lost the data in these policies, and would like it reloaded from prod data:

Staff slips (/staff-slips-storage/staff-slips)
The policies are there (Hold, Pick slip, Request deliver, Transit), but on prod Hold, Pick slip, and Transit all have more data in them than in folio-test.
I think we'll need to dump the json on prod before doing the upgrade, and restore it from our dump after the upgrade.

**Comment by shelleydoljack** [comment]
Likely need to do PUT to the endpoint since the staff slips they use are reference data that are just missing the template part. See on folio-dev what it looks like: https://folio-dev.stanford.edu/settings/circulation/staffslips/6a6e72f0-69da-4b4c-8254-7154679e9d88
