### ISSUE TITLE
Reconnect instance and SRS

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#616]
@shelleydoljack Linh reported that a couple of instances have disconnected from their SRS (again) - could you try and reconnect 

in00000011298
in00000011297
in00000011293 

I'm not seeing anything obvious about these records that might have caused them to disconnect again. See slack convo here - https://stanfordlib.slack.com/archives/C03MB1KHR89/p1708725375678659?thread_ts=1704395995.107019&cid=C03MB1KHR89

**Comment by shelleydoljack** [comment]
Followed [this doc](https://docs.google.com/document/d/18sw0_fnWrns4hfy55-Us5IpZQLe3gp_UgWFxk16AQiw/edit?usp=sharing) to make the latest generation record "ACTUAL".
