### ISSUE TITLE
Load all desired users to FOLIO

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#62]
When correct users are identified from Symphony #60 and UnivIDs collected #61

Need to add chunks of UnivIDs to file of IDs to harvest from user registry/transform/load to FOLIO.  Once file is created, can run script

/s/SUL/Harvester/current/run/do-person-harvest.sh file file-of-ids

**Comment by Laszlo-J** [comment]
Per Mario & Rebecca, please load the following users from Symphony:

• Expired users
    o with outstanding loans or billed items
    o with anything charged out
    o with an unexpired hold
• SUL-created users (fee-borrowers, etc.)
• Coordinate-created users
• Expired student users
• Courtesy card users (including spouses)
• On Leave users
• Retiree users

I think the last 4 should already be in the University load? Not sure.

**Comment by dlrueda** [comment]
@Laszlo-J Please add how to identify these users in Symphony.

e.g. for SUL-created users, what is their profile and/or other fields to look for to identify them.  
same for coordinate-created users,
courtesy card users,
on leave users,
retiree users

**Comment by Laszlo-J** [comment]
Based on a talk with Mario made a spreadsheet of SUL's user profile and associated types. Most profiles have an associated type, but some don't:
https://docs.google.com/spreadsheets/d/1GUTd90EvrWogfQ9nSTGMyMm7VYpRE-GPm4FlOibmJ80/edit#gid=0

Second sheet has coordinate types I discovered, but still trying to reach GSB & Law to update this.

Also, still checking on highlighted cells, but this should give you enough to make a start. I'll update ticket once everything's totally verified.

Mario states "on leave" students aren't needed - they get no borrowing privileges while away so not in Symphony.

For retirees, only emeritus faculty/acad staff get borrowing, noted in the sheet.

**Comment by jgreben** [comment]
Verify that this is done and ask Mario to QA.

**Comment by jgreben** [comment]
We've got 45K users loaded into folio-test. Mario has done his QA already. Closing..
