### ISSUE TITLE
Update Aeon to latest version

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#621]
Needed for production in mid-April, per Sarah.  Test can and should be done as soon as possible

From Vivian:

We will work on a new app, Arclight@SUL, from 3/18 - 4/19 (1st WC), that supports discovering and accessing the archival collections.

After the 1st WC, we plan to integrate Archlight@SUL with SearchWorks and Aeon in the April to May timeframe. Sarah informed me that to integrate with Aeon, your team needs to upgrade Aeon to the next version. I want to know if your team can do the Aeon upgrade around mid-April.

**Comment by dlrueda** [comment]
Going to version 5.2

**Comment by jgreben** [comment]
Stage is complete. Aeon client on sul-aeon-stage.stanford.edu is updated to match v5.2 server.

**Comment by jgreben** [comment]
Went to v6. There may be some web work to do. If so, seperate ticket.
