### ISSUE TITLE
Update criteria for assigning graduate and postdoctoral patron groups

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#624]
Per Mario
What should be changed is the logic of when the postdoctoral patron group is assigned to a user.
As explained by Josh, the current logic is any user with a privgroup student:phd, student:postdoc, or student:doctoral, will get assigned the postdoctoral patron group.
Instead we want:
A user with a privgroup student:phd or student:doctoral will get assigned the graduate patron group.
A user with a privgroup student:postdoc will get assigned the postdoctoral patron group.

**Comment by dlrueda** [comment]
Sample user that is being assigned postdoctoral, and they want instead graduate, is
2558248011
Gilbert, Matthew
06439615

**Comment by jgreben** [comment]
Fixed by https://github.com/sul-dlss/userload-harvest/pull/28
