### ISSUE TITLE
ABLE - Stop stripping ending punctuation from 245$a

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#625]
The z39.50 configuration is stripping ending punctuation from the 245$a (and maybe ending white space?) causing some spacing issues in ABLE - see screenshots. Collection Care would like to stop stripping ending punctuation. I cleared this with Hilary some time ago since the config is shared with Illiad but it should be tested in both places before putting into production. 

Barcode: 36105231183083
<img width="1335" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2k2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--72beda04d4a83f34c67a6980f734d33f670b4e5b/Screenshot%202024-03-04%20155901.png" alt="Screenshot 2024-03-04 155901.png" />

**Comment by jgreben** [comment]
@ahafele The zserver config does strips ending spaces, colons, forward-slashes, and equal signs (`[ :/=]`) from the end of 245$a. Do we want to still remove any of these or just keep them all?

**Comment by ahafele** [comment]
Checking with Collection Care.

**Comment by ahafele** [comment]
Hannah says
KEEP ending spaces and colons
REMOVE forward-slashes and equal signs

I'd like to have collection care and Hilary test before putting into production.

**Comment by ahafele** [comment]
Collection Care changed their minds and now want to keep **=** also

So would be - If the marc field is 245a it will now only replace / with an empty string. Spaces and colons : and equals = will be left alone.

**Comment by jgreben** [comment]
Closing for now. Let me know if this needs to be looked at again.
