### ISSUE TITLE
QA the user data in folio-test

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#63]
Once we have started loading users from the production registry, need to 

- [x] look at the user records loaded.  Do they have the correct information in them?  (User group, address, etc)

- [x] request to load some no-longer-valid users (by harvesting a file of specific UnivIDs(.  Check that they are made inactive in FOLIO.

- [x] check expire dates

- [x] Document QA process

**Comment by Laszlo-J** [comment]
Asking Priv staff if they can do the QA. What's the ETA for loading patrons?
