### ISSUE TITLE
Complete locations spreadsheet - SAL3

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#64]
Talk to each library about list of locations they want to retain for FOLIO, fill out locations spreadsheet with location code, discoveryDescription, etc.

- [x] Science
- [x] Law
- [x] Business
- [x] Art
- [x] ARS
- [x] Education
- [x] Music
- [x] Tanner
- [x] Hopkins
- [x] Green
- [x] Earth-sci
- [x] Rumsey map
- [x] Engineering
- [x] East-asia
- [x] Classics
- [x] HILA (Hoover Lib & Archives)
- [x] Special Collections
- [x] Media Center
- [x] SAL
- [ ] SAL-Newark
- [x] SAL3

**Comment by dlrueda** [comment]
Have NOT listed Media, SAL, SAL3, SAL-NEWARK

Not sure if these libraries will be needed in FOLIO.  TBD.

**Comment by dlrueda** [comment]
Rebecca wants MEDIA to exist in FOLIO as Media Center.  So, do locations

**Comment by dlrueda** [comment]
Waiting for Alexis to do some investigation about SAL-NEWARK.  Not making locations for it at the moment.

SAL, make locations.  It will be a thing for 3-5 yrs minimum

**Comment by dlrueda** [comment]
Waiting on SAL3 to determine if it will be a library or just a service point in FOLIO (probably a library but waiting to confirm)

**Comment by jgreben** [comment]
Don't need SAL-Newark
