### ISSUE TITLE
"reconnect" SRS to instances

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#641]
List of instances not connected to MARC https://docs.google.com/spreadsheets/d/1HOFq98uOM6tCwN7zQ1aVSp5oVhBx9yI7gV0GcAExuog/edit#gid=0

**Comment by ahafele** [comment]
@dlrueda I requested edit access for you and I for the sheet above.

**Comment by dlrueda** [comment]
I'm finding that some of the HRID's do not have any SRS record in the records_lb table that have the HRID in the external_hrid field.  So maybe these will have to be set back to source=FOLIO and allow a future overlay to get an SRS record.

I think after the HRID's on the spreadsheet are corrected, we can generate another report, correct the new ones, and the rest set to source=FOLIO.

**Comment by dlrueda** [comment]
All of these SRS records have no record that has state=ACTUAL.
Jeanette requests we set the record with the most recent created_date to have state=ACTUAL, but I am checking that it is also the highest generation record OR has a correct matching_id.

**Comment by dlrueda** [comment]
okapi=# select a.external_hrid, a.id, a.leader_record_status, a.state, a.generation, a.created_date
okapi-# from sul_mod_source_record_storage.records_lb a
okapi-# where a.external_hrid in ('in00000001227', 'in00000001266', 'in00000003045', 'in00000003388', 'in00000003392', 'in00000003586', 'in00000003587', 'in00000003591', 'in00000003593', 'in00000003815')
order by a.external_hrid, a.created_date;

and eliminate any HRID's where one of the records has state=ACTUAL

Then this select to review the id to update to ACTUAL
okapi=# select a.external_hrid, a.id, a. leader_record_status
, a.state, a.generation, a.created_date
from sul_mod_source_record_storage.records_lb as a
inner join (
select external_hrid, max(created_date) credate
from sul_mod_source_record_storage.records_lb
where external_hrid in ('a13582227','a13582228','a13582412')
group by external_hrid
) as b on a.external_hrid = b.external_hrid and a.created_date = b.credate;
 external_hrid |                  id                  | state |        created_date        
---------------+--------------------------------------+-------+----------------------------
 a13582227     | 8308b12b-0ff1-4a4b-940b-1e4df13e9998 | OLD   | 2024-01-18 11:39:10.511-08
 a13582228     | d69d6a6e-3e24-4b11-b9ba-14aeb465348c | OLD   | 2024-01-18 11:39:10.511-08
 a13582412     | 5a982b78-db9b-4a96-8e18-e1a8e6e0144e | OLD   | 2024-01-18 11:39:14.907-08

Get just the ids
select a.id
from sul_mod_source_record_storage.records_lb as a
inner join (
select external_hrid, max(created_date) credate
from sul_mod_source_record_storage.records_lb
where external_hrid in ('a13582227', 'a13582228', 'a13582412', 'a13582594', 'a13602558', 'a13603307', 'a13603374', 'a13633293', 'a13671682', 'a13691817', 'a13692180', 'a13693302', 'a13695771', 'a13695783', 'a13695896', 'a13696022', 'a13696145', 'a13696728', 'a13733028', 'a13733348', 'a13733714', 'a13733716', 'a13733802', 'a13741769', 'a13742206', 'a13742259', 'a13763472', 'a13763688', 'a13763769', 'a13763772', 'a13763797', 'a13763816', 'a13763871', 'a13776068', 'a13776283', 'a13781369', 'a13798886', 'a13799480', 'a13799571', 'a13816635', 'a13816825', 'a13816888', 'a13816969', 'a13837863', 'a13838596', 'a13838759', 'a13838768', 'a13838769', 'a13859842', 'a13859918')
group by external_hrid
) as b on a.external_hrid = b.external_hrid and a.created_date = b.credate;

For those IDs, set state to ACTUAL, e.g.,
update sul_mod_source_record_storage.records_lb
set state = 'ACTUAL'
where id in ('5ff8f78f-a2fe-4b69-a35a-8d8715fc7dd0', 'd64c8dd8-78af-40ac-a0ec-e9771594a260');

**Comment by dlrueda** [comment]
Records from original spreadsheet all updated as of 8/12/24.  Jeanette is going to run another report tomorrow (after derived tables in meted are updated), and she'll add to another tab of the spreadsheet if there are others.

**Comment by dlrueda** [comment]
SQLs I'm doing

select a.external_hrid, a.external_id, a.id, a.leader_record_status, a.state, a.generation, a.created_date
from sul_mod_source_record_storage.records_lb a
where a.external_id in (list of instance UUIDs)
order by a.external_id, a.created_date;

select a.external_hrid, a.external_id, a.id, a.leader_record_status, a.state, a.generation, a.created_date
from sul_mod_source_record_storage.records_lb as a
inner join (
select external_id, max(generation) gener
from sul_mod_source_record_storage.records_lb
where external_id in (list of instance UUIDs) 
group by external_id
) as b on a.external_id = b.external_id and a.generation = b.gener;


select a.id
from sul_mod_source_record_storage.records_lb as a
inner join (
select external_id, max(generation) gener
from sul_mod_source_record_storage.records_lb
where external_id in (list of instance UUIDs)
group by external_id
) as b on a.external_id = b.external_id and a.generation = b.gener;
