### ISSUE TITLE
Acq fiscal year on invoices script - Before Rollover

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#645]
All libraries would like to have a script run that is supposed to fix an issue with fiscal years on invoices (new in Poppy).
Invoices created prior to Poppy are not populated with the fiscal year. It is blank. Only new invoices created will have them. This script is supposed to fix that and populate the fiscal year on those invoices: https://folio-org.atlassian.net/browse/MODINVOSTO-174. 

They would like to have this run after we upgrade to Poppy but before Rollover.

**Comment by shelleydoljack** [comment]
SQL script to update invoice fyrID: https://folio-org.atlassian.net/browse/MODINVOSTO-174?focusedCommentId=203942
```
WITH updated_invoices AS (
    SELECT inv.id AS invoice_id,
           to_jsonb(trx.jsonb->>'fiscalYearId') AS fiscal_year_id
    FROM <tenant>_mod_invoice_storage.invoices AS inv
    JOIN <tenant>_mod_finance_storage.transaction AS trx
        ON trx.jsonb->>'sourceInvoiceId' = inv.id::text
    WHERE inv.jsonb->>'fiscalYearId' IS NULL
)
UPDATE <tenant>_mod_invoice_storage.invoices AS inv
SET jsonb = jsonb_set(inv.jsonb, '{fiscalYearId}', ui.fiscal_year_id)
FROM updated_invoices AS ui
WHERE inv.id = ui.invoice_id
  AND ui.fiscal_year_id IS NOT NULL;
```

**Comment by shelleydoljack** [comment]
On folio-dev (since it has prod data from 7/25/2024):
```
okapi=# select count(*) from sul_mod_invoice_storage.invoices where jsonb ->> 'fiscalYearId' is null;
 count 
-------
  8669

okapi=# select count(*) from sul_mod_invoice_storage.invoices where not jsonb ->> 'fiscalYearId' is null;
 count 
-------
  1312
```
The psql script should update 8,669 invoices.

**Comment by shelleydoljack** [comment]
Started on folio-dev 8/9/2024 at 14:45PDT:
```
WITH updated_invoices AS (
    SELECT inv.id AS invoice_id,
           to_jsonb(trx.jsonb->>'fiscalYearId') AS fiscal_year_id
    FROM sul_mod_invoice_storage.invoices AS inv
    JOIN sul_mod_finance_storage.transaction AS trx
        ON trx.jsonb->>'sourceInvoiceId' = inv.id::text
    WHERE inv.jsonb->>'fiscalYearId' IS NULL
)
UPDATE sul_mod_invoice_storage.invoices AS inv
SET jsonb = jsonb_set(inv.jsonb, '{fiscalYearId}', ui.fiscal_year_id)
FROM updated_invoices AS ui
WHERE inv.id = ui.invoice_id
  AND ui.fiscal_year_id IS NOT NULL;
```
Reponse was `UPDATE 8613`. Took about 15s

```
okapi=# select count(*) from sul_mod_invoice_storage.invoices where jsonb ->> 'fiscalYearId' is null;
 count 
-------
    56

okapi=# select count(*) from sul_mod_invoice_storage.invoices where not jsonb ->> 'fiscalYearId' is null;
 count 
-------
  9925
```
1312 + 8613 = 9925

**Comment by shelleydoljack** [comment]
It looks like the 56 that didn't update was legitimate. They are all status = Open so no transactions yet.
```
select count(*) from sul_mod_invoice_storage.invoices where jsonb ->> 'fiscalYearId' is null and jsonb ->> 'status' = 'Open';
 count 
-------
    56
```

**Comment by shelleydoljack** [comment]
@scanedastanford Do you think we should test FYRO to see if this update would affect that? I did the work on folio-dev to populate the fiscalyearId in the invoice data. I did notice that we don't have a fiscal year filter in the Invoices app on folio-dev, which is weird, since it is on folio (prod). The versions in both environments are the same so not sure what that's about.

**Comment by scanedastanford** [comment]
The invoices app should have a fiscal year filter. What does that mean that it doesn't have it on dev? I refreshed my cache just in case and now I can't get into dev. It says "Authentication issue instant is too old or in the future"

**Comment by shelleydoljack** [comment]
That authentication issue requires you to do a hard refresh.

I updated the data on folio-test since there is a fiscal year filter there.
```
select count(*) from sul_mod_invoice_storage.invoices where jsonb ->> 'fiscalYearId' is null;
 count 
-------
  1002

okapi=# select count(*) from sul_mod_invoice_storage.invoices where not jsonb ->> 'fiscalYearId' is null;
 count 
-------
   175
```
After running the psql script, the response was `UPDATE 383`.
```
okapi=# select count(*) from sul_mod_invoice_storage.invoices where jsonb ->> 'fiscalYearId' is null;
 count 
-------
   619

okapi=# select count(*) from sul_mod_invoice_storage.invoices where not jsonb ->> 'fiscalYearId' is null;
 count 
-------
   558

okapi=# select count(*) from sul_mod_invoice_storage.invoices where jsonb ->> 'fiscalYearId' is null and jsonb ->> 'status' = 'Open';
 count 
-------
   619
```

**Comment by scanedastanford** [comment]
Was it run for all invoices? I ran a metadb report for folio-test. There are still some invoices without a FY.
[Invoices_fy_202408091531.csv](https://github.com/user-attachments/files/16567452/Invoices_fy_202408091531.csv)

**Comment by scanedastanford** [comment]
Oh nevermind. I understand what it's doing now. It's not adding the FY to Open invoices. Which I think is ok

**Comment by scanedastanford** [comment]
> @scanedastanford Do you think we should test FYRO to see if this update would affect that? I did the work on folio-dev to populate the fiscalyearId in the invoice data. I did notice that we don't have a fiscal year filter in the Invoices app on folio-dev, which is weird, since it is on folio (prod). The versions in both environments are the same so not sure what that's about.

I don't think we need to since it updates the FY in invoices only. The transactions linked to invoices already include the FY and I think that's what rollover looks at.

**Comment by shelleydoljack** [comment]
Ok, so then I'll probably also do this tonight on prod since it's best to do it while nobody is working in the system. Sound okay to you, @scanedastanford ?

**Comment by scanedastanford** [comment]
Sounds good. Thanks Shelley!

**Comment by shelleydoljack** [comment]
Counts on prod before running the psql script:
```
okapi=# select count(*) from sul_mod_invoice_storage.invoices where jsonb ->> 'fiscalYearId' is null;
 count 
-------
  8558

okapi=# select count(*) from sul_mod_invoice_storage.invoices where not jsonb ->> 'fiscalYearId' is null;
 count 
-------
  1844

okapi=# select count(*) from sul_mod_invoice_storage.invoices where jsonb ->> 'fiscalYearId' is null and jsonb ->> 'status' = 'Open';
 count 
-------
    12
```

Response `UPDATE 8546`. Counts after running the psql script:
```
okapi=# select count(*) from sul_mod_invoice_storage.invoices where jsonb ->> 'fiscalYearId' is null;
 count 
-------
    12

okapi=# select count(*) from sul_mod_invoice_storage.invoices where not jsonb ->> 'fiscalYearId' is null;
 count 
-------
 10390

okapi=# select count(*) from sul_mod_invoice_storage.invoices where jsonb ->> 'fiscalYearId' is null and jsonb ->> 'status' = 'Open';
 count 
-------
    12
```
@scanedastanford also completed.

**Comment by scanedastanford** [comment]
Thank you! I checked in metadb and it looks correct.
