### ISSUE TITLE
Analyze Green locations

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#65]
- Which are flat out mistakes
- Which are obviously real and should be added to FOLIO locations spreadsheet
- Which need more analysis, with a data dump to help do that

**Comment by dlrueda** [comment]
Email with all locations sent to Laszlo 1/11

**Comment by Laszlo-J** [comment]
[green loc codes.xlsx](https://github.com/sul-dlss/FOLIO-Project-Stanford/files/7857785/green.loc.codes.xlsx)

Review is done. Many need to be analyzed, even if they're mistakes... We need to clean-up that data. Let me know if you want this broken out further or if the one sheet is okay.
