### ISSUE TITLE
Correct amounts in SUL finance transactions

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#655]
From team [meeting notes](https://docs.google.com/document/d/1Ub4cdion62k3teJlvDejkpqBQ09j_54z4fxCgqkJItw/edit) - Some finance transactions have the incorrect amount in them, so total summary isn’t displaying the correct amount of money. Suzette thinks updating the amount in the transaction record is what needs to be done. This is happening because there’s a box in the invoice line, release encumbrance, that isn’t being checked and should be.  And sometimes even if they go back to correct this and say “release the encumbrance”, it isn’t releasing.  But only sometimes.  3 funds so far with 94 transactions.

Suzette is creating a report for what needs to be fixed. 
@scanedastanford please add here when done.

**Comment by scanedastanford** [comment]
~~[fix encumbrance awaiting payment amount.xlsx](https://github.com/user-attachments/files/16383670/fix.encumbrance.awaiting.payment.amount.xlsx)~~ Use updated report in comment below

I'm attaching the transaction ids that need to be corrected. What needs to be corrected is the encumbrance amountAwaitingPayment amount. The existing amounts should be replaced with the amounts in Column I "encumbrance_awaiting_payment_amount". Let me know if you have any questions. Thank you!

**Comment by ahafele** [comment]
-stage is occupied with rollover testing right now. 
@scanedastanford will look for a couple examples of this on -test so the plsql plus Fix Encumbrance script can be run and outcome can be verified before running in production.

**Comment by ahafele** [comment]
Updated report from @scanedastanford to be used when running the plsql on -stage and -prod
[fix encumbrance awaiting payment amount 2.xlsx](https://github.com/user-attachments/files/16498885/fix.encumbrance.awaiting.payment.amount.2.xlsx)

**Comment by ahafele** [comment]
The plsql Josh ran on -stage updated the transactions with the correct awaiting payments amount. However the Awaiting payment amounts at the budget level remained incorrect even after running the Fix Encumbrance script. Based on this[ troubleshooting doc](https://folio-org.atlassian.net/wiki/spaces/DD/pages/1779802/How+to+fix+issues+with+finance+data), Suzette wonders if we also have to update the budget level amounts. [See # 4 - Update Budget's amounts. ](https://folio-org.atlassian.net/wiki/spaces/DD/pages/1779802/How+to+fix+issues+with+finance+data#Howtofixissueswithfinancedata-4.UpdateBudget'samounts)

The impact of this problem is that the invoices can not move from approved to paid for endowed funds because they have restrictions and FOLIO thinks they are overexpended. And acq cannot accurately understand fund amounts in order to spend things out/move things around at end of year. Work around would include using metadb reports for accurate numbers and to remove the restriction on the endowed fund so they can pay those invoices, but to remove the restriction you have to increase the allocation so it's not overexpended then remove restriction and then decrease the allocation. Risky because would have to tell payments staff to not pay anymore on that fund. 

13 funds in this state - 2 are endowed.

**Comment by scanedastanford** [comment]
Per Dennis: _This value is stored in the budget and updated as pending payment type transactions are created/updated. So it would only be coming from pending payment transactions but it is possible that direct manipulation of transactions would cause this value to get out of sync. Eg. deleting a pending payment transaction without first setting its value to 0.
To correct this value you should be able to simply change it via the API. This value should equal the total value of pending payment transactions on the budget. Ie. if there are no pending payment transactions on the budget this value should be set to 0._

The corrections in this ticket were on encumbrance transactions so I don't think we need to do this since Dennis says it comes from pending payment transactions. I can provide the pending payment amounts to be corrected in the budget after i run reports.

**Comment by shelleydoljack** [comment]
Testing to correct awaitingPayment amount in budget on folio-dev: https://folio-dev.stanford.edu/finance/budget/9d273fb1-fb37-550f-96ff-9c29c24c37d9/view/?limit=50&offset=0&query=ARTARCH-SUL

set awaitingPayment to 2751.87. Screenshot of before:
![Screenshot 2024-08-09 at 3 14 43 PM](https://github.com/user-attachments/assets/d897f082-4a17-46b7-83b6-7e86121515ae)

Screenshot after doing a PUT to /finance/budgets/:
![Screenshot 2024-08-09 at 3 17 09 PM](https://github.com/user-attachments/assets/62742607-c444-4b55-a98c-6cf97a13801b)

**Comment by shelleydoljack** [comment]
Screenshot after doing a PUT to finance-storage/budgets:
![Screenshot 2024-08-09 at 3 21 01 PM](https://github.com/user-attachments/assets/d2aaf1c5-5521-4e92-a2de-6412aa189054)

**Comment by scanedastanford** [comment]
Hi Shelley, here's the spreadsheet. Please update awaitingPayment to the highlighted values in the spreadsheet column E.
[Transactions_202408091704 (2).xlsx](https://github.com/user-attachments/files/16567948/Transactions_202408091704.2.xlsx)

**Comment by shelleydoljack** [comment]
Done in prod. @scanedastanford

**Comment by scanedastanford** [comment]
Thank you! It looks correct now, the budget totals all match the transactions.

I will continue to review the budget until rollover, in case errors pop up from now until then. If there are any, should I add them here, or create a new ticket?

**Comment by shelleydoljack** [comment]
@scanedastanford Let's create a new ticket if needed. Maybe in the FOLIO support jira so that we aren't exposing info to the public.
