### ISSUE TITLE
Add two new IPs to access okapi for Caiasoft

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#673]
Need to add two IPs for access to okapi-prod and okapi-test

These are for one other Caiasoft developer
52.9.21.118
54.153.8.197

**Comment by jgreben** [comment]
Added with https://github.com/sul-dlss/folio-k8s/pull/244

After merging upgrade okapi deployments with helm -n ${namespace} upgrade -f okapi/resources.yaml -f okapi/overrides-${namespace}.yaml -f allowed-ips-${namespace}.yaml okapi okapi-folio-sul/okapi
