### ISSUE TITLE
Post rollover cleanup - Lane and Law

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#675]
Run same process as #662 to remove FY24 encumbrances for Lane and Law. I've attached the list provided by @trapido. Irina can you please confirm this is the correct list to use? 
@shelleydoljack let me know when you think you want to run this and I'll let Lane and Law know. Do you want to run on stage first or straight to production? [fyro_pol_encumbrances_in_prev_fy.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzMxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1269c08699b66a6035d8f5522471ee656228f107/fyro_pol_encumbrances_in_prev_fy.xlsx)

**Comment by shelleydoljack** [comment]
I'll run it in stage first. Do they want test too so they can see in metadb?

**Comment by shelleydoljack** [comment]
Started running on stage at 10:30am PDT.

**Comment by ahafele** [comment]
Awesome, yes please run on test also.

**Comment by shelleydoljack** [comment]
Stage finished at 12:06pm PDT. Started test at 12:26pm PDT.

**Comment by shelleydoljack** [comment]
Test finished at 9/23/24 6:30pm PDT

**Comment by ahafele** [comment]
Lane is ready. Waiting on Law's data review still. 
@shelleydoljack was Business done in your test since they were included in the spreadsheet?

**Comment by shelleydoljack** [comment]
I did all that were in the spreadsheet. Since stage took 2 hours and test took 6, prod will either take 2 or 6 hours to run 🤣 so I can start it in the evening to run overnight. Either way, let's wait until everybody reviewed/approved. Sound good?

**Comment by ahafele** [comment]
Sounds good! I'll comment here when I have the green light from all.

**Comment by ahafele** [comment]
You can go ahead and run on production.

**Comment by shelleydoljack** [comment]
Ok. I'll start it tonight. It looks like the DAGs for fix encumbrances and ap payment reports won't interfere. Not sure if I'm forgetting anything else.

**Comment by shelleydoljack** [comment]
Started prod at 8:24pm PDT.

**Comment by shelleydoljack** [comment]
Prod finished Wed Sep 25 10:37:26 PM PDT 2024.
