### ISSUE TITLE
Upgrade folio-dev and folio-test to Poppy CSP 6

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/FOLIO-Project-Stanford#677]
[Upgrade Checklist](https://docs.google.com/spreadsheets/d/1Ol4Qo_PcVI7To95g8P4aicVOstLJpITHmeHCjQMrPfE/edit?usp=sharing)

**Comment by shelleydoljack** [comment]
folio-dev is at CSP 6. Many issues with folio-test to CSP 6 so it is at CSP 3.

**Comment by jgreben** [comment]
Moving on to CSP7
