### ISSUE TITLE
Create workgroup for access to digital bookplates UI

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/FOLIO-Project-Stanford#680]
Access to the digital bookplates UI in libsys-airflow should be granted through a workgroup, similar to VMA. @ahafele who should have access to the UI?

**Comment by ahafele** [comment]
For now it should just be
Libsys
Suzette
Linh
Ryan at law
If you could make me an administrator then I will add additional people to the work group as needed.

**Comment by shelleydoljack** [comment]
@dlrueda I'm assigning to you. When I go to [workgroup manager](https://workgroup.stanford.edu) and click on create workgroup, the screen I see has a drop-down to select a stem and the only stem I see is `~sdoljack`. I assume group name part A is supposed to be "sulair" or "sul" or "dlss".
![Screenshot 2024-10-09 at 2 04 54 PM](https://github.com/user-attachments/assets/9970609c-9ca2-47cb-a421-3b9adb34bbf4)
The VMA workgroup is called `sulair:libsys-vendor-managers`. I think we do something similar for bookplates? `sulair:libsys-bookplates`.

**Comment by dlrueda** [comment]
well, turns out I don't have any options under stems either.  I wonder who made the one for VMA?  @jermnelson any idea?

**Comment by dlrueda** [comment]
dlss:appteam is the "Libsys" workgroup to add to this once it's made

**Comment by dlrueda** [comment]
diss:appteam can be administrators.  If can't assign that workgroup, then ahafele and dlrueda.

Name of new workgroup sulair:libsys-dig-bookplates

**Comment by kamchan** [comment]
New workgroup sulair:libsys-dig-bookplates has been created.  I've added dlss:appteam as the administrator so anyone in dlss:appteam should be able to manage and add users.  Please let me know if there are any questions.  thanks

**Comment by dlrueda** [comment]
I added Ryan T, Suzette, and Linh.
