### ISSUE TITLE
Request to delete Encumbrance IDs

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#682]
https://jirasul.stanford.edu/jira/projects/FOLIO/issues/FOLIO-271

**Comment by jgreben** [comment]
I tested doing this on folio-dev:

In the database:
`update sul_mod_finance_storage.transaction set jsonb = jsonb - 'paymentEncumbranceId' where id in ('38e04050-f49c-46f5-ac2e-2f63825277d5', 'b431e0a6-e7f3-4e78-9d0c-532e97301ba8', 'c61a6d6f-0524-4f4e-a815-2ae36bccce13', 'dcb35103-bed2-4cc1-a515-79d61ab3f898', '77de39d3-2869-49c2-991f-a9cd83707b20', 'cfe46914-f7e7-40c9-9063-7c88265c3928');`

Then I cancelled the invoice `6202024-01A` successfully using the client.

I will go ahead and run the database update on production.

**Comment by jgreben** [comment]
This is done on the folio-prod database. Suzette can go ahead and cancel the invoice with the client.

**Comment by ahafele** [comment]
Updated JIRA ticket. Closing this one. Thanks @jgreben !
