### ISSUE TITLE
Two email for Fix encumbrance both say 2025

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#685]
For the last couple weeks, I see two emails each with subject line LAW 2025 and two for LANE 2025.

The logs in those emails have different numbers in them.  I suspect that one of the runs is really for FY 2024?  Or is the first run failing and we try one more time and end up with two emails?

**Comment by jgreben** [comment]
This probably happened because the failed DAG run retries one time when it fails.

**Comment by jgreben** [comment]
The duplicate one was actually from airflow-dev. I paused the DAG on airflow-dev and airflow-stage. Working on a different subject line for prod/non-prod.

**Comment by jgreben** [comment]
Fixed by https://github.com/sul-dlss/libsys-airflow/pull/1399
