### ISSUE TITLE
Run digital_bookplate_instances DAG with config for new funds lacking required data

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/FOLIO-Project-Stanford#687]
8 funds in the SDR DigitalBookplate collection did not have display Label "Symphony Fund Name" in the public Cocina, so the digital_bookplate_instances DAG did not get triggered for them. Andrew is fixing the data in SDR. Meanwhile, we can run digital_bookplate_instances with a configuration that has the fund data needed to find instances paid in folio on these funds and trigger the add 979 dag for them. Here is the config to trigger the dag: [digbkplate_redo_funds_conf.json](https://github.com/user-attachments/files/17624836/digbkplate_redo_funds_conf.json)

**Comment by shelleydoljack** [comment]
Running on sul-libsys-airflow-dev.

**Comment by shelleydoljack** [comment]
It took ~10 minutes to run both digital_bookplate_instances and digital_bookplate_979s for airflow-dev. Andrew is going to fix the filenames for the ones that have the duplicated .jp2 file extension. Wait until he does that before running in stage and prod (and need to update the funds conf json).

**Comment by shelleydoljack** [comment]
Andrew fixed the data in SDR. The plan is to manually trigger fetch_digital_bookplates today so that when digital_bookplate_instances runs tomorrow at 2am it has the updated data. Also manually trigger digital_bookplate_instances the fund conf json today to get the 8 missing populated.

**Comment by shelleydoljack** [comment]
Updated funds conf: [digbkplate_redo_funds_conf.json](https://github.com/user-attachments/files/17636654/digbkplate_redo_funds_conf.json)

**Comment by shelleydoljack** [comment]
Manual dag run for fetch_digital_bookplates: https://sul-libsys-airflow-prod.stanford.edu/dags/fetch_digital_bookplates/grid?run_id=manual__2024-11-05T18:02:14.829056%2B00:00&execution_date=2024-11-05+18:02:14.829056%2B00:00&tab=graph&dag_run_id=manual__2024-11-05T18:02:14.829056%2B00:00

**Comment by shelleydoljack** [comment]
Dag run triggered for the updated funds: https://sul-libsys-airflow-prod.stanford.edu/dags/digital_bookplate_instances/grid?dag_run_id=manual__2024-11-05T13%3A38%3A54-07%3A00

**Comment by shelleydoljack** [comment]
add 979s completed. 5 add_marc_tags_to_record tasks completed as False (so didn't add 979s). See https://sul-libsys-airflow-prod.stanford.edu/xcom/list/?_flt_0_task_id=add_marc_tags_to_record&_flt_0_run_id=manual__2024-11-05&_oc_XComModelView=value&_od_XComModelView=asc for the ones with return_value False and you can click on the Task Id to get to the Log of the task instance to see which Instance Id.

FYI @dlrueda @ahafele

**Comment by ahafele** [comment]
Thanks so much @shelleydoljack!! 
@dlrueda do you want to respond to Sonia since you've been leading the convo?

**Comment by dlrueda** [comment]
Sent email to Sonia et all
