### ISSUE TITLE
How do we handle location SHADOW in FOLIO?

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#69]
Libraries use this as home (or current) location in Symphony for all sorts of reasons, with the desired end result that the record is not exported to SearchWorks.

This is a shadowed location in Symphony.

Not sure there is such a thing as a shadowed location in FOLIO?  There is a suppress from discovery checkbox.

Will we be able to limit on location easily for the SW export in the same way? Will we keep the location SHADOW but for them all, activate the suppress checkbox?

**Comment by ahafele** [comment]
Related to #48

**Comment by ahafele** [comment]
Options in FOLIO that could be used for some of the current shadowed uses 
- Suppress from discovery checkbox
- Status of In Process (non-requestable) or Unavailable
- create a "shadow" FOLIO location for each Library and suppress all from export to SW
- ...
In #48 we are gathering a list of all examples and will ask stakeholders about whether or not to migrate, then will need to decide how to handle each circumstance. 

Closing this ticket.
