### ISSUE TITLE
Identify acquisitions requirements for an ILS

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#7]
Gather acquisitions requirements for an ILS

(already pretty much done by Acq group, so just add doc to Libsys FOLIO drive)

**Comment by shelleydoljack** [comment]
Documented in https://docs.google.com/spreadsheets/d/1CKcoRsHnhO2c6-I61T0gDG9cN2BUYZnKNdU8eCnL3tU/edit#gid=0
