### ISSUE TITLE
How do we handle location BASECALLNUM in FOLIO?

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#70]
We use home location BASECALLNUM in Symphony for serial records, to attach the order record to.  

In Symphony, order record is attached to a call number.  We wanted a call number that was not for a specific volume/item, because if the volume/item was changed, e.g., needed to be transferred or withdrawn, it would strand the order.

How do we attach an order to a bib record in FOLIO?  Does it attach to a call number?  Do we need BASECALLNUM in FOLIO?

**Comment by shelleydoljack** [comment]
Look at this [ER diagram for orders](https://wiki.folio.org/display/ACQ/Acquisitions+Orders+Module?preview=/1416170/14454299/FOLIO_Acq_Orders_ERD_v5%20(1).png)

The order does not have a link to instance or item. The orderline has an instanceId in it (not shown in the ER diagram but it is in the [json schema](https://s3.amazonaws.com/foliodocs/api/mod-orders/p/order.html#orders_composite_orders_post)).

The orderline also has a location object, which has a locationId and holdingsId:
```
"locations": {
     "description": "a list of the location records for this purchase order line",
     "id": "locations",
     "type": "array",
     "items": {
          "description": "The location details",
          "type": "object",
          "$schema": "http://json-schema.org/draft-04/schema#",
          "properties": {
              "locationId": {
              "description": "UUID of the (inventory) location record",
              "type": "string",
               "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
           },
           "holdingId": {
              "description": "Holding UUID associated with order line",
              "type": "string",
              "$schema": "http://json-schema.org/draft-04/schema#",
              "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
           },
           "quantity": {
              "description": "combined/total quanitity of physical and electronic items",
               "type": "integer"
            },
           "quantityElectronic": {
              "description": "quantity of electronic items",
              "type": "integer"
           },
           "quantityPhysical": {
              "description": "quantity of physical items",
              "type": "integer"
            }
       },
      "additionalProperties": false
   }
}
```

**Comment by ahafele** [comment]
Discussed in [Metadata Subgroup](https://docs.google.com/document/d/1oF_EcPV20-Rt_w_mZoU4ULAMkz8rJNMezAgxwELfaLI/edit#bookmark=id.vzolordptudg) and with Linh. Since Orders link to Instances (or can link) we don't need this dummy item. The holdings record itself will contain the base call number. Need to confirm with Acq what to do with item notes on the basecallnum item. 
See example: 10727685 (in both symphony and folio-test)

**Comment by ahafele** [comment]
Linh would like to know if it is possible to move this info into the POL Receiving Note. Maybe this should be part of the serials check-in history etc. work? Will also discuss with acq subgroup. More to come....

**Comment by ahafele** [comment]
There is a portion of the extended info item notes that acq wants preserved from the basecallnum items. This is similar to the issue with bound-with items we plan to abandon. We need a strategy for moving these to the holdings or another item. Or we could just keep the items.

**Comment by ahafele** [comment]
Moved remaining issue to #359
