### ISSUE TITLE
How do we handle location INPROCESS in FOLIO?

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#71]
The location INPROCESS is used in both current and home locations in Symphony.

General workflow for a book that’s been received is to create the item with the final home location, and edit current location to INPROCESS.  When it arrives at the shelving location, current location is updated to be home location.

But home location INPROCESS is also used, especially for items destined for SAL3.

Will we still use a location to track INPROCESS status?  or items that are uncatalogued in SAL3 (or another cataloging unit)?

**Comment by shelleydoljack** [comment]
There are a few item statuses that we may want to use for INPROCESS items, depending on the SAL3 thing. There are these statuses in Folio: In process, In process (non-requestable), In transit. See https://docs.google.com/spreadsheets/d/1QOFKqenPqMSOtsEODUVc9ILZQCViW4dHMfJSANYKg8U/edit?usp=sharing . 

General workflow for a book may be the status is updated to "Available" once it gets to its final shelving location. I think the same status for items destined for SAL3: "Available". Items uncataloged in SAL3 might be "In process (non-requestable)."
