### ISSUE TITLE
How do we handle location MISSING in FOLIO?

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#73]
Normal procedure is to leave home location as is, and charge the item out to a xxx-MISSING pseudo patron.  Current location of those xxx-MISSING users is MISSING.

How is this handle in FOLIO?  Same way, with charges to pseudo patrons?  Still have a “location” of MISSING that needs to be created for each library?

**Comment by shelleydoljack** [comment]
Missing is an item status in FOLIO. From the item status documentation (draft):
- The item is not on loan to a patron and cannot be found. This status is generally used if the library is still searching for the item or waiting to see if it reappears.
- An item can be marked *Missing* through the Inventory or Data import apps.
- A *Missing* item can be checked out to a patron; FOLIO shows a warning to the staff member, and then allows the checkout if the staff member confirms they want to continue. When the checkout occurs, the item status changes to *Checked out*.
- A *Missing* item can be placed on hold; it cannot be recalled or paged.

**Comment by dlrueda** [comment]
So, we’ll do with item status, not a checkout to a “missing” pseudo patron.
