### ISSUE TITLE
How do we set the status or temporary loc for an item during load?

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#75]
Does status get explicitly set?

Is status different than effective location?  Does it get calculated from location information?

How do we trigger it to make it do that calculation?

On load, we set the permanent location in the holdings from the Symphony home location.  What about current location when it’s different?  Do we assign that to temporary location?  What about if it was charged out in Symphony (current location would be CHECKEDOUT, SUL-BIND, REPAIR, etc), do we still want to update the temporary location?

Do we “set a status” or does it get set from temporary location, or when we load charges after holdings/items?

https://wiki.folio.org/display/FOLIOtips/Circulation+Interactions+Allowed+By+Item+Status

**Comment by shelleydoljack** [comment]
See consul page [Item State](https://wiki.folio.org/display/FOLIOtips/Item+State+in+FOLIO) for information related to [Circulation Interactions Allowed By Item Status](https://wiki.folio.org/display/FOLIOtips/Circulation+Interactions+Allowed+By+Item+Status).

[Holdings and Items Effective Location Logic in FOLIO](https://wiki.folio.org/display/FOLIOtips/Holdings+and+Items+Effective+Location+Logic+in+FOLIO) needs review too.

**Comment by shelleydoljack** [comment]
Do not set Holdings Effective Location or Item Effective location when loading records. It is a value computed by FOLIO.

Holdings Effective Location
> It has no influence on circulation behavior. As of Juniper, it does not appear in the FOLIO UI - only in the underlying data.
> This value is computed by FOLIO as the first value it finds in the following list:
> - Holdings temporary location
> - Holdings permanent location

Item Effective Location
> FOLIO sets the item effective location to the first location value it finds, going down this list in order:
> -  Item temporary location
> -  Item permanent location
> -  Holding temporary location
> -  Holding permanent location

Set item status given these values: https://github.com/folio-org/mod-inventory-storage/blob/91e3590d9139887d624436be14a3cd32c89ea3e8/ramls/item.json#L245-L275

Maybe we create a map for the Symphony current locations that infer item status to these ^^ values and when loading items, we set the item status that way. Looks like we relate the itemID for a loan in the loan record (see required fields itemId, loanDate, and action at https://github.com/folio-org/mod-circulation-storage/blob/master/ramls/loan.json).

**Comment by shelleydoljack** [comment]
Some good descriptions for temp/permanent holdings/item locations at https://wiki.folio.org/pages/viewpage.action?pageId=54888358:

Item Metadata Elements | Description | Repeatable | Required
-- | -- | -- | --
Permanent holdings location |Defined in Settings > Inventory > Item > Loantype | NR | N
Temporary holdings location |  Defined in Settings > Inventory > Item > Loantype | NR | N
Temporary item location |Temporary item location is the temporarily location, shelving location, or holding which is a physical place where items are stored, or an Online location. The location is defined by Institutions, Campuses, libraries, and locations. Permanent location can be assigned at the holding level, and be overridden at the item level if needed |NR | N
Permanent item location | Permanent item location is the default location, shelving location, or holding which is a physical place where items are stored, or an Online location. The location is defined by Institutions, Campuses, libraries, and locations. Permanent location can be assigned at the holding level, and be overridden at the item level if needed |NR | N

**Comment by shelleydoljack** [comment]
Started a mapping spreadsheet for Symphony locations > item statuses and item temporary locations.
https://docs.google.com/spreadsheets/d/1QOFKqenPqMSOtsEODUVc9ILZQCViW4dHMfJSANYKg8U/edit?usp=sharing

**Comment by shelleydoljack** [comment]
Decision doc regarding [Permanent/Temporary/Status/Holdings loc vs. item loc](https://docs.google.com/document/d/1csvryV1yKfi1XcBl6i_Re7YUpFWEOb4sCagSDE6PGLo/edit?usp=sharing)

**Comment by jgreben** [comment]
@dlrueda you are reviewing the spreadsheet, yes?

**Comment by dlrueda** [comment]
I reviewed the spreadsheet, added a few temporary locations that have been made.  

I think, with all the good research Shelley did here that our strategy should be:
Set item status based on item current location, according to spreadsheet.  We can tweak it later.  If spreadsheet specifies a temporary location, set hat in FOLIO item, otherwise leave it blank.

@shelleydoljack if you agree we’re ready to make a mapping (I hope so), maybe you and Jeremy can make one for item status/temploc?  I didn’t make a ticket for it, but you can.

**Comment by dlrueda** [comment]
and @shelleydoljack  you can close this too, if you think we’re good

**Comment by shelleydoljack** [comment]
Updated mapping file in PR with latest data from spreadsheet: https://github.com/sul-dlss/folio_migration/pull/5
