### ISSUE TITLE
Add a MIGRATION-ERR location for all libraries

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#76]
Do on both .tsv in GitHub and settings spreadsheet in FOLIO Implementation drive

**Comment by jermnelson** [comment]
Discovered last night we also need a more general MIGRATION-ERR location not specific to a library or location.

**Comment by dlrueda** [comment]
Do we need this INSTEAD of the library-specific MIGRATE-ERR location?  (I would be happy if the answer is yes!)

**Comment by dlrueda** [comment]
and how do we make this?  Normally a location is built after selecting a library.  Not sure how to create a location without a library

**Comment by jermnelson** [comment]
I think we can move to just a single `MIGRATION-ERR` location. Maybe we can associate the location with Green but know that this is the most general case.
