### ISSUE TITLE
Select UNEXPIRED users from Symphony, load to FOLIO

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#77]
Use seluser to find unexpired users in those categories.  Retrieve UnivID and add to registry load.

Might want to chunk it up 

Depends on https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/80

**Comment by jgreben** [comment]
expired date = NEVER for CNF, CNS, CNAC

there MIGHT be some users with these profiles that have expire date > TODAY but I’d be surprised

**Comment by dlrueda** [comment]
example seluser: seluser -e">TODAY" -pCNF

**Comment by dlrueda** [comment]
REU, REG, RED should do the seluser for -e”>=TODAY”

**Comment by dlrueda** [comment]
put script in /s/SUL/Bin/folio_symphony_extract

**Comment by dlrueda** [comment]
Final list of profiles to look for:
CNF,CNS,CNAC,REU,RED,REG,MXAC,MXF,MXAS,MXAS-6LMT,MXAS-25LMT,MXAS-BDRCT,MXD,MXFEE,MXS,LAWFEE,MXALUM-LAW,MXFEE-BUS

Create script to select UNEXPIRED users with these profiles.
Script will need two calls to seluser (each call uses same -p list of profiles), but different -e criteria:
-e”>TODAY”
and
-e”NEVER”

(Most CNF,CNS,CNAC are NEVER, but there are a few users with those profiles that do have an actual expire date, so need to look for both -e flavors)

Output UnivID, which is the Symphony “alt_ID” field (-E flag)

Harvest these UnivIDs from the registry and load to FOLIO
