### ISSUE TITLE
How do we handle new book shelf in FOLIO?

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#79]
charge out?  location?

There are branches that do both right now.

Charge out to new book pseudo patron ...  The pseudo patron has a curloc of NEWBOOK. If it gets charged to a user it’s a double-charge.  When returned, WFs tells staff to route back to “NEWBOOK” location.

Location.... only current location gets changed.  If user charges it out, upon return it is routed to its home location

How should it be implemented in FOLIO?
For circ subgroup to handle I think?

**Comment by ahafele** [comment]
Some related slack convo - https://folio-project.slack.com/archives/CAM25LTGV/p1631635759032200

**Comment by dlrueda** [comment]
Above slack looks like consensus in Sept 2021 was to have a temporary location of New Book Shelf.

Cornell said they used to use a pseudo patron, but that was confusing for users and desk staff.

Mark Arnold of Missouri State is debugging an app he wrote to add and then delete various item notes e.g. “New Book Ingest” with dates, check in note, new book note.  I think this is their way of tracking new books?

Having a “new book” status was discussed, but there isn’t currently (as of Sept 2021 at least) a way to create custom status.

Ann-Marie confirmed a temp location is a common way to handle it, with physical sticker indicating NBS.  “You could also include a Statistical code like **New Book Shelf Sept 2021** and then use that code to identify all the older NBS titles after 6 months, and update the item to remove the temp loc and the Stat code

**Comment by shelleydoljack** [comment]
Temporary location does seem right. But how does it get updated, through a circulation transaction or we just update the field in folio?

**Comment by dlrueda** [comment]
Manually update of the temporary location is required, even if item is checked out while in that temporary location.  When item is checked back in, location reverts to temporary location, status reverts to available.  

Most places add a note saying when they put the item on the new book shelf, and run reports off the date in the note to remove after x amount of time.  Mark Arnold’s app allows a scan of an itemID to update the temporary location and the note. He said in late March ’22 that he was working to make the “app” generic enough to be useful for all.
