### ISSUE TITLE
Load locations from locations-new spreadsheet to folio-test.dev, folio.dev

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#82]
all locations from locations-new spreadsheet need to be added to folio-test.dev.

This is for locations for Rumsey and Tanner, plus the MIGRATE-ERR locations.

Also need to catch up on folio.dev, there are some locations  in the main locations spreadsheet that were not loaded to folio.dev from previous load

**Comment by dlrueda** [comment]
After loaded, please move these lines to the main locations spreadsheet

**Comment by dlrueda** [comment]
Lane locations are also included in locations-new spreadsheet to load to folio-test.dev and folio.dev

**Comment by jermnelson** [comment]
Here is the current list of location codes on folio-dev:

BUSINESS-STACKS
SCIENCE-SHELBYTITL
BUS-COMPF
BUS-LOCKED
BUS-TP
BUS-PER
GREEN-IC
HILA-RR
SCIENCE-STACKS
BUS-TEMP
BUS-INSTRUCTOR
BUS-MEDIA
BUS-NEWS-STKS
GREEN-STACKS
LANE-STACKS
BUS-IRONMT
BUS-PERMRES
BUS-REF
EDU-CURRICULUM
EDU-STACKS
BUSINESS-CAREER
SCIENCE-SHELBYSER
EDU-CURRSTOR
EDU-INSTRUCTOR
EDU-LOCKED
EDU-MICROTEXT
EDU-REF
KU/CC/DI/A
KU/CC/DI/M
KU/CC/DI/O
KU/CC/DI/P
E
KU/CC/DI/2
BUS-ATCIRCDESK
BUS-ARCH
ARS-FOLIO
ARS-LOCKED
ARS-RECORDINGS
ARS-REF
ARS-STACKS
ENG-EQUIPMENT
ENG-INSTRUCTOR
ENG-PERMRES
ENG-SCIFI
ENG-PER
ENG-STACKS
ENG-STK-NONCIRC
ENG-TERM-COLL
ENG-TIMO-COLL
EDU-MIGRATE-ERR

**Comment by dlrueda** [comment]
Need to remove the initial locations that were created on folio.dev as well (some Business, etc.). The ones to remove are in above comment
BUSINESS-STACKS
SCIENCE-SHELBYTITL
GREEN-IC
HILA-RR
SCIENCE-STACKS
BUSINESS-CAREER
SCIENCE-SHELBYSER

Dunno about these. These were default ref data.  Not sure about the E, is that real?
KU/CC/DI/A
KU/CC/DI/M
KU/CC/DI/O
KU/CC/DI/P
E

**Comment by shelleydoljack** [comment]
the KU* are for diku tenant, i think. not sure about E. i'll run a delete and load and see what happens.
