### ISSUE TITLE
Create permission sets for various levels of unit/staff activity

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/FOLIO-Project-Stanford#83]
Now that SSO is working, we should be importing all staff records from the registry. We now need to create permission sets for various levels of staff, scoped to the functions that they need based on their role ands and units.

**Comment by dlrueda** [comment]
Darsi to convene a task group for this

**Comment by shelleydoljack** [comment]
Good starting point:[Guides to FOLIO Permissions](https://wiki.folio.org/display/FOLIOtips/Guides+to+FOLIO+Permissions)

We also need to figure out how acq units are getting assigned in conjunction with this.

**Comment by shelleydoljack** [comment]
I started a folder for keeping notes in for the new task group: https://drive.google.com/drive/folders/16d_auaD7FUBwzcGQH6tfw7b3LfDec4Uz

**Comment by shelleydoljack** [comment]
Maybe we fork this repo https://github.com/folio-org/folio-tools/tree/master/add-users and modify the pset json files to the specifications that the task group creates. We can use the users that are created with the add-users.js script in the cypress tests.

**Comment by jgreben** [comment]
Permissions subgroup is working on this.

**Comment by jgreben** [comment]
There are now 25 permission sets and a task to migrate them from one instance to another. If there need to be additional permission sets added as an ongoing matter, future tickets should be created.
