### ISSUE TITLE
Select subset of EXPIRED users from Symphony, load to FOLIO

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#84]
Note well, this is a DIFFERENT SCRIPT than #77

This is for EXPIRED users.  We will run both scripts for each new test instance, and for the production instance.

Summary of users to select:
After finding expired users, select those
* with charges
* with bills with balance >0.00 and bill reasons LOST,LOST-CLAIM (-r flag)

**Comment by dlrueda** [comment]
Select for these profiles:
CNF,CNS,CNAC,REU,RED,REG,MXAC,MXF,MXAS,MXAS-6LMT,MXAS-25LMT,MXAS-BDRCT,MXD,MXFEE,MXS,LAWFEE,MXALUM-LAW,MXFEE-BUS

-e expire date in the past, e.g., -e”<20220207”

For subsequent selbill selection, -b”>0.00” -r”LOST,LOST-CLAIM”

For charges, seluser -c”>0”

No selection needed for holds, we will NOT import an expired user to FOLIO just for an attached hold.

**Comment by dlrueda** [comment]
Output the -E flag, Symphony’s alt ID, which is the UnivID.

Attempt to harvest from the registry.  
Figure out which no longer have an XML document, meaning we cannot get from the registry (we’ll have to extract data from Symphony, create the json, and load to FOLIO -- will be in separate ticket)

**Comment by jgreben** [comment]
Do you mean `CLAIM-LOST`? When I use `LOST-CLAIM` I get `**Policy does not existLOST-CLAIM -rLOST,LOST-CLAIM`

**Comment by dlrueda** [comment]
Ugh, sorry, yes, I meant `CLAIM-LOST`
