### ISSUE TITLE
Investigate potential to use workgroups to manage permission sets in FOLIO

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#86]
Look into what EXISTING workgroups can do for us.  

If we have to create workgroups, I don’t think that gains us much, we can have a set of Google docs with staff lists instead?

If existing workgroups would work, can we create process to assign correct permission sets?

**Comment by shelleydoljack** [comment]
There are a lot of workgroups that begin with `sul*`. There are some `sul:acq-*` and `sul_acquisitions:*` groups that mind lend itself to folio roles. SUL has workgroups like `sul:*`, `dlss:*`, `sdr:*`. Some `lane:*` workgroups looks promising. There are `law:libstaff` and `law:libsups` workgroups. There are some `gsb-library:*` groups. I'm not sure any of the existing workgroups would lend themselves well to be used by folio. Some are used for shared email accounts or access to folders. It would probably be easier for managers to add permission sets for their users in folio than to manage them in workgroup and rely on mapping (and updating the mapping when/if permissions change) that data from the registry to the folio user load.

**Comment by shelleydoljack** [comment]
Permission sets and Stanford Workgroups pros/cons discussion document: https://docs.google.com/document/d/1iZ7Twe3ECRdmiYST9DxCgJ_yb_yPHKO8G2IVTP32z9Q/edit?usp=sharing

**Comment by dlrueda** [comment]
Determined in subgroup that creating all these work groups and managing FOLIO staff permissions with them doesn’t gain enough to make it practical.
