### ISSUE TITLE
Is there an equivalent of an override in FOLIO?

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#88]
In Symphony, if logged in as say a student account, a staff member will see a prompt for an override when attempting a function the student login is not allowed to do.  Enter the override, then proceed with that function.

Does FOLIO have something like this?

**Comment by ahafele** [comment]
Yes, for some circulation functions - e.g. permission=circulation.override-patron-block  permission=circulation.override-item-block. 
I'm not finding anything like this for the other apps.

**Comment by shelleydoljack** [comment]
Status in FOLIO: not developed; Jira issue: https://issues.folio.org/browse/UXPROD-2645
