### ISSUE TITLE
Create permission set for a tenant-wide administrator

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#89]
Can start with folio-tools/add-users repo: 
https://github.com/folio-org/folio-tools/tree/master/add-users

**Comment by dlrueda** [comment]
Or can review in FOLIO Snapshot, where they are prefixed with “Role” (Login: diku_admin / admin; Latest snapshot: https://folio-snapshot.dev.folio.org/) 

More info about this starter set: https://wiki.folio.org/display/FOLIOtips/Using+Sample+Role-Based+Permission+Sets+on+the+Reference+environments

**Comment by shelleydoljack** [comment]
I think it depends on the definition of administrator. Is "admin" for system administration or admin for certain apps in the system? "System admin" permission set should have all permissions. "<FOLIO app> admin" should have all permissions for that FOLIO app and then some, depending. People assigned to "<FOLIO app> admin" should have regular meetings/coordination with system admin folks.

**Comment by dlrueda** [comment]
Look at Sul_admin superuser’s permission set (it isn’t in the UI, need the api endpoint).  Which ones does this user NOT need, take them out and put them in a text file, write a script to create that permission set.  Then can assign this permission set to those that are going to be highest level FOLIO app admin.

**Comment by dlrueda** [comment]
Agree that “admin” permission set should just have all permissions.  OK to close this.
