### ISSUE TITLE
Add sel to get the csv for holdings and items to marc export

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/FOLIO-Project-Stanford#90]
Also need to figure out how to get the item xtended info notes out and which ones are want.

**Comment by shelleydoljack** [comment]
`echo 3195771 | trs selcallnum -iC -oKCpBZ | trs selitem -iN -oSBylmZ.9990.Z.9998.Z.9996.Z.9997.Z.9000.`
Currently only grabs one techstaff note even though there are multiple.
```
3195771|DEWEYPER|550.6 .U58O|78-741|36105018958574  |EARTH-SCI|STACKS|STACKS|||i:vct|||
3195771|DEWEYPER|550.6 .U58O|78-742|36105018958582  |EARTH-SCI|STACKS|STACKS|||i:vct|||
3195771|DEWEYPER|550.6 .U58O|78-743X|36105018958590X |EARTH-SCI|WITHDRAWN|WITHDRAWN|||Item moved to analytic record, 10/20 jmc.|||
3195771|DEWEYPER|550.6 .U58O|78-744|36105018958608  |EARTH-SCI|STACKS|STACKS|||i:vct|||
```

**Comment by shelleydoljack** [comment]
CIRCNOTE = 9990
PUBLIC = 9998
TECHSTAFF = 9996
CIRCSTAFF = 9997
HVSHELFLOC = 9000

**Comment by dlrueda** [comment]
csv generated.  columns are:

catkey,call # type, base call number,volume info, barcode,library,homelocation,currentlocation,item type
