### ISSUE TITLE
How do we get all of the item extended info values (if there are more than one TECHSTAFF, for instance)

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/FOLIO-Project-Stanford#91]

**Comment by shelleydoljack** [comment]
Per https://api.sdusers.net/wiki/index.php/Selitem:

> -oZ: This option uses the [VED entry number](https://api.sdusers.net/wiki/index.php/VED_Entry_Numbers#Item_Extended_Info) to specify which fields to output, e.g. selitem -oZ.9998. to output a PUBLIC note. Note that if there are more than one of the specified note type in a record, only the first of each specified type will be included in the output.

**Comment by shelleydoljack** [comment]
We can use veddump to get the itemxinfo records out:
`echo 3195771 | trs selcallnum -iC -oKCpBZ | trs selitem -iN -ok | trs veddump -aitemxinfo -fITEMXINFO -oITEMXINFO`
```
*** DOCUMENT BOUNDARY ***
FORM=ITEMXINFO
.TECHSTAFF. i:vct
.TECHSTAFF. For holdings consult Branner Library see 940 note
```

**Comment by shelleydoljack** [comment]
And here's how to do it with pipe-delimited output (although you get duplicate data for each row where there are multiple TECHSTAFF notes:
`echo 3195771 | trs selcallnum -iC -oKCpBZ | trs selitem -iN -oKSBylm | trs selved -fITEMXINFO -iV -oSed`
```
3195771|DEWEYPER|550.6 .U58O|80-996|36105018953609  |EARTH-SCI|STACKS|STACKS|TECHSTAFF|ENTRY>i:vct<ENTRY|
3195771|DEWEYPER|550.6 .U58O|80-996|36105018953609  |EARTH-SCI|STACKS|STACKS|TECHSTAFF|ENTRY>For holdings consult Branner Library see 940 note<ENTRY|
3195771|DEWEYPER|550.6 .U58O|80-997|36105018954284  |EARTH-SCI|STACKS|STACKS|TECHSTAFF|ENTRY>i:vct<ENTRY|
3195771|DEWEYPER|550.6 .U58O|80-997|36105018954284  |EARTH-SCI|STACKS|STACKS|TECHSTAFF|ENTRY>For holdings consult Branner Library see 940 note<ENTRY|
3195771|DEWEYPER|550.6 .U58O|80-998|36105018954250  |EARTH-SCI|STACKS|STACKS|TECHSTAFF|ENTRY>i:vct<ENTRY|
3195771|DEWEYPER|550.6 .U58O|80-998|36105018954250  |EARTH-SCI|STACKS|STACKS|TECHSTAFF|ENTRY>For holdings consult Branner Library see 940 note<ENTRY|
```

**Comment by shelleydoljack** [comment]
Lastly, maybe put the ved data in a JSON object for "easy" digestion?:
`echo 3195771 | trs selcallnum -iC -oKCpBZ | trs selitem -iN -oKSBylm | trs selved -fITEMXINFO -iV -oSM`
```
3195771|DEWEYPER|550.6 .U58O|80-996|36105018953609  |EARTH-SCI|STACKS|STACKS|{"TECHSTAFF":[{"A":1,"D":"i:vct","I":"","X":0},{"A":2,"D":"For holdings consult Branner Library see 940 note","I":"","X":1}]}|
```

**Comment by dlrueda** [comment]
Add -oB to selitem output with veddump:
`echo 3195771 | trs selcallnum -iC -oKCpBZ | trs selitem -iN -okB | trs veddump -aitemxinfo -fITEMXINFO -lITEM_ID -oITEMXINFO`
to get ITEM_ID as part of output
```
*** DOCUMENT BOUNDARY ***
FORM=ITEMXINFO
.ITEM_ID. 36105018954284  
.TECHSTAFF. i:vct
.TECHSTAFF. For holdings consult Branner Library see 940 note

*** DOCUMENT BOUNDARY ***
FORM=ITEMXINFO
.ITEM_ID. 36105018954250  
.TECHSTAFF. i:vct
.TECHSTAFF. For holdings consult Branner Library see 940 note
```

**Comment by dlrueda** [comment]
Thoughts on what is best:
not veddump, too much to parse on too many lines.
If adding these notes to already-created FOLIO items as a post-item-import step, the pipe-delimited might be easiest?

If adding during import, probably json easiest if has to be done during mapping phase of airflow process

**Comment by ahafele** [comment]
Working on mapping here in #102
