### ISSUE TITLE
Generate mapping of holding code IDs to FOLIO locations (for order import)

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#93]
Suzette is beginning to look at getting data to us so we can load orders.

In Symphony, each order line has a “holding code” that contains library/home location/item type/etc.  FOLIO specifies a location.

Use our library/location mapping to map Symphony holding code -> FOLIO location in the order

**Comment by shelleydoljack** [comment]
Do we need to map the Symphony item type in the holding code to the corresponding FOLIO thingie?

**Comment by dlrueda** [comment]
The FOLIO thingie being the material type maybe?  

We should ask Suzette in the next Acq subgroup meeting, or have a separate session with her to nail down some questions.  

But also I just checked on the Lane migration spreadsheets for something resembling “material type” for order related records and didn’t see anything.  Weird.  
https://docs.google.com/spreadsheets/d/1cNINncsqNI2vY3nZh9Ri31Wq6D0nfq2EQJqE31O4Zi4/edit#gid=376854230

**Comment by shelleydoljack** [comment]
yea, I was looking at the [orderline json](https://s3.amazonaws.com/foliodocs/api/mod-orders/p/order-lines.html#orders_order_lines_post) and didn't see a material type so I guess orderlines don't have that data. 🤷

**Comment by shelleydoljack** [comment]
I put them in the spreadsheet https://docs.google.com/spreadsheets/d/19nXAJgwUjXekwEpf4iOIyA1eWcaaKIo6wSfQg8Guqo4/edit?usp=sharing .
The "holdings codes" sheet is the Symphony policy exported with an extra column E, the concatenation of library and location. The sheet "folio_migration/locations.tsv" is from https://github.com/sul-dlss/folio_migration/blob/main/mapping_files/locations.tsv , again, with an extra column that concatenates library and location. The sheet "mapping" is columns D and E from the holdings codes sheet and the third column is a VLOOKUP of the data in the locations.tsv sheet, using the library/location column as key. I still need to go through it and make sure the formula didn't mess up (it doesn't like it when the key doesn't exist in the sheet you are looking up). The problem rows/need review are highlighted in red (in progess).

**Comment by shelleydoljack** [comment]
This is ready for review now. The sheet labelled "mapping" has the holding codes in column A and the folio location in column C. The rows highlighted in red do not have a mapping because either the library/location is not done yet (e.g. SPEC, GREEN), the holding code is obsolete, or the holding code will be deprecated.

N.B. we have an EAR-READY-REF location. Can this be standardized to EAR-REF (like the others) (are REF and READY-REF different?)?

**Comment by dlrueda** [comment]
EAR-READY-REF is indeed a thing, and actually they are no longer putting anything into their plain old REFERENCE location.
(and yes I tried to convince them to use REF and not READY-REF)

**Comment by dlrueda** [comment]
I reviewed the spreadsheet as it is currently.  Some SPEC-COLL mappings have been added since it was run I think.  And we will have GREEN and MEDIA mappings soon, so we can wait to run it again.

There were maybe 3 lines that were red (aside from Spec/Green) that have a mapping (in the mapping ticket anyway #66) but maybe are not in the mapping_files/locations.tsv ? So maybe we need to fix that up slightly before running again too.

Best to wait until GREEN/MEDIA mappings are done.

**Comment by shelleydoljack** [comment]
Revisit once https://github.com/sul-dlss/folio_migration/pull/7 is resolved.

**Comment by dlrueda** [comment]
@shelleydoljack this is ready to run again.  A few updates to the mapping tsv (see above) needed first to avoid errors.  Hope what I wrote before when I reviewed it initially is clear.

**Comment by shelleydoljack** [comment]
@dlrueda I "re-ran" the spreadsheet VLOOKUP on tab 3 "mapping" using the locations.tsv file in the PR https://github.com/sul-dlss/folio_migration/pull/7 . I fixed the VLOOKUP formula so that it does an exact match and gives an error when the library_homelocation key doesn't exist. The cells highlighted in red are from the last review; I didn't change the cell coloring. For the ones where there is no folio location, my guess is we either create it or change the symphony location (and symphony holding code -> location policies in Symphony) to get the desired folio locations. But maybe those will end up in the migration error locations?

**Comment by shelleydoljack** [comment]
@dlrueda I'm getting close to needing the holding code -> folio location code mapping completed for the order migration code. I just need the `#N/A` error cells in the mapping tab filled in with a folio location code. If there isn't a folio location to map a holding code to or if it requires a lot of discussion, I could just map them to the library's error migration catch-all location.

**Comment by dlrueda** [comment]
I think you went ahead and mapped to the library’s error migration catch-all location in the case of no folio location to map to.  I think this is the right solution.

**Comment by dlrueda** [comment]
@shelleydoljack as we add more locations to FOLIO, and their mapping from Symphony to the migration locations.tsv mapping file, we will need to also add them to this Google doc?  Or a .tsv file somewhere?

**Comment by shelleydoljack** [comment]
When we add more locations to FOLIO, we need to update [the mapping spreadsheet](https://docs.google.com/spreadsheets/d/19nXAJgwUjXekwEpf4iOIyA1eWcaaKIo6wSfQg8Guqo4/edit?usp=sharing). Instructions on generating a new mapping, etc. are on a tab in the spreadsheet.
