### ISSUE TITLE
Decide how to populate Settings->Tenant->Addresses

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#94]
This is reference data, used in orders.  Suzette has created a few in folio-test.dev instance.

For future instances, do we want to extract these from current instance to load to new instance?  Or do we want this in spreadsheet form?

**Comment by jgreben** [comment]
We will do this from a spreadsheet. Suzette to create a spreadsheet.

**Comment by jgreben** [comment]
~~Depends on #48~~
