### ISSUE TITLE
Run query to see what user extended info notes we have.

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#97]
For the user records, it sounds like “NOTE” “STAFF” and “PRIVNOTE” are used for notes.

Do a query to see which types of notes are used in what frequency.

Laszlo/Catherine think all notes should be migrated to FOLIO user.  But a few users have 20+ notes, and maybe they can consolidate them, clean them up a bit first

**Comment by jgreben** [comment]
~~PRIV-STAFF notes: (W.9994.) - 2657 unique users~~
~~CIRC-STAFF notes: (W.9996.) - 2314 unique users~~
~~NOTE: (W.9998.) - 3942 unique users~~
~~COMMENT: (W.9999.) - 519 unique users~~

~~E.g ` seluser -oUW.9994. 2>/dev/null | grep -v "||$" | awk -F'|' '{print $1}' | sort -u`~~

**Comment by jgreben** [comment]
I am not seeing a difference in total entries for a note field and those unique/sorted with a userkey. Looks like there is only one note of each type per user to me. Maybe I am doing something wrong with the `sels` ¯\_(ツ)_/¯ ?

**Comment by jgreben** [comment]
@dlrueda 👆 please take a look.

**Comment by dlrueda** [comment]
Right, using seluser will only get you the first one, even if there are many.  

The logic/tools I think will be the same as for item, and Shelley documented them in this ticket
https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/91

So, I think using one of the other tools will work better for this.

**Comment by jgreben** [comment]
To find multiples this is what we need:
`head -10000 all_unexpired_uniq.keys | seluser -iE -oKB 2>/dev/null | selved -fUSERX -iV -ePRIV-STAFF -oSM 2>/dev/null`
or
`head -10000 all_unexpired_uniq.keys | seluser -iE -oKB 2>/dev/null | selved -fUSERX -iV -ePRIV-STAFF -oSed 2>/dev/null`

**Comment by jgreben** [comment]
See files here:
- `sirsi@bodoni /s/SUL/Dataload/folio_symphony_extract/Users/userxinfo_notes`
  - `egrep -v "^[ ]+[1][ ][0-9]+\$"` will filter out the line with just 1 entry
  - `awk '{print $1}' | sort | uniq -c` gives the spread

- 134 users with PRIV-STAFF notes.
  - 11 with multiple notes. 
  - spread:
```
123 1
  8 2
  3 3
```
- 405 users with CIRC-STAFF notes. 
  - 79 with multiple notes. 
  - spread:
```
326 1
 48 2
 18 3
  8 4
  1 5
  4 6
```
- 157 users with a NOTE. 
  - 23 with multiple notes.
  - spread:
```
134 1
  1 16
 20 2
  1 5
  1 6
```
- 24 users with a COMMENT. 
  - 2 with multiple comments.
  - spread:
```
23 1
 2 2
```

**Comment by jgreben** [comment]
@dlrueda 👆 please take a look and let me know if you need more info.

**Comment by dlrueda** [comment]
Thanks for the counts, that’s good info.  

Can @jgreben and @Laszlo-J consult on this and decide what info would be useful for circ subgroup folks (or maybe just Catherine) to review.  I know there was a thought to clean up/consolidate multiples, and then migrate everything.

Maybe files can be put in the “Circulation working group” folder in the FOLIO Implementation drive

**Comment by dlrueda** [comment]
Also, I think it’s userkey in that file?  

I’m guessing the information Catherine would like is userID, xinfo type, and note itself so she can quickly review.  Hopefully you have the full data somewhere.

**Comment by Laszlo-J** [comment]
Josh chatted with me about this; given how few notes there are per user, I'm comfortable with importing/combining note for each user without reviewing. Suspect the one with 16 notes is Prof. Bernstein.

I'll double-check with Catherine in our weekly and if she approves combining sight unseen, I'll close this ticket.

**Comment by Laszlo-J** [comment]
Looks like Catherine _does_ want to check the notes to see if there's critical ones. Waiting for her email confirmation and will update the ticket.

**Comment by Laszlo-J** [comment]
@jgreben , Catherine wants to see the users and the associated notes. Please generate and post to location @dlrueda mentioned: https://drive.google.com/drive/folders/1D2kr7X-KgmDuk_JE9xNDCq475r7jn6-D?usp=sharing

Also be sure selected users exp date = NEVER to catch instructors/staff.

**Comment by jgreben** [comment]
@Laszlo-J For this report I am using all the "unexpired" keys that I generated in https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/77, which are all the users who are/will be loaded into FOLIO.

**Comment by jgreben** [comment]
@Laszlo-J see folder link above for files to review☝️.

**Comment by Laszlo-J** [comment]
> @Laszlo-J For this report I am using all the "unexpired" keys that I generated in #77, which are all the users who are/will be loaded into FOLIO.

Thanks!

**Comment by Laszlo-J** [comment]
Per Catherine, okay to import user notes as is.

Okay to import all notes into one note.

Desired: some way to import in time/date code order, otherwise difficult for staff reading them.

Desired: insert carriage return between notes, to improve staff readability
