### ISSUE TITLE
Determine what sels to use to identify “open orders"

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#98]
We want to migrate all “open orders”

Suzette says these are
- in current fiscal year
- no cancel segment
- not received
- not paid

Review rollover templates to help figure out exact selorderline/selorder commands needed to find which orders we would migrate

**Comment by shelleydoljack** [comment]
The code is in `/s/SUL/Bin/folio_symphony_extract/Orders`
